### ISSUE TITLE
[RPI2] Jessie upgrade - ES no more autostart on boot

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#1003]
I've decided to upgrade to Jessie... well for some reasons I can't explain! It went smooth but the only issue I've got far thus far is with the autostart ES on boot. I can't get it to work as before. I've seen Raspbian version is hardcoded in the retropie-setup script so I decided to force it to version "8" in scriptmodules/supplementary/autostartemustat.sh but still no luck... 

Apart from that whenever I launch ES from the command line it works very well and I've got no issue with any emulators (ok I'm using only RA cores). 

If I can do anything please give me a shout.

**Comment by joolswills** [comment]
autostart won't work on jessie. it's disabled on jessie on purpose until a new method is incorporated. 

You may have collisions with jessie packages too, unless you reinstall some stuff. retropie only works on jessie since a few days, and it is currently only supported from source installs.

**Comment by joolswills** [comment]
this would be best posted on the forum, as it's not really a bug - and jessie support is not "official" yet.

**Comment by joolswills** [comment]
(Regarding autostarting emulationstation on systemd on jessie it's on my todo list)

**Comment by joolswills** [comment]
autostart support is now working for jessie - but note jessie is not yet "recommended", and retropie is still designed primary for wheezy.
