### ISSUE TITLE
Add [Theme] - Simple Big Art Theme

### ISSUE THREAD

**Issue by robertybob** [RetroPie/RetroPie-Setup#1005]
I've taken the theme from the forums by Ewzzy, made a few cosmetic changes and fixed the error which prevented me and @HerbFargus from using it (well, I've tested it on my RPi 1 anyway). 

https://github.com/robertybob/es-theme-simplebigart

**Comment by HerbFargus** [comment]
I've tested it and it works now.

**Comment by robertybob** [comment]
Right, should be good to go @joolswills - pushed a commit to fix another cosmetic issue. Is there anything I need to do from my end?

**Comment by HerbFargus** [comment]
This one may also be worth looking at by smithers. It's basically the same thing but much more complete- though the style is more a slight alteration of the simple theme with large box art.

https://github.com/HerbFargus/es-theme-clean-look

**Comment by robertybob** [comment]
Thanks @HerbFargus I'll check that one out. Have I done the right thing by creating a repo? Do I need to do some kind of pull request (i.e should I have created an issue?) to get things moving?

**Comment by HerbFargus** [comment]
yeah your repo looks great, Jools will get to it when he gets to it (if you remember the last themes up on the issue tracker spent a better portion of a year or two on the issue tracker before they were included.) just be patient :) In the mean time Rookervik and I have been working on a theme, its almost complete, just missing a few controllers and needs a few minor tweaks on the logos.

https://github.com/HerbFargus/es-theme-carbon

or if you like the only box art feel:

https://github.com/HerbFargus/es-theme-carbon-centered

**Comment by joolswills** [comment]
done. many thanks.

**Comment by sergioad** [comment]
Somebody could help me? I am not a graphical desigber so I can not do it by miself, could you help me to add Wonderswan and Wonderswan color compatibility for simple big art? sincerely it is my favorite ES theme and I wish have those system pages themed

**Comment by joolswills** [comment]
@sergioad Please use the forum for help.

**Comment by sergioad** [comment]
Ok
