### ISSUE TITLE
"Value too large for defined data type"

### ISSUE THREAD

**Issue by eusi** [RetroPie/RetroPie-Setup#1016]
Hey.

As the title says, it's not able to run a huge image (above 2gb).

In my case I tried a psx game (pbp file of 2.2gb) on pcsx_rearmed-emulator on RetroPie on my RPi2.

Probably issue and approach to solve this: https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type

Is this problem made by RetroPie or its emulator (here: pcsx_rearmed) and fixable?

Greetz
eusi

**Comment by joolswills** [comment]
I don't think we are doing anything special/different in the way we are compiling, so I guess it needs fixing upstream.

**Comment by adrianmoisey** [comment]
This might be because the ARM devices on the Pi are 32bit. I imagine upstream won't/can't fix this.

**Comment by joolswills** [comment]
Should be able to support large files on the rpi1 with source changes though despite being 32bit.

**Comment by joolswills** [comment]
Closing here as I see you have reporting it upstream. thanks.

**Comment by adrianmoisey** [comment]
Do you have a link to the upstream bug? I'd like to follow it.

**Comment by joolswills** [comment]
https://github.com/notaz/pcsx_rearmed/issues/59

**Comment by adrianmoisey** [comment]
Thanks

**Comment by johnweland** [comment]
notaz has said that the issues has been pushed. Not sure when retro pie will get it though.

**Comment by joolswills** [comment]
you can install from source now and test it

**Comment by johnweland** [comment]
I'm still kinda of new to that process, but I'll attempt to give it a go this week.

**Comment by johnweland** [comment]
Hey works! I went to the experimental packages and installed pcsx_rearmed large file support is enabled. Of course I have to remap my keys and get my psx bios dropped in.

**Comment by dankcushions** [comment]
the standalone fix was merged in to the libretro version a few days again. I can run 2GB .pbps on it. try recompiling that from source and it should be fine :)

**Comment by johnweland** [comment]
Hey thanks, worked like a charm.
