### ISSUE TITLE
Virtualboy doesn't compile

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1019]
Breaks as if this commit:

https://github.com/libretro/beetle-vb-libretro/commit/a34b4ea75ca6b51cf6bb9634297decc80d5a55a8

Simple fix

**Comment by joolswills** [comment]
should be sorted now.

**Comment by HerbFargus** [comment]
Thanks mate- I'll test it once I have a chance but I'm sure it will work fine.

**Comment by HerbFargus** [comment]
Verified working by another user
