### ISSUE TITLE
Supporting illuminated controls

### ISSUE THREAD

**Issue by NeoID** [RetroPie/RetroPie-Setup#1028]
On my first arcade build I used a second screen in the marquee to display the button configurations for any given system/game. On my latest build, based on RetroPie, I would love to do the same, but instead of using a second screen, I think about using illuminated buttons.

My idea is to illuminate only the buttons that are active/in use depending on the emulator or game running. I see that runcommand.sh is called before each system launches and knows about what system and rom has been launched. I think about hooking into that script to illuminate my buttons, but what kind of script runs when the emulator quits? I see that it outputs:

"Press a key or joystick button to co
============================="

But I can't find where that's defined. Any idea on this matter or better suggestion on how to determine when a given system/game is started and exited? :)

**Comment by joolswills** [comment]
this is in runcommand.sh and is shown before a game is loaded - this issue tracker is not for support though - please use the retropie forum - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
