### ISSUE TITLE
Nintendo DS emulator not building (lr-desmume)

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1030]
this is my error log:

http://pastebin.com/B4FHmXY5

**Comment by HerbFargus** [comment]
its already been logged upstream it would seem: https://github.com/libretro/desmume/issues/61

**Comment by joolswills** [comment]
Yep.

**Comment by joolswills** [comment]
reversed that patch in our build script - it builds now - but untested.

**Comment by HerbFargus** [comment]
yeah it runs now, I'll close this then until upstream is fixed. thanks
