### ISSUE TITLE
*NOT AN ISSUE, SORRY I DIDNT KNOW WHERE ELSE TO CONTACT*

### ISSUE THREAD

**Issue by pancakeykakes** [RetroPie/RetroPie-Setup#1032]
I wanted to ask the contributors/devs of this project if they wanted to work with me on incorporating an idea using the script I wrote, but I don't quite think it qualifies for a pull request. We can talk here or via email.

Sorry again for posting it here. Still learning how github works and didn't see any other method of contact.

**Comment by joolswills** [comment]
When you open an issue on github - it says "Please review the guidelines for contributing to this repository." - if you click the link it explains to use for forum for discussion

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by joolswills** [comment]
Better to start on the forum perhaps, and we can go from there. thanks.

**Comment by pancakeykakes** [comment]
My apologies, I'm in mobile.
