### ISSUE TITLE
/dev/tty in runcommand.sh

### ISSUE THREAD

**Issue by satanasov** [RetroPie/RetroPie-Setup#1044]
Hello,

First of all - nice work.

Second - I'm trying to create a bridge that allows start of emulationstation from within Kodi. All is perfect but there is issue with using the virtual TTY (/dev/tty).

Could the runcommand.sh be patched to use /dev/tty0 or /dev/console so the script does not fail?

**Comment by joolswills** [comment]
please use for the forum for support - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
