### ISSUE TITLE
amstrad emulation failing

### ISSUE THREAD

**Issue by cheekymonkat** [RetroPie/RetroPie-Setup#1048]
Hi, I performed an upgrade and also a new SD image install - but it appears that the amstrad emulation now just fails and returns to ES screen.  happens for all the games.

I've the latest PI.

Anyone else seen this?

Also - is there a download available for SD 3.0 as I'd like to go back.

Thanks

**Comment by joolswills** [comment]
anything in /tmp/runcommand.log ?

**Comment by cheekymonkat** [comment]
yes (I decided to look after sending the email!)

/opt/retropie/emulators/cpc/cpc4rpi: error while loading shared libraries:
libEGL.so.1: cannot open shared object file: No such file or directory

Thanks Alan

**Comment by joolswills** [comment]
I will have a new binary up in a minute. I know what the problem is.

**Comment by cheekymonkat** [comment]
awesome thanks!

**Comment by joolswills** [comment]
Please go to retropie-setup, menu 5, and choose cpc then install from binary.

**Comment by joolswills** [comment]
BTW it would have fixed it had you rebuilt it from source - it failed due to it linking with the wrong EGL library on my dev system. However it doesn't even need to link to EGL, so I removed the dependency. This emulator will be replaced at some point with Caprice32 (it is basically a renamed caprice32). There is also a libretro Caprice32 emulator you can try also with retropie (switch from pre-launch menu)

**Comment by cheekymonkat** [comment]
great thanks! worked a treat.  Thanks for your rapid response.  Great tool!

**Comment by cheekymonkat** [comment]
Sorry - have a new issue (maybe related) - I get no sound at all?  I hear it from other emulators - any ideas?

Thanks

**Comment by joolswills** [comment]
Via HDMI or headphone ? Did you set the audio configuration correctly  (From retropie-setup / configuration)

**Comment by joolswills** [comment]
There is sound on it, I can confirm here, so it sounds like a configuration issue your end

**Comment by cheekymonkat** [comment]
Ah, yes - sorry - I was getting sounds for other emulators from the HDMI connection but once I switched to headphone it worked... sorry my mistake!
Thanks
