### ISSUE TITLE
Menus on gamelist scrolling time to time in automatically way

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/RetroPie-Setup#1059]
The Menus on gamelist scrolling time to time in automatically way, without my intervention...
Is it a feature or a bug?
If is a feature how can i disable it?

**Comment by joolswills** [comment]
You have a buggy/broken controller.

**Comment by LodanZark** [comment]
I am using a SNES Buffalo usb controller, I just tested on windows over joy.cpl and its working properly, I even touched the cables meanwhile plug in to see if would trigger some weird behaviors and non issue was found, anyway I will try a different gamepad just to make sure.

**Comment by HerbFargus** [comment]
I had some old buggy controllers that did the same thing, I switched controllers and have had no issues since. The other thing you can try is reconfiguring your controller but not sure if that will help at all if it is a hardware issue.

**Comment by LodanZark** [comment]
I have 2 Buffalo USB controllers, one does the trigger that issue and other one don't, the odd thing is that issue isn't affected in gameplay since I left an RPG opened in afk mode and the character didn't move or trigger any action, plus both gamepads works very good in gamepad callibration software on windows xD go figure...

**Comment by Tele42** [comment]
Hypothetically, the windows driver could have implemented a quirks-mode and automatically detects the issue, while on linux, either a generic kernel module is used or a best-effort was made with the hardware whoever made the module had at the time. I do not have controllers like this, so I can only speculate.

**Comment by joolswills** [comment]
nothing we can do about it currently - if it is a known hardware issue that can be fixed in the driver, this needs to be fed upstream to the linux kernel etc.
