### ISSUE TITLE
oricutron: oric-1 & atmos emulator

### ISSUE THREAD

**Issue by gonzo-the-great** [RetroPie/RetroPie-Setup#1065]
i see we have no oric emulation yet?
will this be suitable?

https://github.com/pete-gordon/oricutron

**Comment by joolswills** [comment]
Thanks. I'll try it out. Written by someone I know too :)

**Comment by HerbFargus** [comment]
Just as a future reference there is a working module in the retropie-extra repository https://github.com/zerojay/RetroPie-Extra/blob/master/scriptmodules/emulators/oricutron.sh

**Comment by joolswills** [comment]
Now added to RetroPie main repo (in experimental)
