### ISSUE TITLE
VGA issue

### ISSUE THREAD

**Issue by bistule** [RetroPie/RetroPie-Setup#1076]
Hi,

I bought a VGA converter here : 
http://www.amazon.fr/gp/product/B00J63HWD0?psc=1&redirect=true&ref_=oh_aui_detailpage_o01_s00
cause my Acer X193HQ :
http://www.lcd-compare.com/moniteur-ACEX193HQB-ACER-X193HQb.htm
has only a VGA entry.

So, to configure my retropie, i wrote this in /boot/config.txt : 

"
# uncomment if you get no picture on HDMI for a default "safe" mode

hdmi_safe=1

#disable_commandline_tags=1

#uncomment this if your display has a black border of unused pixels visible
#and your display can output without overscan
#disable_overscan=1

#hdmi_ignore_edid_=0xa5000080

#uncomment the following to adjust overscan. Use positive numbers if console
#goes off screen, and negative if there is too much border
#overscan_left=30
#overscan_right=15
#overscan_top=20
#overscan_bottom=10

#uncomment to force a console size. By default it will be display's size minus
#overscan.
#framebuffer_width=1366
#framebuffer_height=768

#uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

#uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=81

#uncomment to force a HDMI mode rather than DVI. This can make audio work in
#DMT (computer monitor) modes
hdmi_drive=2

#uncomment to increase signal to HDMI, if you have interference, blanking, or
#no display
#config_hdmi_boost=4

#uncomment for composite PAL
#sdtv_mode=2
#sdtv_aspect=1

#for more options see http://elinux.org/RPi_config.txt
gpu_mem_256=128
gpu_mem_512=256
gpu_mem_1024=256

overscan_scale=1
arm_freq=950
core_freq=250
sdram_freq=450
over_voltage=6
"
but, when i reboot, i still have this value:

pi@retropie ~ $ tvservice -s
state 0x12000a [HDMI DMT (4) RGB full 4:3], 640x480 @ 60.00Hz, progressive
and my display is totally awful, flat, and pixelised ! :-1: 

even i choose hdmi group 2 ande mode 81 !

with tvservice -m DMT, i found this values for my screen : 
Group DMT has 11 modes:
  (prefer) mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive
           mode 5: 640x480 @ 72Hz 4:3, clock:31MHz progressive
           mode 6: 640x480 @ 75Hz 4:3, clock:31MHz progressive
           mode 8: 800x600 @ 56Hz 4:3, clock:36MHz progressive
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive
           mode 10: 800x600 @ 72Hz 4:3, clock:50MHz progressive
           mode 11: 800x600 @ 75Hz 4:3, clock:49MHz progressive
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive
           mode 17: 1024x768 @ 70Hz 4:3, clock:75MHz progressive
           mode 18: 1024x768 @ 75Hz 4:3, clock:78MHz progressive
           mode 81: 1366x768 @ 60Hz 16:9, clock:85MHz progressive

With the tvservice command, i can change the resolution, but, after reboot, this settings disapear !

Someone has the same issue ?

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

Please use the RetroPie-Setup for support questions. This is not a RetroPie issue btw, but more of a Raspbian configuration issue.
