### ISSUE TITLE
PPSSPP Improper Controller Keys 

### ISSUE THREAD

**Issue by Omnija** [RetroPie/RetroPie-Setup#1078]
Recently installed ppsspp and tried to setup my controller, but when i pressed (B) it would get Direction (Up) and (A) would be Directional (Left). The Controller inputs are fully incorrect. 
I'm using an xbox 360 rock candy controller.

**Comment by joolswills** [comment]
Maybe they have hardcoded mapping - You should report this upstream perhaps - maybe by first starting on their forum if it's a configuration issue - http://forums.ppsspp.org - nothing I can do to help (don't even have your controller). try another controller too ?

**Comment by joolswills** [comment]
There is also the libretro core ?

Sorry to close, but I don't think there is anything we can do currently - seeing if other users have the problem on the forum, and if they managed to remap their controllers may be an option. Or use a keyboard? :)
