### ISSUE TITLE
LXDE (startx) black screen

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1079]
Just posting this as a reference for others in that using startx after installing lxde doesn't work unless you delete the contents of 

/etc/profile.d/10- emulationstation.sh

**Comment by joolswills** [comment]
fixed. requires emulationstation autostarting to be disabled/enabled to update the script.

**Comment by HerbFargus** [comment]
I'll verify when I've got the time but will consider this closed.
