### ISSUE TITLE
[lr-fba-next] new release - v0.2.97.37

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#1080]
Hi!! seems that good fellas from FBA just released a new version with bugfixes, new drivers, etc. (read here http://www.fbalpha.com/view/227/). And @barbudreadmon was kind enough to update his libretro port (https://github.com/libretro/libretro-fba). 

I'm building it right now and will try to update this thread to let you know if it's worth it! 

Thanks :)

**Comment by joolswills** [comment]
Yeh saw that yesterday - not built it yet, so am interested in feedback.

**Comment by nemo93** [comment]
Stable, no crash during a 2h play session. Brings lot more options in RetroArch Core Options especially for Neogeo or other Arcade systems. CPS3 run lot better one this one as Jojo games have no more glitches and Red Earth just works this time. Don't see any difference on Neogeo games as previous version was already great. Also it seems this newer version handles a lot better some Sega games as Alien Storm works fullspeed and without glitches. Same goes with Turbo Outrun. 

At the end I'd say it's a no brainer and definitely worth the upgrade.

**Comment by barbudreadmon** [comment]
Sorry, i still have no clue about the issue with irem games on arm, what i know : 
- It is not endian related
- It is not x86 specific instruction related (no ASM code)
- It is probably related to nec V30 cpu (all affected games uses this cpu)
- The cpu emulator is not necessarily the culprit since m90 emulation (which also uses V30) is working

**Comment by joolswills** [comment]
I thought it might be due to ARM having unsigned chars by default, but it made no difference when I forced it to signed-char :/

**Comment by nemo93** [comment]
been added to the 3.3 release \o/ (https://github.com/RetroPie/RetroPie-Setup/wiki/Changelogs)

**Comment by dips52** [comment]
nemo93 

Can you give any more information on how you got red earth to run? I have tried what feels like all versions but still have no luck getting it to run on latest FBA with pi3. 

I'm trying this one again but don't have a good feeling about it: 

Capcom Play System 3 Emulator v1.0 - "Warzard / Red Earth" - année: 1996 - fabricant: "Capcom" 

Télécharger : warzard.zip 
Taille : 34.51 Mo
