### ISSUE TITLE
[RPi2 Retropie 3.2.1] Error installing lr-mame2010: "mame2010_libretro.so not found"

### ISSUE THREAD

**Issue by kilateped** [RetroPie/RetroPie-Setup#1081]
Hello, hope you can help me.
I'm trying to install experimental lr-mame2010 package trough RetroPie setup, but I can't. It says it couldn't find mame2010_libretro.so in tmp/build/lr_mame2010.
What am I doing wrong?

Thank you.

**Comment by joolswills** [comment]
did you update retropie-setup script first ?

**Comment by kilateped** [comment]
Yes I did.

**Comment by joolswills** [comment]
then I will need a log from the RetroPie-Setup/logs folder - use a site like pastebin.com or similar.

**Comment by kilateped** [comment]
http://pastebin.com/697kmBUH
Thanks.

**Comment by joolswills** [comment]
You have not updated the retropie-setup script

**Comment by kilateped** [comment]
How many times do I need to update it? First time I entered retropie-setup script I chose "Update RetroPie- Setup script" and entered ok.
Do I need to update it every time I want to install a package? Or maybe I didn´t update correctly?

**Comment by joolswills** [comment]
it should show an error if it didnt update correctly. try "git pull" from terminal also.

lr-mame2010 was fixed on the 6th November (after upstream changes). So long as you updated after that lr-mame2010 should built correctly. I can see from the log it is referencing stuff that has changed so it must be it didn't update.

**Comment by joolswills** [comment]
If you mean you updated retropie-setup at some point some weeks ago, then you will need to update it again.

**Comment by kilateped** [comment]
This is from the first time I tried to install:
http://pastebin.com/7h2Zm0gN
I did some more tries without any success, then I replace lr-mame2010.sh file with the one prior 6th November, and tried again without success. The first log I send you is from this last try.

**Comment by joolswills** [comment]
Why are you manually replacing files?

That log file is also an out of date lr-mame2010.sh

Just update RetroPie-Setup (if you have modified local files, you will need to `git reset --hard` or `git stash` your changes or else it won't be able to update).

**Comment by kilateped** [comment]
Ok. I´ll start from scratch tonight, format SD card, Install RetroPie image, update setup script and install lr-mame2010. I´ll tell you if I am successful.
Thank you for your help. I´ll tell you later.

**Comment by joolswills** [comment]
it works as I just built it here. Just follow my instructions above and you should be able to sort it. No need to start from scratch.

**Comment by kilateped** [comment]
Ok.

**Comment by kilateped** [comment]
Ok, did what you said and success ;) 
Thank you very much!
I found some games running slowly (like run and gun 2, versus net soccer...) do you think it's possible to get them run near normal speed? Maybe overclocking or is just the mame version not capable of running them smoothly?

**Comment by joolswills** [comment]
there is a reason the mame2010 is in experimental. the pi2 cpu is too weak i'm afraid. best bet is the 2003 mame perhaps.

**Comment by joolswills** [comment]
You can use the forum for further support / feedback.
