### ISSUE TITLE
Supertux.sh crashes on exit

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#1083]
As the title says Supertux (installed from experimental packages) crashes on exit.

Has anyone the same problem?

rpi1 model b, 512 MB, retropie-v3.2.1-rpi1 image, simple theme

**Comment by HerbFargus** [comment]
When you say crash what do you mean by that? Does it freeze?

**Comment by Haris1977** [comment]
Only a "black screen" and stays there forever. Have to unplug the power cable and plug it back

**Comment by HerbFargus** [comment]
It would be safer to ssh in and reboot than to unplug the cord. https://github.com/RetroPie/RetroPie-Setup/wiki/ssh.

**Comment by Haris1977** [comment]
Apart from the unplug thing, is it normal to have a black screen ??(does not revert back to es).

**Comment by HerbFargus** [comment]
No its not normal- hence why its in experimental. I'll look into it when I find some time

**Comment by Haris1977** [comment]
Ok thanks:)

**Comment by HerbFargus** [comment]
did you update your setup script first before installing? the ports function was recently changed and that may have fixed the issue as I just ran it and it did not freeze on exit.

**Comment by HerbFargus** [comment]
or if you don't want to reinstall (as the raspbian is offline right now) you can edit the `/home/pi/RetroPie/roms/ports/SuperTux.sh`
to look like this:
```
#!/bin/bash
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 _SYS_ supertux ""
```

**Comment by Haris1977** [comment]
I updated the setup script and re-downloaded the game. Now it works as expected and does not freeze on exit. 

Only drawback is that my left analog stick (wireless xbox compatible controller) is very sensitive to movement.

**Comment by HerbFargus** [comment]
glad its sorted.

For the analog settings, You may have to find the deadzone settings in the configuration files in the backend somewhere:

http://supertux.lethargik.org/bugs/view.php?id=169

otherwise you could just set the controls to the dpad,

**Comment by Haris1977** [comment]
I find (joystick-deadzone  4096). So what is the number i have to use? lower or higher?
