### ISSUE TITLE
USB ROM Service disable doesn't work

### ISSUE THREAD

**Issue by dankcushions** [RetroPie/RetroPie-Setup#1086]
1) Installed latest retropie SD card image (3.2.1) and booted with my USB stick full of roms removed. 
2) Disabled the USB ROM service via the setup menu, rebooted and then inserted USB stick full of roms
3) They began transferring to the SD card regardless

Looks like the disable isn't working in this version?

**Comment by joolswills** [comment]
Looks like it was broken from when it was added back in Feb btw - before that it never had a disable option.

**Comment by objectchris** [comment]
perfect, thanks! i've updated the script and it works fine now :)
