### ISSUE TITLE
lr-mednafen-pce is requesting my github login and password when compiling from source

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1088]
Log started at: Tue Nov 17 16:27:27 EST 2015
/home/pi/RetroPie-Setup/tmp/build/lr-mednafen-pce /home/pi/RetroPie-Setup

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'lr-mednafen-pce' : PCEngine emu - Mednafen PCE core port for libretro
= = = = = = = = = = = = = = = = = = = = =

git clone --depth 1 "https://github.com/petrockblog/mednafen-pce-libretro.git" "/home/pi/RetroPie-Setup/tmp/build/lr-mednafen-pce"
Cloning into '/home/pi/RetroPie-Setup/tmp/build/lr-mednafen-pce'...
Username for 'https://github.com':

**Comment by gizmo98** [comment]
@petrockblog has no mednafen-pce-libretro repo (anymore?).

**Comment by joolswills** [comment]
It's possible I removed it as we no longer needed our fork due to upstream changes. Can't remember but we can switch to the upstream repo.

**Comment by joolswills** [comment]
oh wait. sorry - nothing to do with me - misread and though it was on the RetroPie repository.

**Comment by ProxyCell** [comment]
I'm not sure if this matters but it is a RPI2 running Wheezy (I gave up on Jessie for now...)
Is this just being given the wrong git repo URL?

**Comment by joolswills** [comment]
the repository is removed - I guess @petrockblog removed it - his repository may have had changes from upstream I guess but we can find the upstream repo and use that (if it works).

**Comment by ProxyCell** [comment]
the "fast" variant of this is still there

**Comment by HerbFargus** [comment]
If this was the upstream, https://github.com/libretro/mednafen-pce-libretro
It no longer exists. Probably superceded by pce-fast.

**Comment by ProxyCell** [comment]
thanks @HerbFargus :+1:  but google and archive dot org do not have a cache of it :(

**Comment by joolswills** [comment]
then perhaps we can just remove the old module. I will look into it further when I get a moment. there may be some other alternative libretro emulators too.

**Comment by joolswills** [comment]
@ProxyCell for now just install from binary and don't worry about it.

**Comment by ProxyCell** [comment]
:+1: 

Thanks @joolswills

**Comment by petrockblog** [comment]
I am sorry for that! Without double checking it I assumed that that fork is not needed anymore. I will try to find an alternative ...

**Comment by ProxyCell** [comment]
thanks @petrockblog 
its nothing of critical concern but it is different from the fast variant as it focusses on accuracy over speed - i figure its worth letting people switch between the two if there is a need based upon the game/software

**Comment by joolswills** [comment]
If it is unsupported upstream, it may have been removed for a reason (ie not being needed). I am happy to remove the module unless someone has evidence over better accuracy etc vs the other libretro core.

**Comment by joolswills** [comment]
I found another fork of it, but it dates back to 2012. If it is not being maintained by libretro devs anyway, I don't see the point in keeping it. I'm going to remove the module.

**Comment by ProxyCell** [comment]
@joolswills i agree, i'm not familiar with anything that REQUIRES this but i had been using it for quite a while over the FAST

**Comment by petrockblog** [comment]
I also found a fork from 2012 - probably the same. I have forked that now so that the module would work. But we could also remove the module. It is not that we are really loosing functionality in RetroPie without that ...

**Comment by joolswills** [comment]
>me: so mednafen-pce-libretro became beetle-pce-fast-libretro there were never two ports ?
> <retroarch dev> correct

**Comment by ProxyCell** [comment]
this is crazy, we've had two for ages and they were entirely the same?
