### ISSUE TITLE
Add [Theme] - retroplay_clean_canela

### ISSUE THREAD

**Issue by InsecureSpike** [RetroPie/RetroPie-Setup#1089]
hi guy's would you like to review my new theme for addition to the theme installer?

https://github.com/InsecureSpike/retroplay_clean_canela

small file size (under 6MB)
clean & clear looking
16:9 & 4:3 aspect ratio compatible!
interchangeable logo banners
34 alternate & extra logo banners availabe @ https://insecurespike.wordpress.com/the-downloads/

screenshot viewable here https://insecurespike.wordpress.com/clean_canela-screenshots/

thank you

**Comment by InsecureSpike** [comment]
just replaced the "RetroPlay" text wallpaper with a no text wallpaper

**Comment by joolswills** [comment]
For themes to be added to our theme installer your repository needs to be named like `es-theme-simple` eg `es-theme-retroplay-clean-canela`

**Comment by InsecureSpike** [comment]
oh sorry, are they ok now?

**Comment by joolswills** [comment]
yep. Ill test / add them when I next do some development. thanks.

**Comment by InsecureSpike** [comment]
awesome thank you

**Comment by InsecureSpike** [comment]
great! both are now ready whenever someone has some time
thanks

**Comment by HerbFargus** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/1091/files

**Comment by joolswills** [comment]
@HerbFargus have you tested them ?

**Comment by HerbFargus** [comment]
I haven't tested the latest changes, I'll test within the hour though and report back

**Comment by HerbFargus** [comment]
They work fine, though I think the clean version is supposed to have a main system wallpaper? Right now it just shows up as a white background. The gamelist wallpaper shows up fine. @InsecureSpike do you want to check and make sure this theme is working as you intended? Regardless, minor details can be fixed upstream and it can still be merged I think.

**Comment by HerbFargus** [comment]
Yeah you're missing the clean_mainmenu.png on this theme, otherwise it seems fine.

**Comment by InsecureSpike** [comment]
sorry, the wallpaper is there now, thank you

**Comment by HerbFargus** [comment]
They have been added, you can update your setup script and they should be there- so you should be able to close your two tickets now.

**Comment by InsecureSpike** [comment]
thank you!
