### ISSUE TITLE
Mupen64Plus Controller config - A / B buttons recognized as dpad buttons?

### ISSUE THREAD

**Issue by TheReal1604** [RetroPie/RetroPie-Setup#1101]
Hey Guys,

got some problem with a fresh retropie installation...

For psx and snes the controller config works just fine, but for n64 i have the strange issue that the a / b / x / y button is recognized as dpad left / right / up / down.. in Super Smash bros. 

Did the reconfiguration via script.. have tried to set the controls via Inputautocfg.ini .. just not working. (Checked the button numbers before with jstest)

Got a Dragonrise controller.

Anyone a idea how i can fix this?

Greetz
TheReal

Edit: Here is the DragonRise section from the Inputautocfg.ini

[DragonRise Inc. Generic USB Joystick]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = key(275) axis(0+)
DPad L = key(276) axis(0-)
DPad D = key(274) axis(1+)
DPad U = key(273) axis(1-)
Start = button(9)
Z Trig = button(10)
B Button = button(3)
A Button = button(1)
C Button R = button(7) axis(3+)
C Button L = button(6) axis(3-)
C Button D = button(1) axis(4+)
C Button U = button(0) axis(4-)
R Trig = button(5)
L Trig = button(4)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by HerbFargus** [comment]
make a backup, delete Inputautocfg.ini, update your setup script, do a full binary install, reconfigure your controllers, and then see if it works.

**Comment by TheReal1604** [comment]
Thx for your very fast response. What is the preferred way to rebuild the controller config? Retro pie-Setup Script?

**Comment by HerbFargus** [comment]
its automatically done through the emulationstation controller config now after a full binary update. just added yesterday

**Comment by TheReal1604** [comment]
Hey HerbFargus,

with your steps, it worked now! Thanks for that!

Additionally i configured the gles2n64 as default video plugin.. after your steps i now have no sound in n64... any idea? :-P

**Comment by gizmo98** [comment]
@TheReal1604 
Audio plugin does not auto detect audio output path. To use 3,5mm audio jack you have to modify mupen64plus.cfg.

**Comment by gizmo98** [comment]
I think this can be closed now.
