### ISSUE TITLE
If installing on a non-raspbian basesystem (osmc) some dependencies are not met (also tvservice problems)

### ISSUE THREAD

**Issue by mcobit** [RetroPie/RetroPie-Setup#1106]
Missing dependencies are (for now):
alsa-utils
libusb-1.0

Also /opt/vc/bin is not in PATH which leads to "tvservice not found" errors.
Quick workaround: 
add
export PATH=$PATH:/opt/vc/bin
to /usr/bin/emulationstation

**Comment by joolswills** [comment]
thanks will sort the path out - the alsa-utils and libusb-1.0 issues should be resolved now.

**Comment by joolswills** [comment]
tvservice is used directly from runcommand so I will add it to that

**Comment by mcobit** [comment]
Great :-)

**Comment by joolswills** [comment]
runcommand should be ok now.

**Comment by joolswills** [comment]
Am closing as these problems are now solved. Note that with the current RetroPie-Setup and EmulationStation the launch script has changed, and we no longer force a restart. See https://github.com/RetroPie/RetroPie-Setup/pull/1190 and https://github.com/RetroPie/EmulationStation/pull/17
