### ISSUE TITLE
Button delay when i playing

### ISSUE THREAD

**Issue by sylvio78** [RetroPie/RetroPie-Setup#1114]
I installed Retropie on my Raspberry PI 2. I set my joystick ( Generic USB ) and when I press any button during the game, have late reply on the game . 
It is a very small delay, but is bad when game.
I already tested with other joysticks, and the result is the same.
What I do??

Thanks!!

**Comment by joolswills** [comment]
Please use the forum for help with this - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
