### ISSUE TITLE
Button Mapping of PC Engine

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/RetroPie-Setup#1117]
Why PC engine has buttons mapped to "B Y" instead "B A" like other 2 buttons consoles (NES, SMS, GG, etc), is it a bug?

Is it possible map "II" to "B" and "I" to "A", and set up turbo levels with "Y" for "II" and "X" to "I"?

**Comment by joolswills** [comment]
Please use the forum for support - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

But the answer is because that's the mapping the author of the libretro core chose. You can remap it though on a per emulator basis. You can get help for this on the forum.
