### ISSUE TITLE
Wrong button mapping when raspi-config launched from retropie menu

### ISSUE THREAD

**Issue by ali1234** [RetroPie/RetroPie-Setup#1121]
To reproduce:

1. Start up retropie, see emulation station menu.
2. Go to retropie menu, then select raspi-config option.

When in raspi-config, I must press "B" to activate the select/finish buttons. In other such text-mode config screens it is done with the "A" button.

**Comment by ScOULaris** [comment]
I have noticed this as well.

**Comment by tynor88** [comment]
Yes me too, minor bug :-)

**Comment by joolswills** [comment]
Not a bug - we use a joy2key script to convert joypad to keypresses. As raspi-config uses a different console gui from RetroPie-Setup it has different controls. This won't be changed - and for this sort of configuration a keyboard is still easier.

**Comment by joolswills** [comment]
raspi-config is not developed by us either.
