### ISSUE TITLE
Reboot option halts/hangs the system when raspi-config is launched from menu

### ISSUE THREAD

**Issue by ali1234** [RetroPie/RetroPie-Setup#1122]
To reproduce:

1. In EmulationStation go to retro pie menu and launch raspi-config
2. In raspi-config select the "reboot system" option (last one in the list.)

Expected result: system should reboot.
Actual result: System halts/hangs and I must power cycle it.

System: Raspberry Pi 2 with official 7" display, retropie 3.2.1.

**Comment by joolswills** [comment]
As we don't maintain raspi-config there is nothing I can do about that really, just use the reboot from within emulationstation.

**Comment by ali1234** [comment]
It's been my experience that the reboot option of raspi-config works correctly when run from within an official raspbian image...

**Comment by HerbFargus** [comment]
Though the reboot function seems to work fine after running expand filesystem etc.

**Comment by joolswills** [comment]
I don't see a "reboot system" option in raspi-config (apart from after you expand filesystem etc which works)

**Comment by joolswills** [comment]
retropie-setup has "Perform Reboot" as the last option, which works fine here also.

**Comment by ali1234** [comment]
Yes, it was after I resized the filesystem. Didn't realize the option wasn't there before. Anyway, it didn't work for me. The system halted instead of rebooting.

**Comment by joolswills** [comment]
it reboots here - maybe you got unlucky or something. No-one has mentioned this before and this something everyone runs after install. You could try and reproduce it, perhaps something related to your hardware setup etc.

**Comment by HerbFargus** [comment]
Possible bad SD card, power supply, too aggressive overclock etc.

**Comment by joolswills** [comment]
ok to close ?
