### ISSUE TITLE
PS3 Controllers Default to Players 3/4 When Xbox Driver Is Also Installed 

### ISSUE THREAD

**Issue by shealey** [RetroPie/RetroPie-Setup#1125]
Issue:
PS3 controllers are always assigned to players 3/4 when connecting to the retropie. 

The retropie should be able to dynamically assign wireless inputs to players in the order that they connect via bluetooth including a mix of input types e.g. player 1 - PS3 Controller, player 2 - Xbox controller, player 3 - 8bitdo controller etc...

Reproduction Steps:
1: Install the PS3 Controller driver
2: Pair 2 PS3 controllers via bluetooth
3: Install the xbox controller driver

Workaround:
Uninstall the xbox controller driver via sudo apt-get remove xboxdrv

Version:
RetroPie 3.2.1

**Comment by joolswills** [comment]
you may have some luck editing the xboxdrv config in /etc/rc.local - You may be able to configure it so it works as you want for your setup but it might need hardcoding for how you want your controllers connected. These are 3rd party applications, and although we have some improvements in the ps3 driver, the xboxdrv is not developed by us. We also ship with an older version currently. See documentation here http://pingus.seul.org/~grumbel/xboxdrv/xboxdrv.html

**Comment by joolswills** [comment]
xboxdrv has been updated and has been improved somewhat, but you still would need to manually configure the xboxdrv if you want it only used for id 0/2 etc

**Comment by joolswills** [comment]
I dont think it's realistic to ever make these two drivers work together dynamically in a way that would work for all set ups. Closing.
