### ISSUE TITLE
lr-ppsspp is not listed on the experimental menu

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1126]
I did a full install from source on everything last night (Wheezy, gave up on jessie) and I noticed that lr-ppsspp is not listed on the experimental menu.

It is on the "install individual..." menu

**Comment by HerbFargus** [comment]
An astute observation... https://github.com/RetroPie/RetroPie-Setup/commit/8c7967c44c58e3d9f408021e40aafd20894d39fa

It's a feature not a bug.

**Comment by ProxyCell** [comment]
yeah i thought i saw a commit like that once in the past but i couldn't see PPSSPP in the "Build from source" menu either

**Comment by joolswills** [comment]
ok. that is a bug. I mean't to switch the menus, not remove it. I'll fix that.

**Comment by joolswills** [comment]
now fixed.

**Comment by ProxyCell** [comment]
thanks @joolswills
