### ISSUE TITLE
Accidentally changed joypad default controls, need help changing them back.

### ISSUE THREAD

**Issue by FrankHughes** [RetroPie/RetroPie-Setup#1131]
I bought a Raspberry Pi 2 with Retropie installed. Not 2 minutes out of the box I accidentally accessed a menu to reconfigure my wireless PS3 controller (the only input device to my Pi) and changed the controls. Now I don't know what the controls are, I don't know how to change them back or reset them. I need help. What do I do? I am a Mac user and not very skilled at solving these kinds of problems. Please HELP!
-Frank

**Comment by joolswills** [comment]
This issue tracker is not used for support - please use the RetroPie forum https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
