### ISSUE TITLE
Retro Achievements

### ISSUE THREAD

**Issue by kryptalivian** [RetroPie/RetroPie-Setup#1132]
Can we get Retro Achievements implemented from retroachievements.org. I see Retroarch is implementing this into builds.

Thanks!

**Comment by robertybob** [comment]
Lakka has this, so I wondered whether the version of RetroArch that RP uses has this feature already, hidden away?

**Comment by HerbFargus** [comment]
It will eventually be incorporated into retroarch once retroarch sorts out their 1.3 release and its deemed stable enough to be compiled on retropie.

**Comment by joolswills** [comment]
It is compiled in but untested. Because you can't enter the username/password from within RGUI it will need manual configuration.

**Comment by kryptalivian** [comment]
So we just need to enter it into the Retroarch.cfg file?

**Comment by joolswills** [comment]
try setting these in /opt/retropie/configs/all/retroarch.cfg

```
cheevos_username = "yourusername"
cheevos_password = "yuourpassword"
cheevos_enable = true
```

**Comment by kryptalivian** [comment]
I'll try it tonight and let you know if it was successful. Thanks for getting that all setup! :-)

**Comment by zerojay** [comment]
Since OP hasn't commented, this appears to not be working yet.

**Comment by kryptalivian** [comment]
Test it with Chrono Trigger and confirmed working! :-D

**Comment by zerojay** [comment]
Ah, you're right. The issue here is that we don't have a core that supports achievements on NES which is an upstream issue.

**Comment by joolswills** [comment]
Can this be closed now ?

**Comment by kryptalivian** [comment]
Yes, but can we get a compatible nes emulator?

**Comment by zerojay** [comment]
That's going to have to come from upstream, isn't it?

I would say this should be closed.

**Comment by gizmo98** [comment]
Seems to be QuickNES supports achievements:
https://pitendo.wordpress.com/2016/01/07/adding-achievements-to-nes/

We have no QuickNES module atm.

**Comment by zerojay** [comment]
I've submitted a pull request for the QuickNES module specifically to support achievements for the NES platform: https://github.com/RetroPie/RetroPie-Setup/pull/1270
