### ISSUE TITLE
Alsa error

### ISSUE THREAD

**Issue by josepe36** [RetroPie/RetroPie-Setup#1133]
Hello

New on raspberry i ve trie retropie.
The emulastation start and freeze on loadi g page.
The i look in tty an error message tell me a out Alsa device error.
Is it a classic problem  ?
The raspberry is b2+

I ve not installed on sd card but usb device without dd.
Are there specifics scripts at boot level i missed to starr

**Comment by joolswills** [comment]
I doubt it is alsa related, but please could you start by using the forum for help, and we can go from there, as this is likely a configuration issue.  https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
