### ISSUE TITLE
Trouble viewing emulationstation via remote desktop on PC

### ISSUE THREAD

**Issue by Flourpowder** [RetroPie/RetroPie-Setup#1134]
I'm fairly new to the raspberry pi (and Linux). I have searched for days, and found unrelated topics. I am trying to connect my laptop (windows 10) to the raspberry pi via remote desktop. This works as far as I can tell as I log in, and it gives me the pi@retropi ~ $ line. But emulation station is running on the raspberry pi (it is hooked up via HDMI to my tv). So, I try to just see what the command emulationstation on the remote desktop app would do, and it gives the following message (on the remote desktop connection screen and in a loop):

Xlib: extension "RANDIR" missing on display ":10.0".
Keyboard layout unknown, please send the following to the SDL mailing list (sdl@libsdl.org):
lvl0: Error creating SDL window!
       Could not get EGL display
lvl0: Renderer failed to initialize!
lvl0: Window failed to initiliaize!

Again, not sure if that is the way I was supposed to do it or if the remote desktop connection should have just immediately shown emulationstation like the raspbery pi is showing on the tv, but any help would be much appreciated.

**Comment by joolswills** [comment]
This is not a support area - please use the retropie forum https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
