### ISSUE TITLE
[lr-reicast] testing

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#1139]
I just saw a new "libretro" repo has been created here https://github.com/libretro/reicast-emulator. Needs further testing. Will keep this thread updated. Needs also comparison with the "non lr" reicast version from Retropie.

**Comment by robertybob** [comment]
Great news!

**Comment by robertybob** [comment]
Slightly off-topic, but does this have any impact on the non-reicast version that RetroPie uses? Will different flags be needed when compiling? https://github.com/reicast/reicast-emulator/pull/832

**Comment by joolswills** [comment]
what do you mean by "impact" ?

**Comment by joolswills** [comment]
We will need to update our module when our RPI branch is updated, and update for the X11 build to use SDL2.

**Comment by joolswills** [comment]
This ticket is unrelated - please use foe forum for discussion etc.

**Comment by joolswills** [comment]
(or open a new ticket if you have an issue with something related to development)

**Comment by gizmo98** [comment]
Lr-reicast cannot be build atm.

**Comment by gizmo98** [comment]
And sdl2 support would be nice if input setup is easier.

**Comment by joolswills** [comment]
we include a lr-reicast module now (thanks @gizmo98) so I'm going to close this - doesn't work on RPI, but it can be tested again in the future.
