### ISSUE TITLE
USB controller converter gets added twice.

### ISSUE THREAD

**Issue by phaseIV** [RetroPie/RetroPie-Setup#1140]
Hi and congrats on a new release! I have this issue where my USB controller converter (it's a TwinUSBJoystick, for connecting two ps1 controllers) is registered twice when entering a game.

After a game is started the yellow line at the bottom reads; 'Twin USB Joystick configured in port #0', 'Twin USB Joystick configured in port #1' and again 'Twin USB Joystick configured in port #0', 'Twin USB Joystick configured in port #1'. So in the end the RGui menu gives me four controllers to choose the input from.

It is caused by this setting in retroarch.cfg;
#Input device driver. (Valid: linuxraw, sdl, dinput)
input_joypad_driver = sdl2

I tried changing the driver in retroarch-joypads/TwinUSBJoystick.cfg from 'udev' to 'sdl2' but the issue remains.

**Comment by gizmo98** [comment]
Change `input_joypad_driver = sdl2` into `input_joypad_driver = udev`.

**Comment by phaseIV** [comment]
Well, yeah, that’ll fix the issue but I prefer to use sdl2 since it treats analog devices much nicer.

I already used sdl2 with older RetroPie versions (and experienced the issue described above) but since sdl2 became the default driver (in 3.3) I decided to file it as an issue.

**Comment by joolswills** [comment]
I would report it upstream to RetroArch then.

**Comment by phaseIV** [comment]
Okay, I'll move over to RetroArch then, thanks. With an issue like this it's hard to specify where it happens and what territory it belongs to. Close this issue if you like.

**Comment by joolswills** [comment]
Understood - thanks.

I wonder if we should change the default back to udev - there are other issues with the sdl2 driver it seems in regards to matching autoconfig against device name. I will do some further teting.

**Comment by joolswills** [comment]
The driver has now been changed back to udev.
