### ISSUE TITLE
SGX isn't compatible anymore (Retropie 3.3)

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/RetroPie-Setup#1142]
Making the "lr-mednafen-pce-fast" as main emulator of PC Engine it's pretty wise, mainly because has the standard button mapping BA instead BY, the problem it's that doesn't support SGX (Super Grafx) games, but the emulator "lr-mednafen" does, and i cannot find that emulation core in the latest retropie build.

**Comment by HerbFargus** [comment]
The current default superseded the previous as the upstream repi no longer exists:

https://github.com/RetroPie/RetroPie-Setup/commit/514f68579c6657ecd875cff13f4f8e6932a6ba75

As far as button remappings use the core remap options or set up your own custom configs for it. 

http://m.youtube.com/watch?v=liJKFUZX4PM
