### ISSUE TITLE
Dreamcast

### ISSUE THREAD

**Issue by roydenstorm** [RetroPie/RetroPie-Setup#1147]
Have the Dreamcast emulator working, it loads no problem, but I cant get passed the "set date/time" screen, I am able to change the date/time, so left/right and up/down work, I just cannot use "select" button. I've tried changing the config files for my controller(xbox 360 wireless) and anything else I could think of. Any and all help would be greatly appreciated.

p.s. I also just got the Intellivision emulator working though I am having some controller issues with it as well, I just haven't taken a look yet to see if I can fix it, but if anyone already knows what to do please let me know :)

Thanking you all in advance for your time and effort it will be greatly appreciated :)

**Comment by joolswills** [comment]
Please use the forum for help - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by roydenstorm** [comment]
ive been trying to post to that forum but cannot seem to find anywhere that allows me to create anew post lol, really user friendly that site is lol 

    On Thursday, December 24, 2015 11:48 AM, Jools Wills <notifications@github.com> wrote:
 

 Please use the forum for help - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md—

**Comment by gizmo98** [comment]
Press A/B/X or Y. Don't press Select. I don't think you will get any help today. It's Christmas. No one should be on the forums now.

**Comment by gizmo98** [comment]
Just for information. The dreamcast controller had no select button.

**Comment by roydenstorm** [comment]
though I appreciate the response I don't think you're reading my problem correctly. The "select" button is on-screen, maybe  take a look at the dreamcast emulator and see what I'm talking about :)

**Comment by roydenstorm** [comment]
and ill never get help on that forum because I cant even find the option to create a new post lol

**Comment by roydenstorm** [comment]
though I appreciate the response I don't think you're reading my problem correctly. The "select" button is on-screen, maybe  take a look at the dreamcast emulator and see what I'm talking about :) 

    On Thursday, December 24, 2015 12:43 PM, Stefan <notifications@github.com> wrote:
 

 Press A/B/X or Y. Don't press Select. I don't think you will get any help today. It's Christmas. No one should be on the forums now.—

**Comment by InsecureSpike** [comment]
got the forum you want to post in, then scroll right to the bottom, that gives you the option to create a new topic......

**Comment by gizmo98** [comment]
Narf. It states "select" but means press X Y or A B. ;-) 
If you press select reicast quiets.

**Comment by gizmo98** [comment]
It just means "select this date" and does not mean "press select". Ok, it os confusing 😉

**Comment by roydenstorm** [comment]
I tried every button on my controller and keyboard long before I came to this forum for help, I appreciate your trying but still stuck on that damn screen ;(

**Comment by roydenstorm** [comment]
lol well pressing every single button on my controller and keyboard does absolutely nothing!!! so yes it is so confusing 

    On Thursday, December 24, 2015 1:48 PM, Stefan <notifications@github.com> wrote:
 

 It just means "select this date" and does not mean "press select". Ok, it os confusing 😉 —

**Comment by joolswills** [comment]
Please use the forum as requested.
