### ISSUE TITLE
Add platform x86

### ISSUE THREAD

**Issue by gizmo98** [RetroPie/RetroPie-Setup#1148]
I play with the idea to use a cheap x86 barebone for RetroPie as a speed upgrade.
I have modified the script a little bit so platform x86 will be detected:
https://github.com/RetroPie/RetroPie-Setup/compare/master...gizmo98:x86?expand=1

Tested with Debian Jessie, Cinammon, VirtualBox, snes9x-next, nestopie, genesis-plus-gx and emulationstation. ;-)

The user has to be in group admins to run setup script. RetroPie app launcher can be found in start menu (type retropie in search box).

**Comment by joolswills** [comment]
Looks good! :)
