### ISSUE TITLE
RetroArch MAME mapping issues?

### ISSUE THREAD

**Issue by rastolpho** [RetroPie/RetroPie-Setup#1151]
When using AdvMAME, cannot vine bind the circle, triangle, square and cross on a PS3 controller using Bluetooth.

Switched over to lr-mame4all and after setting up proper mapping (for coins and all) only P1 gets saved (but simulate D-pad to Analog always gets reset). This is an issue for games that need coins to play on specific players such as TMNT or Simpsons as coins need to be inserted as Players1, 2, 3 and 4 for different characters.. All this using the same controller.

Using MAME4All the mapping gets saved no problem, however, I cannot find a way to stretch the screen to wide as I have done with the lr-cores on retroarch.cfg. Any help on this one would be appreciated!

**Comment by joolswills** [comment]
You might do better to get help on the forum first - There looks to be an answer for advmame in http://blog.petrockblock.com/forums/topic/mapping-ps3-buttons-in-advancemame-1-2-retropie-3-0/
