### ISSUE TITLE
lr-ppsspp Not Reading Config File

### ISSUE THREAD

**Issue by craigerskine** [RetroPie/RetroPie-Setup#1157]
I'm trying to override some settings from the default retroarch config for PSX and PSP... it works for PSX but not PSP.

I think the file from /opt/retropie/configs/psp/retroarch.cfg is not being read. I use the same lines in both PSX and PSP configs:

    video_shader_enable = false
    rewind_enable = false

Again, it works in PSX but not PSP. And yes, when I launch a game it is indeed using lr-ppsspp.

**Comment by joolswills** [comment]
Please use the RetroPie forum for help. https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by craigerskine** [comment]
I don't need help, I already know how it is supposed to work, I'm reporting a bug.

**Comment by joolswills** [comment]
I believe it's like a configuration issue your end hence suggesting you use the forum first. if reporting a bug, I will require the complete configurations etc (can use pastebin.com or similar for large files).

**Comment by joolswills** [comment]
configs/all/retroarch.cfg
configs/psp/retroarch.cfg
configs/psp/emulators.cfg please.
