### ISSUE TITLE
Configure Retroarch Controller Missing

### ISSUE THREAD

**Issue by marvinej** [RetroPie/RetroPie-Setup#1159]
The Configure Retroarch controller option is missing from my retropie-setup thus i am unable to use my snes controller by following the instructions in the wiki

running the latest version

**Comment by gizmo98** [comment]
Which wiki page do you refer to? Retroarch guys removed retroarch-joyconfig a long time ago. There is no retroarch-joyconfig anymore. Controllers should be setup through emulationstation.

**Comment by marvinej** [comment]
The video you link to for configuring usb controllers says to use this
option. If this is no longer required then why doesnt the NES work with my
usb snes controller out of the box? It wont work with the xbox controller
either when i install xboxdrv. The main interface works but the emulators
dont.

**Comment by joolswills** [comment]
please reference the wiki page in question. thanks.

**Comment by HerbFargus** [comment]
The wiki is created by users, and most videos are outdated as the retroarch-joyconfig was a somewhat recent removal. I will make an updated video at some point (hopefully soon) and update the wiki
