### ISSUE TITLE
Wonderswan Save Issue

### ISSUE THREAD

**Issue by Omnija** [RetroPie/RetroPie-Setup#1162]
Wonderswan and Color save games in the bios folder.

These lines should be added to each individual emulators retroarch.cfg to make sure they save in the game folder.
system_directory = /home/pi/RetroPie/roms/wonderswancolor
system_directory = /home/pi/RetroPie/roms/wonderswan

Neogeo Pocket and Color save in the home folder still unsure why or how to redirect them.

**Comment by gizmo98** [comment]
Sounds like a core problem because system_directory is for bios files https://github.com/libretro/RetroArch/blob/master/retroarch.cfg#L74

**Comment by Omnija** [comment]
I believe it's the "mednafen" emulators that tend save where they please.

**Comment by gizmo98** [comment]
What happens if you set `savefile_directory = /home/pi/RetroPie/roms/wonderswan`?

**Comment by Omnija** [comment]
nothing, i've already tried multiple times this was the only method that worked. I still yet to find a method to get neogeo pocket working.

**Comment by gizmo98** [comment]
Ok. I had seen some lines of code suggesting this:
https://github.com/libretro/beetle-wswan-libretro/blob/master/libretro.cpp#L542

On the other hand i do not understand why system_directory is base_directory:
https://github.com/libretro/beetle-wswan-libretro/blob/master/libretro.cpp#L524

**Comment by Omnija** [comment]
As for the Neogeo Pocket emulators, i don't think they are even declared a location to save. Which is probably why they can't be directed in any way.

**Comment by HerbFargus** [comment]
we had the same issue with gpsp, save states only work in the directory it's installed in

**Comment by joolswills** [comment]
@HerbFargus that wasn't a libretro emulator issue though afair

**Comment by HerbFargus** [comment]
Ah, yeah i suppose you're right.

**Comment by gizmo98** [comment]
@joolswills @HerbFargus 
In my opinion we could set system_directory for both systems if wonderswan needs no bios file?!

**Comment by Omnija** [comment]
That's what i did to correct wonderswan systems but didn't work for Neogeo Pocket/Colour  (saves home folder of pi)

**Comment by HerbFargus** [comment]
@Omnija 

For NeoGeo Pocket try these fixes for the save dir:

https://github.com/HerbFargus/beetle-ngp-libretro/commit/590b6b496b65d31458351840e221e3cf4b16911d

**Comment by HerbFargus** [comment]
@Omnija try out the fix on my branch and tell me if it fixes the issue:

https://github.com/HerbFargus/beetle-ngp-libretro/tree/save-fix

**Comment by HerbFargus** [comment]
the `savefile_directory` code still needs to be sorted upstream but now in game saves will at least default to the rom directory now. same for NGP
