### ISSUE TITLE
Disconnect BT ps3 controller

### ISSUE THREAD

**Issue by havnar** [RetroPie/RetroPie-Setup#1167]
As far as I could read in the documentation there is no way to disconnect a ps3 controller once it has been paired. This sucks all the juice out of my ps3 controllers when I leave the pi idle, unless I choose to restart the whole system. 

Is this a valid workaround or am I doing a 'feature request' here to unpair BT devices via the menu?

**Comment by gizmo98** [comment]
Press PS button for 10s.

**Comment by havnar** [comment]
I have added this to the wiki page.

**Comment by joolswills** [comment]
thanks
