### ISSUE TITLE
Transfering roms directly to sd card using windows

### ISSUE THREAD

**Issue by bestarock** [RetroPie/RetroPie-Setup#1174]
Hello everyone, i'm kind of new to all this, in the past few weeks i've done many test to get everything straight to play all my retro games. I think i learn from my mistakes but i have an this reccurent problem.

Here's my set : 
Pi 2 (Overclocked at pi 2 setup)
Fresh retropie 3.3.1 image
Sandisk microsd 64G SDXC
Ps3 controller

Here's my problem : 

Is it ok to just take plug my card in my pc and manually transfer the roms to the right directory?

All i see on the wiki or on google are usb, FTP and Samba transfer?!

I ask this cause at first it work, i can play games for days, but i have no idea why but after a random reboot i need to run a manual fsck and have some line like:

has 75 multiply-claimed block(s), shared with 3 file(s):
Clone multiply-claimed blocks... i

I'm sure you know that kind of stuff.

Is this related to the way i tranfer roms? Or can i do something basic to avoid that?

Thank you

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

Please use the RetroPie forum for support.
