### ISSUE TITLE
setting screen lenght and height manually

### ISSUE THREAD

**Issue by chrispin86** [RetroPie/RetroPie-Setup#1179]
In an older Retropie installation i was able to set the screen height and lenght manually for the different emulators in the retroarch menu. So it fills out all the screen. In the newest installation i do not find the possibility to change them.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

Please use the forum for support requests. Thanks.
