### ISSUE TITLE
Kodi: no subtitles displayed

### ISSUE THREAD

**Issue by havnar** [RetroPie/RetroPie-Setup#1192]
I have tried some .mkv files but there is nothing being displayed in regard of subtitles.
The UI says it is enabled but nothing is rendered.

Is this a bug or just a missing feature for now?

**Comment by robertybob** [comment]
Not a RetroPie issue (?) have you looked here? http://kodi.wiki/view/Subtitles

**Comment by havnar** [comment]
This relates to the retropie package of Kodi of course, and yes I have looked there, subtitles should be enabled but are not displayed.
Kept the settings vanilla.

**Comment by zerojay** [comment]
You'll probably have to ask the Kodi upstream developers about that. Perhaps it does not support your form of embedded subtitles.

**Comment by joolswills** [comment]
we use the kodi packages shipped with raspbian, so nothing we can do sorry.
