### ISSUE TITLE
lr-mednafen-pce missing from Retropie 3.4?

### ISSUE THREAD

**Issue by davidj1987** [RetroPie/RetroPie-Setup#1195]
Hey,

I found that some PCE/TG16 games work better, and Supergrafx games work in "lr-mednafen-pce" plain not the fast one. The "lr-mednafen-pce-fast" core works.

I updated to 3.4 and found that it's not working. I tried looking in the install script and cannot find it so I cannot reinstall from the update script. Just curious if it was intentional, but again the pce-fast core still works. The non-fast version is selectable in the option menu you can start before you load a rom though.

**Comment by HerbFargus** [comment]
mednafen-pce doesnt exist anymore. it was superceded by lr-mednafen-pce-fast

https://github.com/RetroPie/RetroPie-Setup/issues/1088

**Comment by davidj1987** [comment]
Hmm... there are some advantages to the non-fast core. By any chance is it possible that Beetle/Mednafen SGX could be ported to Retropie?

**Comment by joolswills** [comment]
We could certainly try it.

**Comment by HerbFargus** [comment]
@joolswills

Is this what we essentially removed? 

https://github.com/libretro/beetle-supergrafx-libretro

**Comment by joolswills** [comment]
well not according to one of their devs, but perhaps they did rename it or they did a better port. I can add it and see.

**Comment by davidj1987** [comment]
Thanks HerbFargus for referencing the past issue and joolswills looking into this. 

The SuperGrafx games that ran in the older mednafen-pce were fullspeed and no issues, a small library sure

**Comment by HerbFargus** [comment]
7 games from what I understand but also supposedly backwards compatible with all of the previous games which makes it more like hundreds. (Unless of course this port only provides support for those 7 games)

**Comment by davidj1987** [comment]
The supergrafx port, on Windows x64 (only version I tried) also runs PC Engine and PC Engine CD games. The Supergrafx was just a beefed up PC Engine and played all the games on hucard and CD.

**Comment by joolswills** [comment]
i've built it. will test and add if it works.

**Comment by joolswills** [comment]
added - if you update retropie-setup you can find it in experimental (to build from source)

**Comment by davidj1987** [comment]
I get an error saying could not successfully build as "mednafen_supergrafx_libretro.so" could not found.

**Comment by joolswills** [comment]
I would need to see a build log from logs/. Probably out of memory or something - I didn't test on wheezy either.

**Comment by davidj1987** [comment]
As requested

[rps_2016-01-20_174139.txt](https://github.com/RetroPie/RetroPie-Setup/files/97832/rps_2016-01-20_174139.txt)

**Comment by joolswills** [comment]
looks like it needs a modification to add "-lrt" to the link libs. This wasn't an issue on Jessie - assuming you are on wheezy, I would get a new 3.4 Jessie image anyway, as wheezy is not going to be supported in the future.

**Comment by davidj1987** [comment]
Did a fresh install from a 3.4 Jessie image, and it works great with the
SuperGrafx games!

**Comment by davidj1987** [comment]
Thanks again for adding the core. If I could make one more suggestion, IMO I would keep both the Supergrafx core (if it gets out of experimental) and the PCE Fast Core. 

For example, Space Harrier, both the US and JP versions do not run on the Supergrafx core as they will crash. Turns out this happens on real hardware when it is in Supergrafx mode. What you can also do is use System Card 3.0 with the Supergrafx Core and use a lesser version of the system card with the PCE Fast Core. No idea if other games have issues though.

I know the CD version of Altered Beast (again on real hardware) only works on System Card 1.0 and other games have easter eggs if you have a lesser system card than 3.0 like Dracula X so what I have done is changed the BIOS directory for PCE Fast to use System card 1.0 in a different folder (still needs to be named syscard3.pce) and it works very well.

**Comment by joolswills** [comment]
No intention of removing the current core.
