### ISSUE TITLE
Retropie PI and CLRMAMEPRO

### ISSUE THREAD

**Issue by egnolegno** [RetroPie/RetroPie-Setup#1196]
Hi, I need help to understand why some ROMSET (AMIDAR, ASTEROIDS as examples) working on Windows MAME emulator do not work on Retropie PI, can you help on this?
Can CLRMAMEPRO help on this?
Thanks and regards

**Comment by objectchris** [comment]
it's all in the wiki https://github.com/RetroPie/RetroPie-Setup/wiki/Managing-ROMs

**Comment by HerbFargus** [comment]
Github is for bug reprts, use the forum for support. 

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by egnolegno** [comment]
Why did you close this issue? On the answers there' s no solution for my issue.
Thanks

Ennio Dolfato

**Comment by egnolegno** [comment]
No, not this issue

Ennio Dolfato

**Comment by joolswills** [comment]
Apologies, but this issue tracker is used for retropie-setup bugs. your issue is related to romsets and the forum is a better place. cheers
