### ISSUE TITLE
change dialog with xdialog

### ISSUE THREAD

**Issue by b4zz4** [RetroPie/RetroPie-Setup#1199]
More beautiful dialog of configuration in rasp-config and others

http://xdialog.free.fr

**Comment by joolswills** [comment]
This would depend on an xserver though. It could be implemented perhaps for when running on x86 under X, but no use to the rpi etc.

**Comment by b4zz4** [comment]
emulationestation dont work over Xserver?!

Jools Wills:
> This would depend on an xserver though. It could be implemented perhaps for when running on x86 under X, but no use to the rpi etc.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/RetroPie/RetroPie-Setup/issues/1199#issuecomment-173592667
> 

-- 
http://maquinaslibres.tk
gpg: http://ba.zza.pl/bazza.asc

**Comment by joolswills** [comment]
It does, but it is only built like that for X11 target (eg retropie-setup on a PC). On the RPI we use the framebuffer directly, which is why retropie-setup is designed for the terminal.

**Comment by b4zz4** [comment]
yes. I thought it how an alternative version when it uses  a monitor and
no a terminal.

**Comment by joolswills** [comment]
The other issue is that xdialog is no longer maintained and not even shipped with Debian, so it's not worth the effort unless there is an alternative that is maintained and includes all the dialog functionality.

**Comment by joolswills** [comment]
There is "zenity" - not sure if it is a drop in replacement though.

**Comment by joolswills** [comment]
Yeh zenity is not compatible either.. Sorry but this is a wontfix - you will have to make due with opening a terminal :)
