### ISSUE TITLE
Copyright of Screenshots in the Wiki?

### ISSUE THREAD

**Issue by edent** [RetroPie/RetroPie-Setup#1204]
I'm writing an article about RetroPie for a magazine and I'd like to include some of the set-up screenshots from your the [Wiki](https://github.com/RetroPie/RetroPie-Setup/wiki/First-Installation)

For example https://cloud.githubusercontent.com/assets/10035308/9140482/cf42f25c-3cee-11e5-8f91-c1fc1c57175c.png

I appreciate that the source code is covered by the GPL, but I wondered if the documentation was covered by something else.

Thanks :-)

**Comment by InsecureSpike** [comment]
hi, if you need any of my theme screen shots they can be found

https://insecurespike.wordpress.com/clean_canela-screenshots/

use as you like

**Comment by joolswills** [comment]
Please go ahead and use the images. Thanks.

**Comment by edent** [comment]
Thanks - much appreciated.
