### ISSUE TITLE
NES and SNES controllers in RetroPie

### ISSUE THREAD

**Issue by JoargTheBard** [RetroPie/RetroPie-Setup#1206]
I and currently working on putting a raspberry pi into an old nes i have. i am using Retropie 3.4  to get the controller ports working, I ordered 2 "SNES/NES Retrokits" from RetroUSB.com. after getting everything up and running with the nes ports, I had the idea to solder a couple snes controller ports to the adapters as well, so that i could use either nes or snes controllers with any of the emulators. My problem is that with the controllers having different numbers of buttons, i have to reconfigure the controls every time i want to switch controller types. is there any way to have both types of controllers have the right buttons configured? Any Help is greatly appreciated.

**Comment by joolswills** [comment]
Not unless you script something to change the configs around as they will be identified as the same joystick device I guess. Please use the forum for support though as this area is used as a bug tracker - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
