### ISSUE TITLE
Installing all themes

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1208]
Could we get an option to install every theme at once rather than doing them one at a time?

**Comment by joolswills** [comment]
Not sure it's a good use of development time - the themes are detailed on the wiki. it doesn't take that long to install them all (no idea why you would want to).

**Comment by HerbFargus** [comment]
It would also cause issues if someone had multiple systems and they chose a theme that gave them a whitescreen. I would just as well keep it as it is.

**Comment by ProxyCell** [comment]
agree with @joolswills and @HerbFargus
