### ISSUE TITLE
Retropie 3.3.1 will not boot fra SD-Card

### ISSUE THREAD

**Issue by hoghrengoring** [RetroPie/RetroPie-Setup#1214]
Model: Raspberry Pie 2 Model B v1.1
Software: Retro pie
Image: retropie-v3.3.1-rpi2.img (Wheezy Standard) and   retropie-v3.4-rpi2.img (Wheezy Standard) 
Power supply: 5V 2A
Micro SD-Card: 8Gb Formated with SD Formatter SW.
Issue: 
First boot
When raspberry pie starts retro pie.
starts Picture "Retro Pie" shows. OK
Problem starting EmulationStation.
Error command.:
	 No more space on device. 
	Press esc to return to console.

what(): boost::filesystem::create_directory: No space left on device: "/home/pi/.emulationstation/gamelists/amstradcpc"
/usr/bin/emulationstation: line 20:

((( and error lines continues infinite )))

Nothing happens when using keyboard.

Conslussion:
Retro Pie not working. What to do?
![img_6770](https://cloud.githubusercontent.com/assets/16955431/12673866/c310917c-c67f-11e5-8743-a876dd8368f9.JPG)

**Comment by joolswills** [comment]
There should be free space on initial boot unless you copied some additional files on ? Please can you use the forum for support first as I don't think this is a bug but related to your set up. There is no RetroPie 4.x image for Wheezy either. 

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
