### ISSUE TITLE
Arcade system for all arcade emulators

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1219]
I think it would eliminate some confusion to have an arcade rom folder for all the arcade systems as the user has the choice to select which emulator each rom uses. Would also consolidate a potential 4 systems depending on how many romset versions the user has.

**Comment by joolswills** [comment]
I agree, but I would like to keep the existing folders still for those that want separate romsets etc.

**Comment by HerbFargus** [comment]
Of course. I meant consolidation for those who would rather have them all in the same folder (just so 3 mame logos don't show up in emulationstation) we definitely should leave what is there currently for those who only have one romset.

**Comment by joolswills** [comment]
Yep. sounds good :)

**Comment by HerbFargus** [comment]
Resolved as of https://github.com/RetroPie/RetroPie-Setup/pull/1221
