### ISSUE TITLE
lr - PPSSPP and PPSSPP emulators not found on script

### ISSUE THREAD

**Issue by MegaFish0527** [RetroPie/RetroPie-Setup#1220]
The lr - PPSSPP and PPSSPP are not visible to download in experimental and individual emulators menu. I have upgraded RetroPie and retropie-setup script to the latest version and rebooted as well. It seems that others also have this issue.

**Comment by joolswills** [comment]
You already have a forum post regarding this and I have replied to you there.

**Comment by MegaFish0527** [comment]
and your answer did not fix the problem... I checked under every single menu in the setup menu and its not there.

**Comment by joolswills** [comment]
I have answered since then.

**Comment by joolswills** [comment]
I asked a question you have no yet replied to.

**Comment by joolswills** [comment]
In any case, if an answer didn't help you should follow up on the original thread, rather than opening another conversation here.
