### ISSUE TITLE
Add Stratagus support

### ISSUE THREAD

**Issue by timfel** [RetroPie/RetroPie-Setup#1227]
Would Stratagus be something worth adding? It can be used to play Warcraft (I+II) as well as Starcraft, provided you have the original games for game-file extraction. If that sounds useful, I can prepare a PR.

**Comment by joolswills** [comment]
Sure. thanks.

**Comment by HerbFargus** [comment]
it would be interesting to see the performance on this vs dosbox

**Comment by HerbFargus** [comment]
Source code for reference:

https://github.com/Wargus/Stratagus

**Comment by HerbFargus** [comment]
added as of https://github.com/RetroPie/RetroPie-Setup/pull/1338
