### ISSUE TITLE
 look into using xboxdrv for joystick to keyboard for kodi

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1231]
Should be able to use xboxdrv to map joystick event device to keyboard, to workaround using a kodi without joystick support built in (the raspbian shipped one).

**Comment by zerojay** [comment]
I started looking into this myself and I think one of the things that would really help out our implementation is how we handle xboxdrv. Right now, we write our options directly into rc.local. I think it would be better if we either used xboxdrv as a daemon (using /etc/init.d/xboxdrv start to run) or if we wrote out all our xboxdrv options out to a separate file (/etc/xboxdrv.sh?) that we would run from rc.local. This would make things a lot easier for us to kill our current xboxdrv when launching Kodi so we can start Kodi up with its own xboxdrv options and then relaunch after we quit Kodi. Anytime we'll want to reinitialize xboxdrv, we can just run that script instead.

Doing some testing on this now.

**Comment by joolswills** [comment]
having an init.d script would be better if we handle the configuration properly - using the -c config file parameter (there is an example in the wiki that is not an improvement really imho).

**Comment by joolswills** [comment]
At least for the RPI this is no longer needed as the pipplware repo we use has joypad support - but we still need to generate the  config automagically, so I shall leave this open for that.

**Comment by joolswills** [comment]
actually no I wont - it makes this thread confusing.
