### ISSUE TITLE
Retropie 3.4 and Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by lucasferreiraestevam** [RetroPie/RetroPie-Setup#1232]
After rolling all over the internet looking for Raspberry Pi model 2 b restarting and losing video signal, I found out it was the frequency of the processor I configured to 400mhz and it worked perfectly. :D

**Comment by joolswills** [comment]
Glad you have it sorted. Please use the forum for discussion / tips and so on - thanks https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
