### ISSUE TITLE
Launch Menu Art crashing ScummVM

### ISSUE THREAD

**Issue by BenWlson** [RetroPie/RetroPie-Setup#1238]
If I enable the new "Launch Menu Art" runcommand feature, ScummVM will crash when trying to load a scraped .svm file. ScummVM will still work fine if I load the main GUI from the .sh file, but it crashes for every game shortly after the box art in displayed when loading the games from .svm files.  Everything works fine again after disabling the "Launch Menu Art" feature.

**Comment by joolswills** [comment]
we might need to disable it for scummvm then, or make scummvm wait for fbi to complete.

**Comment by joolswills** [comment]
Please update retropie-setup from the gui, and try now.

**Comment by BenWlson** [comment]
All better now
