### ISSUE TITLE
Audio Mixer

### ISSUE THREAD

**Issue by BenWlson** [RetroPie/RetroPie-Setup#1241]
If I load the audio settings from the RetroPie menu in Emulationstation, everything works fine, but if I load the RetroPie Setup script from the command line and try to enter the audio mixer settings, it will not respond to any key presses. I have to exit out with Ctrl-C.

**Comment by joolswills** [comment]
Thanks. tty stdin issue - thought I had fixed this. You can access the audio settings via the RetroPie menu directly though instead of via retropie-setup until this is sorted.

**Comment by joolswills** [comment]
please update retropie-setup and try again

**Comment by BenWlson** [comment]
That worked!
