### ISSUE TITLE
kodi "fix" in readme closes kodi but doesn't reopen retropie

### ISSUE THREAD

**Issue by havnar** [RetroPie/RetroPie-Setup#1249]
I have had to apply the "black screen fix" to be able to exit Kodi. (see kodi readme)
However, now when kodi has stopped, retropie does not start back up.

**Comment by HerbFargus** [comment]
Please use the forum for support requests as the kodi fix is currently resolved on the latest release of retropie (Jessie builds kodi 15 which doesn't have the black screen bug) 

Upgrade to Jessie or continue this conversation on the forum.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
