### ISSUE TITLE
Can't pass ou configure the date/hour screen of dreamcast

### ISSUE THREAD

**Issue by andrergc** [RetroPie/RetroPie-Setup#1255]
Hi guys, I'm stuck on this screen, I can change date but when I go to the "select" button, I pressed all buttons and none seems to work. I'm using dualshock 4...pls help me!

**Comment by zerojay** [comment]
You need to set your controls properly to get past it.

**Comment by joolswills** [comment]
Please use the forum for support first - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md thanks.

**Comment by andrergc** [comment]
how I do that?
