### ISSUE TITLE
Terminal permissions

### ISSUE THREAD

**Issue by LegionOblivion** [RetroPie/RetroPie-Setup#1256]
Just loaded the new image and I seem to be having permission issues at the terminal.....typed in the wget command to download the scraper and it came back saying  'permission denied' ....same with the  rm command 'permission denied' ....no idea why as this did not happen with previous images -  also had an issue where F4 to terminal casued the text to go completely grey without colored prompts - anyone else getting these issues?

**Comment by joolswills** [comment]
Please use the forum for support first - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md thanks.

**Comment by LegionOblivion** [comment]
Will do, thanks!
