### ISSUE TITLE
F4 Key and Atari800

### ISSUE THREAD

**Issue by lazerus2000** [RetroPie/RetroPie-Setup#1260]
The F4 key is used to exit EmulationStation, it is also used to start Atari800 games which is fine if you are using a keyboard but not if the setup is inside an arcade cabinet.  An arcade button acting as  "Start" for Atari games can be pushed by mistake whilst in ES putting the player into Linux.
Is there any way I can disable the function of F4 in ES as I don't actually need this for Linux access.

**Comment by joolswills** [comment]
You would need to modify the emulationstation code.
