### ISSUE TITLE
Kernel module not loadable at startup

### ISSUE THREAD

**Issue by rsa2016** [RetroPie/RetroPie-Setup#1263]
Hi,
i compiled an installed the gpio-driver from digital lumberjack (https://github.com/recalbox/mk_arcade_joystick_rpi). Loading the module with modprobe works fine, but loading it automaticaly with /etc/modules did not work.
I´ve searched and read a lot of websites and i´ve no idea anymore. So it might be a flaw. Maybe you can help.
Thx
René

**Comment by joolswills** [comment]
This is not a support area - please use the forum https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md - probably you are putting the module options in /etc/modules but they need to be in a file in /etc/modprobe.d/
