### ISSUE TITLE
Directlaunch Runcommand Crash

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1271]
Before we actively pursue setting certain systems (e.g. Kodi see https://github.com/RetroPie/RetroPie-Setup/pull/904)  as directlaunch from emulationstation we need to

- create a function for directlaunch
- address crashing on exit when implemented with runcommand

From testing kodi works fine when launched directly with kodi-standalone but if runcommand is used it crashes.

**Comment by HerbFargus** [comment]
Just for reference this is my kodi crash log:

http://pastebin.com/KHT2eTXZ

**Comment by joolswills** [comment]
I just tested and it seems fine here

launching with

```
  <system>
    <name>kodi</name>
    <fullname>Kodi</fullname>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 kodi-standalone</command>
    <theme>kodi</theme>
    <directlaunch>true</directlaunch>
  </system>
```

**Comment by joolswills** [comment]
```
  <system>
    <name>kodi</name>
    <fullname>Kodi</fullname>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ kodi</command>
    <theme>kodi</theme>
    <directlaunch>true</directlaunch>
  </system>
```
works too (and gives the ability to the user to control the commandline etc)

**Comment by HerbFargus** [comment]
No crash on exit? May have been addressed with your last modification to fb_restore. If you're happy I'm happy.

**Comment by joolswills** [comment]
must have been that. or something else. I will switch kodi to direct launch in a PR and we can test.

**Comment by HerbFargus** [comment]
Brilliant :)

**Comment by HerbFargus** [comment]
Seems resolved now.

**Comment by HerbFargus** [comment]
Upon further testing it seems there is an issue with directlaunch in that once implemented it will crash emulationstation when switching themes through the start menu in emulationstation.

To reproduce:

- Install updated kodi from the retropie setup script
- install a different theme than the default
- switch to the new theme - Will crash.

**Comment by joolswills** [comment]
This should be opened against ES then.

**Comment by HerbFargus** [comment]
opened here: https://github.com/RetroPie/EmulationStation/issues/37
