### ISSUE TITLE
xbox one controller setup

### ISSUE THREAD

**Issue by eblabs** [RetroPie/RetroPie-Setup#1272]
There was a mention of partial xbox one controller support in the 3.4 release notes. What exactly has changed, and is there anything specific I need to do in order to use an xbox one controller?

Thanks!!

**Comment by zerojay** [comment]
This should be a forum post, not a post to the issue tracker.

Our version of xboxdrv has some preliminary support for Xbox One controllers. You'll have to try it out and let us know how it works for you as I don't think any of us actually have one to test with.

**Comment by joolswills** [comment]
Yeh please use the forum, thanks. - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by eblabs** [comment]
Thanks for the quick reply! Ill do some tests and follow up there.

Cheers!
