### ISSUE TITLE
Replace uae4all with uae4all2

### ISSUE THREAD

**Issue by postman83** [RetroPie/RetroPie-Setup#1276]
Hi,

first of all, thanks fot the great work with this fantastic program.
The question is very simple but i'm a newbie, how can i replace an emulator in retropie? I need to replace uae4all with uae4all2.
I simply install the image of retropie with all emulator in a sd and now i don't know how to replace them.
Can you give me some advice?
Really thx and sorry for my english.

**Comment by joolswills** [comment]
You didnt read the link at the top when opening a ticket - https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md - please use the forum
