### ISSUE TITLE
Frequent pauses lr-ppsspp

### ISSUE THREAD

**Issue by cooky069** [RetroPie/RetroPie-Setup#1280]
Iv been testing out psp emulation for the first time using lr-ppsspp and overall getting good results. I have one or two problems however, games seem to run fine then I get a pause for a few seconds and a solid yellow light on the pi before emulation resumes and the light goes out . I assume it must be while the sd card is reading. My sd card is an integral class 10 and running on a pi 2. I also only get about 14 fps, not sure if this is a related issue or not

**Comment by zerojay** [comment]
Likely the system thrashing during heavy swap usage. I recently switched my RetroPie install over to a hard drive and I no longet get the heavy swaps at all when using PPSSPP.

**Comment by joolswills** [comment]
it's nothing we can fix (we are not the emulator authors)  - it's an io issue though.

**Comment by cooky069** [comment]
Thanks guys , that's pretty much what I was thinking . Will try a faster card or swap over to a hdd. Zerojay do you just run your roms from the hdd or have you set up the entire image to boot from it ?

**Comment by zerojay** [comment]
I set up everything to boot from the hard drive. The important part, as far as I can tell, is that I created a 2GB swap partition on the hard drive (as opposed to the swap file on the sd card that you normally get). I used some of the information here to help me: http://raspberrypihobbyist.blogspot.ca/2013/07/running-from-external-hard-drive.html
