### ISSUE TITLE
Could not install package(s): subversion flac

### ISSUE THREAD

**Issue by avedianj** [RetroPie/RetroPie-Setup#1281]
I'm getting this error after updating retropie, any ideas?

**Comment by HerbFargus** [comment]
How did you update? its not really important anyways as its only a dependency for duke nukem. what hardware are you running

**Comment by joolswills** [comment]
sounds like a network issue but without a log we cannot advise.

**Comment by zerojay** [comment]
Have you attempted to update since?

**Comment by joolswills** [comment]
putting it down to a network issue.
