### ISSUE TITLE
Genesis/Mega Drive emulator not acknowledging any cheevos

### ISSUE THREAD

**Issue by coreyhussell** [RetroPie/RetroPie-Setup#1282]
I have played a handful of Megadrive games and it logs me into the retro achievements but I can't seem to earn any on Genesis. When I go online it recognizes that I just played the games but i can't seem to get any cheevos, even though I did do them in game. They never pop up in game and don't show up on my user profile on RA: Coreyhussell. I use lr-picodrive.

**Comment by zerojay** [comment]
I've noticed this as well, but the bug is upstream. Nothing to do with us to my knowledge.

**Comment by coreyhussell** [comment]
Thanks for the reply. I posted on the RA forum bugs section. I will update if I hear anything.

**Comment by joolswills** [comment]
Should work with lr-picodrive now - rebuild from source and test - see https://github.com/libretro/picodrive/pull/22

**Comment by coreyhussell** [comment]
I updated the Retropie-Setup script, rebooted, rebuilt lr-picodrive from source, rebooted again. Then tried some Genesis games and none will load now. Goes black screen then back to game select menu. Double checked the Megadrive emulator was set to Picodrive. Can anyone confirm this?

**Comment by joolswills** [comment]
it's possible recent upstream changes broke it - I'll test.

**Comment by coreyhussell** [comment]
just an extra note on this.  I also tested some Master System games on lr-Picodrive with the exact same result.  Something is kicking me out of the emulator before it has a chance to boot.

**Comment by CloneDevil** [comment]
Problem with crash of picodrive after rebuilding from source still occurs.

/tmp/runcommand.log:
> /opt/retropie/emulators/retroarch/bin/retroarch: symbol lookup error: /opt/retropie/libretrocores/lr-picodrive/picodrive_libretro.so: undefined symbol: __aeabi_idiv

**Comment by joolswills** [comment]
That is not related to cheevos support - Please open a new ticket for build/link issues

**Comment by joolswills** [comment]
(and detail configuration please - ie rpi version, version of retropie-setup script)

**Comment by joolswills** [comment]
I submitted a fix for the undefined symbol error to the upstream libretro repository
