### ISSUE TITLE
How to set timeout for ps3 controller?

### ISSUE THREAD

**Issue by avedianj** [RetroPie/RetroPie-Setup#1286]
I use a ps3 controller over bt with my model b but if I forget to manually turn off the controller the battery dies very soon. I followed a guide a while back and edited a file but it never worked. I just updated lady night to the latest version and am hoping there is a way to accomplish this. Does anyone know how i can set my controller to automatically power off after x minutes of inactivity? Thanks

**Comment by gizmo98** [comment]
It's only enabled for shanwan controllers at the moment.

I will close this issue because there is already an open issue:
https://github.com/RetroPie/RetroPie-Setup/issues/1193
