### ISSUE TITLE
How do I install the xbox userspace driver from supplementary menu

### ISSUE THREAD

**Issue by dorfli** [RetroPie/RetroPie-Setup#1287]
I'm having the same issue as issue #902 and I don't know how to install the xbox userspace driver from supplementary menu.  I'm not very good with computers so please explain it to me like I'm 5 yrs old.  I don't know what the supplementary menu is, and I don't know where the drivers are.  Thanks,

**Comment by HerbFargus** [comment]
This is a bug tracker. Please use the forum for support thanks.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
