### ISSUE TITLE
TFT wont display through HDMI 

### ISSUE THREAD

**Issue by zonga50** [RetroPie/RetroPie-Setup#1289]
http://www.amazon.com/gp/product/B00WQMB1H6?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00 this screen is what i have, i can't for the life of me figure out how to get retro pi to just display. the screen when powered on is just plain white.

**Comment by zerojay** [comment]
It says on the page there that it needs a custom driver. Have you installed it?

**Comment by HerbFargus** [comment]
This isn't really a bug or even related to retropie's code. Please use the forum for support.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by zonga50** [comment]
How do i install the drivers but still run retro pi as the OS

**Comment by joolswills** [comment]
This is not a support area - please use the forum as requested. thanks.
