### ISSUE TITLE
Add TI-99/4A Emulator

### ISSUE THREAD

**Issue by cdu13a** [RetroPie/RetroPie-Setup#129]
Currently tracking down an emulator for the [TI-99/4a](http://en.wikipedia.org/wiki/Texas_Instruments_TI-99/4A) that I can get working on the Raspberry Pi.

Will add once I find/make a working emulator.

**Comment by bryancdickson** [comment]
VERY interested in this

**Comment by Esshahn** [comment]
Anything new here?
