### ISSUE TITLE
[Bug] Runcommand menu "Exit (without launching)" not working

### ISSUE THREAD

**Issue by BenWlson** [RetroPie/RetroPie-Setup#1291]
Not sure at what point this stopped working, but with an updated setup script, this menu selection does in fact load the game instead of returning to emulation-station.

**Comment by HerbFargus** [comment]
I tried it the other day and dint have that problem. I'd have to test again and see if I can reproduce

**Comment by joolswills** [comment]
It is broken - I'll fix it.

**Comment by joolswills** [comment]
fixed in 3ef32eaa83238932cac392c05b4f2e3c5451bc08
