### ISSUE TITLE
Github slow download speeds

### ISSUE THREAD

**Issue by thetonyleone** [RetroPie/RetroPie-Setup#1299]
Hello, 

I was just signing up to download retropie and the download speeds from GitHub are really slow. Im only getting 35KB/sec. It will take 6 hours to download the whole image. Anyone else having problems?

**Comment by HerbFargus** [comment]
Likely your network. no problems here

**Comment by thetonyleone** [comment]
I checked multiple downloads even from Microsoft and other sites plug speed tests and dont see a problem on mine. 
![slowness](https://cloud.githubusercontent.com/assets/17532271/13381179/d4a8f338-de09-11e5-8003-6b5918d810fe.png)

**Comment by joolswills** [comment]
Maybe a problem between you and the particular machine serving up the data. Try it again - you might get a different machine in the CDN. This issue tracker is for bugs with RetroPie - we are not responsible for Githubs hosting - use the forum for further discussion.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
