### ISSUE TITLE
Rebuild lr-mame2003 binary (config/nvram fixes)

### ISSUE THREAD

**Issue by zerojay** [RetroPie/RetroPie-Setup#1300]
As per https://github.com/libretro/mame2003-libretro/pull/17, the lr-mame2003 core not being able to read/write MAME controller configurations and NVRAM has been fixed. I've tested it and it appears to work well. At this point, if it cannot find the directories it is looking for, lr-mame2003 will create the missing directories itself. It appears to default to the system directory which seems to be set to the ROMs directory at the moment, creating $romdir/configs and $romdir/nvram, the only downside of this change.

Users can rebuild lr-mame2003 from source until an updated binary is released.

**Comment by joolswills** [comment]
binaries have now been rebuilt.

**Comment by joolswills** [comment]
thanks.
