### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by saulhudson** [RetroPie/RetroPie-Setup#1306]
Hi

Not an issue and maybe already answered but will RetroPie take advantage of the new Bluetooth capabilities of the Raspberry Pi 3 so we can connect PS3 controllers without cables?

**Comment by joolswills** [comment]
When you open a new issue it links to https://github.com/RetroPie/RetroPie-Setup/issues/new which says to use the forum for discussion. Thanks.

RetroPie already has bluetooth support - if you are using the image, you have Raspbian running, so you can use the bluetooth commandline tools also.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md even.
