### ISSUE TITLE
SMS extension for Game Gear platform

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1311]
Can the SMS extension be added for the game gear platform please? There are at least 9 games that I know of which are distributed as "*.sms" for the game gear. This is apparently because the roms are headered as SMS (done by developers of the original game) which the GG then played in a different mode than the usual GG stuff.

Both of the supported GG emulators used in RetroPie (genplus and osmose) can play SMS natively so this shouldn't be a problem.

**Comment by HerbFargus** [comment]
https://github.com/RetroPie/RetroPie-Setup/commit/edc78a92bbb4b751f5eb4af3999dd29b081d59df
