### ISSUE TITLE
Official support for Hardkernel ODROID-C1+ and ODROID-C2?

### ISSUE THREAD

**Issue by Hedda** [RetroPie/RetroPie-Setup#1314]
Any plans by the RetroPie team to officially support Hardkernel's ODROID-C1 and/or ODROID-C2?

I would think that supporting ODROID-C1+ and ODROID-C2 would not be that much different than Raspberry Pi devices?

Maybe the RetroPie team could get a sponsoring deal with Hardkernel?

What makes these very attractive devices to RetroPie users is they offer more power at same price as Raspberry Pi.

If too late to begin supporting the Amlogic S805 based ODROID-C1+ then ODROID-C2 is Amlogic S905 based.

**Comment by joolswills** [comment]
We have basic Odroid-c1 support already. some info here - https://github.com/retropie/retropie-setup/wiki/Odroid

**Comment by joolswills** [comment]
I would add that the ODroid c1 Mali GPU drivers are not that great, and you can only have either X or accelerated framebuffer currently afaik, not both, and the software support isn't as good as that of the RPI from my experience.

**Comment by Hedda** [comment]
Cool. Personally I'm really only interested in ODROID-C2 though.

Maybe a parnership with Hardkernel could sort stuff like drivers?

**Comment by HerbFargus** [comment]
I wouldn't hold your breath on that

**Comment by joolswills** [comment]
if they were to send me some boards (I have an odroid-c1) then I could look at improving compatibility, but I wouldn't want to be under any obligation. They need to contact us though.

**Comment by Twitch0815** [comment]
Just adding a +1 
Have two c1+ I wish I could trade for raspi 3's but would be nice to use them as emulation station. 

Are you guys active working on the binary installation method as opposed to just source? 
Maybe some better documentation about what will compile and what will not?

**Comment by HerbFargus** [comment]
There won't be any odroid binaries. you will have to install them from source and only some libretro emulators are supported, It's unlikely to ever get the same level of support as the pi because odroid doesnt have the same software support that the raspberry pi foundation provides.
