### ISSUE TITLE
Game Engine Game Selector Through Runcommand

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#1320]
Due to the likelihood of more game engines being added in the future (e.g. openbor, zsdx, cgenius etc) It may be worth integrating a game selector through runcommand for game engines as it is unrealistic to treat game engines as their own systems due to theming limitations etc. It will also help keep the ports menu simpler.

Would be an extension of this: https://github.com/RetroPie/RetroPie-Setup/issues/398

**Comment by joolswills** [comment]
(just mention this on the other ticket and I will do it as part of #398)
