### ISSUE TITLE
PPSSPP will not compile on Ubuntu 15.10 x86

### ISSUE THREAD

**Issue by jsawhite** [RetroPie/RetroPie-Setup#1326]
Not sure if this is the proper place or not, but the PSP emulator errors out building on an X86 install of Ubuntu.  Oddly, it works just fine on X64, but I assume that's not ideal to run on.  Attached is the error log I pulled on just this emulator.
[rps_2016-03-04_090916.log.txt](https://github.com/RetroPie/RetroPie-Setup/files/159224/rps_2016-03-04_090916.log.txt)

**Comment by joolswills** [comment]
Needs to be reported upstream to the ppsspp project (Try building it manually rather than using the retropie-setup script)
