### ISSUE TITLE
Add Raspi3 Overclock setting to raspi-config

### ISSUE THREAD

**Issue by Twitch0815** [RetroPie/RetroPie-Setup#1341]
So I got my Raspi3 in today.
I have the correct power 5v 2500 ma 
I have standard heatsinks applied with thermal paste
and a well ventilated case with an active fan. 

Can anyone suggest a starting point for overclock and how to test I can see what I can get mine table to then share that overclock.  And then maybe that could be added to the automatically configurable settings in retropie?

**Comment by joolswills** [comment]
we don't maintain raspi-config - it's part of raspbian. Use the forum for discussion / support as mentioned in the link at the top when you open an issue on github

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
