### ISSUE TITLE
MESS core support for libretro

### ISSUE THREAD

**Issue by DrMaxwell** [RetroPie/RetroPie-Setup#1342]
Can we add MESS to the experimental cores please? It may be able to run older computer based systems that don't tax the systems resources.

**Comment by joolswills** [comment]
it is already added.

**Comment by DrMaxwell** [comment]
Sorry Jools I've been away for a month now and should have checked before posting. Thank you for adding the core. What romset does is support?

**Comment by joolswills** [comment]
See here for info http://blog.petrockblock.com/forums/topic/libretro-mess-in-new-retropie-3-6/

**Comment by DrMaxwell** [comment]
Thank you mate
