### ISSUE TITLE
Add music/sound on boot

### ISSUE THREAD

**Issue by petrockblog** [RetroPie/RetroPie-Setup#135]
Might be helpful:

http://schivmeister.wordpress.com/2009/11/29/arch-linux-boot-time-music/

http://www.murga-linux.com/puppy/viewtopic.php?t=75854&sid=52462a53a8930383d0f19c4244c427b2

**Comment by ProxyCell** [comment]
is this still desired?
here is a royalty free sound clip - https://www.freesound.org/people/zagi2/sounds/248117/

would you like me to add it in?

**Comment by C-Fu** [comment]
YES! :)


Adri Idzwan Mansor
General Manager
Iron Ore Division
Malaysian Coal & Minerals Corporation Sdn Bhd

**Comment by joolswills** [comment]
Ugh. Bootup music. Horrible :) If this feature is added it should definitely be off by default (just my opinion on it)

**Comment by robertybob** [comment]
I like this idea, but then again I'd also like there to be an option to turn it off in case it gets annoying. Perhaps if it is implemented, and it is made clear how to change the music to whatever you like, that would be agreeable?

**Comment by ProxyCell** [comment]
yeah i realized that "music" wasn't a good idea after posting it lol
would a much simpler/shorter chime sound be supported?

i wanted to mention that anything we pick here would end up becoming VERY CLOSELY associated with the RetroPie project over time like how other console startup sounds are. you sure you would want it off by default though joolswills?

now i'm thinking something more like this (not EXACTLY this though!)
https://www.freesound.org/people/CosmicD/sounds/37576/

i'm leaning more and more towards a "chiptune" loop now - modern "retro". there are dozens of royalty free samples here:
http://www.looperman.com/loops/tags/royalty-free-8-bit-loops-samples-sounds-wavs-download

**Comment by joolswills** [comment]
I'm not a fan of boot up sounds. I'm in no way making a decision on this - just a personal opinion oh mine.

Once upon a time I used this as a boot up sound on my Amiga (a tune - this one actually - http://modstream.exotica.org.uk/modstream/?md5=ef71afd942e0eb649f37793d7497bb34&fm=mp3 ). Great tune but bootup sounds ended up driving me mad, to the extent I used to remove the speaker from certain Apple products :)

<advert> you can find lots of great demo scene chip tunes / loops on modland - http://www.exotica.org.uk/wiki/Special:Modland

**Comment by ProxyCell** [comment]
well whether it is on or off by "default" is up to petrockblog right?
and the "default" is largely just whatever the distributed image is setup with. turning it off probably will be the same as turning off the splash screen in terms of the options and interface for it. probably could set it up to be exactly the same where you can pick from a list of sounds...

**Comment by C-Fu** [comment]
I rather have "relevant" sounds while browsing on a particular system (a-la Recalbox-OS) than boot-up, but if one would want a boot-up sound option (like most modern consoles), I would like it if it blends seamlessly throughout boot-up and system/game selection as well. Something very slow, low volume, light, non-distracting. Kinda like this

https://www.youtube.com/watch?v=gC6AWtQzXTw

**Comment by joolswills** [comment]
Boot up videos are now fully supported - so you could combine some audio with a picture/video of your choice.

**Comment by ProxyCell** [comment]
yay!

this sounds hard however. like i mean finding appropriate video feels harder than sounds/chimes/etc
i am working on a theme for this too so i might just work on them together and hopefully they will match/coordinate lol

**Comment by joolswills** [comment]
It's not difficult to combine a picture with some audio into a video file. There is plenty of software for this.

**Comment by joolswills** [comment]
I may add some support for manually starting some audio just before the picture splash is started, but the sync wouldn't be perfect then - doing it as a video will sync better, and it will wait until the video is finished to load emulationstation, so you can have it complete nicely etc then.

**Comment by ProxyCell** [comment]
yeah i meant in the creative sense this is harder than just a chime, it does make it a look/sound a lot cooler when showing it to others for the first time
gives it a more "polished" feel

**Comment by joolswills** [comment]
Can you elaborate ? When you say a Chime do you mean like the old MAC power on sound ? The thing is, we cannot play anything that early really anyway.

**Comment by ProxyCell** [comment]
sort of like the middle C chord on Macs (they still use it by the way)
but before the video support was added, i was thinking of just adding a sound effect (a chime for instance) along with the script to load the splash screen static image

nothing special, thanks for implementing this by the way. i will try for an audio/video splash now.

**Comment by joolswills** [comment]
it will be very tricky to sync a chime exactly with the image displaying using two separate programs - so in this case you are def better off making a video (even it's just a picture or so). Or use the new carbon animation (update retropie-setup and its available as retropie2015-carbon-anim) - and add some audio to it ;-)

**Comment by HerbFargus** [comment]
You could also use this animation:

https://docs.google.com/uc?id=0B2TMeZ6iEFvHVDFHeWxiQXViVnM&export=download

Lots of options for sure.
