### ISSUE TITLE
Scrape Directory

### ISSUE THREAD

**Issue by symbios24** [RetroPie/RetroPie-Setup#1354]
Hello, i have latest retropie released v3.6 and i used the build-in Scraper for various systems like mame4all/snes/megadrive etc. does anyone know in what directory are the scraped files/images so i can copy them and i don`t have to scrape everytime a new version is out.
thank you

**Comment by HerbFargus** [comment]
Github is for bug reports. Please use the forum for support:

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
