### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by Snimchenko** [RetroPie/RetroPie-Setup#1357]
Hello,everyone!
I want to translate retropie interface to russian language.
How i can do it?

**Comment by joolswills** [comment]
it isn't possible and we have no framework for localisation at all currently. apart from manually editing every string in the code. sorry.

**Comment by Snimchenko** [comment]
> it isn't possible and we have no framework for localisation at all currently. apart from manually editing every string in the code. sorry.
Maybe you create a list of words that need to translate for me to i translated them?

**Comment by joolswills** [comment]
there is so much on our todo list, we don't have a high priority for this sorry and I doubt we will do it. I believe recalbox has localisation though so you could try that.

**Comment by joolswills** [comment]
even if we had all the strings translated, changing everything over to get translated would be more work than we have time for currently.

**Comment by Snimchenko** [comment]
ok,thank you :)

**Comment by MayMih** [comment]
It's strange so how in the retroOrangePi branch they achived localization support, at least in the EmulationStation menu?!
