### ISSUE TITLE
Sorting systems in setup menus

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1367]
I noticed today that systems were sorted in the scraper so I thought maybe it was a good idea to have the systems re-sorted in the source/install/setup menus as well.

**Comment by HerbFargus** [comment]
They are sorted by groups: standalone emulators, libretro, and ports

**Comment by HerbFargus** [comment]
And the menu will be changing anyways

**Comment by joolswills** [comment]
yeh. they are sorted :)
