### ISSUE TITLE
AMSTRAD CPC Emulation: Main Menu freezes on Raspberry Pi 3

### ISSUE THREAD

**Issue by jammet** [RetroPie/RetroPie-Setup#1371]
Pressing F10 should open a general config/options/settings menu, but it cannot be used not exited, and freezes the emulator.

**Comment by joolswills** [comment]
https://github.com/libretro/libretro-cap32/issues/9

Also you might want to try rebuilding from source - if that doesn't help, please report the problem upstream. thanks.
