### ISSUE TITLE
2 Bluetooth PS3 controller Rasberrypi 3

### ISSUE THREAD

**Issue by elbarbari** [RetroPie/RetroPie-Setup#1374]
I succefully added a PS3 controller through built in Bluetooth of Rasberrypi 3. I also got second PS3 controller registered as player 2. So I have led 1 and led 2 registered as player 1 and player 2. 

How can I activate player 2 in emulation station consoles through Bluetooth. 

Thank you.

**Comment by gizmo98** [comment]
So both controllers are registered as player 1 and 2 (led 1 and 2) through bluetooth and you ask how to activate player 2 in emulationstation?! Try to rerun input configuration (start button --> input configuration). If this not helpful use the forum for further support.
