### ISSUE TITLE
Retroarch 1.3.0 problem

### ISSUE THREAD

**Issue by efraimsangil** [RetroPie/RetroPie-Setup#1383]
Hi!
I use Retropie 3.6.
This version uses Retroarch 1.3.0.

So, when I change any option in rgui, when I click on “Save New Config” appear this msg:

Failed saving config to “/opt/retropie/configs/snes/snes9x_next_libretro/.cfg”

The problem is that use “/” in filename -> snes9x_next_libretro/.cfg is filename.

Where I can fix that?

Regards

**Comment by joolswills** [comment]
update retropie-setup and rebuild retroarch from source via menu 5 (or reinstall from binary as the binaries were updated recently), to see if it fixes it.

**Comment by efraimsangil** [comment]
Downloading.... in a few minutes I tell you :) Regards

**Comment by joolswills** [comment]
I think it isn't fixed, ill open a ticket on the retroarch bugtracker

**Comment by efraimsangil** [comment]
I try it again and still fail...

**Comment by joolswills** [comment]
https://github.com/libretro/RetroArch/issues/2793

**Comment by MegaFish0527** [comment]
I have a RPi2 and this also happens to me, but slightly differently. The "Failed saving config to “/opt/retropie/configs/snes/snes9x_next_libretro/.cfg” error appears on the bottom left of the screen when opening a snes game. When I go into the RGUI and try to do something, it glitches and goes back to whatever the previous screen was. I updated it today (3/17/2016 5:00 PM).

**Comment by lionking03** [comment]
the failed.... message wax fixed few hours ago, [https://github.com/libretro/RetroArch/issues/2793](url)
just rebuild from source retroarch and no message anymore
the issue wih the save config on RGUI are still there

**Comment by joolswills** [comment]
Now fixed. I have updated the retroarch binaries also.

**Comment by efraimsangil** [comment]
Ok, now it's working!!! Great job!
