### ISSUE TITLE
Game screen shrinked to top left corner when using overlay, 

### ISSUE THREAD

**Issue by windale** [RetroPie/RetroPie-Setup#1390]
I have a raspberry Pi 2, I am on 1080p 60Hz. I set this in my ‘config.txt’ -
hdmi_group=1
hdmi_mode=16

it may just be a coincidence, but after updating the setup script my overlays still show full screen but the game screen now appears in the top left corner and a lot smaller.

I am using LodanZark's GBA, GB, and GBC overlays and it happens on all of them.

Is it anything to do with this commit, note I am on Pi 2 ?

https://github.com/RetroPie/RetroPie-Setup/commit/521f1c01fdad1d30931696caccc19e4615bc414a

[configs.zip](https://github.com/RetroPie/RetroPie-Setup/files/180835/configs.zip)

**Comment by joolswills** [comment]
I guess you will need to change your custom viewport parameters as it will be rendering at full res now rather than within 640x480. If you don't want this you can set 640x480 render res in the configuration editor. For further help please use the forum. Cheers.
