### ISSUE TITLE
reboot after scraping takes forever

### ISSUE THREAD

**Issue by desionalpha** [RetroPie/RetroPie-Setup#1397]
Please excuse me if this problem was already addressed somewhere else. After searching I still haven't found any mention of it.

I have a week old install of RetroPie on a RasPi 1 (model A). Everything was running very well until I used the scraper by Steven Selph. Which in all fairness did an EXCEPTIONAL job very quickly. Unfortunately, now each time I hit F4 or attempt to REBOOT or SHUT DOWN, it takes forever to finish. I find myself watching the cursor blinking in the top left hand corner for about 20 minutes before the actual process of rebooting begins. Any suggestions?

Sorry again if it is already covered somewhere else, or if I am just blindly missing something completely obvious. I am VERY new to this and within this past week alone I have learned so much from this project, from this site and all the video tutorials that it is incredible. Even so, there is so much I don't yet understand. Thanks for your help in advance!

**Comment by joolswills** [comment]
Please use the forum for support. The reason it takes longer is because it is saving the metadata/gameslists.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
