### ISSUE TITLE
3.5" screen help

### ISSUE THREAD

**Issue by Konoa** [RetroPie/RetroPie-Setup#1398]
i cannot for the life of me get the waveshare 3.5in tft to work. a few months ago i got it to display the cmd line but the emulation station was still going thru hdmi. help is welcome!

the screen is a Waveshare 3.5 RPi LCD (A) V3 SpotPear.

**Comment by HerbFargus** [comment]
Github is for bug reports not support requests. Please use the forum for support:

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
