### ISSUE TITLE
Improvement: ScummVM 1.8.1pre config file -> config directory

### ISSUE THREAD

**Issue by jimbo27** [RetroPie/RetroPie-Setup#1402]
Recently I installed the new version of ScummVM over my existend version via RetroPie. After fiddling around with it I found out:
The config file $home/.scummvmrc is no longer used in v1.8.1pre. Instead there is the new config file $home/.config/scummvm/scummvm.ini

I suggest to abandon the symbollink for .scummvmrc and instead use this new one:
ln -snf $configdir/scummvm $home/.config/scummvm

I tested this on my system. It works flawlessly.

**Comment by joolswills** [comment]
that folder is already symlinked I believe so the creation of the other symlink can just be removed.

**Comment by joolswills** [comment]
aah no sorry my bad we symlinked the /home/pi/.scummvm folder - will update.

**Comment by joolswills** [comment]
fixed.
