### ISSUE TITLE
Reicast multiple controller mapping broken

### ISSUE THREAD

**Issue by vretro** [RetroPie/RetroPie-Setup#1407]
Auto controller mapping for Reicast is broken for more than 1 controller.

Only player 1 controller is recognised in game (any).
Tested using 2 Buffalo SNES controllers and only 1 is detected and mapped.

Controllers both setup using EmulationStation before launching clean installs of Reicast.

**Comment by joolswills** [comment]
Our configuration system only currently handles the configuration of a single controller currently.

**Comment by vretro** [comment]
Possible solution for multiple controllers in Reicast: http://blog.petrockblock.com/forums/topic/dreamcast/page/2/#post-121888

**Comment by vretro** [comment]
Another possible solution for multiple controllers in Reicast:
http://blog.petrockblock.com/forums/topic/dreamcast/page/2/#post-122354

**Comment by gizmo98** [comment]
Multiple controller support is possible now.
