### ISSUE TITLE
Using snes usb gamepad for super mario war port

### ISSUE THREAD

**Issue by doofusrick45** [RetroPie/RetroPie-Setup#1409]
This isn't quite an "issue", but I've looked all over to see if it is possible to configure an snes usb gamepad to work with super mario war. Is this possible? If so, could you please point me in the right direction? I've tried creating a retroarch.cfg file under the /retropie/configs/smw and inserting the configuration build I have for the snes, however; it did not work. Thanks in advance!

**Comment by joolswills** [comment]
Please use the forum for support with this as detailed when opening an issue. https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
