### ISSUE TITLE
RetroPie Setup script: Show version/latest commit of current installation?

### ISSUE THREAD

**Issue by zigurana** [RetroPie/RetroPie-Setup#1413]
The setup script nicely displays the Script version (eg: 3.6), as well as the last commit to the repository.
What I would really like is to see if I am already up to date with that latest commit, or not.

I know, I could just try and remember if I have updated since the last commit, but it seems like something the script should be able to tell me as well. And seeing I am lazy as an @$$...

Count it as a nice-to-have

**Comment by joolswills** [comment]
it doesn't show the last commit to the repository - it shows the last commit you have to your copy, so you can see from the date and compare. I don't really want to add more functionality to this really.
