### ISSUE TITLE
Unable to Map Generic PS3 Controller (Gasia) in 3.6

### ISSUE THREAD

**Issue by swizzle1** [RetroPie/RetroPie-Setup#1414]
I have some generic PS3 controllers (non Sony).  When connected to the RetroPie through USB cables and starting the mapping process it recognizes them as Gasia Co PS Gamepad.

In 3.6 they will only recognize the first button pressed and not register any other inputs.  

In 3.5 they work perfectly fine.

**Comment by bestarock** [comment]
I've had the same problem, the easiest way to fix it is to configure the controller via bluetooth, then after it will work plugged in. You can use it as a temporary solution.

**Comment by gizmo98** [comment]
https://github.com/RetroPie/RetroPie-Setup/issues/1420#issuecomment-207214070
