### ISSUE TITLE
Sound over aux won't work in mupen64

### ISSUE THREAD

**Issue by alwe2710** [RetroPie/RetroPie-Setup#1424]
I tested some games in different emulators. SNES Gameboy, etc. work perfectly. But in N64 I can't get any sound over aux. Only if I change it to HDMI I get from HDMI a sound. And if I choose the 'normal' mupen64 emulator for one rom in the start settings. But then I get a bad Video quality please fix this.

**Comment by joolswills** [comment]
see last two posts here - https://github.com/RetroPie/RetroPie-Setup/issues/1104#issuecomment-207950131

Also please use the forum first in the future for configuration help - this issue tracker is for bugs (and if not sure, always best to post to the forum to get feedback)
