### ISSUE TITLE
Kodi 16

### ISSUE THREAD

**Issue by madalbino1** [RetroPie/RetroPie-Setup#1425]
Hello I can't seem to play HD videos (with a resolution higher then 1280x720) anymore, all they do is show my tv blue screen like it would be changing resolution but then says no signal since updating Kodi from the previous 15.2 version to the 16 version unless I change the video output resolution from 1280x720 to 1920x1080 which all my HD videos are. Unfortunately there is a bug changing kodi resolution to to 1920x1080 when I quit out of Kodi and reload ES it doesn't switch the resolution back to 1280x720 if I'm right is the resolution that ES is running in so I'll get ES only showing up in the bottom left corner of my screen like it running at 720 resolution when the screen is really in a 1080 resolution.

**Comment by joolswills** [comment]
use the forum first as mentioned when opening a ticket https://retropie.org.uk/forum/
