### ISSUE TITLE
Linux Headers and GameCon installation fails

### ISSUE THREAD

**Issue by semaf** [RetroPie/RetroPie-Setup#1428]
Linux Headers 4.1.19 and Gamecon installation fails while it gives a 404 error during the download of the Linux-Headers with the RetroPi-Setup.

The URL here is correct: https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/linux-headers-4.1.19-v7%2B_4.1.19-v7%2B-2_armhf.deb

**Comment by joolswills** [comment]
Just tested here and it downloaded it ok - please make sure you have the latest version of retropie-setup and post a log and steps to reproduce if you can still see the problem.

**Comment by semaf** [comment]
I am using berryboot-20160313-pi2-pi3.zip and downloading RetroPi directly from there. After all updates and RetroPi Update over RetroPi-Setup is the Error still there. Will try uninstalling and installing it over Terminal again.

**Comment by joolswills** [comment]
BerryBoot have their own kernel version which is differently named - you will have to do it manually in that case as the automatic install is for Raspbian.

**Comment by semaf** [comment]
Automated one does not work too.. I have installed the headers from the url above and still not working with the command "modprobe: FATAL: Module gamecon_gpio_rpi not found"

**Comment by joolswills** [comment]
on Raspbian ?

**Comment by joolswills** [comment]
I don't think this will work on berryboot TBH. use the Raspbian image - we don't support the BerryBoot image I'm afraid - it is provided due to demand only, but as BerryBoot have a kernel shared between the various distros, some stuff will not work out of the box.

**Comment by semaf** [comment]
So installing Raspian and afterward RetroPi is better.. Jessie is not a Problem right?

**Comment by HerbFargus** [comment]
retropie is built on raspbian. just use the image provided

**Comment by joolswills** [comment]
You can do it that way, or use our premade image which is based on Jessie.

**Comment by semaf** [comment]
I will give a try.. Hope it will work :)

One more question which has not to do with the topic: I could find Pinouts for NES Controllers but not that for GPIOs. Which GPIO are needed to be connected that RetroPi will detect the NES Controller?

**Comment by joolswills** [comment]
Please use the forum for further help. Thanks.

**Comment by joolswills** [comment]
I will add a warning dialog to the gamecondriver with some information if it can't find the kernel headers.

**Comment by semaf** [comment]
Used without a reply!
https://retropie.org.uk/forum/topic/95/nes-controller-to-raspberry-pi-2-gpio

**Comment by joolswills** [comment]
Maybe no-one has the answer yet - I have no idea regarding nes pinouts - I would have to google it.

**Comment by joolswills** [comment]
I googled "nes gpio raspberry pi " and found https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=79703 as the first match - if that is of any use.
