### ISSUE TITLE
put all on default settings

### ISSUE THREAD

**Issue by alfredox123** [RetroPie/RetroPie-Setup#1430]
how to put ALL settings of all emulators and options from emulation station and retroarch to their default options?

**Comment by HerbFargus** [comment]
did you read the text before you posted your issue? this is a configuration matter, not a bug. please post on the forum:  https://retropie.org.uk/forum/

**Comment by joolswills** [comment]
I guess the answer to that was no - unfortunately it doesn't seem to  matter how clearly we request users use the forum first, it is ignored :(
