### ISSUE TITLE
Texas Instruments TI-99 Emulator Support

### ISSUE THREAD

**Issue by stevetb** [RetroPie/RetroPie-Setup#1435]
I would like to put in a request a Texas Instruments TI-99 Emulator to be added into RetroPie.  I found a link to several emulators which may work or already be supported.  ##

http://www.99er.net/emul.shtml

Please let me know if I can do anything to assist in moving this into an experimental build.

Thank you,
Stevetb

**Comment by HerbFargus** [comment]
Already been done on zerojays repo:

https://github.com/zerojay/RetroPie-Extra/blob/master/scriptmodules/emulators/ti99sim.sh

**Comment by stevetb** [comment]
Why is this not added to the main RetroPie Experimental Install Section?  This was a huge system back in the 1980's, seems worthy to me.

**Comment by HerbFargus** [comment]
We are working on some fundamental changes to the menu before we add anymore new systems, but you can easily install the extra modules from zerojay's repository in the meantime: https://github.com/zerojay/RetroPie-Extra

**Comment by stevetb** [comment]
Thank you HerbFargus.  I went through the installer and had some errors tonight.  I will go through the logs and see if it is related to 3.7 and submit to ZeroJay.  I appreciate the help.  Please give the developers a nudge to add if you can :-)

**Comment by HerbFargus** [comment]
I am one of the developers ;)

**Comment by stevetb** [comment]
Be gentle on yourself then, hahaha

**Comment by HerbFargus** [comment]
added as of https://github.com/RetroPie/RetroPie-Setup/pull/1514
