### ISSUE TITLE
REtropie 3 issues with XinMo. 2 buttons are not being detected on Player 2

### ISSUE THREAD

**Issue by MiguelHuerta88** [RetroPie/RetroPie-Setup#1436]
I HAVE MY CABINET SET UP EXACTLY HOW IT STATES HERE. https://gameroomsolutions.com/raspberry-pi-3-retropie-setup-easy-guide/

However, when Im using lr-mame2010 my player 2 buttons for input a and input r don't work. Any help will be great
thanks

**Comment by HerbFargus** [comment]
github is for bug reports related to retropie. This is a configuration issue. post on the forum as requested by the initial text you failed to read.

https://retropie.org.uk/forum/
