### ISSUE TITLE
Upgrade broke the display drivers

### ISSUE THREAD

**Issue by GAMELASTER** [RetroPie/RetroPie-Setup#1442]
I have an Touch screen, where drivers is available only in .img packages. (so I cannot use the RetroPie IMG and manually install drivers). The upgrading the things updates the some drivers and broke display drivers. Is possible to disable the auto upgrading in RetroPie-Setup?

**Comment by joolswills** [comment]
Why did you not post to the forum as directed when opening an issue ? https://retropie.org.uk/forum/
