### ISSUE TITLE
lvl0: 	Error initializing SDL! 	No available video device

### ISSUE THREAD

**Issue by cristinallamas** [RetroPie/RetroPie-Setup#1448]
I cant' seem to get this working, read many issues in the internet but found no answer

```
pi@raspberrypi:~ $ emulationstation
lvl0: 	Error initializing SDL!
	No available video device
lvl0: 	Renderer failed to initialize!
lvl0: 	Window failed to initialize!
pi@raspberrypi:~ $
```

**Comment by HerbFargus** [comment]
This is not a bug related to RetroPie as you are using stock a raspbian rather than the image we provide. 

Post on the forum as requested by the text you ignored when opening this issue.

https://retropie.org.uk/forum/
