### ISSUE TITLE
Galaga wouldn't load via MAME4All nor other cores due to missing files

### ISSUE THREAD

**Issue by gofirst2220** [RetroPie/RetroPie-Setup#1450]
See title. It would result in missing files not being loaded because it doesn't expect specific files that are already there for MAMEdev.org own MAME Emulator as seen here:
<img width="456" alt="filesexist" src="https://cloud.githubusercontent.com/assets/2223981/14763202/2d54e350-0954-11e6-97d4-75fad9a8d12d.PNG"> 

FYI the screenshot above is for the Galaga zip file that matches with MAME64

**Comment by joolswills** [comment]
This is not a bug - Please use the forum for support as clearly mentioned when opening a ticket https://retropie.org/forum/ - and read https://github.com/retropie/RetroPie-Setup/wiki/MAME
