### ISSUE TITLE
Add player-statistics , level-up-system/ranks/badges/achievements [Feature Request]

### ISSUE THREAD

**Issue by Micr0Bit** [RetroPie/RetroPie-Setup#1451]
player could earn experience and unlock ranks or badges/achievements by pressing a specific controller-button "x" times ... playing x-amount of time on a system/game ... and so on 
could have that level-up-system visually appear on a "local profile-page"

**Comment by zerojay** [comment]
https://retro-acheivements.org

**Comment by Micr0Bit** [comment]
@zerojay : thx , i had exactly this in my mind when thinking about this feature ... but could not remember the website anymore :) (this and steam) 
* http://retroachievements.org

and here an example for a profile with badges : 
http://retroachievements.org/User/KanaMojo

**Comment by HerbFargus** [comment]
We won't be implementing anything like this outside of the functionality retroarch already provides.

**Comment by Micr0Bit** [comment]
retroach looks more of a dead end tbh. -> http://retroachievements.org/viewtopic.php?t=9

well i would love to see something similar for retropie , but i understand that its gonna happen from "here" ... maybe someone picks this up and gets interested

**Comment by Micr0Bit** [comment]
oh my bad sry ... i see "retroarch" now ... im gonna check that out , thx guys

**Comment by HerbFargus** [comment]
For the record it's in the documentation:

https://github.com/retropie/retropie-setup/wiki/RetroAchievements
