### ISSUE TITLE
Multiple (same) controllers (joystick)

### ISSUE THREAD

**Issue by jacksonfylle** [RetroPie/RetroPie-Setup#1453]
Hello,

I've two controllers DragonRise
pi@retropie:~/RetroPie/roms $ lsusb
```
Bus 001 Device 005: ID 0079:0006 DragonRise Inc. Generic USB Joystick
Bus 001 Device 004: ID 0079:0006 DragonRise Inc. Generic USB Joystick
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
The thing is one of my joystick is upside down (arcade cabinet) and i cannot really modify that.
So when i configure the first and the second joystick, after a reboot or when i launched a games, the configuration of the second is wrong. For examples when i go left i'm going to the right.

```
pi@retropie:/opt/retropie/configs/all/retroarch-joypads $ ls
DragonRiseInc.GenericUSBJoystick.cfg DragonRiseInc.GenericUSBJoystick.cfg.bak
```
I've try to modify the configuration file /opt/retropie/configs/all/retroarch.cfg and add two player but it doesn't seems to work.

```
input_player1_a_btn = 1
input_player1_b_btn = 2
input_player1_y_btn = 3
input_player1_x_btn = 0
input_player1_start_btn = 9
input_player1_select_btn = 8
input_player1_l_btn = 4
input_player1_r_btn = 5
# input_player1_left_btn =
# input_player1_right_btn =
# input_player1_up_btn =
# input_player1_down_btn =
# input_player1_l2_btn =
# input_player1_r2_btn =
# input_player1_l3_btn =
# input_player1_r3_btn =
input_player2_a_btn = 1
input_player2_b_btn = 2
input_player2_y_btn = 3
input_player2_x_btn = 0
input_player2_start_btn = 9
input_player2_select_btn = 8
input_player2_l_btn = 4
input_player2_r_btn = 5
```

Emulstation recognize two gamedpad.

I hope you understand my problem, sorry about my english.

**Comment by HerbFargus** [comment]
This is not a bug. for configuration help ask for support on the forum as requested by the text you ignored when posting this issue.

https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md
