### ISSUE TITLE
Cordless gamepad deleted from repository

### ISSUE THREAD

**Issue by JosepZ** [RetroPie/RetroPie-Setup#1456]
If I install retropie sd image, my Logitech rumbepad cordless 2 is detected and I can configure buttons. All works fine.

But If I install retropie from repository, this gamepad is detected at the first emulator station boot, but it do nothing when I press a button to configure it.

Is there any library not included in repository?

**Comment by joolswills** [comment]
You have a thread open on the forum already.

**Comment by JosepZ** [comment]
Sorry.

I am new here, so not sure if this is am issue or not. My apologies if this is the wrong place.
