### ISSUE TITLE
New linapple issues. (easy fixes..)

### ISSUE THREAD

**Issue by dabonetn** [RetroPie/RetroPie-Setup#1462]
Ok, I haven't tried a new PI only install, but trying it on the pc I see 2 problems.

The Linapple fails on pc compile. It's missing libsdl-image1.2-dev
This is an added dependency not in the original linapple.

I'm changing the linapple.conf file to autostart and go full screen.
This will cure the emulation not autostarting.

Thanks.
Later,
dabone

**Comment by HerbFargus** [comment]
@dabonetn  would enabling joystick 1 by default cause any issues because currently the script enables both joysticks on install. no sense in scripting it if you have it set upstream

**Comment by dabonetn** [comment]
I only have one enabled, because most games only supported one joystick. 
There was only one joystick port on the machine.

Just let me know what changes you want to my repo.

Later,
dabone

**Comment by HerbFargus** [comment]
well if it doesnt hurt to have both enabled may as well, it will simplify the module.

As an aside when I was testing your changes it still required a keyboard to start up my pacman game and choose a joystick but I suppose that is to be expected as it was originally a computer. all the same its an improvement from how it used to be.

**Comment by dabonetn** [comment]
That depends on the program, some games just require a joystick. Choplifter is an example.

**Comment by dabonetn** [comment]
But because my Pi is built into a computer, I always have a keyboard handy..

[http://www.lemon64.com/forum/viewtopic.php?t=56679](url)

**Comment by HerbFargus** [comment]
I see. 

I've made some changes feel free to test.

https://github.com/RetroPie/RetroPie-Setup/pull/1463

and feel free to enable the second joystick by default (not sure if it makes a difference or not.)

**Comment by HerbFargus** [comment]
Added as of https://github.com/RetroPie/RetroPie-Setup/pull/1463
