### ISSUE TITLE
Can't figure out how to have two player 1's

### ISSUE THREAD

**Issue by Keithg488** [RetroPie/RetroPie-Setup#1464]
So I have my Raspberry pi 3 with retroarch 3.5 all set up. My Set up right now is I have two Arcade style Joypads for players 1 and two they are each on their own board and are plugged in via two separate USB ports. They both work fine and play each game as player one and two respectively. Here is my issue though I also have two wired xbox 360 controllers that i want to also issue as player 1 and two. I have different friends playing at different times so I would like it to be as easy as whoever is player 1 or player 2 can either use the arcade/joystick controls or pick up the respective xbox 360 controller but I cant find anywhere how to map a player to two controllers at once

**Comment by joolswills** [comment]
```
Please post to the forum first, as many "issues" can be solved with configuration changes. 
```
