### ISSUE TITLE
Vice errors on x11 install (PC x86)

### ISSUE THREAD

**Issue by dabonetn** [RetroPie/RetroPie-Setup#1466]
ok, I've been trying retropie on xubuntu and see the following vice errors.

It's prefixing /lib to the install directory so it's installing vice to /opt/retropie/emulators/vice/lib/
(Under the amd64 it's the same)

But the emulators.cfg is pointing to:

vice-x64="/opt/retropie/emulators/vice/bin/x64 %ROM%"

Also the sdl-vicerc that is created only contains the line
[C64]

**Comment by joolswills** [comment]
I made an error when last updating this module to work on 64bit Ubuntu/X11 - I have duplicated the prefix line, but I suspect I meant to rename one of the options. Will sort thanks.

**Comment by joolswills** [comment]
Should be ok now - must have been a c&p fail or some test code - removed the additional prefix line. on 64bit lib is symlinked to lib64, as otherwise it doesn't find the system roms etc.
