### ISSUE TITLE
Emulation Station es_systems.cfg typo

### ISSUE THREAD

**Issue by biscuits99** [RetroPie/RetroPie-Setup#1467]
It looks like in (RetroPie 3.7)
`/etc/emulationstation/es_systems.cfg` may have a typo

In the <extension> node for ZX Spectrum, the SNA isnt prefixed with a full stop. For both upper and lower case.

`<extension>sna .szx .z80 .tap .tzx .gz .udi .mgt .img .trd .scl .dsk .zip SNA .SZX .Z80 .TAP .TZX .GZ .UDI .MGT .IMG .TRD .SCL .DSK .ZIP</extension>`

**Comment by HerbFargus** [comment]
fixed as of https://github.com/RetroPie/RetroPie-Setup/commit/d0809432f23cb4cec6de7601ae4dd53efa0ac6e4
