### ISSUE TITLE
Add ResidualVM and Sam Coupé art for ES Theme: Pixel

### ISSUE THREAD

**Issue by RetroPieNerd** [RetroPie/RetroPie-Setup#1468]

**Comment by robertybob** [comment]
Surely this belongs on the forum, not here?

**Comment by ehettervik** [comment]
Yeah, lol. Pixel has a github page, but I didn't make it. I maintain Pixel from posts on the forum. :D  Herb showed me this post, so I'm working on updating it.

**Comment by RetroPieNerd** [comment]
Sorry, lol! I will close this issue! :D

**Comment by RetroPieNerd** [comment]
Thanks!
