### ISSUE TITLE
ROMs on External Storage

### ISSUE THREAD

**Issue by leachey123** [RetroPie/RetroPie-Setup#147]
Is there a way to change where retropie searches for ROMs?  If it is just looking for a directory shouldn't you be able to just change the directory it is looking for?  I'm filling up my SD card and was hoping to use something that is laying around the house without having to buy anything.

**Comment by jens-b** [comment]
Sorry for asking here again, or may be i have a suggestion:
I symlink the roms folder from sd card to my usb Harddisk, after that i delete the script 01_retropie_copyroms in the /etc/usbmount/mound.d dir. 
I think this should work? 
After that i am able to copy the roms via smb directly to the usb hard drive and retropie should copy the roms automatically to the sd card?

May be this could be an option for users who don't want to copy from usb drive to sd card?
