### ISSUE TITLE
Not detect hold button from dualshock4 and  there is "1 Gamepad detected"

### ISSUE THREAD

**Issue by bishamontn** [RetroPie/RetroPie-Setup#1476]
I have RetroPie running in a Raspberry pi 3 with OSMC (based in debian-jessie). I have followed all instructions I have gotten here https://github.com/retropie/retropie-setup/wiki/Setting-up-a-PS4-controller and I have paired my controller with bluetoothctl tool. Now just pressing PS button my controller turns on the blue light and it connects to the system.

When I go to configure input in emulestation I can see "1 GAMEPAD DETECTED" but pressing buttons do nothing. I can't configure it. Any help is welcome, it's driving me crazy.

**Comment by joolswills** [comment]
Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes.
