### ISSUE TITLE
Newest GlideN64 code doesn't work on the Raspberry Pi

### ISSUE THREAD

**Issue by loganmc10** [RetroPie/RetroPie-Setup#1479]
This is more of a heads up than an issue with RetroPie. The latest GlideN64 is not going to work on the Raspberry Pi. See this issue:

https://github.com/gonetz/GLideN64/issues/982

I don't really have the know-how to fix this issue, but I thought you should be aware, and perhaps there is someone that can work with gonetz to resolve this problem. You can close this issue if you see fit.

**Comment by joolswills** [comment]
thanks.
