### ISSUE TITLE
Quake/Doom RPT and PAK files

### ISSUE THREAD

**Issue by mclucario** [RetroPie/RetroPie-Setup#1486]
The Files seem to have a special permissions attribute and cant be overwritten while using samba

**Comment by joolswills** [comment]
Please can you provide me with the exact path of a file in question. I don't think there is a problem here, but I can check. If they are symlinks, they can be deleted and new files copied in their place.

**Comment by joolswills** [comment]
The permissions seem fine for doom. Quake pak had 600 permissions, which should have been fine, but I have forced it to 644 for future installs.
