### ISSUE TITLE
Pc-engine cd 6 button controller issue

### ISSUE THREAD

**Issue by mxstar1** [RetroPie/RetroPie-Setup#1490]
using a xbox controller, driver or no driver. and switching to the 6 button controller through retroarch, the dpad is glitching out bad making it impossible to control. 2 button, no problem, except in some fighting games you  need more buttons

**Comment by joolswills** [comment]
Did you post for support on the forum first in case it's a configuration issue? Also which emulator - the default one ?

**Comment by joolswills** [comment]
Closing due to no feedback.
