### ISSUE TITLE
avoiding confusion with RetroArch RGUI configuration

### ISSUE THREAD

**Issue by meleu** [RetroPie/RetroPie-Setup#1491]
This isn't a bug, but a request for a better description about RetroArch at RetroPie menu. (We discussed about it in the forum: [https://retropie.org.uk/forum/topic/208/solved-what-retroarch-cfg-should-be-writable](https://retropie.org.uk/forum/topic/208/solved-what-retroarch-cfg-should-be-writable))

The current description says:
Launches RetroArch with the GUI raised so you can change RetroArch options. Note: changes will not be saved unless you have enabled **writing to the retroarch.cfg file**.

A more accurate description which would avoid confusion would be this:
Launches RetroArch with the GUI raised so you can change RetroArch options. Note: changes will not be saved unless you have enabled **"Save Configuration On Exit" option**.

**Comment by joolswills** [comment]
Done - note for simple changes like this you can create a PR automatically from the github interface. Might have been quicker than opening the issue ;-)
