### ISSUE TITLE
AMIGA controls differences between RPi1 and RPi2/3

### ISSUE THREAD

**Issue by padremayi** [RetroPie/RetroPie-Setup#1493]
The hardcoded controls is different from RPi1 and RPi3 (or 2).

With RPi3 (or 2) the button for emulator menu is F12
With RPi1 the button for emulator menu is CTRL SX

With RPi1 the hardcoded buttons don't work, they work only with RPi3 (or 2)

**Comment by joolswills** [comment]
uae4arm has been updated recently and you probably have an older version running on the rpi1 machine. Did you update both ?

**Comment by padremayi** [comment]
For sure on RPi3 I have the latest version, installed yesterday evening. But as I said before I have to use F12 in order to enter UAE4arm menu.

On RPi1 I'll check the version

**Comment by joolswills** [comment]
That is correct. It switched to F12.

**Comment by padremayi** [comment]
Update the AMIGA page on GitHub

**Comment by joolswills** [comment]
Feel free. It's a wiki.

**Comment by padremayi** [comment]
Ok, is there another command to be updated?

**Comment by joolswills** [comment]
not sure what you mean ?

**Comment by padremayi** [comment]
Another control that is reported incorrect on the wiki

**Comment by joolswills** [comment]
The wiki has documentation on uae4all - not sure it really covers uae4arm currently. So if you are going to edit it, you need to make a new section for uae4arm

**Comment by HerbFargus** [comment]
From home page of the wiki 
```
This wiki is supposed to be created by the users of the RetroPie setup script for the users of the script. Everyone can contribute to it!
```

**Comment by padremayi** [comment]
Ok but the controls are hardcoded, who codes them?

**Comment by joolswills** [comment]
The emulator author/porter for uae4arm -

https://github.com/Chips-fr/uae4arm-rpi

**Comment by joolswills** [comment]
This would be best continued on the forum - we prefer to use this issue tracker for bugs only (which is why it asks to use the forum before opening a ticket)

**Comment by padremayi** [comment]
Ok thanks, I was not able to find this type of informations on UAE4arm, now it's clear ;-)
