### ISSUE TITLE
xin mo dual arcade controller not using 2 players

### ISSUE THREAD

**Issue by mickie456** [RetroPie/RetroPie-Setup#1496]
Hi, i've used the latest version of retropie (3.8) and am having difficulties with configuration of the 2 players/controllers.

The system seems to see the controllers as 1 player/controller since this is using one usb cable to connect: http://www.xin-mo.com/dual-players-controller.html

I've searched and found some people with the same issues. Can anyone tell me if there already is a solution to this problem?

Greets, Mick

**Comment by joolswills** [comment]
>Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
