### ISSUE TITLE
Kernel Version not updating

### ISSUE THREAD

**Issue by sheldon25** [RetroPie/RetroPie-Setup#1497]
Hi there. I have been reading that updating to kernel version 4.4 and then downgrading the bluetooth has been alleviating the freezing issues. However when I update the retropie script, then update using the binaries, it does not seem to upgrade the kernel version. I check this by running uname -a. respone in get is <Linux retropie 4.1.19v7-aufs #1 SMP Sun Mar 13 12:48:13 CET 2016 armv7l GNU/Linux
I have also tried using rpi-update, using a fresh retropie 3.8 image file and using sudo apt-get update && sudo apt-get dist-upgrade. Hopefully to see my kernel version change from 4.1 to 4.4. If anyone has encountered this and has a proper flow of steps to ensure a smooth upgrade that would be appreciated. If i am not in the right place, i apologize.

**Comment by joolswills** [comment]
Please use the forum for support as detailed when opening an issue.
