### ISSUE TITLE
ES is not autostarting

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1498]
inside of the autostart.sh file, I found this:

raspi-config nonint do_boot_behaviour_new B2

Which is a command that returns the following error each time: do_boot_behaviour_new: not found

pi@raspberrypi:~ $ sudo raspi-config nonint do_boot_behaviour_new B2
/usr/bin/raspi-config: 1238: /usr/bin/raspi-config: do_boot_behaviour_new: not found

i found this yesterday, waited until now to post it because i wanted to double-check with a fresh install to ensure it wasn't something boneheaded I did

**Comment by joolswills** [comment]
Update retropie-setup and it should work again.
