### ISSUE TITLE
Solarus install script fail on retropie 3.8

### ISSUE THREAD

**Issue by tomazed** [RetroPie/RetroPie-Setup#1501]
[rps_2016-06-01_181441.log.txt](https://github.com/RetroPie/RetroPie-Setup/files/293906/rps_2016-06-01_181441.log.txt)

Installation fail with the makefile not being able to build
[100%] Generating data.solarus
/bin/sh: 1: zip: not found
CMakeFiles/zsdx_data.dir/build.make:1184: recipe for target 'data.solarus' failed
make[2]: *** [data.solarus] Error 127
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/zsdx_data.dir/all' failed
make[1]: *** [CMakeFiles/zsdx_data.dir/all] Error 2
Makefile:117: recipe for target 'all' failed

**Comment by joolswills** [comment]
was missing zip dependency. either manually install zip or update retropie-setup and try again. thanks.
