### ISSUE TITLE
MAKE DOOM EASIER TO PORT IN

### ISSUE THREAD

**Issue by TheDevasator** [RetroPie/RetroPie-Setup#1503]
can you guys make it way easier to put in the full games of doom such as ultimate doom or doom 2 and also make it so its easier to use mods like brutal doom because going through all these scripts and terminals i always mess it  up somewhere and its to hard. PLZZZ. or someone could make a video explaining how to do it. that would be better than text

**Comment by joolswills** [comment]
>Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
