### ISSUE TITLE
x86 setup: "sh: 1: retroarch: not found"

### ISSUE THREAD

**Issue by AxxlForce** [RetroPie/RetroPie-Setup#1505]
after executing retropie_setup.sh on a x86 Ubuntu 16.04 machine and doing an install from source that's what i get when trying to load a core from emulationstation.

retroarch is installed in /opt/retropie/emulators/retroarch . if i make it available via PATH in .bashrc I can run "retroarch" from command line but it doesn't detect any cores.

**Comment by joolswills** [comment]
I will need a copy of the build log from RetroPie-Setup/logs

**Comment by joolswills** [comment]
and a copy of `~/emulationstation/es_log.txt` please and `/tmp/runcommand.log` (after launching something)

**Comment by AxxlForce** [comment]
i've searched my entire hdd there is no runcommand.log. but then again I'm unable to launch something in the first place.

Here's the logs: 
https://docs.google.com/uc?id=0BwToJlEUVDK1V0NHLXZ3ZnBVdXM&export=download

**Comment by joolswills** [comment]
You have made a manual/custom emulationstation configuration via es_systems.cfg ? RetroPie does not use this

```
retroarch --fullscreen -L /usr/lib/libretro/fceumm_libretro.so PATH_TO_ROM
```

but launches via runcommand

**Comment by joolswills** [comment]
You have either edited `/etc/emulationstation/es_systems.cfg` or you have an older/own config in `~/.emulationstation/es_systems.cfg`

**Comment by AxxlForce** [comment]
that's true i did create my own ~/.emulationstation/es_systems.cfg as i thought that was mandatory. allrite, will removing ~/.emulationstation do the trick then? unfortunatelly i can't check back until monday. thanks for the help so far!

**Comment by HerbFargus** [comment]
See the guide here: when installing from the setup script the es_systems.cfg will be generated automatically. as this issue tracker is for bugs not configuration issues, please continue any discussion on the forum as requested initially when you first opened this issue.
