### ISSUE TITLE
RetroArch Quick Menu for N64 & PSP

### ISSUE THREAD

**Issue by C0ncat** [RetroPie/RetroPie-Setup#1510]
The default hot key for access to the retroarch quick menu while in game seems to cause RetroArch to crash, regardless of the rom loaded, for lr_mupen64plus and lr_ppsspp.  I have not encountered the issue in other cores.

The same can be said for the default hotkey for reset.  I'm on v3.8.1, clean install.

Hoping someone can verify this is an issue and it's not just me.

**Comment by joolswills** [comment]
You already have a thread open on the forum. Please wait for a reply.
