### ISSUE TITLE
Unable to connect wifi iusing rpi3 native wifi module.

### ISSUE THREAD

**Issue by eddywebs** [RetroPie/RetroPie-Setup#1515]
I have  WPA-PSK [TKIP] + WPA2-PSK [AES] password protected wifi, however I try to connect to wifi it errors out stating Unable to connect to network <network name>

Any ideas why ?

**Comment by HerbFargus** [comment]
Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.

**Comment by eddywebs** [comment]
Got it thanks for the tip :)
