### ISSUE TITLE
Registering Bluetooth option not working in latest script (12th June 2016)

### ISSUE THREAD

**Issue by biscuits99** [RetroPie/RetroPie-Setup#1524]
Using RetroPie 3.8.1 the BT Register and Connect option works fine.
But when updating the RetroPie script (12th June 2016) and re-trying it doesn't seem to begin the process at all.

A user has also reported this here (Gert-Jan Mulder):
https://www.youtube.com/watch?v=RsybSJEPZJM

> only problem, trying to do it with a nes30 pro (2 accutally), but i looks like after i update the install script of retropie; i cannot search for any BT devices. i think it is a bug in 3.8.1.
> do you have any ideas?﻿

Also. this thread mentions users with the issue:
https://retropie.org.uk/forum/topic/1905/retropie-3-8-bluetooth-configure-issue/5

Here is an example of what happens:
https://www.youtube.com/watch?v=WKjH6vyBT0Q

**Comment by joolswills** [comment]
Sorry - broke it with my recent additions due to a duplicate function name. Primarily due to a bad name originally - I need to rework this module a bit more to tidy some of it up perhaps.
