### ISSUE TITLE
Can't connect to RetroPie 3.8 via Mac Shared Drive (SSH Works)

### ISSUE THREAD

**Issue by JCrew7384** [RetroPie/RetroPie-Setup#1528]
Hi... Having some trouble with my new RetroPie. Pretty new to this stuff. I was able to get it loaded onto a Raspberry Pi 3, and some ROMS loaded through USB method. I am trying to connect via Mac shared server. I see the RetroPie but it won't let me connect as guest or using the pi/raspberry user/pass. I am successfully able to connect via Terminal/SSH to the Raspberry. Any thoughts why this isn't working?

This is the error I get: There was a problem connection to the server "retropie". Check the server name or IP address, and then try again.

**Comment by HerbFargus** [comment]
https://github.com/RetroPie/RetroPie-Setup/issues/1454
