### ISSUE TITLE
Kodi missing from experimental packages

### ISSUE THREAD

**Issue by christopherduffy86** [RetroPie/RetroPie-Setup#1536]
Every tutorial I can find on installing kodi on retropie says to install via experimental packages. However there is no option or mention of kodi in experimental packages on retropie as of this date.

**Comment by joolswills** [comment]
If you have updated retropie-setup the structure has changed - see https://github.com/retropie/retropie-setup/wiki/updating-retropie#40-dev-setup-script - please use the forum for support with using retropie-setup - this issue tracker is for bugs only.

**Comment by joolswills** [comment]
(Kodi is found in the optional packages section)

**Comment by christopherduffy86** [comment]
I'm afraid not. There's no mention of Kodi at all.

**Comment by joolswills** [comment]
it is there. please use the forum for further help if you can't find it.
