### ISSUE TITLE
Subfolders support

### ISSUE THREAD

**Issue by mase76** [RetroPie/RetroPie-Setup#1538]
Hi!
Please support subfolders in the roms/$machine folder.
Many rom collections contain subfolders for country or alphabetical order.

**Comment by joolswills** [comment]
Emulationstation does support roms in subfolders, but not when scraping. Although we have made some changes to ES, we are not planning on doing any major development on it.

**Comment by InsecureSpike** [comment]
easier to edit the es_systems.cfg file, to add new emulator pages, and you can split your rom sets up like that. and they can be scraped so alls good
