### ISSUE TITLE
Can't skip joystick configuration

### ISSUE THREAD

**Issue by kimurantti** [RetroPie/RetroPie-Setup#1542]
I have usb joystick and when I start the emulationstation for the first time, the joypad config runs. The joystick has 1 button and I configure the directions and the button ok, but when I get to the second button configuration (which I don't have) I can't skip it. The instructions say you could skip this by pressing any key, I tried pressing the joystick button and all the keyboard buttons for a while, but no skipping. 

I can exit the config with F4, but no configuration is saved.

**Comment by HerbFargus** [comment]
> Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
