### ISSUE TITLE
Add How to Remove/Clear Scraped Data

### ISSUE THREAD

**Issue by Greenhawk84** [RetroPie/RetroPie-Setup#1556]
In the wiki, it would be nice to add how to clear the scraped data for a system and return it to the standard ROM list without info.

**Comment by joolswills** [comment]
If you want to know how to do it, you can ask for help on the forum. You can then edit the Wiki yourself to add it if you think it is useful. Everyone can contribute to the wiki, and this issue tracker is not designed for things like this (any help question could be worded as - please add to the wiki how to do).
