### ISSUE TITLE
Cant delete duke.rts and duke3d.grp

### ISSUE THREAD

**Issue by mclucario** [RetroPie/RetroPie-Setup#1565]
I cant replace/delete duke.rts and duke3d.grp in /roms/ports/duke3d/ while using samba.

**Comment by joolswills** [comment]
Can't reproduce it here, it might be because they are symlinks on v3.8.1 but this has changed with the latest retropie-setup script. Please use the forum for more help.

**Comment by mclucario** [comment]
ok thanks.
