### ISSUE TITLE
Making Scraper Skip Programms

### ISSUE THREAD

**Issue by mclucario** [RetroPie/RetroPie-Setup#1566]
The scraper tries to scrape the Dreamcast Systemmanager, the DosBox (where the scraping actually works), or the UAE4ALL. It would be nice if there would be a hardcoded way to skip that or at least a setting in a config file.

**Comment by joolswills** [comment]
Which scraper ? It would be best to use the forum first for ideas/support as mentioned when opening a ticket. Thanks.
