### ISSUE TITLE
RetroPie Quake: Player tends right when moving forward

### ISSUE THREAD

**Issue by Matrx007** [RetroPie/RetroPie-Setup#1569]
I just installed retropie to my raspberry pi, when I playied Quake first time it worked, but now it tends like right when moving forward (Letter W). **Please help!**

**Comment by joolswills** [comment]
>Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
