### ISSUE TITLE
Gamecon Driver - 4.0 beta2

### ISSUE THREAD

**Issue by deathly87** [RetroPie/RetroPie-Setup#1575]
Hi Guys,

i have a big problem to install the gamecon driver on the latest version.
At first i update the RetroPie-Setup script, then i want to install the gamecon over the driver package.
Everytime i get some issues. I have try to install the driver manually, but dont work. On 3.8.1 everything works.
 
Logs: http://pastebin.com/B9FuEeq4

BR
André 

PS: sorry for my bad english :P

**Comment by joolswills** [comment]
You should post first on the forum as directed when opening an issue, and I will advise. I suspect you have run rpi-update to install a bleeding edge kernel - you will need to downgrade to the last packaged version for this.

**Comment by joolswills** [comment]
if you haven't use rpi-update, you should make sure your kernel is up to date - `sudo apt-get update; sudo apt-get dist-upgrade`
