### ISSUE TITLE
Unknown platform

### ISSUE THREAD

**Issue by alphaonex86** [RetroPie/RetroPie-Setup#1577]
Hello,

Can you add odroid-c2 and odroid-c2-64 package?
Start on my odroid c2, I have:
Unknown platform - please manually set the __platform variable to one of the following: armv7-mali generic-x11 odroid-c1 rpi1 rpi2 rpi3 rpi3-64 x86

Cheers,

**Comment by joolswills** [comment]
no - as I don't have an odroid-c2 - if the mali gpu is the same  as the c1 you can try armv7-mali

**Comment by joolswills** [comment]
Please note - You should use the forum first as directed when opening an issue
