### ISSUE TITLE
SNES30 Hotkeys stop working in N64 emulator 

### ISSUE THREAD

**Issue by jravetch** [RetroPie/RetroPie-Setup#1579]
SNES30 controllers with 2.67 firmware.  SNES, NES, Attari, Sega everything works as expected.  When I start N64 emulator, the controllers work fine in the game; however, when I want to exit the game back to ES, the hotkeys (Select + Start) no longer works.  After trying the hotkey combo for some time, the controllers are no longer recognized by Retroarch.  I need to remotely trigger a reboot, remove the controllers then repair them.

**Comment by joolswills** [comment]
We do not use this issue tracker for support. Please use the forum as directed when opening an issue

>Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.

https://retropie.org.uk/forum/
