### ISSUE TITLE
Need help setting up a second controller

### ISSUE THREAD

**Issue by zahno** [RetroPie/RetroPie-Setup#158]
Hi, 
first of all, sorry if my choice of words is a little weird, I'm from germany :)
I already asked this question on the retro-pie website but I wasn't sure if that's the correct place to ask (because here are much more setup-questions like mine) and I'm hoping to find a solution soon :) 

I have troubles setting up a second controller. I'm using a USB-to-SNES-adapter with two ports for two controllers. 
The setup for the menu-control works fine, I am able to navigate trough the menu with both controllers without any problems.
I changed the retroarch.cfg file by copy- and pasting the configurations of the first controller (that already works fine in games) and changing the index to "1" and "player1" to "player2" what should be correct, right? 

Now to the weird part: 
Controller 2 does NOT work unless I press any button of controller 1 at the same time. That is the only way that controller 2 does react at all while I'm in a game. Again, controller 1 and 2 work fine in the menu independent of each other. 
When I swap the index-numbers of the controllers in the retroarch.cfg file they still do the same thing but swapped (controller 1 works only if any button on controller 2 is pressed). That makes me guess this is a settings-problem and not a hardware-problem. 

Has anyone an solution to this?? I'm falling into despair... :)

**Comment by deanshelton913** [comment]
seems like the file has been fixed in source.  https://github.com/libretro/pocketsnes-libretro/blob/master/src/ppu.cpp#L717
Index1 is correctly there. This has been fixed by https://github.com/libretro/pocketsnes-libretro/commit/9bfbd02b2bfba3bb2362d4cdf566a632d14186cd

**Comment by deanshelton913** [comment]
Yet i still have issues with it (failsause) I must have borked something. My player2 does not work for SNES still.... :(

**Comment by Martijn085** [comment]
Still no fix for this? The second controller is working fine in N64 but not with SNES...

**Comment by joolswills** [comment]
this ticket is closed - two controllers work fine in general. Please use the forum for further help/support.
