### ISSUE TITLE
Add Option to Switch Region Specific Console Logos/Names

### ISSUE THREAD

**Issue by shirizaan** [RetroPie/RetroPie-Setup#1582]
Please add an option to the RetroPie-Setup script to switch consoles to what is appropriate for a specific region (i.e. Megadrive -> Genesis and PC Engine -> Turbografx 16). This can currently be done by editing the config files directly but is far from user friendly. It would also open up the possibility of other regions such as Super Nintendo -> Super Famicom, etc.

**Comment by joolswills** [comment]
May consider this in a later release, but for now it's a low priority.

**Comment by ProxyCell** [comment]
I would like to add one note that I feel is important to this:
Changing the name/logo will not re-order the platforms. So the TurboGrafx16 will still be alphabetically sorted as PC-Engine in the Emulation Station menu and not be near SNES but be closer to Ports still.
You may find it more convenient to leave them.

**Comment by dukesilverfan** [comment]
ProcyCell, the current way to rename and change the logo is editing the es_systems.cfg file, and by re-ordering the file, you can re-order how the systems appear in Emulation Station. If joolswills decides to do this, I am sure that can be taken into account as well. It seems easy enough to follow the wiki and do this manually though, so I don't know how much benefit this enhancement offers.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/1759 deals with this
