### ISSUE TITLE
Roms were gone from the list

### ISSUE THREAD

**Issue by Emanuelus** [RetroPie/RetroPie-Setup#1584]
Hi, I played some roms on different systems to see if they work, when I turned the "console" on the second day sees me only games and systems in which I played the day before in the files all roms are unchanged.
I am not advanced user, Retropie work for me on RPI Zero.

**Comment by joolswills** [comment]
>Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
