### ISSUE TITLE
[Controller] X360 wireless - button change in ES

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#1586]
Since a few days and after I've ran through the Controller Configuration of ES again, I see that now to select item under ES I have to press the B button (red) of my X360wi controller instead of A (green- which was the case before). And now A is to cancel or go back to previous level (instead of B previously). It's a bit confusing to be honest and I'm not sure if this is desired behavior.

**Comment by joolswills** [comment]
By default if controllers are set up as directed in the wiki, on a 360 controller A will be back / B will be select. We ask people post to the forum first, so we can advise on configuration before a ticket is created (and make sure it's not a configuration issue). 

Please post the problem to the forum, detailing version info, method to reproduce and so on. Also include you configs from `/opt/retropie/configs/all/emulationstation`  and `/opt/retropie/configs/all/autoconf.cfg`
