### ISSUE TITLE
Unclear doom documentation

### ISSUE THREAD

**Issue by Pitel** [RetroPie/RetroPie-Setup#1587]
https://github.com/RetroPie/RetroPie-Setup/wiki/Doom#how-to-launch-doom-iwads-and-mods-pwads-from-emulationstation-using-lr-prboom

Where should I put those scripts?

**Comment by joolswills** [comment]
in roms/ports.

This issue tracker is not for support as is clearly mentioned when opening an issue

>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
