### ISSUE TITLE
I have not all Emulators

### ISSUE THREAD

**Issue by Menijo** [RetroPie/RetroPie-Setup#1588]
Hello,
I've just install Retropie in my Rpi3, but i cant play MSDOS games cause i dont have /opt/retropie/configs/pc/dosbox-SVN.conf and /home/pi/RetroPie/roms/pc folders. What can i do?
I installed the last version.

Thanks

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/
