### ISSUE TITLE
Is this x86 only (not x64)?

### ISSUE THREAD

**Issue by johnodon** [RetroPie/RetroPie-Setup#1589]
I just spent most of the day messing with this and trying to get it to run on 16.04 x64.  My genuine PS3 controllers just refused to work correctly in ES (d-pad was non-responsive).

I then noticed that the repo has 'x86' in the name.  Does this only work with x86 or am I missing something?

I'm building a new x86 install stick as we speak so I may have my answer before I see one here.  :)

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
