### ISSUE TITLE
retropie.cfg not working with lr-snes9x-next

### ISSUE THREAD

**Issue by psthompson** [RetroPie/RetroPie-Setup#1590]
In 3.8.1, when using lr-snes9x-next as the default SNES emulator, the global and emulator specific retropie.cfg files do not work. When loading a rom, text displays that says Logitech F310 Not Configured. This may be an issue specific to the F310, but I do not have any other gamepads to test. The F310 also works with other emulators without any issue.

If you switch the default emulator for SNES to snes9x and use the /opt/retropie/emulators/pisnes/snes9x.cfg file, the gamepad works without issue.

**Comment by psthompson** [comment]
It seems that this was being caused by configs that I had imported from an old version. I started fresh, and not everything works great!

**Comment by joolswills** [comment]
Also please note the text when opening a ticket - this issue tracker is not used for support and even issue should be posted first to the forum.
