### ISSUE TITLE
advmame 0.94.0 and 1.4 entries not removed from emulators.cfg in 'Arcade' when emulator is uninstalled

### ISSUE THREAD

**Issue by movisman** [RetroPie/RetroPie-Setup#1597]
As per above, the following lines are left in /opt/retropie/configs/arcade/emulators.cfg after uninstalling advmame from RetroPie-Setup:

advmame-0.94.0="/opt/retropie/emulators/advmame/0.94.0/bin/advmame %BASENAME%"
advmame-1.4="/opt/retropie/emulators/advmame/1.4/bin/advmame %BASENAME%"

Can these be removed automatically like the others to prevent selection of an emulator which isn't installed?

**Comment by joolswills** [comment]
thanks. fixed.

**Comment by movisman** [comment]
Cheers man. Seriously minor but thought i'd flag!
