### ISSUE TITLE
Add 'pulse' as a option for audio_driver in the RA config script

### ISSUE THREAD

**Issue by johnodon** [RetroPie/RetroPie-Setup#1601]
I am installing RP on Lubuntu 15.10 and have to install pavucontrol to be able to even get sound (setting HDMI device as fallback).  The issue I am having is that the alsa driver is very choppy.  If I switch to sdl2, the audio cleans up but some games lag (from what I understand it uses a lot of resources).

If I install RA manually on the same platform and switch to the 'pulse' driver, everything works perfectly.  However, pulse is not currently an option in the setup script (only alsa, alsathread and sdl2).  No matter how I try with RP to set audio_driver manually to pulse, it always reverts back to alsa.

**Comment by joolswills** [comment]
if you make sure `libpulse-dev` is installed and reinstall from source, it will be built with pulse support (It may well be already) - just manually edit `/opt/retropie/configs/all/retroarch.cfg` and set the audio driver to it.
