### ISSUE TITLE
Frame rate drop with PSP

### ISSUE THREAD

**Issue by z0raiel** [RetroPie/RetroPie-Setup#1612]
Hello.

I'm trying to play PSP game on a Raspberry Pi 3 but I'm facing some issue with both the emulators ppsspp and lr-ppsspp. When I start a game both the sound and the video are very slow and disturbed. I'm facing this issue with Monster Hunter Freedom United and Dante's Inferno, I didn't try other PSP games.

Currently I'm not overclocking and I'm playing with the default settings. Did anybody face this issue? In case how did you solve it?

Thanks for you support.

This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.

**Comment by joolswills** [comment]
You didn't read the text when opening a ticket (at the end of your post).
