### ISSUE TITLE
check/update libretro cores after renames

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1614]
There has been a bunch of repository renaming and target name changes in libretro upstream. Need to go through our libretro cores and fix up any that are broken. Not considering renaming our modules at this stage though.

**Comment by gizmo98** [comment]
I have seen most snes cores changed:
pocketsnes --> snes9x2002
SNES9x NEXT --> snes9x2010
CATSFC --> snes9x2005
fba --> fbalpha
