### ISSUE TITLE
Add option to disable IPv6

### ISSUE THREAD

**Issue by n-i-x** [RetroPie/RetroPie-Setup#1623]
In Retropie 4.0, IPv6 gets enabled. This is causing some issues with apt (super slow downloads for hosts with AAAA records). Please enable an option in RetroPie-Setup to disable IPv6.

**Comment by joolswills** [comment]
ipv6 shouldn't be used unless you have an ipv6 connection though. This is out of the scope of retropie though - retropie is not a distro but is installed on top of an existing distro. We do provide some helpers for Raspbian, but only when really need. You might want to suggest this is instead added to raspi-config which would be a more suitable place - https://github.com/RPi-Distro/raspi-config

to disable you can follow this guide - 
https://www.leowkahman.com/2016/03/19/disable-ipv6-raspberry-raspbian/
