### ISSUE TITLE
Can't load GlideN64 texture packs

### ISSUE THREAD

**Issue by alwe2710** [RetroPie/RetroPie-Setup#1624]
Normally GlideN64 can load N64 TexturePacks. But If I try loading Djipi Zelda OoT Textures I'm getting the default textures. Is there a better working version of the plugin?

**Comment by joolswills** [comment]
Did you post on the forum first ?

**Comment by roberterdin** [comment]
I'm having the same issue, see https://retropie.org.uk/forum/topic/3941/hires-texture-packs-not-loading
