### ISSUE TITLE
Default disable of virtualboy rewinding

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1625]
This took me forever to track down but for months I was having trouble getting any VB games to load and I figured out it was due to the rewind_enable in the master retroarch.cfg being set to TRUE by myself

after I added this line at the TOP of the VB retroarch.cfg it all worked fine again:
rewind_enable = false

**Comment by HerbFargus** [comment]
these are both mentioned in https://github.com/libretro/beetle-vb-libretro/issues/7 and https://github.com/RetroPie/RetroPie-Setup/issues/1266 and all the same its an upstream issue that needs to be addressed upstream
