### ISSUE TITLE
Allow 4 controllers by default on snes 

### ISSUE THREAD

**Issue by frranck** [RetroPie/RetroPie-Setup#1634]
Hello,

Is there a reason we need to add input_libretro_device_p2 = "257" to get 4 controllers to work on snes ? Shouldn't this be a default value ?

ref:  https://retropie.org.uk/forum/topic/3283/how-to-configure-4-pads-for-bomberman-snes/4

**Comment by dankcushions** [comment]
some games do not work with the multitap plugged in, just like the original hardware. see http://nintendo.wikia.com/wiki/Super_Multitap
