### ISSUE TITLE
grep error message after playing libretro ports

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1636]
I am seeing the following error message printed on my screen (very briefly) after playing lr-tyrquake/nxengine/dinothawr ports mentioned in the subject. Both ports are LR:
`grep: /opt/retropie/configs//retroarch.cfg: No such file or directory`
`grep: /opt/retropie/configs/quake/retroarch.cfg: No such file or directory`
`grep: /opt/retropie/configs/cavestory/retroarch.cfg: No such file or directory`
`grep: /opt/retropie/configs/dinothawr/retroarch.cfg: No such file or directory`

Please note the TWO slashes between configs and retroarch in the first one I posted as I caught that one on video.

Otherwise everything is fine but this could be a sign of something being misconfigured.

**Comment by joolswills** [comment]
I think I know what the issue is, but it helps if you mention what version of retropie-setup you are running when reporting issues.

**Comment by ProxyCell** [comment]
you're right, my apologies. i'm always using the latest everything, script, modules, etc.
