### ISSUE TITLE
Xbox 360 wireless controller not working in emulators

### ISSUE THREAD

**Issue by kentonbmax** [RetroPie/RetroPie-Setup#1640]
What I have tried in 3.8.1:
1. With and without xbox drivers
2. Updating all input drivers
3. Reinstall / configure emulations station. 

The controller works in emulation station but never works in a single emulator.

**Comment by joolswills** [comment]
have you posted on the forum ?

**Comment by kentonbmax** [comment]
Sorry new to this, will do that.
