### ISSUE TITLE
8bitdo contoller stops working when PS3 driver installed

### ISSUE THREAD

**Issue by swd120** [RetroPie/RetroPie-Setup#1643]
This is with an 8bitdo NES30 controller paired in start+r mode - I don't know if it affects other 8bitdo controllers, but it very well could.  This is with a Pi3 using the integrated Bluetooth.

Replication steps:  

1. Pair 8bitdo NES30 in start+R mode
2. Test controller in game/emulation station (should work fine)
3. Install PS3 input driver via Retropie-Setup
4. Try to use 8bitdo controller in EmulationStation/or a game - It will fail to register inputs
5. Uninstall PS3 input driver via Retropie-Setup
6. Test controller in game/emulation station (should work fine)

Sidenote:  After PS3 driver is installed - View registered/connected bluetooth devices in Retro-Pie Setup shows an error.  It starts working again after uninstalling PS3 driver.

It would be ideal to be able to use the NES30 controllers for older games, and PS3 controllers for N64/PSX/Dreamcast etc.  

Let me know if there's any other information I can provide.

**Comment by gizmo98** [comment]
Sorry. You cannot use ps3 controllers and other bluetooth controllers at the same time. The ps3 sixad driver disables and replaces the bluetooth daemon.
https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/ps3controller.sh#L83

**Comment by joolswills** [comment]
Also - please always post to the forum first as detailed when opening a ticket. When pairing a ps3 controller there is a big warning now on the current retropie that details this. Some people have managed to pair their devices first, then install the ps3 driver afterwards and have said their devices still pair, however this is "untested".

**Comment by joolswills** [comment]
(and it doesnt seem to work in your case)

**Comment by swd120** [comment]
The device still pairs - the inputs don't register properly though.

I don't quite understand why you would close this as an issue though...  Seems like an outstanding problem that should be noted in the issue log, even if its not something that can be fixed in a short timeframe...

**Comment by joolswills** [comment]
We are not responsible for every piece of software we ship with - however as I wrote above when you go to pair a PS3 controller, a window opens up stating this incompatibility.
