### ISSUE TITLE
Need help getting speaker set up

### ISSUE THREAD

**Issue by craftersshaft** [RetroPie/RetroPie-Setup#1644]
Ok, so I got a speaker for my pi, and there's one problem: No audio. I turned it on, no audio. Off, no audio. When I go into the audio mixer, it crashes. I found an article for HDMI, but I'm not good at coding, only setting up. https://www.raspberrypi.org/forums/viewtopic.php?p=234358#p234358

**Comment by joolswills** [comment]
Please read the text again which you removed when opening a ticket

>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
