### ISSUE TITLE
Standalone?

### ISSUE THREAD

**Issue by TigerClaw33** [RetroPie/RetroPie-Setup#1647]
Hi,
I want to by a raspberry pi 3 to use it for retro gaming. Is RetroPie a Standalone operation system or do I need a os as ubuntu or debian for it? What is the best way?

**Comment by HerbFargus** [comment]
> Please make sure you read the "guidelines for contributing" above before opening an issue. Support questions should go to the forum. Please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
