### ISSUE TITLE
Make wolf4sdl-sw-v14 default for Wolf4SDL

### ISSUE THREAD

**Issue by dudleydes** [RetroPie/RetroPie-Setup#1651]
The current scriptmodule for Wolf4SDL assigns the wolf4sdl-3dr-v14 binary as default in emulators.cfg meaning that the shareware version installed will not run.

The binary wolf4sdl-sw-v14 needs to be made default.

**Comment by joolswills** [comment]
Thanks. This broke when a change was made so we don't change defaults when they are already set.

By changing the order we call the addPort for them this will be fixed (the opposite was round from before).

**Comment by joolswills** [comment]
should be fixed in 59f647ca02ed5dc956dcc1939376d2a722bf0f6b (will only affect fresh installs)
