### ISSUE TITLE
Video splashscreens continue playing after ES is fully loaded

### ISSUE THREAD

**Issue by n-i-x** [RetroPie/RetroPie-Setup#1655]
Video splashscreens continue playing in their entirety. This causes some weird artifacts like when using the carbon video splashscreen there are harsh white bars across the top and bottom when ES displays its splashscreen.

RetroPie should kill the omxplayer process before launching ES.

**Comment by joolswills** [comment]
This should be on the forum as mentioned when opening an issue - this isn't a bug (but you can change the behaviour manually). It's just ES showing up behind the video (omxplayers black background has a lower priority - this needs a fix in omxplayer).

You can put a delay in or wait for ES. Killing it would upset a lot of users who like ES loading in the background.

You can also use a video that fits your screen exactly.
