### ISSUE TITLE
can't find 310 Install PS3 controller driver

### ISSUE THREAD

**Issue by the4anoni** [RetroPie/RetroPie-Setup#1657]
RetroPie 4.0 ,Rpi 3 ,bt onboard. Updated script twenty times...

**Comment by the4anoni** [comment]
Also reinstalled 3 times...

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
