### ISSUE TITLE
Steven Selph's Scraper Unable to scrape mounted drives

### ISSUE THREAD

**Issue by whalingman** [RetroPie/RetroPie-Setup#1658]
I've come across an issue with Steven Selph's Scraper, where it's unable to scrape a mounted Amazon Cloud Drive.

I've mounted my ACD using acd_cli, using:
`acd_cli mount -ao /home/pi/RetroPie/Amazon`

I've also edit the cfg for ROM folder location to match the folder structure in ACD. When running the built in EmulationStation scraper, it recognizes the roms such. Exiting EmulationStation and running Steven Selph's Scraper via RetroPie-Setup, doesn't seem to work. All it seems to do is check for new updated hashes, and doesn't actually search.

Anyone have any idea why the might be? Will Symlinks be needed possibly, rather than changing the directory location?

Thanks!

**Comment by joolswills** [comment]
Most likely due to the FUSE implementation - Not something we can fix, and not a RetroPie issue. You should also post to the forum first as mentioned when opening a ticket.
