### ISSUE TITLE
Limelight discovery quit causes script to quit

### ISSUE THREAD

**Issue by smartroad** [RetroPie/RetroPie-Setup#1659]
I have been trying to play with Limelight but have an issue when it goes to the discovering 'GeForce PCs'. It says to hit CTRL-C to stop the search, but when you do it actually quits the script completely. Otherwise it just sits there for ages apparently not doing anything :(

I can't uninstall it either for the same reason - I wanted to do an update of all parts but this just stops it dead

**Comment by joolswills** [comment]
You are probably better off using moonlight - which isn't yet implemented automatically. see https://github.com/RetroPie/RetroPie-Setup/issues/1082

However I will see if the ctrl+c can be fixed up.

**Comment by smartroad** [comment]
Cool thanks, I'll look at moonlight. :)

**Comment by joolswills** [comment]
Closing as limelight is now replaced with moonlight.
