### ISSUE TITLE
Enhancement - Add saved game flash drive option

### ISSUE THREAD

**Issue by kentonbmax** [RetroPie/RetroPie-Setup#1664]
There is constant need for configuration and uninstalling tweeking with retropie, it would be nice to manage saved games externally, I dont want to get to the end of MS or MS2 save just before the boss and loose the save. 

Thinking you would create a folder on the flashdrive, retropie\saves and it would format similar to roms, saves would be stored locally until the saved flashdrive is connected when they would be auto copied.

**Comment by joolswills** [comment]
You can script this simply enough - but please use the forum and people may give you ideas on how to do it. I don't think this is something I am interested in implementing currently but there are external tools to help - eg https://github.com/Death259/PiAssist can upload save games to dropbox I think.
