### ISSUE TITLE
Can't save or load game states

### ISSUE THREAD

**Issue by zahno** [RetroPie/RetroPie-Setup#167]
Hi,
I get the error-message "failed to save state to "/media/romsHDD/SNES/...." when I try to save my games, loading of course doesn't work either. I have my roms stored on an external HDD. Also I changed the retroarch.cfg file so I can save the game over my joypad ("input_save_state_btn = "..""), but when I do the combination in the game, I only get a big yellow writing that says "failed to save state".
Why is that? How can I fix it? 
Thank you

**Comment by giovannibotta** [comment]
I have the same issue but I don't have a FAT partion:

    Device         Boot    Start      End  Sectors  Size Id Type
    /dev/mmcblk0p1          8192  2121093  2112902    1G  e W95 FAT16 (LBA)
    /dev/mmcblk0p2       2121728 15286271 13164544  6.3G 85 Linux extended
    /dev/mmcblk0p3      15286272 15351807    65536   32M 83 Linux
    /dev/mmcblk0p5       2129920  3178495  1048576  512M 83 Linux
    /dev/mmcblk0p6       3186688  3315711   129024   63M  c W95 FAT32 (LBA)
    /dev/mmcblk0p7       3317760 15280127 11962368  5.7G 83 Linux

where mmcblk0p7 is mounted on /

**Comment by giovannibotta** [comment]
Actually the error I get is "Failed to load state ..." (when I try to save).

**Comment by joolswills** [comment]
This ticket is two years old and closed - please post on the forum for help. Sounds like a permissions issue. https://github.com/RetroPie/RetroPie-Setup/blob/master/CONTRIBUTING.md

**Comment by giovannibotta** [comment]
Never mind, I had my shortcuts backwards :)
