### ISSUE TITLE
[Feature Request] Adding N64 DD (Nintendo 64 Disk Drive)

### ISSUE THREAD

**Issue by RetroPieNerd** [RetroPie/RetroPie-Setup#1670]
[Here is the website for N64 DD Emulation.](https://64dd.org/)
You could use [MAME](https://64dd.org/tutorial_mame.html) for this.

**Comment by joolswills** [comment]
> For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

**Comment by joolswills** [comment]
This would be the wrong place for a request like this also, unless there is already an emulator that would work on the RPI that supports it - https://github.com/mupen64plus/mupen64plus-core/issues/129
