### ISSUE TITLE
New Image Retropie 4.0.2 - slow lr-snes9x-next

### ISSUE THREAD

**Issue by Stueck** [RetroPie/RetroPie-Setup#1687]
Hi,

I use the newest image 4.0.2.
Playing with emulator lr-snes9x-next is extreme laggy (e.g Mario Kart) in sound and picture.
When I use lr-catsfc there is no notable problem.
I tried the solution from here: https://github.com/RetroPie/RetroPie-Setup/issues/1251
But it didn't work for me.

Is there a problem in the release?

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
