### ISSUE TITLE
code documentation

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1694]
Document helper functions via Doxygen & https://github.com/Anvil/bash-doxygen

This is just a reminder for myself - initial docs are about 60% done

for anyone interested - output is something like http://malus.exotica.org.uk/~buzz/retropiedocs/html/helpers_8sh.html (no bug reports please, still a WIP - and draft)

**Comment by zigurana** [comment]
This is great! Can we help, or do you want to create a first version yourself?
Where I work, doxygen-comments are placed just above the functions, makes it a breeze to go through the code and get an idea of what's going on. Are you going for the same (type of) implementation?

**Comment by joolswills** [comment]
I don't need any help currently thanks.

Check the first link in my post above for info of the implementation.

**Comment by joolswills** [comment]
here is an example using bash-doxygen - https://github.com/Anvil/bash-argsparse/blob/master/argsparse.sh

**Comment by joolswills** [comment]
PR in https://github.com/RetroPie/RetroPie-Setup/pull/1705 - probably still some mistakes in the documentation, but it's basically complete for helpers.sh
