### ISSUE TITLE
Controller 2 not working when switching SNES emulator

### ISSUE THREAD

**Issue by Rottweiler** [RetroPie/RetroPie-Setup#1701]
Whenever you switch emulator for the SNES games, controller #2 stops working. I've tested it in "Mario World.smc" and whenever it's Luigi's turn to play, only controller #1 works.

Here's the research I've conducted from the different emulators so far:

- pisnes = square picture, kind of blurry, one remote, can't exit out with start+select
- snes9x-next = crystal clear picture, two remotes, LAG
- armsnes = crystal clear picture, one remote 
- catsfc = crystal clear picture, one remote

The reason why I want to switch emulator in the first place is that the other emulators seem to emulate this game much better.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.
