### ISSUE TITLE
Scraper Bug

### ISSUE THREAD

**Issue by symbios24** [RetroPie/RetroPie-Setup#1703]
Hello, there is a problem/bug with the latest Retropie version 4.0.2 when i press the scrape now option to get some game images for example for pc-engine games, it throws me to the command line and it says that i don`t have rights/privileges to write to the scrape folder "/opt/retropie/configs/all/emulationstation/downloaded_images"

When i do this with an older version v3.8.1 everything is working fine

Can this be fixed please?

Thank you

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

**Comment by symbios24** [comment]
hi i tried to post at forum first and i got an not enough tags error so i posted here after

**Comment by joolswills** [comment]
You need to put in at least one tag when posting to the forum (eg the word scraper)

**Comment by symbios24** [comment]
how can i put tags?

**Comment by joolswills** [comment]
In the box that says Enter tags here, between 5 and 15 characters each

**Comment by symbios24** [comment]
impossible i cannot do it, i tried so many times,anyway thanks
