### ISSUE TITLE
Removed ROM remains in Game & Scrape Lists

### ISSUE THREAD

**Issue by Makitk** [RetroPie/RetroPie-Setup#1704]
When removing ROMS from a USB drive, RetroPie does not automatically seem to realise this.
The removed ROM remains in the game list and will also get scraped again and again.

I have not seen a method for manually refreshing the ROM listing from within ES, so this bug is starting to get truly annoying.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
