### ISSUE TITLE
Has location of retroarch.cfg changed?

### ISSUE THREAD

**Issue by Grey112358** [RetroPie/RetroPie-Setup#1709]
Is /opt/retropie/configs/all/retroarch.cfg still the path for that file on Retropie 4?

I don't have a retropie folder, only a RetroPie folder and it does not contain a configs folder.
Has it moved or is there a command I don't know to access it on terminal (OSX Putty).

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
