### ISSUE TITLE
Getting an error when trying to run emulationstation

### ISSUE THREAD

**Issue by JakeStatefarm11** [RetroPie/RetroPie-Setup#1712]
Hi there,
I'm new to this community, and I'm not familiar with how issues get reported. I am running Raspbian on the Raspberry Pi 2, and whenever I attempt to run "emulationstation", it says, "X is running. Please shut down X in order to mitigate problems with losing keyboard input. For example, logout from LXDE."
Does anybody have a solution for this?

**Comment by joolswills** [comment]
It is clearly mentioned in the text you removed when posting the issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
