### ISSUE TITLE
A Way To Fix "White Screen Of Death" when changing themes [Idea on how to fix a bug]

### ISSUE THREAD

**Issue by MrDiamond123** [RetroPie/RetroPie-Setup#1714]
I found out if you go in to a game console menu when the "White Screen Of Death" is happing, it will if it. Also it won't happen if your in a console menu already. What I'm saying, when you change the theme it should go in to the RetroPie menu then out of it after.

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
