### ISSUE TITLE
Vice x64: Joystick Binding Problem -> New Version of Vice

### ISSUE THREAD

**Issue by jimbo27** [RetroPie/RetroPie-Setup#1716]
With the new Version of Vice (SDL2) there was a bug which results in loosing some joystick bindings at startup of Vice.
See here:
https://retropie.org.uk/forum/topic/3972/vice-c64-emulator-now-supports-sdl2

I posted this upstream and there is already a solution for this:
https://sourceforge.net/p/vice-emu/bugs/796/

There is a new version of Vice: r31978
https://sourceforge.net/p/vice-emu/code/HEAD/tree/

May I ask politely someone to compile this new version for our RetroPies? Unfortunately I am not capable of doing this.

**Comment by joolswills** [comment]
I will update the module when 2.4.32 comes out.

**Comment by G0nz0uk** [comment]
Hello,  yes I'm getting this issue in Retropie 4.0.3,  can't wait for this to be fixed.

**Comment by G0nz0uk** [comment]
I can confirm I'm getting this too on Retropie. 

Keep up the great work. 

Thanks

**Comment by joolswills** [comment]
Please use the "add your reaction" button if you want to add feedback on an issue.

**Comment by joolswills** [comment]
An updated vice is now included with the fix.
