### ISSUE TITLE
Cant run retropie_setup.sh

### ISSUE THREAD

**Issue by whallz** [RetroPie/RetroPie-Setup#1721]
when following instructions on ubuntu wily i get ": No such file or directory" error and cant setup:

λ 161021_105742 whallz @ ~ git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
Cloning into 'RetroPie-Setup'...
remote: Counting objects: 244, done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 244 (delta 50), reused 49 (delta 3), pack-reused 0
Receiving objects: 100% (244/244), 1.54 MiB | 33.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
Checking connectivity... done.
λ 161021_105905 whallz @ ~ cd RetroPie-Setup/
λ 161021_105947 whallz @ ~/RetroPie-Setup chmod +x 
AUTHORS               COPYRIGHT.md          .github/              LICENSE.md            README.md             retropie_setup.sh     tools/
CONTRIBUTING.md       .git/                 .gitignore            platforms.cfg         retropie_packages.sh  scriptmodules/        
λ 161021_105947 whallz @ ~/RetroPie-Setup chmod +x retropie_setup.sh 
λ 161021_105958 whallz @ ~/RetroPie-Setup sudo ./retropie_setup.sh 
: No such file or directory
λ 161021_110004 whallz @ ~/RetroPie-Setup

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
