### ISSUE TITLE
Odroid- XU4 - Retropie install

### ISSUE THREAD

**Issue by stikoyan** [RetroPie/RetroPie-Setup#1723]
I'm fairly new to this so I apologize if this is a redundant question.  I haven't seen any information recently so I will ask here.  I have an odroid XU4 and am trying to install retropie on it.  Is this compatible and is there instruction you can point me to do so if possible.  I have it running on a PI3 but like the extra power of the XU4.  Thanks.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
