### ISSUE TITLE
fix up ppsspp build on rpi

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1726]
Need to use the separated armv6/armv7 raspberry pi toolchain files.

**Comment by joolswills** [comment]
https://github.com/hrydgard/ppsspp/issues/9104

**Comment by joolswills** [comment]
now building correct on the rpi - patch included until it has been accepted upstream.

**Comment by ProxyCell** [comment]
This is not building for me still. I ran this twice today on RPi3, latest updated firmware/software/etc.

[rps_2016-11-01_161732.txt](https://github.com/RetroPie/RetroPie-Setup/files/565486/rps_2016-11-01_161732.txt)

**Comment by joolswills** [comment]
some things have changed since then. I pushed another patch upstream, but was doing a final build test before upload - hence this ticket is still open ;-)
