### ISSUE TITLE
Dreamcast doesn't appear

### ISSUE THREAD

**Issue by alexmejor** [RetroPie/RetroPie-Setup#1728]
Hello everyone.
I have a problem with dreamcast emulator, it just doesn't appear in the roms folder with the rest of the emulators... i tried to create the folder "dreamcast" myself and put inside a game (sonicadventure.cdi) but still nothing, and of course I've rebooted the raspberry... what can I do?
thanks.

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
