### ISSUE TITLE
building ppsspp quits the retropie_setup script

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#1733]
the building of ppsspp is working perfectly again but at the end of it, it just quits out of the script

**Comment by joolswills** [comment]
This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.

**Comment by joolswills** [comment]
Also without even a git revision or log I cannot help.

**Comment by joolswills** [comment]
I tested building on my tpi3, and was unable to reproduce btw.

**Comment by joolswills** [comment]
hmm. aah you mean when selecting "back"  ? could be a problem in retropie-setup - I will re-open this.
