### ISSUE TITLE
Issue with Retroarch rgui in 4.1 with keyboard navigation

### ISSUE THREAD

**Issue by christianhaitian** [RetroPie/RetroPie-Setup#1737]
On a Raspberry PI 2, with the recent update to RetroPie 4.1, I am no longer able to properly navigate rgui via keyboard. I can scroll up and down but can not select any of the options and the enter key causes rgui to crash.  This wasn't an issue with Retropie 4.0.4.  Navigation in emulation station works fine.

Thanks

**Comment by joolswills** [comment]
You already have a thread on the forum - 

https://retropie.org.uk/forum/topic/4997/issue-with-rgui-in-4-1

Please wait there for an answer

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.

Note if there is a problem here, it will be with RetroArch and the bug should be reported there.
