### ISSUE TITLE
Bring Back Times Played/Last Played In MetaData

### ISSUE THREAD

**Issue by BGallagherHollywood** [RetroPie/RetroPie-Setup#1738]
After I updated to 4.0 a few months ago, I noticed that one feature I always enjoyed was gone for some reason. There was a feature in the metadata that showed you how many times you have played each game, and when the last time each game was played. I was hoping that this would be added back in future versions, but I just updated to 4.1 today, and I noticed it's still gone. Is there a way that I can possibly add this feature back in the metadata code? Or that it could be brought back in the next version of Retropie?

**Comment by joolswills** [comment]
You have a thread on the forum.
