### ISSUE TITLE
hatari 2.0 is out

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1739]
https://retropie.org.uk/forum/topic/5017/hatari-2-0-released

Need to check 4:3 mode

**Comment by CoalaJoe** [comment]
+1

**Comment by amigagamer** [comment]
Latest Hatari 2.1 release now respects original 4:3 aspect mode in Fullscreen SDL2

manually built on Jessie,  X in the fullscreen box in Hatari screen options.  as yet untested from retropie build scripts

**Comment by Spillbrain** [comment]
Version 2.2.1 and still no movement on this?

**Comment by smithjd15** [comment]
> Version 2.2.1 and still no movement on this?

https://github.com/libretro/hatari/issues/8

**Comment by cmitu** [comment]
Latest Hatari (2.3.0) is included with https://github.com/RetroPie/RetroPie-Setup/commit/7100334bfe5dee6f8eedc7fe454c51355b19ffe9.
