### ISSUE TITLE
OpenPHT missing from packages in 4.1 setup script.

### ISSUE THREAD

**Issue by crogers2287** [RetroPie/RetroPie-Setup#1740]
When I access the experimental package menu, openpht is not listed there.

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
