### ISSUE TITLE
Koid wont install from menu

### ISSUE THREAD

**Issue by cryptominers-online** [RetroPie/RetroPie-Setup#1747]
hi guys cant get kodi to install via the config is there any update or commands i need to do thanks

**Comment by joolswills** [comment]
You didn't follow the instructions when opening an issue (apart from removing the text)

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
