### ISSUE TITLE
mupen64plus config file wrong path

### ISSUE THREAD

**Issue by uwe42** [RetroPie/RetroPie-Setup#1748]
Symptoms:
Not able to for emulator write a file to the SaveSRAMPath, therefore not able to save the game.

Error in log file (/dev/shm/runcomand.log)
`Core Warning: couldn't open eeprom file '/RetroPie/roms/n64/[game name].eep' for writing`

Reason:
Path dose not exist, it should be:
`/home/pi/RetroPie[...]` or `~/RetroPie/[...]`

Quick fix:
Create `/RetroPie/roms/n64/` and set rights, start game, show log, error gone.

Try correct fix:
edit `/opt/retropie/config/n64/mupen64puls.cfg` and change
`SaveStatePath 
SaveSRAMPath `
to `/home/pi/RetroPie[...]`
but has no effect. Tried reboot as well.

Edit:
Could circle the issue more:
`/opt/retropie/emulators/mupen64plus/bin/mupen64plus.sh`
in line 23 and 24:
`datadir="$home/RetroPie"
romdir="$datadir/roms"`

if this should get the home dir, it should be `$HOME`, `$home` is a empty string so it will append nothing and lead to the path to the / root.

**Comment by joolswills** [comment]
I broke this recently when I removed some lines from the file. Will sort.

**Comment by joolswills** [comment]
done. thank.

**Comment by uwe42** [comment]
thank you for the quick fix.
