### ISSUE TITLE
RetroPie does not by default set up NstDatabase.xml for Nestopia

### ISSUE THREAD

**Issue by andrewlxer** [RetroPie/RetroPie-Setup#1752]
In the default Nestopia configuration, Holy Diver (JP) for NES has significant issues with RetroPie.  I eventually tracked down the issue to a missing NstDatabase.xml.

Nestopia is configured to look for NstDatabase.xml in /home/pi/RetroPie/BIOS, however it is not populated there by default.  Considering it's distributed as part of Nestopia itself and not under any copyright restrictions, I think it would be helpful to copy it there by default for better NES compatibility.

**Comment by joolswills** [comment]
Thanks. Will look into it.
