### ISSUE TITLE
NEs30

### ISSUE THREAD

**Issue by romeoz13** [RetroPie/RetroPie-Setup#1753]
I have connected one NES30 to retropie 4.1 but when I try the second it comes up as FC30 Gamepad and wont connect.

**Comment by joolswills** [comment]
Please re-read the text you removed when postng

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
