### ISSUE TITLE
Could not successfully build N64 emulator MUPEN64Plus (GLideN64/projects/cmake/plugin/release/mupen64plus-video-GLideN64.so not found).

### ISSUE THREAD

**Issue by ericcurtin** [RetroPie/RetroPie-Setup#1756]
Running standard Retropie install on Ubuntu Mate 16.04 x86_64, getting above build failure. Logs:

https://drive.google.com/file/d/0B4a7iambBA1ST19QaEJPNjQ5NGc/view?usp=sharing

**Comment by ericcurtin** [comment]
I just took a read of the logs, should have done this sooner! I see where the issue is.

**Comment by joolswills** [comment]
Closing as this was resolved.
