### ISSUE TITLE
Are there technical reasons a .deb isn't delivered?

### ISSUE THREAD

**Issue by ericcurtin** [RetroPie/RetroPie-Setup#1757]
Just a query are there technical reasons why the setup script compiles everything from source? I tried to install this on Ubuntu Mate 16.04 x86_64 last night and it didn't work because one of the git repos the script builds from doesn't build on Linux at the moment.

Are there decisions being made at compile/link time that is dependant on the type of x86_64 macine you have? Or is it that nobody has gotten around to making a .deb? Because it would prevent this kind of scenario happening if .deb were available.

**Comment by joolswills** [comment]
Please re-read the text you removed when postng

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
