### ISSUE TITLE
not works any button after loads game

### ISSUE THREAD

**Issue by Megido6** [RetroPie/RetroPie-Setup#1761]
but i can use shortcuts for close game/open menu
after 20 seconds buttons start working.
gamepad LogitechF310

**Comment by joolswills** [comment]
Please re-read the text you removed when postng

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.

**Comment by Marc34** [comment]
Bug still here.
