### ISSUE TITLE
DUALSHOCK 3: Not all versions of the controller work

### ISSUE THREAD

**Issue by Slimior** [RetroPie/RetroPie-Setup#1762]
I currently have two DUALSHOCK 3  (the ps3 ones) controllers, that i want to connect to the Retropie 4.1 standing firmly on top Raspbian Jessie lite.

One of the controllers is from the original 'fat' ps3 bundle (it can be distinguished by 3.7V rating on the battery), while the other one is from 'PS3 Slim' edition (5.0V rating). They do not have any other distinct differences - they look and work with ps3 the same way, however when connected to the Retropie, even though detected, the older (3.7V) one does not register d-pad and right side (square, circle etc) buttons. The newer (5.0V) works perfectly fine out of the box.

Is it a sixad bug, or a Retropie one? I have both of them on me, so I could help in further tracing the issue and, potentially in solving it.

**Comment by joolswills** [comment]
Please re-read the text you removed when posting

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
