### ISSUE TITLE
Expand memory card(resize)

### ISSUE THREAD

**Issue by symbios24** [RetroPie/RetroPie-Setup#1768]
Hello i was wondering how can i run the script that expands the memory card space upon first boot with the blue screen that says Resizing filesystem i know i can run the raspi-config tool to expand the card space, but i really want to run it the other way.

Thank you

**Comment by dankcushions** [comment]
https://github.com/RetroPie/RetroPie-Setup/issues/1354#issuecomment-193658587
https://github.com/RetroPie/RetroPie-Setup/issues/1703#issuecomment-250270554
