### ISSUE TITLE
RetroPie scummvm

### ISSUE THREAD

**Issue by sarchese** [RetroPie/RetroPie-Setup#1769]
I have a problem with the emulator. I put the games in / roms / scummvm and when I load in the maquiena I do not have the emulator. Everyone appears to the emulator but not me.  Thx.
![unbenannt](https://cloud.githubusercontent.com/assets/21952764/20721975/1f3cbe3c-b665-11e6-99a7-586068d50678.PNG)
![retropie](https://cloud.githubusercontent.com/assets/21952764/20721992/318c184e-b665-11e6-916c-4f69b84f2117.PNG)

**Comment by joolswills** [comment]
Please re-read the text you removed when postng

> This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/
> 
> Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
> 
> For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.
> 
> Please remove this text before posting.
