### ISSUE TITLE
Kof 98 issue

### ISSUE THREAD

**Issue by raineltan** [RetroPie/RetroPie-Setup#1774]
I just can't seem to get KOF 98 running on any emulators on retropie 4.1. I'd tried lr-fbalpha, PiFBA, GnGeo-Pi, lr-mame2003, lr-imame4all, lr-mame2010, AdvanceMAME. None seems to be able to run King Of Fighters 98.

I'm currently running on Raspberry Pi 3 4.1.5 and i already had neogeo.zip, kof98.zip, kof98n.zip all 3 files in the neo geo folder. Every other KOF series runs fine except kof98.

Anyone manage to get it running please advise me how to do it.

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
