### ISSUE TITLE
addUdevInputRules or related setup code should ensure the user is added to "input" group

### ISSUE THREAD

**Issue by kal444** [RetroPie/RetroPie-Setup#1778]
I am not sure how I encountered this issue but for a while I couldn't detect any game controller attached and I thought it was related to xbox driver change.

Finally spent time today to figure it out. As it turns out, my user that runs emulationstation isn't in the input group so it wasn't able to read from /dev/input/js*.

I add the user to the input group and all seem well.

Looking at the code, we create the udev rules here in helpers.sh using addUdevInputRules.

It would be nice this code or something around it can ensure the user is added to the input group.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
