### ISSUE TITLE
Shader Issue

### ISSUE THREAD

**Issue by TeddyBeer1983** [RetroPie/RetroPie-Setup#1779]
For some reason, whenever I apply shader settings to a core, it apllies the changes to all cores.

Any way to make it so each system is seperate?

**Comment by joolswills** [comment]
You removed the text but did you read it ?

>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
