### ISSUE TITLE
ZDOOM Not Working

### ISSUE THREAD

**Issue by XD3l** [RetroPie/RetroPie-Setup#1785]
After install when you attempt to load the demo that comes with it, it will return you to Emulationstation.

**Comment by joolswills** [comment]
I have replied to you on your existing forum thread.

**Comment by joolswills** [comment]
now fixed.

**Comment by XD3l** [comment]
Thank you!

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>
