### ISSUE TITLE
Enable Support for KDE Neon

### ISSUE THREAD

**Issue by VR51** [RetroPie/RetroPie-Setup#1786]
KDE Neon is an Ubuntu based OS. Retro Pie will run on Neon but the setup script needs to edited to prevent the 'Unsupported OS' install error.

Edit line 84 of system.sh. Change from:

`Ubuntu|LinuxMint)`

To

`Ubuntu|LinuxMint|neon)`

**Comment by joolswills** [comment]
Thanks. Will do this with some other platform changes I will be making.

**Comment by joolswills** [comment]
This is done.

**Comment by VR51** [comment]
Thank you.
