### ISSUE TITLE
Update to DragonRise USB Driver Linux Kernel

### ISSUE THREAD

**Issue by DancingPigeon** [RetroPie/RetroPie-Setup#1787]
Given the popularity of these controllers I was wondering if/when this fix can be applied to the latest version of RetroPie:

https://github.com/raspberrypi/linux/issues/1755#issuecomment-265983761

**Comment by joolswills** [comment]
Please follow the instructions when opening an issue. (I am getting a little tired of having to continually re-post this).

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.

Having said that - the patch is already in the upcoming raspberry pi kernel (can be updated to with rpi-update). There are forum threads about this already.
