### ISSUE TITLE
RPi3 and PCxs2

### ISSUE THREAD

**Issue by firepro20** [RetroPie/RetroPie-Setup#1794]
Is it possible to get the pcxs2 working on a RPi3 running RetroPie?

**Comment by dankcushions** [comment]
the text you removed:

> This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

the documentation:

https://github.com/retropie/retropie-setup/wiki/Playstation-2

> This is only for x86 builds- Not the Raspberry Pi!.
