### ISSUE TITLE
Pi3 with experimental bootcode (BRANCH=next rpi-update) __platform variable not set in system.sh

### ISSUE THREAD

**Issue by petersteger** [RetroPie/RetroPie-Setup#1809]
in system.sh
get_platform wants BCM2709 to set the variable to pi3.
But with the newest bootfiles (i did an unpdate to boot it from USB) it is BCM2835
please include in select case.

**Comment by joolswills** [comment]
Unfortunately it will require more than just that - https://github.com/raspberrypi/firmware/issues/705

It's no quick fix - need to parse the Revision number.
