### ISSUE TITLE
mk arcade joystick RPi Zero

### ISSUE THREAD

**Issue by matheusfpinto** [RetroPie/RetroPie-Setup#1824]
Hello, I'm building a portable video game with raspberry pi zero. For controls I'm using the mk arcade joystick drivers that are up and running, However is not a way to add the left and right Triggers buttons on the PlayStation 1. I wonder if you are using this driver, Thanks!

**Comment by joolswills** [comment]
https://github.com/recalbox/mk_arcade_joystick_rpi is the github site for that driver.

For more help please use the forum as mentioned when opening an issue.
