### ISSUE TITLE
Mame2014 liberto

### ISSUE THREAD

**Issue by gc9n** [RetroPie/RetroPie-Setup#1825]
Hello
i would like to add the mame2014 liberto emulator , is there any way to do it ?

**Comment by gc9n** [comment]
WTF  man

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
