### ISSUE TITLE
change in required BIOS filename for beetle-pcfx-libretro core

### ISSUE THREAD

**Issue by markwkidd** [RetroPie/RetroPie-Setup#1830]
Due to a minor error in the original porting from standalone Mednafen to libretro, the PC-FX core has been looking for the wrong BIOS filename -- it should be **pcfx.rom** instead of pcfx.bios. This has been corrected as of today's PR: https://github.com/libretro/beetle-pcfx-libretro/pull/15

I thought I'd give you a heads up in case it affects the RetroPie setup script which seems to refer the BIOS by filename.

edit: corrected the link to the PR

**Comment by joolswills** [comment]
thanks.
