### ISSUE TITLE
add sdl1 scummvm to fix joystick and mt32

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1835]
on the RPI with sdl2, the mouse pointer moves large amounts and is unusable under joystick control.

Look into a workaround against scummvm or sdl2.

**Comment by Ilbraschio** [comment]
I'm facing a similar problem, using joystick control behaves like the mouse pointer location is not refreshed while moving, and gets refreshed as soon as i stop to move it.

**Comment by joolswills** [comment]
Will add an optional scummvm linked against sdl1 - this should fix this, and also fix the mt-32 issue - https://retropie.org.uk/forum/topic/10477/scummvm-with-mt-32-support-enabled

**Comment by arielscarpinelli** [comment]
Just to note that new scummvm 2.0 fixes the joystick issues

**Comment by joolswills** [comment]
Thanks. @HerbFargus is doing some testing and we will update soon (removing sdl1 build if no longer needed)

**Comment by HerbFargus** [comment]
can confirm that joystick/dpad is fixed with 2.0
