### ISSUE TITLE
Simple theme favorites

### ISSUE THREAD

**Issue by megahz** [RetroPie/RetroPie-Setup#1840]
hi, is is possible to add the favorites feature in the simple theme?

thanks

**Comment by joolswills** [comment]
This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
