### ISSUE TITLE
Nexus player controller support issues

### ISSUE THREAD

**Issue by massahwahl** [RetroPie/RetroPie-Setup#1841]
Has anyone been able to get this controller to work properly yet? I can't find much online about it, but the controller registered fine but when assigning the buttons the triggers will not register and the start/select buttons won't either. Home button registers but I want to bind a command to that button to exit games. Any help is appreciated!

**Comment by joolswills** [comment]
This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
