### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Markus1995** [RetroPie/RetroPie-Setup#1842]
Hello,

How can i change the Language of the ES?

Thank you in advance

**Comment by joolswills** [comment]
We do not have a multi language es. Recalbox does if you need it. Note when you opened this issue:

This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
