### ISSUE TITLE
Unclear method N°2 : Unix format

### ISSUE THREAD

**Issue by Zblay** [RetroPie/RetroPie-Setup#1843]
Hello, 

I struggled using method N°2 because as a non-expert user i didn't think of editing the wifikeyfile.txt with notepad++ and then click Edit>EOL Conversion>Convert to Unix format. 
I found the trick on this video https://www.youtube.com/watch?v=losE5pdVqsc
Maybe this should be mentionned in method n°2.

Thanks for the amazing work

**Comment by joolswills** [comment]
There should be no need to do EOL conversion on the latest retropie-setup for the wiki config file.

The forum would be the best place for discussion as mentioned when opening an issue. thanks.
