### ISSUE TITLE
NEC PC-8801 support

### ISSUE THREAD

**Issue by nakatamaho** [RetroPie/RetroPie-Setup#1845]
I have just add a NEC PC-8801 (quasi88) support for retropie.
According to http://www.eonet.ne.jp/~showtime/quasi88/index.html, it is licensed under modified BSD license. 

Note: We removed non-free part by disabling commenting out "USE_FMGEN    = 1" in the Makefile.

**Comment by nakatamaho** [comment]
[patch-quasi88.txt](https://github.com/RetroPie/RetroPie-Setup/files/713927/patch-quasi88.txt)

**Comment by joolswills** [comment]
Please submit this as a PR and I will review. thanks.

**Comment by nakatamaho** [comment]
Hi,
https://github.com/RetroPie/RetroPie-Setup/pull/1847
(Is it correct? I'm new to raise a PR...)

**Comment by joolswills** [comment]
No, afraid not. I recommend having a read on the subject and experiment with your own repository to understand how it works.

**Comment by Darknior** [comment]
Woaw so exiting new 👍 

@nakatamaho  do you plan to port too PC-98 ?
I really love this computer ... and i know some people port it perfectly on xBox 1 last year.

For linux you can use the port of Neko Project II called Xnp2. However, as of this writing there are some sound problems that need to be investigated ... they are fixed on xbox and i can have the source code if you want 😎 

http://www.nonakap.org/np2/
https://www.shrinemaiden.org/forum/index.php?topic=11117.0

Thanks

**Comment by cmitu** [comment]
I think this can be closed ? Both `quasi88` and `lr-quasi88` are included now in RetroPie-Setup.

**Comment by cmitu** [comment]
Closing, since the emulators are included in RetroPie-Setup now.
