### ISSUE TITLE
It is completly magic how bad this thing works

### ISSUE THREAD

**Issue by draxd** [RetroPie/RetroPie-Setup#1846]
Hello
I just tried you Retro pie on Raspberry pie 3, and I must say I'm bedazzled how bad this thing does not work. I wish to congratulate to you all on complete incompetence, please kill your self and kill this useless project so that someone else could actually create something that works

**Comment by CoalaJoe** [comment]
Can not reproduce

**Comment by draxd** [comment]
I love your answer on so many levels

**Comment by draxd** [comment]
This is joystick calibration simulation ;)

**Comment by joolswills** [comment]
Thanks for the feedback. I'm impressed you managed to sign up on GitHub. Cheers.
