### ISSUE TITLE
No sound on retropie

### ISSUE THREAD

**Issue by JORDANWELSTEAD** [RetroPie/RetroPie-Setup#1850]
Can someone please help
I'm getting any sound on retropie unless i'm in kodi
When I go to the command line this is what I get
![dsc_0011](https://cloud.githubusercontent.com/assets/10480811/22177645/dd5d9d72-e019-11e6-82bb-b57790710bd9.JPG)
I've looked all over for a solution but I can't find any
I'm running retropie 4.1.6 on a raspberry pi 3 model B

**Comment by joolswills** [comment]
This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
