### ISSUE TITLE
Plymouth entry is removed from cmdline.txt after disabling / enabling splashscreen on boot

### ISSUE THREAD

**Issue by movisman** [RetroPie/RetroPie-Setup#1861]
Hi,

If you configure the splashscreen from the setup script, and select the option to disable the splashscreen on boot, cmdline.txt gets changed and removes plymouth.enable=0 from the file. If you re-enable the splashscreen, the setting is not restored.

Cheers

**Comment by joolswills** [comment]
as a workaround for now instead of "disabling" just remove the splashscreen module completely and reinstall it and it will disable plymouth again. I need to move some functions around. thanks.

**Comment by movisman** [comment]
No worries, I actually stumbled across it by accident, as I selected the disable option by mistake whilst in the menu. Then I noticed console output and realised something must have changed inside the cmdline.txt. Just thought i'd give you a heads up.

Cheers for the help.

**Comment by joolswills** [comment]
This should be resolved now. Note the behaviour is now:

 * only disable plymouth when screensaver module is installed
 * enable plymouth when screensaver module is removed - not when it is just disabled
