### ISSUE TITLE
NES30 Pro and Buffalo Classic 8 USB Gamepad unresponsive in Emulators but works fine in EmulationStation

### ISSUE THREAD

**Issue by guitarjunkee** [RetroPie/RetroPie-Setup#1864]
Hi All,

I am super new to this...so bear with me.

I have retropie loaded (the most recent version as of today), roms work with keyboard (NES only so far), controllers appear to load (little yellow annotations in the bottom left corner of the screen, yet don't work at all with the ROMs). I tried this fix:

cd /opt/retropie/emulators/retroarch/
sudo ./retroarch-joyconfig -j 0 >> /opt/retropie/configs/all/retroarch.cfg

but received the error that "sudo ./retroarch-joyconfig: no such directory"

I am new to Linux but have basic Python and HTML programming experience. Could this be the udev issue that I have read about in other posts? If so, how do I go about fixing this. I have a Resberry Pi 3 B+ with all new images of everything as of today.

Thanks for the help.

**Comment by joolswills** [comment]
Please follow the instructions in the text you removed when opening the issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
