### ISSUE TITLE
PSX emu bug,the game Digimon_Tamers_Battle_Evolution still loading

### ISSUE THREAD

**Issue by maBiBi** [RetroPie/RetroPie-Setup#1868]
somebody can help?

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
