### ISSUE TITLE
Manually inputing gamegenie gameshark and pro action replay codes

### ISSUE THREAD

**Issue by markratner** [RetroPie/RetroPie-Setup#1877]
I have been trying to manually input cheats for my games because most of the ones pre programmed in are incorrect and unusable. I have also made my own over the years and want to put custom codes in. I would like a step by step tutorial on how to manually add cheats for my games. I would also like to know why there is no support and i cannot find cheats for n64 titles

**Comment by HerbFargus** [comment]
and I would like to know why you didn't post on the forum as requested when you opened the ticket.

>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
