### ISSUE TITLE
Vice won't install on Ubuntu PC 32bit

### ISSUE THREAD

**Issue by hardmanm** [RetroPie/RetroPie-Setup#1878]
Can't install Vice on an Ubuntu PC

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

before you post on the forum please make sure you read the information as requested on registration - more information will be needed to advise (such as a build log).
