### ISSUE TITLE
CoolCV is missing from retropie setup script under Ubuntu 14 after basic install.

### ISSUE THREAD

**Issue by gator2003** [RetroPie/RetroPie-Setup#1886]
What the title says, no CoolCV option in the setup script 4.1.14. Not sure if an oversight or not, thought I'd post anyway.

**Comment by joolswills** [comment]
The included CoolCV is rpi only.

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
