### ISSUE TITLE
Retropie Controller Setting - Right Trigger Skipping on Wireless Gamepads only

### ISSUE THREAD

**Issue by ianpaulstone** [RetroPie/RetroPie-Setup#1888]
Hi There,

I can't seem to map right trigger to the bluetooth controllers I've put onto my retropie. As soon as I map Left Trigger the Right Trigger automatically skips.

This only happens when I'm using the bluetooth controllers that I've installed with a dongle. When I map a cabled controller it maps fine. The problem also reoccurs when I try to map my steering wheel, which means that the brake often has to be the accelerator and the brake pedal itself doesn't work.

The two wireless controllers I can't map are the:

SZMY-POWER Gamepad
ShanWan PC/PS3/Android

The Racing Wheel is the:

Logitech Logitech Racing Wheel

Is there any workaround, or steps I need to take to resolve this issue please?

thank you

Ian

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
