### ISSUE TITLE
Attract Mode after new compile does not start up

### ISSUE THREAD

**Issue by estefan3112** [RetroPie/RetroPie-Setup#1893]
Error message: error while loading shared libraries: libsfml-graphics.s.o.2.3: cannot open shared object file: No such file or directory
Is there anything else I have to update for attract mode to work?
By the way: Attract Mode rules :-).

**Comment by joolswills** [comment]
I'm assuming this is on a Raspberry Pi ? RetroPie v4.1 ? or ?

**Comment by joolswills** [comment]
I reproduced it on a rpi - was due to a recent change.

**Comment by estefan3112** [comment]
Retropie 4.1 with latest setup script, Experimental Package. Cool, I will try it tomorrow!!

**Comment by estefan3112** [comment]
I can confirm that Attract Mode update from within Retropie works again, many thanks!

**Comment by gpr17** [comment]
I am having a similar error, but with libsfml-graphics.so.2.4 is there an issue?
