### ISSUE TITLE
Mupen64Plus ignores volume controls in aida/ES Menu

### ISSUE THREAD

**Issue by liquid600pgm** [RetroPie/RetroPie-Setup#1895]
Just like it says in the title. I have set my volume on aida mixer to 10, and in ES Menu to 10% and Mupen64plus still outputs 100% of the volume. I am using mupen64plus-GLide64.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
