### ISSUE TITLE
Propagate SIGINT to scraper

### ISSUE THREAD

**Issue by sselph** [RetroPie/RetroPie-Setup#1898]
This is a very minor issue. Please prioritize below everything else.

I am testing a change and pressed ctrl+c while running the scraper and it immediately exits everything, but if the scraper gets the INT signal it will gracefully halt by finishing any pending requests then writing the gamelist.xml. I tried to capture the sudo child process ID for the scraper and trap sigint then send kill -INT to the scraper but can't quite get it to work. It was several variations of the following.

```bash
trap 'kill -INT $PID; while kill -0 $PID 2> /dev/null; do sleep 1; done;' INT
sudo -u $user "$md_inst/scraper" ${params[@]} &
local SPID=$!
local PID=`ps --ppid $SPID -o pid=`
wait $SPID
```

Maybe your bash-fu is stronger than mine.

**Comment by joolswills** [comment]
Shouldn't need to background the scraper. This seems to work ok

```
diff --git a/scriptmodules/supplementary/scraper.sh b/scriptmodules/supplementary/scraper.sh
index 724d92b2..85248c62 100644
--- a/scriptmodules/supplementary/scraper.sh
+++ b/scriptmodules/supplementary/scraper.sh
@@ -111,14 +111,17 @@ function scrape_scraper() {
     fi
 
     [[ "$system" =~ ^mame-|arcade|fba|neogeo ]] && params+=(-mame -mame_img t,m,s)
+
+    trap 'trap 2; return 1' INT
     sudo -u $user "$md_inst/scraper" ${params[@]}
+    trap 2
 }
 
 function scrape_all_scraper() {
     local system
     while read system; do
         system=${system/$romdir\//}
-        scrape_scraper "$system" "$@"
+        scrape_scraper "$system" "$@" || return
     done < <(list_systems_scraper)
 }
```

I want to do some global ctrl+c handling in retropie-setup though so I will do this after - however, please see if it works for you.
