### ISSUE TITLE
Retropie won't boot after transfering some ROMs

### ISSUE THREAD

**Issue by vitoorh** [RetroPie/RetroPie-Setup#1900]
Hey, guys! I'm having a issue with my Retropie. Everytime I transfer a large amount of data (psx roms) to my raspberry it won't boot. It spams a lot of messages on the screen, somenthing to do with systemd-fsc[102], inodes, something without compression support. It asks if I want to clear and then fix the erros, which the system always chooses 'Yes'. These messages keep rolling on the screen forever, it's so fast I can't even read it! I've tried to format my microSD card (Transcend 128Gb Class 10) several times but this always happens. The roms I'm tranfering are .pbp files.
Any help will be appreciated. Thanks in advance.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/
