### ISSUE TITLE
Support for Hyperkin X91

### ISSUE THREAD

**Issue by sirdashadow** [RetroPie/RetroPie-Setup#1906]
Xboxdrv does not support the Xbox One Wired Hyperkin X91 because the VID and PID do not match the drivers. The VID is 2E24 and the PID is 1688.

**Comment by joolswills** [comment]
The upstream xboxdrv site is https://github.com/xboxdrv/xboxdrv - although there is currently no development happening. There may well already be a PR for that feature. We are running from another fork which has some additional patches (https://github.com/zerojay/xboxdrv). Xboxdrv also has issues with the current kernel - did you try the xpad driver ?

Also note we prefer the forum to be used as the first point of contact as mentioned when opening an issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
