### ISSUE TITLE
Nyko PlayPad 80692-P37

### ISSUE THREAD

**Issue by mascondante** [RetroPie/RetroPie-Setup#1911]
I notice that two issues were closed on this issue with no progress being made. Please don't be trigger happy with the close button this time. The Nyko PlayPad D buttons are falsely identified by EmulationStation as the keyboard instead of the controller itself. Thus I cannot set up the D pad because it is ignored when registering with my Bluetooth controller. Also the select button does not register either as part of the game pad.

Latest version. Did update, upgrade dist-upgrade and updated the setup script and ran it to upgrade the rest of things.

The easiest fix I see is allowing for listening from multiple inputs as one controller but I'm no expert.

Thanks in advance.

**Comment by joolswills** [comment]
Issues are closed sometimes because the wrong bugtracker is used or the instructions are not followed when opening an issue.

In this case you should first start a topic on the forum - it may be as simple as setting up a udev rule using retropie-setup

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
