### ISSUE TITLE
Mupen64Plus: save actual config version at build time

### ISSUE THREAD

**Issue by gizmo98** [RetroPie/RetroPie-Setup#1925]
I'm a little bit tired modifying config version of GlideN64 every time there is a change. Wouldn't it be smarter to read out config.h and store the actual config version of the current build at build time in a ini file like GlideN64_Config_Version.ini? The startup script can pick up the stored value and set the right value in mupen64plus.cfg.

**Comment by joolswills** [comment]
we could and that may be a good workaround. Even better upstream could change the way it works so you don't need to have the exactly matching version (I don't know of other software in retropie that requires a specific version number in the config).
