### ISSUE TITLE
ScummVM Mouse Going to the left

### ISSUE THREAD

**Issue by GitPi22** [RetroPie/RetroPie-Setup#1928]
I'm having the same issue that the person from this thread had
https://github.com/RetroPie/RetroPie-Setup/issues/1337#issuecomment-193816437

It seems to have been fixed when he updated.

I'm using version 1.9.1Pre with a Wii U Pro Controller. The controller works perfectly for all of the other emulators but with scumm my cursor always goes to the left. I can bring it to about 3/4 of the way to the right side, but the second I let go of the joystick the cursor jumps back to the left side. 

I've found that if i change the resolution of scumm that i can get the cursor a bit farther and launch a game but I cant get it all the way to the right side and it still jumps back to the left.

If anyone has any experience with this I'd greatly appreciate some help.

Thanks!

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
