### ISSUE TITLE
GBA (GPSP) Emulator Key Mappings 

### ISSUE THREAD

**Issue by SergeBakharev** [RetroPie/RetroPie-Setup#193]
I am experiencing two separate issues with the GPSP emulator key mappings:
1. The in-game start button is mapped to the button defined as input_player1_b_btn not input_player1_start_btn.
2. I am unable to exit the emulator (input_enable_hotkey_btn + input_exit_emulator_btn) . This functionality works fine for other emulatorcores.

Just in case its relevant below is my retroarch.cfg (minus the commented settings):
system_directory = /home/pi/RetroPie/emulatorcores/

video_smooth = false

input_player1_a = x
input_player1_b = z
input_player1_y = a
input_player1_x = s
input_player1_start = enter
input_player1_select = rshift
input_player1_l = q
input_player1_r = w
input_player1_left = left
input_player1_right = right
input_player1_up = up
input_player1_down = down

input_player1_joypad_index = 0
input_player2_joypad_index = 1

input_enable_hotkey_btn = 8
input_exit_emulator_btn = 9

input_player1_joypad_index = "0"
input_player1_b_btn = "2"
input_player1_y_btn = "3"
input_player1_select_btn = "8"
input_player1_start_btn = "9"
input_player1_up_axis = "-1"
input_player1_down_axis = "+1"
input_player1_left_axis = "-0"
input_player1_right_axis = "+0"
input_player1_a_btn = "1"
input_player1_x_btn = "0"
input_player1_l_btn = "4"
input_player1_r_btn = "5"
input_player1_l2_btn = "6"
input_player1_r2_btn = "7"
input_player1_l3_btn = "10"
input_player1_r3_btn = "11"
input_player1_l_x_plus_axis = "+0"
input_player1_l_x_minus_axis = "-0"
input_player1_l_y_plus_axis = "+1"
input_player1_l_y_minus_axis = "-1"
input_player1_r_x_plus_btn = "1"
input_player1_r_x_minus_btn = "3"
input_player1_r_y_plus_btn = "2"
input_player1_r_y_minus_btn = "0"

input_player2_joypad_index = "1"
input_player2_b_btn = "2"
input_player2_y_btn = "3"
input_player2_select_btn = "8"
input_player2_start_btn = "9"
input_player2_up_axis = "-1"
input_player2_down_axis = "+1"
input_player2_left_axis = "-0"
input_player2_right_axis = "+0"
input_player2_a_btn = "1"
input_player2_x_btn = "0"
input_player2_l_btn = "4"
input_player2_r_btn = "5"
input_player2_l2_btn = "6"
input_player2_r2_btn = "7"
input_player2_l3_btn = "10"
input_player2_r3_btn = "11"
input_player2_l_x_plus_axis = "+0"
input_player2_l_x_minus_axis = "-0"
input_player2_l_y_plus_axis = "+1"
input_player2_l_y_minus_axis = "-1"
input_player2_r_x_plus_btn = "1"
input_player2_r_x_minus_btn = "3"
input_player2_r_y_plus_btn = "2"
input_player2_r_y_minus_btn = "0"

**Comment by Kvitekvist** [comment]
> I added your way of configuring GPSP input to the wiki!

Hi, I have an arcade stick with 10x bottons. For some reason when I press F10 to map the keys for the GPSP i cannot map LEFT or RIGHT. 

LEFT and RIGHT works great on NES and other emulators but not on GBA with GPSP (which I must run for some games to run).

Any ideas on what I can do to fix or tweak this to work? I do not have controller issues with xbox or PS3 controller. I only have issue with the arcade kit.

I am running on a Pi 2 Model B, with version 4.02 of retropie.

**Comment by joolswills** [comment]
@Kvitekvist please use the forum for support rather than posting on 2 year old closed tickets. https://retropie.org.uk/forum/
