### ISSUE TITLE
Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by Z4st4m** [RetroPie/RetroPie-Setup#1930]
Greetings, when im using my Nintendo Switch Pro Controller via. Bluetooth, everything works like a charm with a little issue.

The "UP" and "DOWN" from the left and right stick doenst work, they doesn't get recognized. D-Pad and everything else works fine.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
