### ISSUE TITLE
Kodi Stand alone no longer working in Kodi 17-RC2

### ISSUE THREAD

**Issue by njloki30** [RetroPie/RetroPie-Setup#1931]
I updated today to Kodi 17.1 I'm running on my pi3 with RetoPie 4.1.21  I was using the stand alone option for Kodi but it doesn't work anymore. The only way i can successfully start and exit Kodi is through the PORTS menu. Using the standalone option, the log throws the error Exception SystemExit in <function _remove at 0x5e556530> ignored and Kodi just hangs on screen with the exit pop up. Not sure why. 

The only other log message i get is when loading Kodi shown here, but it loads and works fine. /usr/bin/kodi: 68: /usr/bin/kodi: /usr/bin/pulseaudio: not found

I'm not necessarily looking for support, but reporting an issue in case it's determined to be a bug or something.

**Comment by joolswills** [comment]
We don't manage /build Kodi - the packager is on the forum though so please just post there as requested when opening a ticket.
