### ISSUE TITLE
Dead link in First Installation documentation

### ISSUE THREAD

**Issue by mmatyas** [RetroPie/RetroPie-Setup#1933]
The `enable ssh` link under https://retropie.org.uk/docs/First-Installation/#transferring-roms / SFTP points to https://retropie.org.uk/docs/ssh, which doesn't seem to exists.

**Comment by joolswills** [comment]
i have fixed the link on the wiki - it was a case sensitivity thing. Docs will be updated later (they are generated from the wiki).

I would prefer for the forum to be used for stuff like this - there are lots of problems on the wiki (as it is user editable), and a ticket for every minor wiki link issues won't be manageable.

**Comment by HerbFargus** [comment]
My bad :) ta
