### ISSUE TITLE
A button forced to bind

### ISSUE THREAD

**Issue by Jan200101** [RetroPie/RetroPie-Setup#1934]
Everytime you want to set the input for a controller you are forced to set the A key, this gets in the way whe n you want to bind controllers with lesser buttons (n64 controller remake for example) where there A button isnt needed in these games

**Comment by joolswills** [comment]
This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
