### ISSUE TITLE
Problems with the PCSX-Rearmed

### ISSUE THREAD

**Issue by ToThrane** [RetroPie/RetroPie-Setup#1935]
Hello

I am using RetroPie 4.2 on my Raspberry Pi B+/Zero 
USB Keyboard
Ethernet

I have tried getting the PCSX-Rearmed emulator to work for about 2 weeks now. I had it up and running and play PS1 games no problems on RetroPie 4.1.20, but i updated the software and all my emulators and now the PCSX-Rearmed do not work.
The Bios are in the right folder and my games are bin/cue.
 
I tried:
Install a new image (RetroPie 4.2)
Install the emulator again
Updated from binary/source
Install a older version of RetroPie (3.8, 4.0 and 4.1)
Tried a Basic install
I updated the RetroPie-Setup.script

I have my computer connected and can look through the shared folders, and found the emulators.cfg file and it say:
pcsx-rearmed = "pushd /opt/retropie/emulators/pcsx-rearmed; ./pcsx -cdfile %ROM%; popd"
I then used the RetroPie's file manager and found the path, but it does not contains the pcsx file

Does anyone have any ideas

**Comment by joolswills** [comment]
his issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
