### ISSUE TITLE
add wip/experimental libretro vice

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1940]
as title. 

I have a WIP module already.

**Comment by joolswills** [comment]
preliminary module added to experimental. The core is a bit WIP still, and lots of stuff isn't hooked up to the GUI. The gui also doesn't seem to save any settings, and by default "True drive emulation" is off, which breaks d64 loading.

Recommend people use the standalone vice emulator for now.

**Comment by windale** [comment]
When "True drive emulation" is OFF you have to enable "Virtual device traps". The difference in loading speed with TDE off is night and day, but like you say, the settings don't save anyway and it's very WIP.

**Comment by joolswills** [comment]
Issues should be reported to the libretro core. They are aware of some of the problems though.
