### ISSUE TITLE
[Freeze] 2 GAMEPADS DETECTED

### ISSUE THREAD

**Issue by knuxyl** [RetroPie/RetroPie-Setup#1945]
On a fresh install of Retropie on Rpi3 on top of debian distro I get the WELCOME screen saying 2 gamepads were detected (my 360 controller and wireless keyboard).

I hold the a button on my xbox 360 controller and it says GENERIC X-BOX PAD but then just sits there. I had installed Retropie standalone earlier and it did not have this problem.

I've tried multiple things and this certainly seems to be a bug source side. The install script ran successfully except for lr-snes9x2002 which I had to go in and make myself because it needed some bandaid flags. Everything else worked.

**Comment by joolswills** [comment]
You didn't read the text you removed when posting.

This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

Please remove this text before posting.
