### ISSUE TITLE
[Request] cdogs-sdl

### ISSUE THREAD

**Issue by Omnija** [RetroPie/RetroPie-Setup#1947]
I've compiled and tested the game and has been working. I think it would a nice addition to the ports games and hopefully gets incorporated. Has controller and multiplayer support.

Source
https://github.com/cxong/cdogs-sdl

Prerequisites
https://github.com/cxong/cdogs-sdl/wiki/Developer-Getting-Started:-Linux

**Comment by joolswills** [comment]
We prefer requests to go to the forum first as detailed when opening an issue

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.

**Comment by zerojay** [comment]
With this merged, shouldn't this issue be closed?

**Comment by joolswills** [comment]
yep. Thanks.
