### ISSUE TITLE
4.2 - No Amiga entry in es_systems.cfg 

### ISSUE THREAD

**Issue by patdnk** [RetroPie/RetroPie-Setup#1949]
There is no entry for Amiga in systems in es_systems.cfg file. Even after installing Amiberry - there is no visibility on UI for Amiga option.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
