### ISSUE TITLE
controller re-configure

### ISSUE THREAD

**Issue by McSterls** [RetroPie/RetroPie-Setup#1950]
I set up RetroPie on a Raspberry 3, installed RetroPie using the official wiki, was able to setup and use my Buffalo controller without issue, loaded ROMs everything works, but I was having issues with MAME games, so i found a RetroPie ISO online that was already configured to run MAME, but after flashing the memory in the Raspberry my controller doesn't work with the new image, and I can't get back to the configure controller screen without having a working controller. I can plug a keyboard in and the only button that seems to work is F4 to drop to the PS prompt. Anyone have an idea what I need to do?

Thanks.

**Comment by HerbFargus** [comment]
>This issue tracker is NOT for Help / Support - Use the RetroPie forum - https://retropie.org.uk/forum/

>Please make sure you read the "guidelines for contributing" above before opening an issue. Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes. Please remove this text before posting.
