### ISSUE TITLE
SSH doesn't work, empty key files

### ISSUE THREAD

**Issue by tom-hines** [RetroPie/RetroPie-Setup#1957]
I enabled SSH via raspi-config, rebooted , attempted to ssh in and got a "connection reset" error.  The logs in /var/log/auth.log showed a problem with the key files.  I looked in /etc/ssh and all the key files were empty.  I had to run ssh-keygen to generate them.  Then it worked.  This should work out of the box.

pi: Model 3B
retropie: 4.2

**Comment by joolswills** [comment]
You must have powered off badly somehow or interrupted it.  Not a RetroPie bug anyway (raspbian). Please use the forum as mentioned when opening an issue.

**Comment by tom-hines** [comment]
Sorry, I thought raspi-config was a RetroPie utility.
