### ISSUE TITLE
dpkg warning during dist-upgrade (xpad.ko)

### ISSUE THREAD

**Issue by cybrnook** [RetroPie/RetroPie-Setup#1960]
(Low hanging fruit)

Just wanted to make mention that on a fresh install of the latest release (4.2 for rpi 2/3) there is an issue during the initial dist-upgrade that is thrown from dpkg:

Unpacking raspberrypi-kernel-headers (1.20170427-1) over (1.20170303-1) ...
dpkg: warning: unable to delete old directory '/lib/modules/4.4.50-v7+': Directory not empty

The contents of this directory are:
/lib/modules/4.4.50-v7+
/lib/modules/4.4.50-v7+/extra
/lib/modules/4.4.50-v7+/extra/xpad.ko

Seems to be an Xbox One Controller driver? Apologies if I am incorrect.

**Comment by joolswills** [comment]
That's a warning not an error.
