### ISSUE TITLE
A few scripting warnings/errors during "Basic Install"

### ISSUE THREAD

**Issue by cybrnook** [RetroPie/RetroPie-Setup#1961]
(Low hanging fruit)

On a fresh install of that latest release (4.2 for rpi 2/3).

During the initial setup script (latest 4.2.2), there are a couple warnings/errors during the "Basic Setup":

Mupen64Plus:
Core: Couldn't open configuration file '/opt/retropie/configs/n64/mupen64plus.cfg'.  Using defaults.
Core Warning: No version number in 'Core' config section. Setting defaults.
Core Warning: No version number in 'CoreEvents' config section. Setting defaults.
UI-Console Warning: No version number in 'UI-Console' config section. Setting defaults.
UI-Console Error: no ROM filepath given

Configuring 'lr-fbalpha' : Arcade emu - Final Burn Alpha (v0.2.97.39) port for libretro:
cp: cannot stat ‘/opt/retropie/libretrocores/lr-fbalpha/metadata/hiscore.dat’: No such file or directory
chown: cannot access ‘/home/pi/RetroPie/BIOS/fba/hiscore.dat’: No such file or directory

**Comment by joolswills** [comment]
Mupen64 can be ignored. FBA issue is just because I need to rebuild binaries after a minor update. Can be ignored also. Please use the forum as mentioned when opening an issue
