### ISSUE TITLE
Kodi fails install from binary in latest build (Ubuntu 16.04.2)

### ISSUE THREAD

**Issue by devildog820** [RetroPie/RetroPie-Setup#1966]
Trying to install Kodi with the latest RetroPie setup script gives a missing packages error in Ubuntu 16.04.2.

```
E: Unable to locate package kodi-peripheral-joystick
E: Unable to locate package kodi-inputstream-adaptive
E: Unable to locate package kodi-inputstream-rtmp
```

Adding the Kodi repo (ppa:team-xbmc/ppa) allows the install to complete.

**Comment by joolswills** [comment]
ok. I'll add the repository.
