### ISSUE TITLE
Question for developers !

### ISSUE THREAD

**Issue by 1Daem0n** [RetroPie/RetroPie-Setup#1977]
I decided to buy a Raspberry Pi 3 _B, tell me if I can play it on PlayStation 2 and Wii, on the site as it is not clearly written. If not, then wait for these emulators to  Raspberry Pi 3 _B ??????

**Comment by joolswills** [comment]
Please use our forum for advice. Thanks

**Comment by joolswills** [comment]
Also - no. You can't emulate those platforms on a rpi
