### ISSUE TITLE
quake 1 mission packs

### ISSUE THREAD

**Issue by symbios24** [RetroPie/RetroPie-Setup#1982]
Hello there, i`m jim

I`m using retropie v4.2 on a raspberry pi2 and installed libretro-tyrquake, quake 1 and episode 5-dopa working fine but mission pack 1 and 2 are not working, when i click to them they return me back to the main menu of retropie i followed the instructions here "https://github.com/RetroPie/RetroPie-Setup/wiki/Quake"

I appreciate if you can help me

ps i cannot post in official retropie forum its very annoying the way it works.

Thank you

**Comment by joolswills** [comment]
What do you mean you cannot post?

**Comment by symbios24** [comment]
i dont know how to post i tried some time following instructions from here but it did not work

**Comment by joolswills** [comment]
Please be more specific. The forums do work as we have over 9000 user accounts.

**Comment by symbios24** [comment]
well not for me anyway thanks for nothing

**Comment by joolswills** [comment]
If you are unable to expand on "did not work" then don't expect me to be able to help you with the forum.

**Comment by symbios24** [comment]
useless anyway

**Comment by joolswills** [comment]
Well done for making the block list.

**Comment by ItsNotNitro** [comment]
thats not good.
