### ISSUE TITLE
ScummVm Air mouse - Cursor working but trapped in bounding box 

### ISSUE THREAD

**Issue by Adfield** [RetroPie/RetroPie-Setup#1984]
Hi,

Not having much luck at the retropie forums so im throwing this out there - feel free to lock if this isn't the appropriate place to post, but I appreciate any potential help.

My plan was to use an air mouse as a sort of 'pointer' to control the point and click interface on my raspberry pi, similar to how Scummvm functions on the wii. 

So i got hold of an old wiimote and a mayflash dolphin sensor bar which plugs into the pie via USB. With the bar set to mode 2 (mouse and keyboard), the sensor bar translates the wiimote's IR signal into mouse movement. 
I got this working to an extent, when in the scumm menu or with a game booted, the cursor moves freely (and surprisingly steady! buttons are mapped etc) but with one huge caveat: the cursor is confined to a small box in the upper left corner of the screen, and hits an invisible wall if you try and move it across the full width of the screen. 

Strangely if i plug a regular mouse back in, the problem disappears and I regain full control of the screen again. 

Pretty close to working but no dice, I'm hoping there's potentially a setting that needs altering somewhere? 

Any ideas? 

The help is hugely appreciated! 

Thanks,

**Comment by joolswills** [comment]
Please use the forum as directed when opening an issue. You have a post there from less than 24 hours ago, and I can't see that anyone directed you to open an issue here.

It's not something that is specifically RetroPie related. Could be a SDL2, driver/hardware, or ScummVM issue.
