### ISSUE TITLE
SSH is not usable without a keyboard

### ISSUE THREAD

**Issue by AllenKll** [RetroPie/RetroPie-Setup#1999]
In the documentation for setup, https://github.com/RetroPie/RetroPie-Setup/wiki/First-Installation#hardware, It is indicated that SSH can be used instead of a keyboard. However, following the link to setup SSH indicates you need to type commands with a keyboard. https://github.com/retropie/retropie-setup/wiki/SSH#enable-ssh

Seems to be an oversite to no have a simple, "Enable SSH" option somewhere in the menu system, that can be reached with a controller.

**Comment by joolswills** [comment]
Please use the forum as indicated when opening an issue.

raspi-config can be launched via RetroPie menu in ES - and can be used with a  joypad.

**Comment by AllenKll** [comment]
Hello,
  I searched the forum, and there is still no answer as to how this can be done.  I believe that maybe it can be done, if so, then this is a documentation bug, if not it is a feature bug.  Either way it is a bug.

**Comment by AllenKll** [comment]
Using version 4.2.  Rasberry pi B

**Comment by dankcushions** [comment]
https://github.com/RetroPie/RetroPie-Setup/wiki/SSH#enable-ssh

**Comment by joolswills** [comment]
It's a support issue. It's not a bug. Missing info in the documentation is not a bug, but as mentioned when opening a ticket, we prefer the forum to be used first. It's as simple as there are more people to advise on things like this there.
