### ISSUE TITLE
No audio in Mupen64Plus on a non-Pi installation

### ISSUE THREAD

**Issue by siddhartha77** [RetroPie/RetroPie-Setup#2001]
PulseAudio is running while EmulationStation is open and it conflicts with the SDL audio in Mupen64Plus leading to no sound in N64 games. While I thought that pasuspender would solve the problem, it doesn't. Instead, you need to stop PulseAudio from running then start it up again once Mupen64Plus exists.

I have updated [the FAQ](https://github.com/RetroPie/RetroPie-Setup/wiki/RetroPie-on-Debian#no-audio-in-mupen64plus) with the solution.

It requires changes to `/opt/retropie/emulators/mupen64plus/bin/mupen64plus.sh`, which I believe may get written over with an update. Specifically, the following lines need to be changed at the end of the file:

    else
        mv $HOME/.config/pulse/client.conf $HOME/.config/pulse/client.conf.bak
        echo autospawn = no > $HOME/.config/pulse/client.conf
        /usr/bin/pulseaudio --kill
        "$rootdir/emulators/mupen64plus/bin/mupen64plus" --noosd --fullscreen --rsp ${RSP_PLUGIN}.so --gfx ${VIDEO_PLUGIN}.so --audio mupen64plus-audio-sdl.so --configdir "$configdir/n64" --datadir "$configdir/n64" "$ROM"
        mv $HOME/.config/pulse/client.conf.bak $HOME/.config/pulse/client.conf
        /usr/bin/pulseaudio --start
    fi

**Comment by gizmo98** [comment]
Which operating system/ubuntu version are you using? I had no audio problem with ubuntu 16.04.

**Comment by joolswills** [comment]
Closing due to no feedback from OP.
