### ISSUE TITLE
Punch Out Von Kaiser Distortion Raspberry Pi Zero

### ISSUE THREAD

**Issue by at2ecw** [RetroPie/RetroPie-Setup#2005]
I had tried Mike Tysons Punch-out and Punch-Out with Mr Dream, and they both have distorted faces on Von Kaiser at the intro screen before you hit start. I have a Raspberry Pi Zero. I haven't gotten to any of the other fighters to check for issues yet.

**Comment by joolswills** [comment]
Please use the forum as detailed when opening an issue.
