### ISSUE TITLE
Cannot get WiiU Pro controller to work after shutting off system

### ISSUE THREAD

**Issue by ForceFLEX16** [RetroPie/RetroPie-Setup#2018]
I followed the instructions found here: https://github.com/RetroPie/RetroPie-Setup/wiki/Wii-U-Pro-Controller

I can get the controller to work, and then can button map it in emulation station;
however, after shutting down the raspberry pi completely, the controller will not work without following all the setup steps again

any help would be greatly appreciated

**Comment by joolswills** [comment]
Please use the forum for support as detailed when opening an issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

>Please remove this text before posting.
