### ISSUE TITLE
Can not connect controller

### ISSUE THREAD

**Issue by g2bb** [RetroPie/RetroPie-Setup#2024]
I just recently received 2 off brand PS3 controllers. when I try to pair them to my pi it identifies them as keyboards and asks for a pin. obviously, it is not a keyboard so I can't put in a pin and the pairing ultimately fails. Is there any workaround or should I just return the controllers and buy some new ones?

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

https://retropie.org.uk/docs/PS3-Controller/
