### ISSUE TITLE
esthemes.sh remove an installed theme if I try to update it with no connection

### ISSUE THREAD

**Issue by meleu** [RetroPie/RetroPie-Setup#2026]
I think the title clearly explains the issue.

It's related with this piece of code:
https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/esthemes.sh#L35-L37

The esthemes removes the current theme before cloning the repo. Therefore, if the cloning procedure fails (e.g.: no connection), the theme was removed.

**Comment by joolswills** [comment]
It's not really a bug - but perhaps I can remove the rm workaround now anyway but I will need to test. If someone doesn't have an internet connection they should definitely not try to update anything though, and if it does fail they can retry,

**Comment by joolswills** [comment]
(If an internet connection fails, there are a lot of things in RetroPie that could go wrong - eg if some download is half finished etc).

**Comment by meleu** [comment]
I noticed ot when testing my PR for updating all ES themes in an offline system and it removed all the themes.

**Comment by joolswills** [comment]
The rm is removed now
