### ISSUE TITLE
I used NON-usb option(noobs) to install RetroPie. Can't get ROMS. 

### ISSUE THREAD

**Issue by mister-r4m1r3z** [RetroPie/RetroPie-Setup#2028]
I installed Retropie via 
git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git. 

I cannot get the emulationstation portion of things to run. I believe that all the raspi-config settings are correct, but I can't get the roms to load anything. The folders are empty. I did not use the USB install and I am not able to just 'copy over' the ROMS from there. 

Can I get some help on getting the correct ROMS dropped in or downloaded directly from the net. I do have wifi already setup. 

**I have already tried removing RetroPie and re-installing. Same issue.**

**Comment by joolswills** [comment]
Please use the forum as directed when opening an issue
