### ISSUE TITLE
Retropie will not boot to emulationstation 

### ISSUE THREAD

**Issue by phillthy** [RetroPie/RetroPie-Setup#2030]
when turning on my Pi instead of emulationstation booting up I am met with the words  illegal instruction what did I do wrong and how can I fix the problem someone PLEASE!!!!! Help me

**Comment by fnkngrv** [comment]
Fresh build, had you been using it, or is it some image you downloaded

**Comment by joolswills** [comment]
This need to go to the forum as directed when opening a ticket. Thanks.
