### ISSUE TITLE
glupen64 returned 128

### ISSUE THREAD

**Issue by KillDozerX2** [RetroPie/RetroPie-Setup#2036]
I keep getting this error

git clone --recursive --depth 1 https://github.com/loganmc10/GLupeN64.git /home/pi/Retropie-Setup/tmp/build/lr-glupen64' - returned 128

**Comment by joolswills** [comment]
You didn't read the text before posting - 

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

Sounds like your retropie-setup is out of date - please use the forum for further help.

**Comment by KillDozerX2** [comment]
I updated the setup right before install

**Comment by joolswills** [comment]
Please use the forum.
