### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by digitalnaiveDE** [RetroPie/RetroPie-Setup#2042]
/opt/retropie/supplementary/emulationstation/emulationstation: error while loading shared libraries: libboost_system.so.1.49.0: cannot open shared object file: no suche file or directory

I am not that familiar with all the information in here. So please spare with me.

I´ve tried to change my retropie from wheezy to jessie and afterwards i´ve tried to update inside the emulationstation to the newest version. I received several errors regarding sources and saw one hint that i should use apt-get autoremove.

After i did this command i have now the error i posted in line 1.

Can you please tell me how to move on from here?

Thanks

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
