### ISSUE TITLE
Manual installation fails due to wrong dependency version

### ISSUE THREAD

**Issue by davidt99** [RetroPie/RetroPie-Setup#2062]
I tried to install retro-pie manually according to the [manual](https://retropie.org.uk/docs/Manual-Installation/) and I had to manually install specific version of these packages, otherwise other packages wouldn't install:
* libasound2=1.0.28-1
* libdrm2=2.4.58-2

After I installed these packages, I was able to complete the installation.

**Comment by joolswills** [comment]
Please use the forum and include a log. Sounds like a dependency issue unrelated to RetroPie.
