### ISSUE TITLE
Playstation scraped metadata doesn't display on game directory

### ISSUE THREAD

**Issue by wolfgangrumpf** [RetroPie/RetroPie-Setup#2067]
Playstation games placed inside a folder to contain the cue and bin file(s) do not display the game metadata (e.g. image, description) when the folder is selected in emulation station.  The metadata MAY be displayed if the folder is navigated into but not always.

**Comment by joolswills** [comment]
https://github.com/RetroPie/EmulationStation is the Emulation Station bugtracker.

Note we prefer issues to be confirmed first on the forum as detailed when you opened this issue here

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
