### ISSUE TITLE
Update of setup script changes boot behavior

### ISSUE THREAD

**Issue by danielmehnert** [RetroPie/RetroPie-Setup#2069]
After updating the retropie setup script on Debian Jessie, my raspberry boots to console login, where it was going to lightdm before. Additionally, the splashscreen is enabled again as default. My proposal would be to make this behavior more transparent / optional or disable it completely.

**Comment by joolswills** [comment]
Please use the forum first as detailed when opening an issue.

I am not aware of any code that enables autoboot unless updating from an older version with autoboot enabled.

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
