### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by retro24** [RetroPie/RetroPie-Setup#2070]
Hi

In the latest retropie v4.2 sonic robo blast2 installation fails with a message about a file is not been found, and tyrquake does not work with quake and with the two mission packs and episode 5 also, it just returns to emulation station after running.

**Comment by joolswills** [comment]
Already fixed - you should update retropie-setup.

Please read the instructions on this issue tracker before posting

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
