### ISSUE TITLE
Include Extra Ports

### ISSUE THREAD

**Issue by retro24** [RetroPie/RetroPie-Setup#2072]
Hi

Is it possible to Add Opena-Arena game to the ports section ?

i also have tested and added more games that working great if you want i can give you the list.

openarena is working flawlessly

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.
