### ISSUE TITLE
Limelight script automated

### ISSUE THREAD

**Issue by lashower** [RetroPie/RetroPie-Setup#2076]
I am working on an automated install/setup of RetroPie and any selected packages on a Raspberry Pi (Raspbian Jessie) via Chef IO.

Currently, my code skims your shell scripts to see if these options are available:
install
install_bin (Or wget methods)
configure
sources
depends
build

When running this tool, I found that it is halting in both limelight.sh and mehstation.sh because it executes the limelight configure command. The problem with this is it runs "java -jar limelight.jar discover," which requires ctrl+c to exit out. Since I am taking an automated approach, ctrl+c is not an option.

It would be nice if you could pair the java call with timeout so that it doesn't hang. EX:
`timeout --preserve-status '5m' 'java -jar limelight.jar discover'`

That way if it doesn't discover the server in 5 minutes, it will gracefully exit out.

Another option is to create a configure_simple function that allows arg input for all of the read commands.

I am more than willing to help with this development if you want me to.

**Comment by joolswills** [comment]
the limelight script is old and needs replacing - but I don't have the time currently or the hardware to test. You could try piping something to it. This is not a bug though as the script is not designed to be automated as you are trying.

This should be posted on the forum as detailed when opening an issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.
