### ISSUE TITLE
System manager/+start reicast Issue on RPI 3b

### ISSUE THREAD

**Issue by markus666** [RetroPie/RetroPie-Setup#2077]
Hi there,

I bought, two month ago, a RPI 3b overclocked at 1.4 Ghz
This is a fantastic machine who allows almost full performances for the PSX, and a really acceptable/very good emulation for the N64 (42 games tested).

I'm actually trying to install reicast, I saw many videos and read many web pages.
I follow all the steps carrefully and it's a succes...some DC games runs really well, I'm very surprised.

Anyway, I have an issue and it's been 4 days, i'm surching for a fix on the web...but I can't find nothing about my problem.

Well, let me explain : Installation works well (from source), update works well to (from source)
I edit (via retropie setup) the ES_System.cfg to get the menu dreamcast pop up on emulation station.
I correctly map the controller, I put my bios on the right folder and the CDi/GDi files in the dreamcast folder create by the instalation.
I can see the games, I can play the games and like I say, some of them run very well.

The problem is that I don't see the +Start reicast.sh entry, so I cannot open the system manager to formate the VMU and so I cannot save the games.
The installation create the file, I can see it on the dreamcast folder (on my PC) but the +Start Reicast option does not pop up on the DC menu.

I allready try (several times) to uninstall/install reicast but nothing to do...no possibility to enter the system manager...
I read some topics where people can run the sh file but it goes to a black screen, I don't even have this chance because the +Start reicast.sh file does not appear for me ;-((
I 'm on retropie 4.2.15 (script update yesterday)

Can anybody help me please.
PS: Sorry for my poor english.

**Comment by joolswills** [comment]
Please use the forum for help.
