### ISSUE TITLE
Retropie ... configuration instead of 13 games.

### ISSUE THREAD

**Issue by erisosa81** [RetroPie/RetroPie-Setup#2087]
I just downloaded retropie using my MAC and Raspberry Pi 3 wireless, but for some reason it does not say 13 games like everyone else it just says configuration, I tried to connect to my wireless home network using the credential transfer and it has been unsuccessful can anyone help me?

**Comment by dankcushions** [comment]
> I just downloaded retropie using my MAC and Raspberry Pi 3 wireless, but for some reason it does not say 13 games like everyone else it just says configuration

this is normal. perhaps you're looking at screenshots from older versions?

> I tried to connect to my wireless home network using the credential transfer and it has been unsuccessful can anyone help me?

please use the forum for support: retropie.org.uk/forum

**Comment by robertybob** [comment]
@erisosa81 This confused me too. I hadn't started from scratch since RP 3.8 so I wondered why the Ports, Dreamcast etc. menus were missing!
