### ISSUE TITLE
Battery Files are not shared

### ISSUE THREAD

**Issue by inukaze** [RetroPie/RetroPie-Setup#2088]
Hi there, someone knows why if i want to play with a Battery file for example of VBA-M, and i after start mGBA, instead of use the same "Battery File" the battery file is replaced instead of use it ?

i lost a gameplay just for start with another core. 

When i do something similar between different emulators, just works fine for example Mednafen W.I.P and VBA-M

i understand this is very possible, because before i use retroarch, for me is a common practice with Battery Files.

This is under RetroArch 1.6.1. i remember under RetroArch 1.3.6 every core created a sub-folder for make their own battery file follow the core.

**Comment by joolswills** [comment]
Please use the forum as detailed when opening an issue
