### ISSUE TITLE
Add AdvanceMESS

### ISSUE THREAD

**Issue by petrockblog** [RetroPie/RetroPie-Setup#210]
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=78&t=23113

**Comment by HerbFargus** [comment]
alright so I currently have AdvMESS working and its actually not as terrible to configure as I had anticipated. This opens up the option for many more systems (in varying degrees of functionality)

see [**HERE**](http://www.progettoemma.net/mess/sysset.php) for a list of MESS supported systems

 but the two systems in particular that I have my eye on are Colecovision and BBC Micro. Unfortunately It doesn't have integrated controller configurations like RetroArch but all controls can be configured from the tab menu (exactly like AdvMAME as they are essentially the same in many ways) AdvMESS likely can be added to the AdvMAME module to avoid code duplication.

## Configurations


#### advmess.rc

A few notes for initial settings for the `advmess.rc` file (These are the important files to keep and preconfigure):

dir_artwork /home/pi/.advance/artwork:/opt/retropie/emulators/advmess/1.4/share/advance/artwork
dir_crc /home/pi/.advance/crc
dir_diff /home/pi/.advance/diff
dir_hi /home/pi/.advance/hi
dir_image /home/pi/.advance/image:/opt/retropie/emulators/advmess/1.4/share/advance/image
dir_inp /home/pi/.advance/inp
dir_memcard /home/pi/.advance/memcard
dir_nvram /home/pi/.advance/nvram
dir_rom /home/pi/.advance/rom:/opt/retropie/emulators/advmess/1.4/share/advance/rom
dir_sample /home/pi/.advance/sample:/opt/retropie/emulators/advmess/1.4/share/advance/sample
dir_snap /home/pi/.advance/snap
dir_sta /home/pi/.advance/sta
device_video_clock 5 - 50 / 15.62 / 50 ; 5 - 50 / 15.73 / 60  # HDMI SETTING
device_video_clock 5 – 50 / 15.73 / 60 # NTSC TV

Lets say I have this compiled properly and I want to just run the colecovision:

#### Rom Folder:

in `/opt/retropie/configs/mame-advmess/image/` I create a folder called `coleco` (its very picky about what it is named)

and then I place my game in `/opt/retropie/configs/mame-advmess/image/coleco` and it does not like spaces, I had to rename them to not have spaces. .zip and .bin worked. likely .col would work too.

#### BIOS Folder

Of course it also needs a BIOS file which was placed in `/opt/retropie/configs/mame-advmess/rom` which HAD to be zipped called coleco.zip and the bios inside was called coleco.rom

#### Launch Perametres

then I ran the game from the terminal (as we'll have to build different launching options for each system we set up: for the coleco it was `./advmess coleco -cart 2010.bin`


#### Module

Just for reference this is my hack of a module I used to compile. It's definitely not ideal and was just done quickly to get it working- ideally it should just be appended into the advmame module (in theory)

```
#!/usr/bin/env bash

# This file is part of The RetroPie Project
# 
# The RetroPie Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="advmess"
rp_module_desc="AdvanceMESS"
rp_module_menus="4+"
rp_module_flags="!x86 !mali"

function depends_advmess() {
    getDepends libsdl1.2-dev
}

function sources_advmess() {
        wget -O- -q "https://github.com/amadvance/advancemame/releases/download/advancemess-1.4/advancemess-1.4.tar.gz" | tar -xvz --strip-components=1
}

function build_advmess() {
        ./configure CFLAGS="$CFLAGS -fsigned-char" LDFLAGS="-s -lm -Wl,--no-as-needed" --prefix="$md_inst/1.4"
        make clean
        make
}

function install_advmess() {
        make install
}

function configure_advmess() {
    mkRomDir "mame-advmess"

    moveConfigDir "$home/.advance" "$configdir/mame-advmess"

        su "$user" -c "$md_inst/1.4/bin/advmess --default"

        iniConfig " " "" "$configdir/mame-advmess/advmess-1.4.rc"
        iniSet "misc_quiet" "yes"
        iniSet "device_video" "fb"
        iniSet "device_video_cursor" "off"
        iniSet "device_keyboard" "raw"
        iniSet "device_sound" "alsa"
        iniSet "display_vsync" "no"
        iniSet "sound_samplerate" "44100"
        iniSet "sound_latency" "0.2"
        iniSet "sound_normalize" "no"
        iniSet "dir_rom" "$romdir/mame-advmess"
        iniSet "dir_artwork" "$romdir/mame-advmess/artwork"
        iniSet "dir_sample" "$romdir/mame-advmess/samples"

        addSystem 0 "$md_id-1.4" "mame-advmess arcade mame" "$md_inst/1.4/bin/advmess %BASENAME%"
}
```

**Comment by HerbFargus** [comment]
Latest script (still has configurations that need to be sorted out)

```
#!/usr/bin/env bash

# This file is part of The RetroPie Project
# 
# The RetroPie Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
# 
# See the LICENSE.md file at the top-level directory of this distribution and 
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="advmess"
rp_module_desc="AdvanceMESS"
rp_module_menus="4+"
rp_module_flags="!x86 !mali"

function depends_advmess() {
    getDepends libsdl1.2-dev
}

function sources_advmess() {
        wget -O- -q "https://github.com/amadvance/advancemame/releases/download/advancemess-1.4/advancemess-1.4.tar.gz" | tar -xvz --strip-components=1
}

function build_advmess() {
        ./configure CFLAGS="$CFLAGS -fsigned-char" LDFLAGS="-s -lm -Wl,--no-as-needed" --prefix="$md_inst"
        make clean
        make
}

function install_advmess() {
        make install
}

function configure_advmess() {
    mkRomDir "mame-advmess"
    mkRomDir "bbcb"

    moveConfigDir "$home/.advance" "$configdir/mame-advmess"

        su "$user" -c "$md_inst/bin/advmess --default"

        iniConfig " " "" "$configdir/mame-advmess/advmess.rc"
        iniSet "misc_quiet" "yes"
        iniSet "device_video" "fb"
        iniSet "device_video_cursor" "off"
        iniSet "device_keyboard" "raw"
        iniSet "device_sound" "alsa"
        iniSet "display_vsync" "no"
        iniSet "sound_samplerate" "44100"
        iniSet "sound_latency" "0.2"
        iniSet "sound_normalize" "no"
        iniSet "dir_rom" "$biosdir"
        iniSet "dir_artwork" "$romdir/mame-advmess/artwork"
        iniSet "dir_sample" "$romdir/mame-advmess/samples"
        iniSet "dir_image" "$romdir"
        iniSet "device_video_clock" "5 - 50 / 15.62 / 50 ; 5 - 50 / 15.73 / 60"

        addSystem 0 "$md_id" "mame-advmess arcade mame" "$md_inst/bin/advmess %BASENAME%"
        setESSystem 'BBC Micro Model B' 'bbcb' '~/RetroPie/roms/bbcb' '.bbc .BBC .img .IMG .ssd .SSD' '/opt/retropie/emulators/advmess/bin/advmess bbcb -floppy %BASENAME%' 'bbcb' 'bbc'
}
```

**Comment by HerbFargus** [comment]
Libretro core has been added as of https://github.com/RetroPie/RetroPie-Setup/pull/1298

**Comment by zerojay** [comment]
The libretro core referred to in #1298 is MAME HEAD.

**Comment by Darknior** [comment]
Really an excellent news 😃 
@HerbFargus i have post a cool TRIC for you on this thread :

https://github.com/RetroPie/RetroPie-Setup/pull/1298

The problem was MESS is not a fast emulator ?
Not a problem @HCF found a solution to really speed up this emulator on xBox 1 with a little trick and make CDI working at full speed !!! 😆 

http://www.emuxtras.net/forum/viewtopic.php?f=189&t=5730&p=73415&sid=a0feb61fc00ba8fb8e1701d97be4a47b#p73415

Go and read it, we can have a full speed MESS on Pie for sure ...
I wish i have help 👍

**Comment by joolswills** [comment]
I'm going to close this as technically we do include advmess (with advancemame). Configuration is down to the user though.
