### ISSUE TITLE
Residualvm not working on fresh installation

### ISSUE THREAD

**Issue by suzsuzuki** [RetroPie/RetroPie-Setup#2123]
I have a rpi3 and using a clean 4.2 Image from retropie website (fresh image - jessie).

After install residualvm from experimental packages I tried to start the emulator but no luck, it just back to ES.

After look at runcommand.log log it says:

Framebuffer is not complete! status: 36061!

I tried also to update scripts and upgrade packages, but I have the same error. In the past I was able to run it. It's broken somewhere now...

**Comment by joolswills** [comment]
GLES seems to be broken on the RPI - an upstream problem.

In the meantime I will make the GUI load with software rendering.
