### ISSUE TITLE
Add lr-atari800 core

### ISSUE THREAD

**Issue by bigboo3000** [RetroPie/RetroPie-Setup#2128]
Hi
The atari800 libretro core is now more complete and can run games for both a5200 and a800.
Could you please add it to Retropie?

**Comment by Darknior** [comment]
WOAW so excellent <3

**Comment by cpoliticas** [comment]
The emulator is in the experimental packages, but for some reason the installation is broken

**Comment by joolswills** [comment]
It's not in experimental yet. I have an unfinished module and have written on the forum that I would complete/test it after the 4.3 release.

Please follow the guidelines of the issue tracker when opening a ticket

>For ideas and enhancements, please also post to the forum first, to see if it is something we would consider and to see if other users would find it useful.

**Comment by psyke83** [comment]
Resolved via commit cd3869ae98b7664ca9f1a28190b6f75376c64665.
