### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by kykkus** [RetroPie/RetroPie-Setup#213]
Hi, i have this problem:
when i try to star emulationstation it tells me that i haven't games, but I copy roms in /home/pi/RetroPie/roms/_/_.*

what's wrong?

Error:

sudo emulationstation
lvl0:   No systems found! Does at least one system have a game present? (check that extensions match!)

**Comment by vulpineblaze** [comment]
I can start emulationstation over SSH, but the window appears on the raspberry pi's screen. 

I'm having trouble getting started. I have the path to some SNES roms correct, but I get the "No systems found!" error..  I have no clue what i'm doing wrong :(
