### ISSUE TITLE
error libsfml-graphics

### ISSUE THREAD

**Issue by gpr17** [RetroPie/RetroPie-Setup#2144]
Error message on running attract from CLI: error while loading shared libraries: libsfml-graphics.s.o.2.4 cannot open shared object file: No such file or directory
Is there anything wrong? Do I need to update anything?
Raspberry pi3, osmc updated

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
