### ISSUE TITLE
".bs" and ".BS" Entries Missing for SNES Entry in RetroPie's Auto-Generated "es_systems.cfg"

### ISSUE THREAD

**Issue by Eckaji** [RetroPie/RetroPie-Setup#2157]
I'm not sure what else to add beyond the title, other than that I tested Satellaview emulation with the ".bs" extension and it does work, though Satellaview ROMs have to be in an uncompressed state with the ".bs" extension to be playable. It is also true that changing the extension to ".sfc" seems to work as well and allows for compression, at least for the one game I tried, but ".bs" is the widely used No-Intro extension so its inclusion makes sense.

**Comment by Pundan** [comment]
You need to add the .BS file extension to your SNES-config in your es_systems.cfg in order for the ROMs to show up. [https://github.com/RetroPie/RetroPie-Setup/wiki/Add-a-New-System-in-EmulationStation](url)

**Comment by Eckaji** [comment]
Yes, I know. 

My issue is that this isn't the default, as most Satellaview ROMs distributed nowadays have the ".bs" extension, and this would save the end-user from having to do so.

Still, I believe the added support of compression by just changing the ".bs" every ROMs extension to ".sfc" is the best route for most users... and I should go add a small section on Satellaview in the SNES part of the wiki advising to do so.

**Comment by joolswills** [comment]
Note you don't need to edit `es_systems.cfg` to add additional extensions (and they will get ovewritten).

Just create a `platforms.cfg` file in `/opt/retropie/configs/all` with 

```
snes_exts=".7z .bin .bs .smc .sfc .fig .swc .mgd .zip"
snes_fullname="Super Nintendo"
```

and then update any snes emulator. you can override any extensions like this (and system names / themes)

**Comment by joolswills** [comment]
I will add this to the system platform.cfg anyway, but if you want to ever adjust other systems extensions use the method above.
