### ISSUE TITLE
After update RetroPie-Setup Joypad dosen't work

### ISSUE THREAD

**Issue by nintendontit** [RetroPie/RetroPie-Setup#2159]
After update RetroPie-Setup there's a splash screen with NOTICE:... and confirmation, on this I can't use JoyPad for confirmation. I use keyboard for click OK button, after that return to RetroPie-Setup and JoyPad works as usual.

Sorry for bad English

**Comment by joolswills** [comment]
It is. I have a fix in mind.

**Comment by nintendontit** [comment]
I just remove joy2keyStop from line 555 of scriptmodules/admin/setup.sh
But I can think that this work around ca create issue with disable it from ssh
