### ISSUE TITLE
Sound comes on randomly bug

### ISSUE THREAD

**Issue by theofficialgman** [RetroPie/RetroPie-Setup#2167]
When sound is disabled for video snapshots, randomly the sound will turn on for a couple of seconds and then off again (when using video screensavers). Was not present in 4.2.10 but is as off 4.3.3. Also, sliding has been made extremely quick for transitions.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
