### ISSUE TITLE
Retropie update causing error

### ISSUE THREAD

**Issue by kbanger1** [RetroPie/RetroPie-Setup#2168]
I'm trying to update my old 4.2.20 version if Retropie to the latest version. It keeps coming up with an error about my local changes to my platforms.cfg file would be overwritten and that I'd have to either commit my changes or stash them before the merge. I just want to go ahead and commit those changes so how do go about that?

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
