### ISSUE TITLE
Change the default terminal text editor to something other than Vim.

### ISSUE THREAD

**Issue by Valkryst** [RetroPie/RetroPie-Setup#2176]
It's too easy to lock yourself into the Vim editor without being able to exit, even when looking up how to exit Vim, and having to pull the Pi's plug to restart the machine rather than doing a reboot or shutdown/restart. 

An alternative, such as Nano, would be more user friendly and prevent this issue.

**Comment by joolswills** [comment]
This is not a RetroPie issue. You can set default editor in Debian - it is nano by default afaik. But it's an OS issue.
