### ISSUE TITLE
Incorrect wiki + perhaps a way to get rid of ps4 latency and dropped input

### ISSUE THREAD

**Issue by JAnken123** [RetroPie/RetroPie-Setup#2177]
Wiki says that you should try pairing and if that doesnt work in emulationstation you should unpair and do the ds4drv method. I did this and couldn't use the --hidraw method. I had tons of issues with dropped input and generally high latency when connecting without the --hidraw. After trying a lot of stuff in order to resolve my issue what finally did work was to
1. Pair ps4 controller
2. run ds4drv WITH hidraw option

which eliminated all lag. When ran without hidraw i got 2x input for every move though, which was weird. Can someone who also had this issue confirm that this is a solution?

You need to enable bluetooth mode to background to survive reboots and such.

**Comment by joolswills** [comment]
Please use the forum first as detailed when opening an issue - you are far more likely to find someone else with the same controller there too.
