### ISSUE TITLE
Additional line for sound issues wiki page

### ISSUE THREAD

**Issue by peteristhegreat** [RetroPie/RetroPie-Setup#2187]
alsactl restore -P

This fixed the sound issues I was having and it wasn't listed in the RPi wiki or RetroPie wikis.

**Comment by joolswills** [comment]
It's an open wiki so if you think it should be added, please do.

**Comment by joolswills** [comment]
Please use forum for discussion of wiki changes and not this bugtracker as detailed when opening a ticket. Thanks.
