### ISSUE TITLE
4.3.4 issue - cannot use any joypad while in emulator (all Retroarch cores)

### ISSUE THREAD

**Issue by drwhoelse** [RetroPie/RetroPie-Setup#2191]
4.3.3 and earlier, I was able to use joypad (Xbox 360, 8Bitdo FS30 Pro or GameSir G3s) in any emulator.  I could use keyboard at same time.

After updating to 4.3.4, I cannot use any joypad while in emulator (all Retroarch cores).  Keyboard works.  I do see yellow message saying "name of joypad... not configured" at startup of any emulator.  I removed config lines for keyboard and joypad from CFG files.  I used ES for first-time setup with joypad, and then played fine with any emulator.  When I add keyboard, then joypad stopped working.  It's like Retroarch only accepts keyboard, and ignores joypad.  Joypad will work again in ES after quitting emulator via keyboard commands.

(My system is Xubuntu 17.10 64-bit)

**Comment by joolswills** [comment]
Nothing has changed regarding retroarch, but please use the forum and wait for help there, as detailed when opening an issue.
