### ISSUE TITLE
fix attract mode build on rpi

### ISSUE THREAD

**Issue by tednilsen** [RetroPie/RetroPie-Setup#2193]
binaries fails when executing attract mode, check attractmode.sh, line 150

replace the line:
`    isPlatform "rpi" && params+=(EXTRA_CFLAGS="$CFLAGS -I$md_build/sfml-pi/include -L$md_build/sfml-pi/lib")`

with this one:
`    isPlatform "rpi" && params+=(USE_GLES=1 EXTRA_CFLAGS="$CFLAGS -I$md_build/sfml-pi/include -L$md_build/sfml-pi/lib")`

...all good, check out https://github.com/mickelson/attract/blob/master/Compile.md

**Comment by psyke83** [comment]
Some more changes were necessary in coordination with upstream. This should be now be fixed - make sure to update your RetroPie-Setup script and clean any existing source folder (if necessary) before trying a rebuild. Thanks.
