### ISSUE TITLE
sudo tee not working

### ISSUE THREAD

**Issue by Dopest-Pleb** [RetroPie/RetroPie-Setup#2194]
When using sudo tee for creating files, it just returns a blank command line.  Did this work and I need to find it to write to it, or did I do something wrong?  (Wiimote tutorial)

**Comment by joolswills** [comment]
Use the forum for help as detailed when opening an issue.

**Comment by Dopest-Pleb** [comment]
Which forum?  Also, is there a way to copy and paste whole files when you are in the file manager?

**Comment by joolswills** [comment]
The one linked in the text you removed when opening the issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
