### ISSUE TITLE
lr-mame2000 binary should be rebuilt for nvram fix

### ISSUE THREAD

**Issue by zerojay** [RetroPie/RetroPie-Setup#2195]
The currently available binary version of lr-mame2000 is unable to write out its nvram to disk (see issue 13: https://github.com/libretro/mame2000-libretro/issues/13). A fix for this was made around the end of September and appears to work just fine in my testing, allowing the lr-mame2000 core to properly write nvram to disk: https://github.com/libretro/mame2000-libretro/commit/943cde7bc9c5254f40b6a0edde321714c8beac5f

It would be awesome to have the default binary version of lr-mame2000 updated for this fix.

**Comment by joolswills** [comment]
Please use the forum first - I don't really want to have a ticket every time someone wants a binary updated. The forum is the best place. I already monitor and update libretro cores when I think it's required.
