### ISSUE TITLE
Found bug and how to solve it

### ISSUE THREAD

**Issue by abrmx** [RetroPie/RetroPie-Setup#2196]
Hello

I installed retropie on a fresh installation of debian without X. So the emulationstation didnt work, so I install X and Emulationstation got stucked on the welcome screen. Neither the keyboard or the gamepads worked. So we install LXDE and then Emulationstation worked.

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
