### ISSUE TITLE
PS3 controller recognised but not fully

### ISSUE THREAD

**Issue by beyondserious** [RetroPie/RetroPie-Setup#2199]
Lenovo Thinkpad E525 w/ Mint 18.2 

Running latest version of Retropie and all dependencies fully updated as of 10.11.17.

Issue is when I plug in my PS3 controller (wired) it recognises it as a PS3 controller but when I get to the config screen it only allows for D-Pad up, down left right, A, B, Start, Select, Page up, Page down.

It does not even show the analog sticks or x,y,L1,L2,R1,R2 buttons at all. 

Updated and installed PS3 driver via Retropie setup and tried the sld2 fix and nothing. Also tried to manual edit the Controller.cfg but it didn't register either.

**Comment by joolswills** [comment]
Please post for help on the RetroPie forum.
