### ISSUE TITLE
Run mame roms (mame4all) from my NAS drive (win7 pc). How to edit mame.cfg?

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#2204]
I ve already followed [this](https://github.com/RetroPie/RetroPie-Setup/wiki/Running-ROMs-from-a-Network-Share) with no problems. Everything seems ok except for the fact that i cant run any of my mame (mame-mame4all) roms. 

My files are correct as i can run them through my sd card, but not from nas. I get a missing roms error. Surprisingly those missing roms are indeed inside of my zipped roms. As if the command is trying to unzip the rom but without success.

So i want to edit my mame.cfg (nano /opt/retropie/configs/mame-mame4all/mame.cfg) in order to load mame roms from my NAS drive (win pc). Is this the right syntax? (I ve already created my shared folder in my nas of course) 

[directory]
inp=inp
nvram=nvram
hi=hi
cfg=cfg
snap=snap
memcard=memcard
sta=sta
artwork=artwork
cheat=.
rompath=**/192.168.1.110/Share/RetroPie/roms/mame-mame4all**
samplepath=samples

Rasp Pi 1 Model B, Retropie 4.3, NOOBS image

**Comment by HerbFargus** [comment]
You have a post on the forum. This tracker is not for support.

**Comment by Haris1977** [comment]
Well i did but it says " my post was flagged as spam by Akismet.com". Dont know why..:(
