### ISSUE TITLE
GlideN64 broken

### ISSUE THREAD

**Issue by cptbananas** [RetroPie/RetroPie-Setup#2207]
EDIT: I think this is a an issue introduced by Gliden64, not retropie. Dankcushions has already opened an issue on their tracker https://github.com/gonetz/GLideN64/issues/1665

A recent change to the GlideN64 plugin for Mupen64plus (NOT lr version) resulted in all games becoming unplayable for this plugin. The change is presumed to have entered the repository between 11/1 and 11/17/2017.

thread:
https://retropie.org.uk/forum/topic/14448/n64-emulators-not-loading-textures/1

To replicate:
-Update mupen64plus, either from binary or from source
-Load a rom in mupen64plus with GlideN64 plugin (gles2rice is not affected)

You will encounter the message "init noise textures," then this (screenshots of "Super Mario 64" and "Mario Kart 64")

![20171120_210345](https://user-images.githubusercontent.com/33859073/33061325-556bfd00-ce61-11e7-9674-1e1506e8bdb2.jpg)
![20171120_210451](https://user-images.githubusercontent.com/33859073/33061326-557b5d4a-ce61-11e7-811f-074f5ddb844e.jpg)

**Comment by joolswills** [comment]
If upstream come up with the fix shortly, I will rebuild binaries on the latest code. if not, I will consider bisecting to see when the problem started and roll back the code for the RPI until it's fixed.

**Comment by johnmanko** [comment]
@cptbananas / @joolswills GLideN64 is deferring to RetroPie as a Pi GPU driver issue.

**Comment by dankcushions** [comment]
@johnmanko not deferring, as such. plenty of GPU drivers have issues. it’s just an observation. it will still be fixable within GLideN64.

**Comment by psyke83** [comment]
This is already resolved despite upstream's bug not yet being closed, so I'll close ours. When we move to stretch, there's a segmentation fault related to the shader cache that will need to be fixed, but it's not related to the missing textures anyway.

**Comment by johnmanko** [comment]
when can we see this available to RetroPie installations?

**Comment by joolswills** [comment]
It already is. Please use the forum for help.
