### ISSUE TITLE
Can't choose default emulator

### ISSUE THREAD

**Issue by kamen345** [RetroPie/RetroPie-Setup#2218]
Hi, I a using RetroPie on Emulationstation on regular PC. I have trouble choosing a default emulator for any system. It always runs in a loop and repeats this (example of NES emulator):
`/opt/retropie/supplementary/runcommand/runcommand.sh: line 259: iniConfig: command not found
/opt/retropie/supplementary/runcommand/runcommand.sh: line 266: iniSet: command not found
/opt/retropie/supplementary/runcommand/runcommand.sh: line 259: iniConfig: command not found
/opt/retropie/supplementary/runcommand/runcommand.sh: line 262: iniGet: command not found
No default emulator found for system nes`

**Comment by joolswills** [comment]
Please use the forum as directed when opening a ticket
