### ISSUE TITLE
Doesn't work with latest Raspbian (Check my Terminal output))

### ISSUE THREAD

**Issue by thericeking** [RetroPie/RetroPie-Setup#2224]
I followed the instructions provided here word by word . I was unsuccessful. Please check the terminal output below. Thank you for your time.

pi@raspberrypi:~ $ git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
Cloning into 'RetroPie-Setup'...
remote: Counting objects: 302, done.
remote: Compressing objects: 100% (272/272), done.
remote: Total 302 (delta 58), reused 74 (delta 16), pack-reused 0
Receiving objects: 100% (302/302), 1.60 MiB | 0 bytes/s, done.
Resolving deltas: 100% (58/58), done.
pi@raspberrypi:~ $ cd RetroPie-Setup
pi@raspberrypi:~/RetroPie-Setup $ sudo ./retropie_setup.sh
Sorry - Raspbian/Debian Stretch (and newer) is not yet supported on the RPI

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch
pi@raspberrypi:~/RetroPie-Setup $

**Comment by joolswills** [comment]
Stretch is not yet supported on the rpi as it says. Please use the forum for further help. You can install over Raspbian Jessie or use our premade image.
