### ISSUE TITLE
Configuration messed up after saving settings

### ISSUE THREAD

**Issue by Schneemann2** [RetroPie/RetroPie-Setup#2225]
If i do my joystick settings and save them in the 'save settings' dialog, sound is not working anymore after a reboot. A new installation of vice solves the problem

**Comment by psyke83** [comment]
Please don't use the issue tracker for support issues without first requesting help on the forum and following the guidelines in the pinned topic: https://retropie.org.uk/forum/topic/3/read-this-first

Thanks.
