### ISSUE TITLE
Odyssey 2

### ISSUE THREAD

**Issue by ConradBunton** [RetroPie/RetroPie-Setup#2228]
Odyssey doesn't work on Retropie. When I launch a ROM, the screen become dark and after a few seconds, it come back to the menu.

**Comment by psyke83** [comment]
Please use the forums for assistance & follow the guidelines in the pinned topic: https://retropie.org.uk/forum/topic/3/read-this-first

**Comment by estefan3112** [comment]
You very likely forgot to install the BIOS or you use wrong roms. The forum should tell you.
