### ISSUE TITLE
Add Support for Unattended Updates

### ISSUE THREAD

**Issue by franklesniak** [RetroPie/RetroPie-Setup#2230]
I have a use case where I need RetroPie updates to be fully unattended. I have picked apart some of the bash scripts used in this process, and have come up with the following:

```
cd
cd RetroPie-Setup/
git pull
chmod +x retropie_setup.sh
chmod +x retropie_packages.sh
sudo apt-get update
sudo apt-get -y dist-upgrade
printf 'o\ny\no\n' | sudo ./retropie_packages.sh setup post_update update_packages_gui_setup update
sudo shutdown -r -t 0
```

However, the retropie_packages.sh script still prompts for various things in this process. It would be nice if there was a function for update_packages_unattended_setup or something similar that does not give any prompts.

Let me know if a donation would help push this through. Happy to give this project a Christmas present :)

**Comment by joolswills** [comment]
You have a post on the forum already - Please follow the instructions when opening a ticket - there are more people on the forum and it is a better place for questions like this.

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.

In regards to your script above - no need for the chmods.

you can do something like this

please do not run this too often as it will put strain on our servers! weekly should be enough (at least for the update_packages call

```bash
cd ~/RetroPie-Setup/
git pull
sudo __nodialog=1 ./retropie_packages.sh setup post_update
sudo __nodialog=1 ./retropie_packages.sh setup update_packages 
sudo __nodialog=1 ./retropie_packages.sh raspbiantools apt_upgrade
```
