### ISSUE TITLE
Retropie.cfg question: "false" (With Quotations) vs false (Without Quotations)

### ISSUE THREAD

**Issue by SuperNewb2** [RetroPie/RetroPie-Setup#2237]
When Enableing different features in the retropie.cfg file is there a difference between "true" or "false" with quotations and true or false without quotations. 

here is an example: 
video_vsync = true
video_threaded = "true"

Thanks for the help.

**Comment by joolswills** [comment]
Both should work

This is the wrong place for support as detailed when you opened the issue

>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/
