### ISSUE TITLE
Press 4 ntsc pinn boot rca not working! black screen no matter what do

### ISSUE THREAD

**Issue by edneyhelene** [RetroPie/RetroPie-Setup#2243]
This is an bug that noobs does also haves! the only bootloader that works without issue here is berryboot.

Would like to see the problem fixed on pinn!

Raspberry pi3 model b hardware working ok! 

Pressing 4 while it loads makes no difference. still black screen on rca output! as far as pinn is my favorite OS installer i do want to see it working as fast as possible to be able to use it again =( i do really miss it!

Thanks

**Comment by joolswills** [comment]
Please use the RetroPie forum as requested.
