### ISSUE TITLE
Nintendo DS DraStic emu cant install needs a fix!

### ISSUE THREAD

**Issue by edneyhelene** [RetroPie/RetroPie-Setup#2244]
I see lots of people with the same problem! actually we are not able to install drastic nintendo DS emu and the LR-desmume is almost useless since it's kinda abandonware...

Can you guys please include Drastic on the next release? and please fix the install process, we need it working for today, its an must,..we love it!

There is no nintendo DS emulation without Drastic emu =X i think they updated something and something broke up on the install process, i dont know...please take a look into it and fix..
Love retropi, my favorite !

**Comment by joolswills** [comment]
>This issue tracker is NOT for Help / Support - Please use the RetroPie forum - https://retropie.org.uk/forum/

>Even if you think you have a bug please post to the forum first, as many "issues" can be solved with configuration changes.
