### ISSUE TITLE
Drastic failed package ‘patchelf’

### ISSUE THREAD

**Issue by moscovium115** [RetroPie/RetroPie-Setup#2245]
I don’t know if this is the right place to post this.

At this moment Drastic, the Nintendo DS emulator, cannot be downloaded due to RetroPie not finding  the needed package ‘patchelf’. I asked around on the Subreddit of RetroPie, and I’m not the only one experiencing this. I hope this can be looked into.

Happy holidays.

**Comment by joolswills** [comment]
It's already fixed. Please update RetroPie-Setup. Please use the forum for further support.
