### ISSUE TITLE
Permission Denied when updating on chown command

### ISSUE THREAD

**Issue by Viper911** [RetroPie/RetroPie-Setup#2257]
I am running RetroPie folder from a NAS (Roms, BIOS, etc).  When updating or trying the reset permissions command it shows permission denied when running chown.  I am mounting the nas withe the forced guid, etc as pi, but still seeing these errors.

How do I properly use a NAS to host the roms, etc and have the updates work, etc.

**Comment by joolswills** [comment]
Please use the retropie forum for support.
