### ISSUE TITLE
Please do add redream to opt packages on retropie, WE NEED IT

### ISSUE THREAD

**Issue by edneyhelene** [RetroPie/RetroPie-Setup#2259]
Redream is wonderful!  its the best dreamcast emu ive ever tried, i used it on lakka and loved it ! 
Works much better than reicast!

We need it on retropie! can you guys please include it?

https://github.com/inolen/redream/blob/master/deps/sdl2/docs/README-raspberrypi.md

Also i would like to ask you guys to insert those xbr filters into the default retropie installation, i do really like using them, specially the hibrid one and the xbr 1p...can you guys please do it? love ya!

**Comment by bleonard252** [comment]
They specifically said not to use the issue tracker for feature suggestions. Please put this in the forums.
