### ISSUE TITLE
SSH not found

### ISSUE THREAD

**Issue by Dominique1997** [RetroPie/RetroPie-Setup#2261]
Hi

I installed today the retropie for berryboot.

But now i want to install the ssh, but i can't find the folder of boot.

I updated it already to the latest new version.

**Comment by fredcobain** [comment]
Go to command line (F4)
Type "sudo raspi-config" and press enter
Select "Interfacing Options"
Navigate to and select "SSH"
Choose Yes
Select Ok
Choose Finish

Done

**Comment by joolswills** [comment]
Please use the forum for support as detailed when opening an issue.
