### ISSUE TITLE
Adding the FreeIntv Intellivision emulator

### ISSUE THREAD

**Issue by markwkidd** [RetroPie/RetroPie-Setup#2267]
I've been helping recompile from the forums to setup a github repository and Makefile for their new Intellivision emulator. It may still have some rough edges, but as of today it's been on the libretro buildbot for about a week, and it's been published as part of at least one SNES Classic builds.

Here's the repo: https://github.com/markwkidd/FreeIntv

Do you all think it's far enough along to include in RetroPie setup?

**Comment by markwkidd** [comment]
FreeIntv is now part of the libretro github organization, meaning a new URL: http://github.com/libretro/FreeIntv

**Comment by joolswills** [comment]
thanks.

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/2293
