### ISSUE TITLE
[Enhancement] Add Beetle hardware support to build script for lr-beetle-psx

### ISSUE THREAD

**Issue by movisman** [RetroPie/RetroPie-Setup#2275]
Hi,

As per my last post here:
https://retropie.org.uk/forum/topic/15914/x86-vulkan-driver-option-for-various-emulators-not-showing-up-but-dolphin-works/15

Do you think it would be possible to change the build script so it installs HW support for Beetle, as this enables OpenGL, Vulkan etc which is quite nice for x86 users? Software rendering option is still maintained.

Thanks!

**Comment by psyke83** [comment]
Closed via #2279.
