### ISSUE TITLE
Slow games list loading after a full update

### ISSUE THREAD

**Issue by Melusham** [RetroPie/RetroPie-Setup#2287]
I use retropie-4.3-rpi2_rpi3 on a Pi3B
A couple of days ago i launched the update (all packages and RP kernel.)
Since then the loading time of the game lists (4000 roms in the arcade folder) is a lot longer (not a big issue, around 10-15 seconds instead of 1 or 2, but a very noticeable one) after each game exit.
I've tried with other folders with much less roms, the loading time is not that long so i think this is really about the  number of roms.
Sometimes I've also seen weird listing (only a few dozen of roms instead of 4000), **without filter**.

**Comment by joolswills** [comment]
You already have a thread open on the forum.
