### ISSUE TITLE
Battle Mania Daiginjou entry makes EmulationStation crash

### ISSUE THREAD

**Issue by cosmo0** [RetroPie/RetroPie-Setup#2288]
Repro steps:

- Get [Battle Mania Daiginjou for Megadrive/Genesis](https://screenscraper.fr/gameinfos.php?gameid=1022):
CRC 312FA0F2
MD5 1FFE5B490CDDEB691E3ADD6947024F83
SHA1 FBCF7E899FF964F52ADE160793D6CB22BF68375C
- Add it to your megadrive rom folder (mine is on a NAS, just in case)
- Try to browse to the Battle Mania Daiginjou entry in the Megadrive system
- -> Emulationstation crashes and you return to the shell

Retropie 4.3 on a Raspberry Pi 3

**Comment by joolswills** [comment]
Please use the forum first as detailed when opening a ticket. If confirmed an issue can be opened on our es tracker.
