### ISSUE TITLE
Forum sign-up mails not being sent out

### ISSUE THREAD

**Issue by hholst80** [RetroPie/RetroPie-Setup#2289]
forum sign-up mails are not being sent out as they should. Checked spam and inbox and nothing there.

**Comment by joolswills** [comment]
Can't see any problem. Your signup mail was delivered to the google mail server.

```
2018-02-10 00:18:30 1ekIs9-0001Fg-6L => YOUREMAIL@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.go
ogle.com [2a00:1450:400c:c04::1b] X=TLS1.2:ECDHE_RSA_CHACHA20_POLY1305:256 CV=yes DN="C=US,ST=California,
L=Mountain View,O=Google Inc,CN=mx.google.com" C="250 2.0.0 OK 1518221910 p70si145485wma.88 - gsmtp"
```

**Comment by joolswills** [comment]
Must be in your mailbox somewhere unless gmail lost it (but that's unlikely). You can request another one from the user profile page.

**Comment by hholst80** [comment]
You are right it was sorted by Gmail under one of the other inboxes. I was too tired to think of that possibility yesterday. Sorry about that. Thank you for looking into it.
