### ISSUE TITLE
[Ubuntu 18.04 - alpha or beta] egl.h missing - retroarch not building

### ISSUE THREAD

**Issue by gammelobst** [RetroPie/RetroPie-Setup#2301]
Hi,

i have two fresh installs of Ubuntu 18.04 alpha or beta and the setup-script does not pull egl.h and this leads to a failing Retroarch compile-run.
After installing egl.h manually it does compile core and main.
 I will install the rest afterwards and add more issues here.

Thanks in advance

**Comment by joolswills** [comment]
You don't mention what platform, but we won't support Ubuntu 18.04 until after its released. Please use the forum first as detailed when opening a ticket.
