### ISSUE TITLE
Change discs in PSX emulator

### ISSUE THREAD

**Issue by gardobeson** [RetroPie/RetroPie-Setup#233]
Hey All,

Have any of you had success with changing discs in the PSX emulator?  I boot from the ES gui, then play through Heart of Darkness until the end of disc 1.  I then exit the emulator, and load up disc 2.  When disc 2 is loaded, I press "play" and it then tells me to load disc 1 and press start when finished.  

I saw a post on @petrockblog 's forums: 

(http://blog.petrockblock.com/forums/topic/how-do-i-change-disks-on-psx/) 

this post tells me to configure the following input in ~/RetroPie/configs/psx/retroarch.cfg file:
"
input_disk_eject_toggle =
input_disk_next =
"

(without ", of course). 

Any advice/luck similar stories?

**Comment by mdurrer** [comment]
What has happened to this? Like 2 years later and no solution.
Key bindings don't work, Disc options in the menu doesn't even show up. Core Disk options is there but can't be entered.

Would be very glad if we could solve this!

**Comment by joolswills** [comment]
http://blog.petrockblock.com/forums/topic/best-way-for-psx-multidisc-games/ ?

If something in retroarch is not working as it should it should be reported upstream as it's not a retropie specific issue.

**Comment by Tele42** [comment]
When I last took a look (in March) at libretro's pcsx_rearmed this was working through the retroarch rgui

**Comment by poikidz123** [comment]
Try this, copy the 'Your game name.srm' from disc 1 directory and paste it into the disc 2 directory and rename it after the disc 2 name.
