### ISSUE TITLE
lvl0: Error creating SDL window!

### ISSUE THREAD

**Issue by OxygenGS** [RetroPie/RetroPie-Setup#2337]
Ok, so i run Raspbian, and i did install Retropi like followed on this page:
https://github.com/RetroPie/RetroPie-Setup/wiki/Manual-Installation

All did go well i need to say, i followed all steps and did do the Full Install.
However! Once all is done, and i wanna start emulationstation and hit enter i get to see this.

![29342748_10211204532778294_8797899296474136576_n](https://user-images.githubusercontent.com/37304735/37572184-ab4e2722-2b07-11e8-8bf9-5682e32b73d5.jpg)

I did google it and did apply a code, this one: sudo rpi-update a16f22120d7979dc91e8d2e03fecb611fb0259e0

However, once i did reboot i did only get a white screen and my whole installation was broken ahah, so i did reinstall my pi now but still get the same annoying error/message. How to fix this?

**Comment by joolswills** [comment]
Please use the forum for help - as detailed when open an issue.
