### ISSUE TITLE
Dolphin fails to build on Ubuntu 16.04 (x86_64)

### ISSUE THREAD

**Issue by samplethief** [RetroPie/RetroPie-Setup#2339]
Click on any Gamecube rom/iso and fails to launch, returns to rom browser. (Ubuntu x64)

Emulator has been installed, updated via the emulationstation experimental package manager menu but the folder Emulationstation calls Dolphin-emu at /opt/retropie/emulators/dolphin is empty...

/dev/shm/runcommand.log says:

`Executing: /opt/retropie/emulators/dolphin/bin/dolphin-emu -b -e "/home/myusername/RetroPie/roms/gc/Mario Kart - Double Dash!! (USA).iso" /opt/retropie/supplementary/runcommand/runcommand.sh: line 1006: /opt/retropie/emulators/dolphin/bin/dolphin-emu: No such file or directory`

Fixed the issue by manually apt-get installing dolphin-emu and creating a sym link from /usr/games/dolphin-emu-nogui to /opt/retropie/emulators/dolphin/bin

**Comment by joolswills** [comment]
is this your post ? https://retropie.org.uk/forum/topic/16900/dolphin-folder-is-empty

**Comment by samplethief** [comment]
It is not @joolswills

**Comment by samplethief** [comment]
@joolswills It isnt. But yes looks like the same thing.

**Comment by joolswills** [comment]
For future reference, please use the forum first for reports, as detailed when opening an issue. There are more people there to help.

I will need a build log from RetroPie-Setup to look into this as it installs fine here (I don't have any `/usr/games/dolphin-emu-nogui`  - dolphin installs to  `/opt/retropie/emulators/dolphin/bin`)

I also need full details of your set-up including hardware / operating system and version of retropie-setup script you are using.

**Comment by samplethief** [comment]
Distributor ID: Ubuntu
Release: 16.04
Codename: xenial
CPU: Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz

Installation Script used: https://github.com/RetroPie/RetroPie-Setup

Dolphin Build Log: https://mega.nz/#!Os0UBDiJ!3OxcB-gAIMSVurDLaqVZYRH5gUNCBVV0svPIwaAfhmE

**Comment by joolswills** [comment]
The build fails - it should actually not run the configure, but the module needs some extra code to know that the build has failed to do this. I will do that, but it may just be due to compiler versions on Ubuntu 16.04 as to why it's failing. I built fine on Ubuntu 18.04 (beta). I probably won't get around to looking at this any time soon, so it might be worth trying a newer Ubuntu or waiting till the new LTS is out.

**Comment by samplethief** [comment]
@joolswills Yeah no problem I was just bringing it to your attention, As I say, I have it working fine using a symbolic link to the actual location.

**Comment by joolswills** [comment]
You must have installed another copy for it to be installed there - via Ubuntu packages I assume ?

**Comment by samplethief** [comment]
ah yes, I installed with apt-get install dolphin-emu. Ill add that to the description incase anybody else comes here looking for solutions in the mean time.

**Comment by joolswills** [comment]
I confirmed the issue in a VM. I have worked around the problem by forcing an older version to be built on Ubuntu 16.04.

**Comment by samplethief** [comment]
Nice work thanks
