### ISSUE TITLE
lr-ppsspp build script asks for username and password

### ISSUE THREAD

**Issue by drwhoelse** [RetroPie/RetroPie-Setup#2347]
Below is copy-n-paste of terminal box for building lr-ppsspp...

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'lr-ppsspp' : PlayStation Portable emu - PPSSPP port for libretro
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 "https://github.com/libretro/libretro-ppsspp.git" "/home/ubu/RetroPie-Setup/tmp/build/lr-ppsspp"
Cloning into '/home/ubu/RetroPie-Setup/tmp/build/lr-ppsspp'...
Username for 'https://github.com': 
Password for 'https://github.com':
-------

After I entered blank username and password, I get error 128 message.

**Comment by joolswills** [comment]
upstream have removed the repo as they have a new ppsspp core. We don't yet support that yet. I may be able to restore a fork of the old repo if I have a local checkout, or else we will have to disable the module. You can use the standalone PPSSPP emulator.

**Comment by joolswills** [comment]
actually we have a fork already, so I can just use that for now.

**Comment by joolswills** [comment]
This is fixed in fcd8367616283df50e444d399101716265dfa9dd but please provide more information next time including a full log to help us (This issue was specific to non rpi platforms).
