### ISSUE TITLE
Variable Governor not set in the wiki for Odroid XU4 - Performance Issue

### ISSUE THREAD

**Issue by jocafi** [RetroPie/RetroPie-Setup#2350]
Please update the instructions to set the **governor** variable in the wiki for Odroid XU4 below:

https://github.com/RetroPie/RetroPie-Setup/wiki/Odroid-XU4

I could download an image for Retropie odroid XU4 on the site below and edit the file boot.ini

https://retropie.org.uk/forum/topic/15861/ora-retropie-image-for-the-odroid-xu4

The boot.ini has the following values and documentation for the  governor variable:

```
# --- CPU Governor Setup ---
# Uncomment only one line. New governor is set after 90secs after boot.
# ------------------------------------------
# - Performance (Keep all the CPU's at Maximum frequency)
setenv governor "performance"
# ------------------------------------------
# - Ondemand
# setenv governor "ondemand"
# ------------------------------------------
# - Interactive (Pretty much just like ondemand with more possible customization via sysfs.)
# setenv governor "interactive"
# ------------------------------------------
# - Conservative (Like ondemand, but do the frequency transitions more slowly, great for battery powered applications)
# setenv governor "conservative"
# ------------------------------------------
# - Powersave (Keeps the CPU's to the lowest possible temps)
# setenv governor "powersave"
```

I think, the documentation should mention the value below for better performance:
**setenv governor "performance"**

Regards,
Jocafi

**Comment by joolswills** [comment]
You didn't follow the instructions when opening a issue

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

also - the wiki is user editable. I wouldn't recommend setting the governor to performance by default - ondemand should suffice,
