### ISSUE TITLE
Bombermaaan 

### ISSUE THREAD

**Issue by bjaraujo** [RetroPie/RetroPie-Setup#2358]
I have tested Bombermaaan port for retropie.

https://github.com/bjaraujo/Bombermaaan/blob/master/retropie/bombermaaan.sh

I would like if you could add this port to retropie experimental for others to install and test.

**Comment by joolswills** [comment]
Please submit a PR and it can be tested / included if all ok.

**Comment by bjaraujo** [comment]
I have submitted PR #2383

**Comment by danger89** [comment]
Its merged right? I think it can be closed.

**Comment by joolswills** [comment]
Yep. Thanks
