### ISSUE TITLE
Wifi Updates for Stretch

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#2364]
Per our conversation earlier, 

With the Stretch/Pi3B+ wifi requires localisation so would probably be good to have a check/notification so we don't get a barrage of people wondering why wifi doesn't work on the update.

**Comment by joolswills** [comment]
Thanks. I have mostly done this - will do a PR in the next day or two. Want to do some final testing also on my RPI3 Model B+
