### ISSUE TITLE
lrmame2003 plus binary

### ISSUE THREAD

**Issue by grant2258** [RetroPie/RetroPie-Setup#2374]
would it be possible to add a binary download as its part of libretro now

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.

**Comment by joolswills** [comment]
As per the issue instructions use the forum first - I am not yet happy to move the module into optional packages so it's source only for now.

**Comment by grant2258** [comment]
Fair enough there is some issues with mame2003 at the moment as well. Its probably best to iron these out first before moving mame2003+ in. I accept your choice saying your not happy to move the module into optional packages. I has the same functionality as mame2003 but we are making changes at the moment as soon as we think its at a point we are happy its stable we will address it in the forum.

**Comment by grant2258** [comment]
@joolswills its just to let you know the makefile targetname for mame2003-plus has changed from mame2003-plus_libretro.so to  mame2003_plus_libretro.so when your doing the script updates
