### ISSUE TITLE
GPD Pocket ubuntu 17.10.1 unity RetroPie v4.4 failed to compile some emulators.

### ISSUE THREAD

**Issue by jutleys** [RetroPie/RetroPie-Setup#2376]
Hi i have installed this on my gpd pocket with a build of linux ubuntu 17.10.1 on it all went well following the wikki guide. But quite alot of emaulators are missing. Okay so the only emulators that get compiled with the 32bit basic install are below the rest are missing i have tried rebuilding them again with no luck i hope this can get solved if someone can tell me what files they need i presume i can upload all the log files from ~/RetroPie-Setup/logs. i really hope this gets resolved i need picodrive thanks.

Building and working fine below

arcade
atari2600
atari7800
fba
gb
gba
gbc
n64
neogeo
pcengine
psx
snes

Failed to build below not working

lr-atari800
lr-beetle-ngp
lr-caprice32
lr-fceumm
lr-fuse
lr-genesis-plus-gx
lr-handy
lr-mame2000
lr-mame2003
lr-nestopia
lr-picodrive
lr-quicknes
lr-snes9x2010
lr-vba-next
lr-vecx

Device
GPD Pocket linux ubuntu 17.10.1 unity Retropie v4.4

files from ~/RetroPie-Setup/logs
https://drive.google.com/file/d/1UfDMy_O0qG0J41gnyfwYWM2F4gXK_zjb/view?usp=sharing

**Comment by jutleys** [comment]
files from ~/RetroPie-Setup/logs

[retropie-setup-logs.zip](https://github.com/RetroPie/RetroPie-Setup/files/1934986/retropie-setup-logs.zip)

**Comment by joolswills** [comment]
You already are receiving support on the forum.
