### ISSUE TITLE
Dualshock 4 Connection Problem

### ISSUE THREAD

**Issue by Litschler** [RetroPie/RetroPie-Setup#2379]
When I paired my Dualshock 4-Controller through Bluetooth to my Raspberry Pi 3, it connects successfully. But when I quit the Bluetooth-Settings, I get the message: 

> NOTICE: The ps3 controller driver was temporarily interrupted in order to allow compatibility with standard Bluetooth Peripherals. Please re-pair your Dual Shock Controller to continue (or disregard this message if currently using another controller)

The controller is the only Bluetooth-device I have paired with my Raspberry Pi, but there are many other Bluetooth-devices in the area. I have installed all avalible drivers from the config and I downloaded RetroPie today. The USB-connection works, but I am only able to navigate through EmulationStation, not in ROMs (But I have only tried the ROM Alladin). On keyboard everything worked like a charm since the beginning. I also sometimes get an Undervoltage-Error, but I don't think it has anything to do with that.

**Comment by joolswills** [comment]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.
