### ISSUE TITLE
Scraper "1945kiii.zip" (2.682 Mb) - terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by flop123** [RetroPie/RetroPie-Setup#2380]
Hi, I just made a fresh install of retropie 4.4 and launched ES menu scraper, after few games scraped, ES close and goes to terminal telling: ***terminate called after throwing an instance of 'char const*'***

I could locate that the error appears with "**1945kiii-image.png**", so I rename another .png to bypass that error and all looks to work good now.

The rom md5sum is:
45fb93856bdf172467461e45d430cf69

And the image md5sum is:
ea7c0c8e81c6d6e702d373cb61aa7a79

Thx for your efforts. bb! (image attached)
![1945kiii-image](https://user-images.githubusercontent.com/38666125/39141703-cf0073d6-4728-11e8-849d-67769729fa81.png)

Info: Rpi 3, retropie 4.4 fresh install, roms from usb 64 gb kingstom, TV 43" 4k (resize image error?)

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.
