### ISSUE TITLE
Virtual Gamepad nodejs errors

### ISSUE THREAD

**Issue by me246813579** [RetroPie/RetroPie-Setup#2382]
I am installing Virtual Gamepad, and i know that i have installed NodeJS, but when i install it from the experimental menu, it says cant install nodejs. There is a problem with one of the setup scripts preventing this from working. i am on RetroPie 4.14.30.

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.
