### ISSUE TITLE
Retropie .. NetPlay not on all emulators

### ISSUE THREAD

**Issue by cinemano** [RetroPie/RetroPie-Setup#2399]
Hello
I seem to only have the Netplay option on mame and psx.. how do I add the "launch with netplay" option on other emulators like Vice on Retropie?
Thanks... (which file do I need to edit to add vice) ?

**Comment by joolswills** [comment]
They don't have netplay. Use the forum for support as detailed when opening an issue.

**Comment by cinemano** [comment]
Ive heard vice has netplay...

**Comment by cinemano** [comment]
How do i find the forum to post the question?

**Comment by joolswills** [comment]
https://retropie.org.uk

It was linked in the text you removed when posting here.

**Comment by cinemano** [comment]
I'm afraid I cant seem to use that forum.. everytime I post a question it
gets flagged as spam.. even if I just write "hello" as a question..
that's why I went to github
