### ISSUE TITLE
Latest CoolCV not installed

### ISSUE THREAD

**Issue by mediamoshpit** [RetroPie/RetroPie-Setup#2401]
In reference to [this thread](https://retropie.org.uk/forum/topic/17706/coolcv-6-6-on-retropie-is-v4-4-give-error), CoolCV 6.2 is being installed rather than 6.6. Improvements to CoolCV since 6.2 are as follows.

>Edit: Nov/30/2017 v0.6.6, now Raspberry Pi version included, also added Ctrl+Fn+F4 to save a memory snapshot and Ctrl+Fn+F9 to log PSG values in each frame. (although keys are configurable, Ctrl for these isn't)

>Edit: May/25/2017 v0.6.5, joysticks are now configurable, support shortcuts for full screen and saves state of it for next time ;) (Mac Cmd+Ctrl+f and Windows Alt+Enter), enhancement of VDP emulation and undocumented modes, correction of execution time for some Z80 instructions, and solved bug where Sammy Lightfoot would crash. Raspberry version not available yet.
 
>Edit: Feb/15/2016 v0.6.4, now ADAM keyboard can be fully configured (very useful for users with non-US keyboards), and finally Raspberry version compiled.
 
>Edit: Jan/11/2016 v0.6.3, better emulation for Z80 solves pitch problem in speech in Sewer Sam and Squish'Em Sam, keys F4 and F7 are now configurable, Expertype and ADAM Bomb 2 are now working, fixed some ADAM keys for Windows, added 64K RAM expansion for ADAM, fixed bug in joystick support (not tested), added code to show joystick movement when using F7 (show codes). Raspberry not updated in this version because I didn't found my external keyboard

**Comment by joolswills** [comment]
have updated our archive to the latest binary.
