### ISSUE TITLE
Dreamcast (Reicast) : GPIO controller do not work on Retropie 4.4

### ISSUE THREAD

**Issue by SuperPiboy** [RetroPie/RetroPie-Setup#2408]
Hi Retrogamers,

My hardware configuration : RPI 2, PIGRRL 2, RETROPIE 4.4

There is a setting that i don’t understand. I use RETROGAME (Adafruit controller driver), all work fine as GPIO controller except with Dreamcast emulator (Reicast).
 I followed the instructions (https://github.com/retropie/retropie-setup/wiki/Dreamcast) but my gpio controller RETROGAME does’nt work.

On the other hand, i can set gpio controller with ./reicast-joyconfig, then a file “opt\retropie\configs\dreamcast\mappings\controller_retrogame.cfg” is created.
 I have just one Event named dev/input/event0.
 Conversely, if if plug USB snes gamepad or usb gamepad PS3, they ‘re work fine.

I don’t know what to do , i appeal to your help 

**Bellow all my settings :**

_**controller_retrogame.cfg :**
_[emulator]_
 _mapping_name = retrogame
 btn_escape = 57_

_[dreamcast]_
 _btn_a_ = 56
 btn_b = 44
 btn_x = 45
 btn_y = 29
 btn_start = 28
 btn_dpad1_left = 105
 btn_dpad1_right = 106
 btn_dpad1_up = 103
 btn_dpad1_down = _108_

_[compat]_
 btn_trigger_left = 30
 btn_trigger_right = 31_

**emu.cfg :**
_[audio]_
 backend = auto
 disable = _0_

_[config]_
 _Debug.SerialConsoleEnabled_ = 0
 Dreamcast.Broadcast = 4
 Dreamcast.Cable = 3
 Dreamcast.RTC = -2136789165
 Dreamcast.Region = 3
 Dynarec.Enabled = 1
 Dynarec.idleskip = 1
 Dynarec.unstable-opt = 0
 aica.LimitFPS = 1
 aica.NoBatch = 0
 aica.NoSound = 0
 bios.UseReios = 0
 pvr.MaxThreads = 3
 pvr.Subdivide = 0
 pvr.SynchronousRendering = 0
 pvr.rend = 0
 rend.UseMipmaps = 1
 rend.WideScreen = 0
 ta.skip = 0

[dispmanx]
 height = 480
 maintain_aspect = yes
 width = 640

[input]
 evdev_device_id_1 = 0
 evdev_device_id_2 = 1
 evdev_device_id_3 = 0
 evdev_device_id_4 = 0
 evdev_mapping_1 = /opt/retropie/configs/dreamcast/mappings/controller_retrogame.cfg
 evdev_mapping_2 = /opt/retropie/configs/dreamcast/mappings/controller_retrogame.cfg
 joystick_device_id = -1

[omx]
 audio_hdmi = no
 audio_latency = 100

[players]
 nb = 1

[reios]
 ElfFile =

[testing]
 ta.HashCheckFile =
 ta.HashLogFile =

[validate]
 OpenGlChecks = 0

**Thank you for reading me **

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.
