### ISSUE TITLE
Joystick Configuration Problem

### ISSUE THREAD

**Issue by Retroboii** [RetroPie/RetroPie-Setup#2409]
I've been having a problem with Retropie with my new set of arcade buttons they work on the main men but not in Retroarch (Nes snes etc) they actually worked at first but then I had an issue where I deleted the Retroarch-joypad folder and when I put it back I started getting the error message DragonRise inc controller not configured 
Here is a screen: https://retropie.org.uk/forum/assets/uploads/files/1527189342707-33592049_1777994502239605_5937587983715663872_n.jpg

**Comment by joolswills** [comment]
Please use the forum as detailed when opening an issue.
