### ISSUE TITLE
tried to write to log file before it was open! The following won't be logged:lvl2 EmulationStation-v2.7.5rp                                                                              

### ISSUE THREAD

**Issue by 118k** [RetroPie/RetroPie-Setup#2414]

**Comment by HerbFargus** [comment]
use the forum as requested when opening an issue.

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/
>
>This includes edit suggestions for the wiki. There are more people to help on the forum.
>
>Once a problem has been verified on the forum, an issue can be opened here.
>
>Please remove this text before posting.
