### ISSUE TITLE
N64 Emulator only recognizes inputs from keyboard, not controller

### ISSUE THREAD

**Issue by Smythius** [RetroPie/RetroPie-Setup#2415]
I have a retropie with emulation station and have managed to set up most everything alright but for whatever reason the N64 emulator is the only one that my controller doesn't work properly for. The ONLY input that registers is pressing L2 + R2 to exit the ROM back to the N64 games page (I did have it at one point that select + start did this action) and when launching a game pressing 'A' button will bring up the runcommand window. When I connect a keyboard I am able to play and the buttons are properly mapped and working. Can someone please tell me how to get the emulator to default to my controller instead of keyboard input? 

_*If you give instructions to use the command line please have command within "quotes" or the exact line to copy and paste into the command prompt. I am not very good at knowing where the command starts and what to include. thank you._

Emulation Station: **V2.7.5RP**
RetroPie: **V4.4.1**
Game Pad: **8Bitdo NES30 Pro**
N64 Emulator: **mupen64plus & Mupen64Plus + GLide64 for libretro**

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.
