### ISSUE TITLE
Logitech F710 buttons working as hotkeys in lr-pcsx-rearmed, and some fixed VICE problem

### ISSUE THREAD

**Issue by Vendi76** [RetroPie/RetroPie-Setup#2420]
Model: raspberry pi 3B+
retropie 4.4

I'm using a logitech f710. In Emustation, it's OK. 
I had some issues under VICE, the left analog joy "up" function didn't worked, but luckily found out, that somehow when VICE saved joystick settings, it mysteriously saved a "broken" line for the "up" direction, managed to correct it manually.
When I'm running psx games under lr-pcsx-rearmed, all the buttons work like hotkeys, pressing "x" starts RGUI menu, "start" exits etc.

**Comment by Vendi76** [comment]
I was a lame :) followed retroarch controller setup instructions videos from youtube, and with "autosave on exit" enabled i've messed up the whole thing. It works just perfect, if i only config in emulatorstation, and no additional messing in retroarch.

**Comment by joolswills** [comment]
Please also use the forum for support in the future as detailed when opening an issue. thanks.
