### ISSUE TITLE
ppsspp 1.6.3 build script. ETA

### ISSUE THREAD

**Issue by gerble1000** [RetroPie/RetroPie-Setup#2422]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.

**Comment by gerble1000** [comment]
i cannot seem to build the ppsspp emulator on my pie 3.
im looking forward to a retropie build script :)

**Comment by psyke83** [comment]
Closing. In future, be sure to follow the advice in the issue template (that you neglected to delete & replace when opening this ticket). 

There's an active topic already: https://retropie.org.uk/forum/topic/18116/ppsspp-emulator-update-v1-6-3
