### ISSUE TITLE
lr-mess install script fails (out of RAM) on RPi3B

### ISSUE THREAD

**Issue by jsevakis** [RetroPie/RetroPie-Setup#2424]
lr-mess install from RetroPie-Setup script fails repeatedly on RPi3B. Analysis of log file indicates that it runs out of RAM, even if EmulationStation is quit.

Fully repeatable. Verified with other users and in forum.
Sample log file here: https://pastebin.com/tb38W4j4

**Comment by cmitu** [comment]
Can you try with the latest version of the RetroPie-Script ? It should have been solved by 32c3f7adaa9.

**Comment by joolswills** [comment]
Closing as issue resolved.
