### ISSUE TITLE
Retropiemenu script for installing and updaring Skyscraper (by Lars Muldjord). By 2Play!

### ISSUE THREAD

**Issue by 2play** [RetroPie/RetroPie-Setup#2428]
Please find a retropiemenu script for installing and updaring Skyscraper by Lars Muldjord!
If you want to consider using it on future releases of RetroPie in retropiemenu
Concept-Creation by me, Skyscraper by Lars of course!
With his permission.

https://github.com/2play/Skyscraper

**Comment by joolswills** [comment]
Thanks but we would need it done as a retropie module for inclusion - feel free to share it on our forum though.
