### ISSUE TITLE
Wifi config app/menu is broken - saves passwords with quotation in the middle of the password

### ISSUE THREAD

**Issue by dman777** [RetroPie/RetroPie-Setup#2435]
For `retropie-4.4-rpi2_rpi3.img`... the wifi setup is broken. 

My wifi password is similar to `*foobar99`. The app kept saving it in the `etc/wpa_supplicant/wpa_supplicant.conf` as `"foo"bar99"`. It seem to cut out the password early with the quotations while still keeping a quotations on the end.

**Comment by joolswills** [comment]
You didn't follow the instructions when opening a ticket -

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

Your problem sounds like a keymap issue - RetroPie has a UK keyboard layout by default. You are probably typing a quote but I would need a real world example and steps to reproduce.
