### ISSUE TITLE
Shanwan PS3 controllers not working - retropie 4.4

### ISSUE THREAD

**Issue by allawi951** [RetroPie/RetroPie-Setup#2439]
I have PS3 Shanwan Controller & I tried to update retropie setup and re-install ps3 controller & change it to clone shanwan but my controllers can't pair, only 4 led flashing after plug out the usb for some seconds then switched off.

any ideas how to pair my controlers? I have retropie 4.4

**Comment by joolswills** [comment]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.
