### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pyloshophar** [RetroPie/RetroPie-Setup#2458]
Hi everyone i have follow the instructions and i can run the script , but when im going to install it , it appears this message
tar (child): MalditaCastilla.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

and i dont know how to fix it, please help

**Comment by joolswills** [comment]
Please use the forum as detailed when opening a ticket.
