### ISSUE TITLE
Alot of racist remarks on the DC Compatibility sheet.

### ISSUE THREAD

**Issue by acidmanifesto** [RetroPie/RetroPie-Setup#2466]
https://docs.google.com/spreadsheets/d/1AD91IcudqHP7dDmEXLO25Pzb85uUgAy4chU2QxlZBQk/edit#gid=379183179

I dont know who the trouble maker is, but there is alot of racist and hateful remarks in it.

**Comment by joolswills** [comment]
Please use the forum for problem relating to the wiki and contents. Also please state where in the sheet you identified the bad content (you are also free to remove it - I couldn't see anything from a qiuck glance.
