### ISSUE TITLE
Amstrad zip support

### ISSUE THREAD

**Issue by actraiser30** [RetroPie/RetroPie-Setup#2482]
Hi, lr-caprice32 supports games in zip format can you add this to es_systems.cfg in your next update?

Thanks

**Comment by joolswills** [comment]
Yes, but please use the forum first in the future as detailed when opening a ticket.

**Comment by actraiser30** [comment]
Thanks for the add,i wanted also to say to add kodi in the menu as its own system once its installed.

thanks anyway

**Comment by actraiser30** [comment]
Thanks for the add,i wanted also to say to add kodi in the es_systems.cfg once its installed.

thanks anyway
