### ISSUE TITLE
Latest Reicast does not compile on Ubuntu 16

### ISSUE THREAD

**Issue by thatjoshguy** [RetroPie/RetroPie-Setup#2483]
Due to several changes to the source, the latest release of Reicast will not compile on Ubuntu 16.04 via the "optional packages" script.

By modifying RetroPie-Setup/scriptmodules/emulators/reicast.sh like so:

from:
```
if isPlatform "x11"; then
     gitPullOrClone "$md_build" https://github.com/reicast/reicast-emulator.git
```

to:
```
if isPlatform "x11"; then
     gitPullOrClone "$md_build" https://github.com/reicast/reicast-emulator.git r7
```

RetroPie will download and compile the previous r7 release, which works fine.

**Comment by cmitu** [comment]
This is an upstream problem (https://github.com/reicast/reicast-emulator/issues/1375) which should be resolved there, there is no reason to downgrade every x86 installation to the r7 version.

**Comment by thatjoshguy** [comment]
Fair point and I agree, but in case they drag their feet I offer a temporary solution for those who need it.

**Comment by cmitu** [comment]
They can 'drag their feet' as much as they want to, I'm sure they have their reason.

**Comment by joolswills** [comment]
@thatjoshguy Please follow our procedure first though as detailed when opening a ticket (we ask people to use the forum first). I would also add that we cannot test and support old LTS releases so I am going to close this

**Comment by dmschwartzii** [comment]
Issue fixed upstream

**Comment by joolswills** [comment]
Thanks.
