### ISSUE TITLE
Kodi in ES

### ISSUE THREAD

**Issue by actraiser30** [RetroPie/RetroPie-Setup#2491]
Hi, is it possible to add kodi in the es_systems.cfg once its installed to be shown on the emulationstation menu?

Thank you

**Comment by joolswills** [comment]
You didn't follow the instructions when opening a ticket

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>This includes edit suggestions for the wiki. There are more people to help on the forum.

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.
