### ISSUE TITLE
Add lr-Daphne & Hypseus to Retropie

### ISSUE THREAD

**Issue by Stuart2773** [RetroPie/RetroPie-Setup#2494]
Hi,
This is a pull request to add lr- Daphne to retropie 

https://github.com/libretro/daphne

https://retropie.org.uk/forum/topic/18505/hypseus-new-daphne-fork-to-try-on-retropie

regards,

Stuart

**Comment by joolswills** [comment]
a PR includes code btw. This is not a PR.

**Comment by cmitu** [comment]
Hypseus is not part of RetroPie. The libretro core for Daphne is not working and it's no longer developed.
