### ISSUE TITLE
Quick Question a few seconds.

### ISSUE THREAD

**Issue by ratmandom** [RetroPie/RetroPie-Setup#2501]
Sorry but I could not find this info.

Why does the achievements not appear on Sega mega drive/Genesis and other Sega systems.
... not on retroarch menu list and can not be unlocked ...

Other systems are fine.

I am on a PI ZERO is that why?

And I have tried 2 different retropie builds.

**Comment by cmitu** [comment]
Please use the forum for question and support issues. This tracker is for bugs only.
