### ISSUE TITLE
lr-mupen64plus build fails on rpi2/rpi3

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#2506]
Looks like a makefile issue, as some neon asm is not being built/linked correctly. Older sources work.

Currently bisecting.

**Comment by hhromic** [comment]
I was also trying to debug this, great you are taking care.

**Comment by joolswills** [comment]
It's this commit https://github.com/libretro/mupen64plus-libretro/commit/e54a7279d5610602177c3fcaa6f747a7c0547cfd

The logic as it is now, platform gets "unix" added to it for RPI, and then the rpi logic later isn't included.

I have a fix which I will open a PR for.

**Comment by joolswills** [comment]
PR opened upstream

https://github.com/libretro/mupen64plus-libretro/pull/73

**Comment by hhromic** [comment]
Great job @joolswills, your PR got already merged upstream and I can confirm `lr-mupen64plus` is compiling fine again from source on my RPI3b+. Cheers.

**Comment by joolswills** [comment]
thanks.
