### ISSUE TITLE
GBA - Almost no cheats work - Gameshark (nor Gamegenie)

### ISSUE THREAD

**Issue by DunhamGitHub** [RetroPie/RetroPie-Setup#2514]
Checked cheats for following games:

Golden Sun Game Shark - none work
Golden Sun 2 Game Shark - none work
Pokemon Fire Red - Max PP works, all others (item, wild pokemon) do not
Pokemon Sapphire - none work
Rayman - none work

..all cheats I found mostly on bsfree, they ALL work on "VirtualBoyAdvance" yet NONE work on RetroPie. Too bad

Here is an example cheat file for Golden sun

`cheats = 22

cheat0_desc = "P1 Max STR"
cheat0_code = "8200053C03E7"
cheat0_enable = false

cheat1_desc = "Garet Slot 1 Sol Blade"
cheat1_code = "320009B6000A"
cheat1_enable = false

cheat2_desc = "Garet Slot 1 Mythril Shirt"
cheat2_code = "320009B600FA"
cheat2_enable = false

cheat3_desc = "Garet Slot 1 09 Items"
cheat3_code = "820009B60109"
cheat3_enable = false

cheat4_desc = "No Random Battles"
cheat4_code = "820004780000"
cheat4_enable = false

cheat5_desc = "Have 2 Turns P1"
cheat5_code = "320006440004+320007900004+320008DC0004+32000A280004"
cheat5_enable = false

cheat6_desc = "Have 2 Turns All"
cheat6_code = "320006440002+320007900002+320008DC0002+32000A280002"
cheat6_enable = false

cheat7_desc = "Walk through Walls Hold R"
cheat7_code = "7400013002BF+E2030ECEFFFF+74000130027F+E2030ECE0001+7400013002DF+E2030EC6FFFF+7400013002EF+E2030EC60001"
cheat7_enable = false

cheat8_desc = "Map - Walk through Walls Hold B"
cheat8_code = "7400013003BD+E2030DB6FFFF+74000130037D+E2030DB60001+7400013003DD+E2030DAEFFFF+7400013003ED+E2030DAE0001"
cheat8_enable = false

cheat9_desc = "Garet Slot 1 Psy Cristal"
cheat9_code = "83007D2200BA"
cheat9_enable = false

cheat10_desc = "Isaac Inf PP"
cheat10_code = "8200053A03E7"
cheat10_enable = false

cheat11_desc = "Garet Inf PP"
cheat11_code = "8200068603E7"
cheat11_enable = false

cheat12_desc = "Mia Inf PP"
cheat12_code = "8200091E03E7"
cheat12_enable = false

cheat13_desc = "Ivan Inf PP"
cheat13_code = "820007D203E7"
cheat13_enable = false

cheat14_desc = "Jenna Inf PP"
cheat14_code = "82000BB603E7"
cheat14_enable = false

cheat15_desc = "Exp 25000"
cheat15_code = "8203058061A8"
cheat15_enable = false

cheat16_desc = "Exp 50000"
cheat16_code = "82030580C350"
cheat16_enable = false
`

**Comment by joolswills** [comment]
You need to use the forum first as directed when opening an issue
