### ISSUE TITLE
RetroPie isn't starting with the latest update

### ISSUE THREAD

**Issue by Borotes** [RetroPie/RetroPie-Setup#2521]
Hi, 

I just updated my RetroPie to the latest version and it isn't starting anymore. I made a clean install, updated it and the problem persists.

Stuck on boot: https://i.imgur.com/Fn9nLzS.jpg

Is it a common problem?

I have a Raspberry Pi 3 B+ and the RetroPie Version is 4.4.3.

**Comment by joolswills** [comment]
Use the forum as directed.

**Comment by actraiser30** [comment]
Common problem after full update ussualy happens in rpi1/0 run the retrpie setup script go to the autostart section select command line auto-login press ok and then select boot to emulation station
after reboot retropie and should be ok
