### ISSUE TITLE
Bash variable expansion should be an option

### ISSUE THREAD

**Issue by Ratstail91** [RetroPie/RetroPie-Setup#2538]
Commit 7ec5e2e5eae4897d0f6f9c17ae745a0cc3a41bff resolved issue #2386, however this removes a feature that I require - I'm currently trying to reinstall retropie with this tweak removed. 

Several guides for recording gameplay from the retropie include a trick to prevent old recordings from being overwritten. However, this trick is no longer possible with this "fix".

One such guide can be found here: https://retroresolution.com/2016/07/06/recording-live-gameplay-in-retropies-retroarch-emulators-natively-on-the-raspberry-pi/

I'm requesting an option to allow the $ character to expand bash variables in a safe way.

**Comment by joolswills** [comment]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.
Sorry but you will need to find another way as I don't want to change this functionality. Also please use the forum first as
