### ISSUE TITLE
Newer & simpler method to associate Wiimote

### ISSUE THREAD

**Issue by u1735067** [RetroPie/RetroPie-Setup#256]
Hi there, 

while trying to associate a non official wiimote classic controller, I found this: http://github.com/dvdhrm/xwiimote
Since recent kernel releases (including the one used by RetroPie), an optional module, `hid-wiimote` can be loaded using `modprobe hid-wiimote`, then you use `sudo hidd --search` to find the wiimote without a pin (bluez is not good at this, asking for a pin), and in the syslog : 

```
Jan 18 21:55:21 raspberrypi hidd: New HID device 00:18:00:B2:F5:35 (Nintendo RVL-CNT-01)
Jan 18 21:55:21 raspberrypi kernel: [168934.199087] wiimote 0005:057E:0306.0007: hidraw0: BLUETOOTH HID v3a.1c Gamepad [Nintendo RVL-CNT-01] on 00:1A:7D:DA:71:13
Jan 18 21:55:21 raspberrypi kernel: [168934.200264] input: Nintendo Wii Remote Accelerometer as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:71/0005:057E:0306.0007/input/input30
Jan 18 21:55:21 raspberrypi kernel: [168934.201753] input: Nintendo Wii Remote IR as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:71/0005:057E:0306.0007/input/input31
Jan 18 21:55:21 raspberrypi kernel: [168934.213406] input: Nintendo Wii Remote as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:71/0005:057E:0306.0007/input/input32
Jan 18 21:55:22 raspberrypi kernel: [168935.216422] input: Nintendo Wii Remote Extension as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:71/0005:057E:0306.0007/input/input33
Jan 18 21:55:22 raspberrypi kernel: [168935.223466] input: Nintendo Wii Remote Motion+ as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:71/0005:057E:0306.0007/input/input34
Jan 18 21:55:22 raspberrypi kernel: [168935.224051] wiimote 0005:057E:0306.0007: New device registered
```

You can run test with evtest or xwiishow.

I wanted to share this, as it seems much simpler & integrated than the method proposed in the wiki (https://github.com/petrockblog/RetroPie-Setup/wiki/Wiimotes-with-classic-controllers).

**Comment by MarekK82** [comment]
As described in the [newer Wiki Article](https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-Wii-U-Pro-controller) I managed to pair my Wiimote using `xwiimote`. I can test all functionality with the `xwiishow` command. Also the connection re-establishes automatically.

But... unfortunately, Emulationstation does not recognize the Wiimote as gamepad :-1: 

What am I missing? Anyone can help me out here?

**My system:**
* Raspberry Pi 2
* Raspbian Jessie (2015-11-21)
* RetroPie installed *binary-based*

**Comment by MarckOliver** [comment]
I'm in the same boat as MrksKwsnck.

- Raspberry Pi 2
- RetroPie Image Jessie based (beta)
- Wii U Pro Controller (Third Party)

Any advice?

**Comment by melancond** [comment]
Same as MrKsk.

> RPI 2
> Raspbian Jessie IMG installation (2015-11)
> apt-get update/upgrade
> RetroPie installed binary-based (with bluetooth configuration)
> apt-get install xwiimote

Need help please

**Comment by Alex131089** [comment]
I didn't really got my hands on this since the last posts, but I still have this project in mind and I hope I'll have some time to update all this stuff with latest versions in a few weeks/months (It's currently the last months of my studies) ; maybe someone will find an answer in the meanwhile.
The only thing I see that could go wrong currently is the udev rule (and/or maybe the hid-wiimote module not patched ?).

**Comment by mrbwa1** [comment]
Hello,
 
Retropie 3.4 has made some changes for the bluetooth side of stuff that is supposed to work in the config menu now.  I have seen a few tutorials on the 8bitdo controllers and I believe this will translate to the Wiimote.  A specific UDEV rule is needed and discussed here: https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-a-Bluetooth-controller

I sadly have not had time to test out this technique, but will hopefully have some time to do so shortly.  The UDEV rule will need to be modified with the correct name for the Wiimote.

Again, I haven't had a chance to try, but I believe it should work with a couple potential issues:
-I am unsure if the analog sticks will work (or work correctly) without manual config files
-I do not know if this will handle LED enumeration on multiple remotes

If anyone wants to try, I suggest watching this first, as it talks about potential pitfalls and how to grab the name for the UDEV rule: https://www.youtube.com/watch?v=Q4K3h4CIJwA  (looks like it is the name as reported in bluetoothctl).  I will try to get to it when time permits, but that could take a while, so I wanted to hopefully point folks to something that may work.

**Comment by Alex131089** [comment]
I gave the rule/name here https://github.com/RetroPie/RetroPie-Setup/issues/256#issuecomment-52950792 , for this controller, if it can help :)

**Comment by Arielsicx** [comment]
I'm trying to hook up my wifi controller I did everything that was supposed to be done but my raspberry pi 2 running the latest retro pie keeps saying File not found: /home/pi/mywinput     Can somebody tell me what I'm doing wrong cause that file is there I've seen it

**Comment by Arielsicx** [comment]
I meant wii controller

**Comment by MrksKwsnck** [comment]
@Arielsicx What does the command `ls /home/pi/mywinput` tell you? Remember the file system is case sensitive.

**Comment by Arielsicx** [comment]
Now it says Warning: duplicate absolute axis assignment but it says it twice then it says invalid bdaddr

**Comment by Arielsicx** [comment]
Ok I can get it to work after pressing f4 and then typing exit but it detects it I hold a button down and it freezes I hit f4 again and then it just keeps saying socket connect error (control channel)

**Comment by rockfireredmoon** [comment]
I thought I'd share my solution here, as I am pretty happy with it, and it requires no real amount of configuration other than just mapping the keys in ES and has so far been very stable playing games with it.

Using the latest RetroPie and the hid-wiimote kernel module, the only other thing you need is MoltenGamepad - https://github.com/jgeumlek/MoltenGamepad

This works out of the box with a wiimote, you just need to run it at boot before ES starts up (after having paired your wiimote as normal of course). 

The cool thing about it is that it presents the Wii as another (set of) virtual devices. These are stable, and always available while the daemon is running. The wiimotes can come and go, and moltengamepad deals with all the details. It also can accept remote commands from a pipe which may be useful for integrating with other stuff.

Attached is the systemd unit file I use to start it on boot. The only thing you need to do upon boot is press a button on the wiimote a couple of times. The first time to start the connection, and the 2nd one to activate moltengamepad.

[moltengamepad.service.txt](https://github.com/RetroPie/RetroPie-Setup/files/202414/moltengamepad.service.txt)

Some quick setup instructions

1. Setup your wiimote to use the **standard** hid-wiimote as documented elsewhere (dont use a patched one). So modprobe hid-wiimote then using bluetoothctl to pair is good enough.
2. Download and compile moltengamepad
3. Copy the binary moltengamepad to /usr/sbin 
4. Copy the attached systemd unit file to /lib/ 
5. Enable the service with systemctl enable moltengamepad
6. Reboot
7. Press a key once to connect, then again to activate moltengamepad. 

You can now use ES the map all the buttons as you wish in the normal way. I used both the controller and nunchuck, no idea whether the classic controller works though.

**Comment by MrksKwsnck** [comment]
Wow, I never heard of that *MoltenGamepad* project before. I can't wait to give it a try. Thanks

**Comment by RichardBronosky** [comment]
These instructions like all the others are incomplete and full of assumptions and magic. Everyone who tries to get a modern Wii Remote (with Motion Plus; aka: "Nintendo RVL-CNT-01-TR") in the past 4 years has failed miserably and given up. I suggest anyone who has gotten this far gives up and buys different controllers. If you value your time at $0.25/hour or more, you will save money by giving up.

When you see a statement like, "Setup your wiimote to use the standard hid-wiimote as documented elsewhere", you know who are not going to find the right magic that makes this all work. Give up.

**Comment by polaco1782** [comment]
@rockfireredmoon your solution works great for wiimotes. Thanks a lot!

**Comment by TauPan** [comment]
Thanks @rockfireredmoon . Probably it's helpful to point out that, as referenced in https://github.com/jgeumlek/MoltenGamepad#how-do-i-connect-a-wiimote you need to pair by pressing the red button on the wiimote, then connect, then trust, as explained in https://wiki.archlinux.org/index.php/XWiimote#Auto-Reconnect_is_not_working_after_pairing_with_red_sync-button .

I just need to press power to connect my wiimote + classic controller.

Unfortunately, in legacy emulators (such as atari800 and vice) the d-pad acts as trigger and the left analog is way too imprecise to play (e.g.) boulder dash.
 
But maybe it's possible to remap those buttons with MoltengamePad, haven't fully read the docs yet.

**Comment by TauPan** [comment]
I've just added this info to the wiki. I've removed the example session, as it's not accurate any more.
