### ISSUE TITLE
Unattended Install switch

### ISSUE THREAD

**Issue by douglasorend** [RetroPie/RetroPie-Setup#2571]
I would like to suggest an unattended install switch for the **retropie_setup.sh** script.

**Comment by joolswills** [comment]
Please use the forum first as detailed when opening a ticket.

**Comment by douglasorend** [comment]
Found the answer to my question:

> sudo apt-get install -y git dialog unzip xmlstarlet
> git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git /opt/RetroPie-Setup
> cd /opt/RetroPie-Setup
> sudo __nodialog=1 ./retropie_packages.sh setup basic_install
