### ISSUE TITLE
PS3 controller not recognized

### ISSUE THREAD

**Issue by Tom-Neverwinter** [RetroPie/RetroPie-Setup#2573]
supposedly all ps3 controllers work... apparently not. CECHZC2U is not being detected. 

ps3:
HID\VID_054C&PID_0268
1356 616

**Comment by joolswills** [comment]
Please use the forum first for support / reporting issues. Note that not all ps3 controllers work. We support some clones but certainly not all.

**Comment by Tom-Neverwinter** [comment]
yeah. we know. no effort seems to be spent on non generic controllers. forum is mostly useless. not interested in copy pasting controller scripts or relying on the poor config tools.

**Comment by vschmidt** [comment]
I'm map the ps3 controls and don't know where is the right place to share:

![ps3_controls](https://user-images.githubusercontent.com/45170595/130381898-513d2aa3-a25d-4c0e-ab23-c20bb257650d.png)

The config file is:
My muphen64plus.cfg file controls:

[Input-SDL-Control1]

version = 2
mode = 0
device = 0
name = "Sony PLAYSTATION(R)3 Controller"
plugged = True
plugin = 2
mouse = False
MouseSensitivity = "2.00,2.00"
AnalogDeadzone = "4096,4096"
AnalogPeak = "32768,32768"
DPad R = "button(16)"
DPad L = "button(15)"
DPad D = "button(14)"
DPad U = "button(13)"
Start = "button(9)"
Z Trig = "button(11)"
B Button = "button(6)"
A Button = "button(7)"
C Button D = "button(0)"
C Button R = "button(1)"
C Button L = "button(3)"
C Button U = "button(2)"
L Trig = "button(4)"
R Trig = "button(5)"
Mempak switch = ""
Rumblepak switch = ""
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"
