### ISSUE TITLE
update mame2003 binary

### ISSUE THREAD

**Issue by markwkidd** [RetroPie/RetroPie-Setup#2576]
The current binary build of mame2003 has some significant bugs that have been fixed.

For example: https://retropie.org.uk/forum/topic/2612/mortal-kombat-2-3-umk3-audio/

The current binary is also prior to the vector rendering fixes.

Is it possible to update the binary to avoid more users reporting bugs that have already been fixed?

**Comment by joolswills** [comment]
Use the forum.

**Comment by markwkidd** [comment]
That's fine. There have been many posts already in the forum about this, so
I'm sure others with chime in.

**Comment by joolswills** [comment]
Then you can tag me in a post. I have already seen the thread though - I do not need issues opened with requests to update the binaries. I keep an eye on things and update as I see fit. If you think a change is important you can tag me on the forum and I may consider it.

**Comment by markwkidd** [comment]
That seems totally fair. I know the culture and workflows better over on
the libretro/RetroArch side of things -- I aspire to also doing things "the
right way" in the RetroPie domain
