### ISSUE TITLE
Need help to modify the source code

### ISSUE THREAD

**Issue by QuailBoy** [RetroPie/RetroPie-Setup#2581]
I'm doing an arcade box with retropie and I need to modify the source code to make my raspberry able to wait a signal from a PIR Sensor before it starts the emulation. Where can I put the new part of code? In which file? 
Thanks for your help.

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

There is an /opt/retropie/configs/all/autostart.sh file but this is not the place for support. thanks.
