### ISSUE TITLE
Logitech F310

### ISSUE THREAD

**Issue by testerfr810** [RetroPie/RetroPie-Setup#2583]
hi,

i have a Logitech F310, i have follow 
https://github.com/RetroPie/RetroPie-Setup/wiki/Logitech-Controller

I can navigate in emulationstation but when i want play nothing the gamepad no respond.

this bug is appearedafter Basic install and update.

ty i wait and need help

**Comment by cmitu** [comment]
Please use the forum, as directed in the issue template.
