### ISSUE TITLE
No dreamcast émulator on Retropie odroid xu4 ?

### ISSUE THREAD

**Issue by karatoso** [RetroPie/RetroPie-Setup#2615]
Hello community, thank you for your help possible, I started on Retropie, I am under Odroid Xu4 with minimal 18.04 ubuntu, I am trying to install the emulator Reicast, but it is not in the list of installable emulators, (just like that of the apple2), how can I add it? I had it on Recalbox, but I'm looking to install Retropie that I find more interesting!

**Comment by joolswills** [comment]
You already have a topic open on the forum. Please be patient and wait for a reply
