### ISSUE TITLE
Retroarch won't launch over retropie menu

### ISSUE THREAD

**Issue by Liontek1985** [RetroPie/RetroPie-Setup#2619]
Hello Guys,

I have updated retropie script and then retroarch, now i can´t launch retroarch over retropiemenu
after reflashing the sd card i have make the same stepps and have the self effect...

over emulationstation i can launching games with lr-emulators without problems, only over retropiemenu i cant start it. I see no error only black screen and fallback to retropiemenu

have anyone a solution for that?

best regards fredy

**Comment by joolswills** [comment]
Please ask on our forum.
