### ISSUE TITLE
DOSBox requires the fully bindable Joystick Patch to be able to use the 4th and 5th axis

### ISSUE THREAD

**Issue by JemyM** [RetroPie/RetroPie-Setup#2643]
The current DOSBox have an ancient issue where only axis 0-3 can be bound, making the right stick and right trigger on playstation 4 controllers and an xbox controller useless. This put a halt to the keyboard 2 joypad project that attempts to add joypad controls to all DOS actiongames.

This issue have long since been patched in most popular releases of DOSBox, such as ECE and Daum, but the patch is missing in Retropie. It can however be manually patched sucessfully. Please see dudleydes post here; https://retropie.org.uk/forum/topic/21561/dosbox-does-not-detect-axis-4-or-5-on-ps4-and-xbox-360-controller

We hope you can include the patch so that it can be installed using the setup script rather than the command line.

Here is a post with the patch:
https://www.vogons.org/viewtopic.php?f=32&t=27452&p=314840

**Comment by psyke83** [comment]
I took a look at the latest source and it seems that similar functionality may have been added via different code.

Please test: https://github.com/RetroPie/RetroPie-Setup/pull/2646
