### ISSUE TITLE
XRoar install error 128. Reason: Your setup script is getting an older version!

### ISSUE THREAD

**Issue by KI5JYD** [RetroPie/RetroPie-Setup#2657]
Sorry... I don't do forums. 

However, since I know Ciarian Ainscomb who produces Xroar (I'm a CoCo nut and us old Tandy CoCo/Dragon users are a slowly dying breed, and we must band together as much as possible), his site, https://www.6809.org.uk/xroar/, says that you are downloading an incorrect version. The version in the setup script downloads 0.33.2. That is not available in Mr. Ainscomb's git repo anymore! (He was kind enough to email me that info.)

He said thus:
Tell the RetroPie devs through their GitHub Issues that the reason why RetroPie is spouting an error 128 is because 0.33.2 is no longer available in my git repo. They need to fix their script to reflect the new version, 0.35.3 or the RetroPie Xroar script will not work. 

However, I don't have time (I am such a busy person) to go parsing the files to update your script, so please tell me where I need to change it and I will gladly upload an updated script.

This is the reason why your forum is not providing help. Your script is getting a version that is no longer available.

**Comment by cmitu** [comment]
> . That is not available in Mr. Ainscomb's git repo anymore! (He was kind enough to email me that info.)

This is not true, the 0.33.2 version still exists in the repository. The reason it fails is not the lack of source, but the lack of `makeinfo` - invoked during installation when installing from source.

> This is the reason why your forum is not providing help. Your script is getting a version that is no longer available.

The reason the forum is not providing help is that nobody asked for it there. 

I cannot find a tagged 0.35.3 release in the Git repository that Mr. Ainscomb kindly provides, the last tagged release is `0.35.1` from July 2018. The `0.35.5` (latest) version seems to be from Jan 2019 - but I cannot find any commits in the Git repository past July 2018.
