### ISSUE TITLE
RetroPi VNC Black Screen

### ISSUE THREAD

**Issue by hmt1376** [RetroPie/RetroPie-Setup#2661]
I've been trying to run emulationstation remotely using VNC, but when it connects, it's just a black screen.

I've tried the following methods, but none have worked:

1. Editing /etc/profile.d and changing this line:

[ "`tty`" = "/dev/tty1" ] && emulationstation

**I've also looked at issue #783 but when I select /etc/profile, I don't have this line echo "[ -n "${SSH_CONNECTION}" ] || emulationstation" as it mentions in that issue**

2. Installing XRDP to access emulationstation via its terminal, and starting it, but I still get a black screen.

Any ideas?

**Comment by cmitu** [comment]
Please use the forum, as asked in the template form, when asking for support and not reporting a bug/error with the RetroPie-Setup script.
