### ISSUE TITLE
uae4arm & drastic issue

### ISSUE THREAD

**Issue by PiXxXoN** [RetroPie/RetroPie-Setup#2664]
I don’t know if this is the right place to post this.

At the moment it's impossible to install 'uae4arm' and 'drastic'.

RetroPie could not install package(s):
'libguichan-dev', 'libmpg123-dev', 'libxml2-dev' (uae4arm)
'patchelf' (drastic)

I hope this can be looked into.

**Comment by joolswills** [comment]
Please open a topic on the forum first as detailed when opening an issue here (providing details of your set-up).
