### ISSUE TITLE
8bitdo the left on the right anlog stick not being seen

### ISSUE THREAD

**Issue by Exarkuniv** [RetroPie/RetroPie-Setup#2667]
https://retropie.org.uk/forum/topic/21369/8bitdo-nes30-pro-bluetooth-controllers-not-registering-right-analog-left-and-right-positions-properly

i have both a FC30 pro, and N30 pro with latest firmware on them

i have done all that i can think of with this but after updating Emulationstation it just will not see the lift when i config the controller, but only when it is android mode. 
this is the mode that as been working with every version before and with version 4.4

if i switch it to pro controller mode it will work. yes i know i can use it that way. i will just need to remember to hold down 2 buttons to turn on the controller instead of one.

**Comment by joolswills** [comment]
>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/
