### ISSUE TITLE
Updating DraStic to 2.5.0.4

### ISSUE THREAD

**Issue by DanTheMan827** [RetroPie/RetroPie-Setup#2669]
There's a Linux version of DraStic 2.5.0.4 that's fully SDL2 and fixes compatibility for games that use the microphone.

Is there any particular reason that this isn't used?

https://github.com/Retro-Arena/binaries/blob/master/odroid-xu4/drastic.tar.gz?raw=true

**Comment by quicksilver7837** [comment]
There have been previous permission issues with distribution of drastic. I'll reach out to exophase (the author of drastic) on the drastic forums and see if he's ok with it.

**Comment by DanTheMan827** [comment]
there's also xperia64

**Comment by quicksilver7837** [comment]
https://drastic-ds.com/viewtopic.php?f=5&t=5610

I made a post on their forums. Lets hope I get a response.

**Comment by robertybob** [comment]
Exophase said yes so that's great news!

**Comment by 2play** [comment]
@quicksilver7837 there was a request also and the devs forum and approved the use of that binary 
See here
https://drastic-ds.com/viewtopic.php?t=5610

**Comment by mrcmunir** [comment]
If someone wants to try it under a pure distribution of aarch64 64bits for some devboards that are based on debian or ubuntu it's possible with multilib 

There workaround drastic run on aarch64

sudo dpkg --add-architecture armhf
sudo apt-get update
sudo apt-get install libc6: armhf libstdc ++ 6:armhf

Install small dependencies 
sudo apt-get install libsdl2-2.0-0:armhf
sudo apt-get install libasound2-plugins:armhf
sudo apt-get install zlib1g: armhf
sudo apt-get install libgtk3-nocsd0:armhf

**Comment by joolswills** [comment]
This version is now included.

**Comment by theofficialgman** [comment]
> If someone wants to try it under a pure distribution of aarch64 64bits for some devboards that are based on debian or ubuntu it's possible with multilib
> 
> There workaround drastic run on aarch64
> 
> sudo dpkg --add-architecture armhf
> sudo apt-get update
> sudo apt-get install libc6:armhf libstdc++6:armhf
> 
> Install small dependencies
> sudo apt-get install libsdl2-2.0-0:armhf
> sudo apt-get install libasound2-plugins:armhf
> sudo apt-get install zlib1g:armhf
> sudo apt-get install libgtk3-nocsd0:armhf

I've been able to follow this to run drastic on the nintendo switch but joystick detection doesn't seem to work. Does drastic even support sdl2 joysticks?

**Comment by jksherk** [comment]
> @mrcmunir
> 
> > If someone wants to try it under a pure distribution of aarch64 64bits for some devboards that are based on debian or ubuntu it's possible with multilib
> > There workaround drastic run on aarch64
> > sudo dpkg --add-architecture armhf
> > sudo apt-get update
> > sudo apt-get install libc6:armhf libstdc++6:armhf
> > Install small dependencies
> > sudo apt-get install libsdl2-2.0-0:armhf
> > sudo apt-get install libasound2-plugins:armhf
> > sudo apt-get install zlib1g:armhf
> > sudo apt-get install libgtk3-nocsd0:armhf
> 
> I've been able to follow this to run drastic on the nintendo switch but joystick detection doesn't seem to work. Does drastic even support sdl2 joysticks?
I follow the step and get an error on    sudo apt-get install libsdl2-2.0-0:armhf
can't install , can you help ,thanks

**Comment by cobalt2727** [comment]
> @mrcmunir
> 
> > If someone wants to try it under a pure distribution of aarch64 64bits for some devboards that are based on debian or ubuntu it's possible with multilib
> > There workaround drastic run on aarch64
> > sudo dpkg --add-architecture armhf
> > sudo apt-get update
> > sudo apt-get install libc6:armhf libstdc++6:armhf
> > Install small dependencies
> > sudo apt-get install libsdl2-2.0-0:armhf
> > sudo apt-get install libasound2-plugins:armhf
> > sudo apt-get install zlib1g:armhf
> > sudo apt-get install libgtk3-nocsd0:armhf
> 
> I've been able to follow this to run drastic on the nintendo switch but joystick detection doesn't seem to work. Does drastic even support sdl2 joysticks?

bump

**Comment by DanTheMan827** [comment]
Drastic supports SDL2 joysticks, but I don't know if it loads gamecontrollerdb.txt at all

It's definitely possible to write a LD_PRELOAD library that loads the gamecontrollerdb.txt though, but that would depend on if drastic even makes use of the gamepad interface or if it uses the joystick interface

**Comment by joolswills** [comment]
@cobalt2727 this issue is closed. Please use the forum for support.
