### ISSUE TITLE
Drastic on Retroarch 1.7.6 on MacOSX

### ISSUE THREAD

**Issue by Kokokool** [RetroPie/RetroPie-Setup#2672]
Sorry guys but, i have Retroarch 1.7.6 on Mac OSX 10.8.5 and i've just updated all cores. Can't find DraStic core, only Desmume y melon DS. can anybody help me on this issue?
Best regards to all of you

**Comment by cmitu** [comment]
Please use the forum - you already have a topic there opened. The issue tracker is for bugs related to the RetroPie Setup script.
