### ISSUE TITLE
EmulationStation (enhancement)

### ISSUE THREAD

**Issue by 2play** [RetroPie/RetroPie-Setup#2706]
(enhancement)
to go to the bottom of the menu in EmulationStation you have to go from top to bottom. 
Can you please eneble aslo to be able to go up at top so it can reach bottom option with one click

its useful when you need to quit/reboot etc option

Tx in advance

**Comment by cmitu** [comment]
You maybe want to add this request to the Emulationstation repository - https://github.com/retropie/Emulationstation - not on the RetroPie-Setup, which merely handles the installation of Emulationstation.

**Comment by 2play** [comment]
Tx @cmitu I will do that
