### ISSUE TITLE
IPAC Mini not working 2Player setup (ESCAPE not working)

### ISSUE THREAD

**Issue by helmar74** [RetroPie/RetroPie-Setup#2707]
Sorry for asking this question, but I'm getting insane ;-)

I have a retropie installation with a IPAC Mini (which is the same as a IPAC2).
I have big difficulties to get a 2 Player setup running.
I read a lot of Wiki postings and in a lot of threads, but didn't found a solution yet.
My problem is the following:
I reseted all of the emulationstation input settings.
Than I restart the system and I'm ask to do a controller setup. As I have no controller connected, I configure my buttons on the IPAC Mini.
Afterwards Player 1 and 2 are working. But the ESCAPE Key isn't working.
I configured in /opt/retropie/configs/all/retroarch.cfg the following:
input_exit_emulator = "escape"

After the restart the same. ESCAPE isn't working within lr-mame2003. It seems, that the configuration I've done is completly ignored.
Is there an other file, or I'm doing something wrong?
Does anybody has such a configuration (no controller, only keyboard and IPAC Mini / IPAC2) running and can provide some information?

Of course I also read:
https://github.com/RetroPie/RetroPie-Setup/wiki/Keyboard-Controllers

Thanks a lot

Helmar

**Comment by joolswills** [comment]
Sorry, but you need to use the forum as detail when opening an issue here.
