### ISSUE TITLE
Caprice32 instead capricerpi

### ISSUE THREAD

**Issue by 2play** [RetroPie/RetroPie-Setup#2709]
hi @joolswills 
If i may suggest, i believe at this time you should include caprice32
https://github.com/ColinPitrat/caprice32 or replace the capricerpi (that hasnt been updated as i can see for the last 4y)
Caprice32 and relative lr core have support to the + models and gx4000 that needed so far advmess to run

Just a kind suggestion

**Comment by joolswills** [comment]
This should be a discussion first on the forum.
