### ISSUE TITLE
USB Controller work on Emulstation but not in Raspi-config or to set up wifi/bluetooth etc... (Using Dualshock 4)

### ISSUE THREAD

**Issue by ApollGama** [RetroPie/RetroPie-Setup#2713]

**Comment by ApollGama** [comment]
The controller works normally on Emulstation anf for room but when I enter the raspi-config setup or any other set up outside emulstation it does not work

**Comment by cmitu** [comment]
Please use the forum for support questions, as explained in the issue template.

**Comment by ApollGama** [comment]
ook
