### ISSUE TITLE
Raspberry Pi 3A+ not work.

### ISSUE THREAD

**Issue by sergiopoverony** [RetroPie/RetroPie-Setup#2723]
Raspberry Pi3A+ not work. On any version. Only Rainbow square and no more
Please make release for support this pi/ Last update abowe 1 year ago

**Comment by hhromic** [comment]
You can use the experimental weekly builds of RetroPie from here:
http://files.retropie.org.uk/images/weekly/

However, next time please use the forum as instructed when you opened this issue.
