### ISSUE TITLE
lr-mame2003-plus doesn't build anymore

### ISSUE THREAD

**Issue by thorias** [RetroPie/RetroPie-Setup#2726]
Hello,

Since yesterday,lr-mame2003-plus doesn't build anymore, from install from source.
It starts download the GIT and build but always end up with a "couldn't find mame2003_plus_libretro.so" then a log is created. It was building fine last Friday 31st May...
Could somebody have a look to see what is going on?

Thank you,

Thorias

**Comment by cmitu** [comment]
Please use the forum - as directed in the template - for support questions.
