### ISSUE TITLE
EmulationStation - PSX - Add .chd & .CHD as Recognized ROM Extensions

### ISSUE THREAD

**Issue by MajorDangerNine** [RetroPie/RetroPie-Setup#2728]
`lr-pcsx-rearmed` now has CHD support as of the following commit:

https://github.com/libretro/pcsx_rearmed/commit/ce188d4d7f3b9ad04867c49b424e8497c2ade92b

Due to this, I think `.chd` and `.CHD` should be recognized ROM extensions in EmulationStation for PSX to improve end-user usage of RetroPie.

I would also suggest rebuilding the binary for `lr-pcsx-rearmed`, but end-users can easily build it from source themselves.

**Comment by cmitu** [comment]
Added the extensions in https://github.com/RetroPie/RetroPie-Setup/pull/2730.

**Comment by MajorDangerNine** [comment]
Ah, sorry. Missed that.
