### ISSUE TITLE
Wiki seems to have been spammed

### ISSUE THREAD

**Issue by carinadigital** [RetroPie/RetroPie-Setup#2735]
People are spamming the wiki pages See https://github.com/retropie/retropie-setup/wiki/RetroPie-Ubuntu-16.04-LTS-x86-Flavor
```
Heroin is amazing`
```
Suggest that wiki editing is locked down. There are bad revisions since 4 Jun 2017, so I don't know if people care about this.

> Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This is probalby better dealt with by github admins than the forums

**Comment by joolswills** [comment]
The issue you referenced is fixed. I am not aware of any other problems with the wiki. happy to look into any further problems you find. We may well move the documentation into a repository so edits can be checked. There is no simple way of just locking down the github wiki unfortunately.
