### ISSUE TITLE
Hori GameCube Battle Pad USB Wired Problem with Sticks

### ISSUE THREAD

**Issue by Solus32** [RetroPie/RetroPie-Setup#2739]
RetroPie v4.4 Detect Hori GameCube Battle Pad USB Wired like: Generic X-Box pad

![hori](https://user-images.githubusercontent.com/27927896/59723193-5b807c80-91eb-11e9-9735-9b54fc4bfe57.png)

Everything works fine; the problem lacks on the Left stick and Right stick only works on Nintendo 64 emulator

If you play Playstation emulator doesnt work, neither snes, nes, gba, all the platforms

And i have a Logitech Gamepad F710 works fine the Left stick and Right stick on all platforms on RetroPie

This is my configuration file of Hori BattlePad on the Archive

/opt/retropie/configs/all/retroarch/autoconfig/Generic X-Box pad.cfg

###########################
###########################

input_device = "Generic X-Box pad"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "9"
input_exit_emulator_btn = "9"
input_r_y_minus_axis = "-3"
input_down_btn = "h0down"
input_l_x_plus_axis = "+0"
input_r_btn = "5"
input_save_state_btn = "5"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_select_btn = "8"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_l2_btn = "6"
input_l3_btn = "11"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_a_btn = "0"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "10"
input_l_y_plus_axis = "+1"
input_r2_btn = "7"
input_r3_btn = "12"
input_x_btn = "2"
input_menu_toggle_btn = "2"
input_l_x_minus_axis = "-0"
input_y_btn = "3"
input_r_x_plus_axis = "+2"

Sorry for my english
Greetings

**Comment by langest** [comment]
Works fine for me.
```
pi@retropie:~ $ cat /opt/retropie/configs/all/retroarch/autoconfig/Generic\ X-Box\ pad.cfg 
input_device = "Generic X-Box pad"
input_driver = "udev"
input_r_y_plus_axis = "+3"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "9"
input_exit_emulator_btn = "9"
input_r_y_minus_axis = "-3"
input_down_btn = "h0down"
input_l_x_plus_axis = "+0"
input_r_btn = "5"
input_save_state_btn = "5"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_select_btn = "8"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_l2_btn = "6"
input_l3_btn = "11"
input_l_y_minus_axis = "-1"
input_up_btn = "h0up"
input_a_btn = "2"
input_b_btn = "0"
input_reset_btn = "0"
input_enable_hotkey_btn = "10"
input_l_y_plus_axis = "+1"
input_r2_btn = "7"
input_r3_btn = "12"
input_x_btn = "3"
input_menu_toggle_btn = "3"
input_l_x_minus_axis = "-0"
input_y_btn = "1"
input_r_x_plus_axis = "+2"
```
