### ISSUE TITLE
USB SNES Controller Config Not Saving

### ISSUE THREAD

**Issue by Salad360** [RetroPie/RetroPie-Setup#2743]
Upon system boot I'm asked to configure the controller as usual, and it works to navigate the menues thereafter. However, when I lunch an SNES rom with any of the included emulators, the controller config vanishes, and upon rebooting I'm asked to configure the controller again. 

If I configure the controller and just reboot without launching a rom, I'm also asked to configure the controller again. 

-kernel info about the controller i'm using-
[  201.128250] usb 1-1.1.2: New USB device found, idVendor=0079, idProduct=0011
[  201.128268] usb 1-1.1.2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  201.128279] usb 1-1.1.2: Product: USB Gamepad 
[  201.133843] input: USB Gamepad  as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/0003:0079:0011.0004/input/input3
[  201.135411] dragonrise 0003:0079:0011.0004: input,hidraw1: USB HID v1.10 Joystick [USB Gamepad ] on usb-3f980000.usb-1.1.2/input0

Note that I have a USB N64 controller that made by the same vendor as this one, and I don't have any issues with it.

Emulation station v2.7.5RP

**Comment by joolswills** [comment]
Please use the forum as detailed when opening an issue.
