### ISSUE TITLE
Raspberry Pi 4 Support?

### ISSUE THREAD

**Issue by raidensnake** [RetroPie/RetroPie-Setup#2745]
Are there any plans on supporting the new Raspberry Pi 4?

**Comment by raidensnake** [comment]
Retropie doesn't compile for the 4 as it's says unknown platform.

**Comment by joolswills** [comment]
It's not. It clearly says to use the forum first when opening an issue - you removed the text but ignored it. Asking about future plans isn't a valid issue.

**Comment by raidensnake** [comment]
I can't access the forums like I said before. My ISP is blocked by the server hosts. Also the text didn't appear on here.
