### ISSUE TITLE
[Need Help] Line 11 /home/pi/retropie/supplementary/EmulationStation/emulationstation: No such file or directory…

### ISSUE THREAD

**Issue by weihan1102** [RetroPie/RetroPie-Setup#276]
Hi,
I have a issue.
I am using raspbian and i use the binaries-based installation
When i try to run "emulationstation" command, i get the error :
Line 11 /home/pi/retropie/supplementary/EmulationStation/emulationstation: No such file or directory…

Any Idea?

Sorry for my english

**Comment by bigbadmayo** [comment]
I've got this same problem. Seems to come from messing with RetroArch and saving games. For whatever reason makes emulationstation fail to load and say that it doesn't have permission. I'm reinstalling it from terminal by:
cd RetroPie-Setup
chmod +x retropie_setup.sh
sudo ./retropie_setup.sh

**Comment by tzsiga** [comment]
@bigbadmayo did you managed to solve the problem with the reinstall?

I'm getting the same issue after upgrading from jessie to stretch. ES cannot start, complaining about `libboost_system.so`.

I followed the following guide:
https://retropie.org.uk/forum/topic/16145/retropie-upgrading-raspbian-jessie-to-stretch

**Comment by joolswills** [comment]
This ticket is very old. Please use the forum for help

**Comment by tzsiga** [comment]
@joolswills thanks for the rapid update, I will do that!

**Comment by bigbadmayo** [comment]
For what its worth, I recall reinstalling the OS fixed the issue.
