### ISSUE TITLE
incorrect filename reference in RetroPie-Setup/scriptmodules/ports/dxx-rebirth.sh 

### ISSUE THREAD

**Issue by c0d3h4x0r** [RetroPie/RetroPie-Setup#2762]
Updating dxx-descent from source always fails near the end because this script erroneously tries to move two files named `README.txt`, which do not exist.  The actual filenames produced by the build are `README.RPi`, not `README.txt`.

**Comment by hhromic** [comment]
Why not directly provide a PR with the fix? :)

**Comment by joolswills** [comment]
They removed the old readme files. I will adjust.

**Comment by c0d3h4x0r** [comment]
> Why not directly provide a PR with the fix? :)

Because git is the most user-hostile VCS I’ve ever had the displeasure of using.

**Comment by hhromic** [comment]
Sorry to hear that, for me is a complete opposite experience.
Anyway the issue should be fixed now, thanks for reporting!

**Comment by c0d3h4x0r** [comment]
To be completely fair, it's more GitHub's particular way of using git that infuriates me.  They don't make it easy or obvious how to take changes you've locally committed a clone of a project and somehow convert them to a commit on branch on a fork of a project (which is apparently what's required to create properly-formed pull request).

Indeed, I'm glad it's fixed!
