### ISSUE TITLE
problem with ps3 controler on retropie. ubuntu 

### ISSUE THREAD

**Issue by iraklis777** [RetroPie/RetroPie-Setup#2784]
good evening 

i decided to build an arcade pc with ubuntu 19.04 and retropie. 
i install everything with no problem 
my system is ubuntu 19.04 
and retropie 4.5 
a logic3 bluetooth dongle 
and a sony ds3 controller. 

the  problem is that despite my sony ds3 controller synced properly and connected immidiatelly  to the bluetooth dongle , retropie refuse to see it. 
 i tried with sixaxis driver but no luck. 
when i tried with ps3 driver,  controller synced to retropie but turned  off  immidiately. 
i tried to register via bluetooth  setting on retropie settings , nothing. 
i tried with ubuntu 18.04 
with mint 18
with mint 16 
always the same result. 
controller was synced to dongle but retropie ignores it

the same controller on 4.3 script and mint 18 was working flawlessly. 
any help will be appreciate

**Comment by cmitu** [comment]
Please use the forum as directed in the issue template - the issue tracker is for bug reporting and not for user support. Thank you.
