### ISSUE TITLE
Error initializing SDL while using A/V Jack

### ISSUE THREAD

**Issue by COOLIRON2311** [RetroPie/RetroPie-Setup#2801]
Everything works fine when Pi is using HDMI output.
However, this error occurs when it's using the A/V jack output: 
```
lvl0:   Error initializing SDL!

lvl0:   Renderer failed to initialize!
lvl0:   Window failed to initialize!
```

Firmware: 6c3fe3f096a93de3b34252ad98cdccadeb534be2
Kernel: 4.19.57-v7+

**Comment by joolswills** [comment]
Please use the forum as requested.

**Comment by COOLIRON2311** [comment]
I did. 0 replies in 24 hours.

**Comment by joolswills** [comment]
Well this isn't our job. Please be patient.

**Comment by joolswills** [comment]
You likely didn't get a reply as you didn't provide any details of your setup as requested when registering on the forum. Eg retropie version. I have replied to your post.

**Comment by Jackowski3k** [comment]
> 

whats the point of github issues then?
