### ISSUE TITLE
PS3 Controller - Phantom Movements

### ISSUE THREAD

**Issue by ratedrguy** [RetroPie/RetroPie-Setup#2802]
After running the latest update to retropie, automatic phantom button pushing is occurring with any ps3 controller paired with onboard Bluetooth.  

Problem occurs within ES menu.

Problem occurs when installing the ps3driver or pairing it manually.

The problem does not exist when connecting the ps3 controllers via USB cable (wired).

**Comment by joolswills** [comment]
Please start a topic on the forum first (and provide details of set up as detailed when registering). Thanks.
