### ISSUE TITLE
OpenMSX RetroPie Setup - Script break emulator install

### ISSUE THREAD

**Issue by 2play** [RetroPie/RetroPie-Setup#2822]
When i updated from binary **or** source on a pi3 it deletes all **except** the share folder in the
/opt/retropie/emulators/openmsx/
binary etc all gone /opt/retropie/emulators/openmsx/bin/openmsx

Same today! It seems the scriptmodule is messed up
![image](https://user-images.githubusercontent.com/30235736/63760478-aab7ed00-c8bf-11e9-8b8e-09dcd5b92230.png)

**Comment by cmitu** [comment]
Can you please provide a source install log - post the log to pastebin.com.

**Comment by joolswills** [comment]
The openmsx binaries need rebuilding as they are faulty - I will do that (and will be able to confirm if the source install is ok or not)

**Comment by joolswills** [comment]
I will also add a build check to the code, as it doesn't have one (which is why no error occurred when building the binaries).

**Comment by cmitu** [comment]
I tested the build when changing the module and it was fine, retested today on PI4 and PC and still works.The only thing is the memory requirements - if they're changed (higher) recently, source install might fail. 

I can amend the module with a binary check in the `_build` part.

**Comment by joolswills** [comment]
I've already done it. Just testing.

**Comment by joolswills** [comment]
It wouldn't be memory requirements since I build in a chroot with plenty of ram on the host system. I will sort this.

**Comment by 2play** [comment]
tx for checking gents!

**Comment by joolswills** [comment]
The binaries should be sorted now if you want to retry that @2play. It may have failed building from source for @2play due to running out of memory (A log would be needed to confirm). I may force it to -j1 for the RPI as it struggles even with lots of additional swap. There was also a missing dependency for alsa. I will commit the module fixes later.

**Comment by 2play** [comment]
@joolswills 
Thank you. I tested from binary and all good as it seems! on below setup/script

![image](https://user-images.githubusercontent.com/30235736/63841513-39da0900-c983-11e9-94c5-205ceca5f310.png)

**Comment by joolswills** [comment]
What would help would be a log (not an image), from building from source as requested earlier. logs are compressed and saved in `~/RetroPie-Setup/logs` and can be accessed over SSH etc.

**Comment by 2play** [comment]
I used binary. 
i can run the source and send logs.  I deleted the img that had the failed one. But I can retest on it and revert as I have a backup

**Comment by cmitu** [comment]
> From Source before it seems once compiled to do the same steps as posted on my first post.

No, it's not - source install always compiles the package - the screenshot you posted is from a binary install. Please add a log from a source install, as @joolswills explained.

**Comment by 2play** [comment]
@cmitu 
i heard and read that but you seem not reading mine. 
yes it is from binary. If you read my txt above that source compiled and at the end did the same to the emulators folder. 
after cleaning all it left ONLY share folder again.
Im just stating the result before when i tried both.
I will test on the img that i was trying to update yesterday and happily post logs for your checking.
but maybe the new updated scriptmodule is ok and wont replicate my yesterday error.

reverting

**Comment by joolswills** [comment]
I've not yet updated the script module.

**Comment by 2play** [comment]
ok will retry on the previous img. to be frank i tried also yesterday no latest clean retropie base 4.5.1, updated the script and installed from binary with same result.
installed today a new retropie setup to a clean raspbian and after your last message i tried from binary and went ok.
so this is my full feedback and actions taken so far.
retesting from source on my own img as promised and reverting with results @joolswills

**Comment by joolswills** [comment]
I reproduced an out of memory error on a rpi3 even with rpSwapOn 1500. 2000 seemed to be ok. Was very slow though due to the swapping.

**Comment by 2play** [comment]
hi @joolswills 
finally finished compiling after 2h 
[rps_2019-08-28_151605.log.gz](https://github.com/RetroPie/RetroPie-Setup/files/3552187/rps_2019-08-28_151605.log.gz)
on my img that had probs yesterday when i posted.
finished without failing BUT it left only a share folder in the emulators/openmsx folder
like yesterday

Clean boot, all default...
Here is the script

**Comment by 2play** [comment]
![image](https://user-images.githubusercontent.com/30235736/63879419-fc4d9e00-c9cb-11e9-9dc2-51bec7bc65a0.png)

rather right after from binary

![image](https://user-images.githubusercontent.com/30235736/63879636-69f9ca00-c9cc-11e9-8b44-6c2702992631.png)

**Comment by 2play** [comment]
[rps_2019-08-28_174324.log.gz](https://github.com/RetroPie/RetroPie-Setup/files/3552217/rps_2019-08-28_174324.log.gz)
log from binary just afterwards

**Comment by joolswills** [comment]
Was an out of memory issue. Should be sorted now but needs a lot of ram.

**Comment by joolswills** [comment]
I didn't work out why the binaries were broken but I suspect it could have been due to just not having rebuilt them after @mitu fixed up openmsx previously.
