### ISSUE TITLE
After Buster migration  /dev/ttyACM0 no longer exists

### ISSUE THREAD

**Issue by jbirdlebough** [RetroPie/RetroPie-Setup#2824]
migrated strectch to buster on RPI3 where /dev/ttyACM0 was working prior to buster, then installed SD on RPI4 x4GB, everything works but..  ls -l /dev/t* shows /dev/ttyAMA0 and USB0 but not the required /dev/ttyACM0 needed by an app which I have no source to recompile.

Tried all kinds of things but no joy.

What is needed to get RPI4 on buster setup for a /dev/ttyACM0 device?

Appreciate any help, J

**Comment by joolswills** [comment]
This isn't a RetroPie issue. Feel free to use our forum, but you may be better off asking on the raspberry pi official forums.
