### ISSUE TITLE
Cannot install or update Splitwolf from source

### ISSUE THREAD

**Issue by tacgnol3** [RetroPie/RetroPie-Setup#2826]
I cannot install or update Splitwolf from source

It's reporting an error ..

Error running 'git clone --recursive --branch master https://bitbucket.org/linuxwolf6/splitwolf.git /home/pi/Retropie-Setup/tmp/build/splitwolf' returned 128

I can install it from binary without issue.

other apps are installing fine from source.

**Comment by joolswills** [comment]
This should be fixed now by @cmitu
