### ISSUE TITLE
Quake3 mouse lag on quake3 port

### ISSUE THREAD

**Issue by drduker** [RetroPie/RetroPie-Setup#2833]
Forum posts doesn't like my tags...

Using on a raspberry pi 4.  Installed retropi but installed as raspberry pi 3b+ in install script.
My mouse has no lag on the desktop.  Quake3 is useless as a port within retropi if the mouse lag time is so terrible!

**Comment by cmitu** [comment]
RPI4 is not yet fully supported - see https://github.com/RetroPie/RetroPie-Setup/issues/2749.
