### ISSUE TITLE
Ask GitHub account after update

### ISSUE THREAD

**Issue by friishon** [RetroPie/RetroPie-Setup#2835]
After update the retropie i have this problem, retropie ask me for a GitHub account...
What have i to do? 
![IMG_20190907_220446_914](https://user-images.githubusercontent.com/19889173/64481700-4dd30580-d1e2-11e9-9462-e52281d9f674.jpg)

**Comment by joolswills** [comment]
Update retropie-setup script. Please use the forum for support first as directed when opening an issue.

**Comment by joolswills** [comment]
If you are sure your system is updated, you may have to remove and reinstall retropie manager as the repository changed.
