### ISSUE TITLE
Odroid RetroPie N64 lagging or not working

### ISSUE THREAD

**Issue by tobeytrout** [RetroPie/RetroPie-Setup#2874]
Hi, looking for some advice. I'm a rookie with no programming experience. All I can do is follow instructions, and sometimes those go over my head.
A couple years ago I built a Raspberry Pi with Retropie, but wanted more power, especially for n64. So I'm building an odroid xu4 with RetroPie (via Odroid Retro Arena). I already asked them this issue, and they couldn't figure it out and said to start a new issue here.
After writing ORA's image to my 128gb micro SD card, I transferred over my old bios and roms and it works pretty well. About half the n64 roms I've tried don't work well. Issues with lagging or I just can't see anything. Roms like Mario Tennis, NBA Hangtime, Donald Duck Goin' Quackers, Yoshi's Story, and others are virtually unplayable.
I've tried different emulators, that didn't help. I've checked the backgroundsmode to make sure it's "stripped", I've adjusted resolution, I've deleted the roms and replaced them with new roms and have the same issues.
It's probably either the emulator or an issue with my bios (is that possible?) that I transferred over. Any advice?
Is the power just too weak...do I need to get a nvidia shield?
Thanks in advance,
Tobs

**Comment by joolswills** [comment]
Please use the retropie forum for help with retropie as detailed when opened an issue. We don't support retro arena images though
