### ISSUE TITLE
Debian Stretch install and libc6

### ISSUE THREAD

**Issue by paulmorabito** [RetroPie/RetroPie-Setup#2895]
I'm trying to install RetroPie in a Debian Stretch container on my Chromebook and I get the following iddue with libc6 version:

```
paul@penguin:~/RetroPie-Setup$ sudo ./retropie_setup.sh
Did not find needed package(s): gcc g++ build-essential python-pyudev. I am trying to install them now.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
 g++ : Depends: g++-6 (>= 6.3.0-9~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Unable to install packages required by /home/paul/RetroPie-Setup/retropie_packages.sh - Could not install package(s): gcc g++ build-essential python-pyudev.
```

The current version in Stretch is 2.24-11+deb9u4.  It looks like I need 2.29-2 however, I would need to go to testing branch. Installing only libc6 from here is likely to cause other problems, being relied upon by many other packages in the system.

Is there any way to install without moving to testing branch fully?

**Comment by joolswills** [comment]
This looks like an issue with your system rather than retropie due to package source etc. But you need to start a topic on the forum first as detailed when opening an issue. Thanks.
