### ISSUE TITLE
RetroArch broken after updating Retropie setup script(to 4.5.7) and RA from binary

### ISSUE THREAD

**Issue by jackboa82** [RetroPie/RetroPie-Setup#2944]
Good day All,
After an update of Retropie Setup Script (to ver. 4.5.7) , I have an issue with Retroarch (after update from 1.7.6 to 1.8.2) I can not load any emulator. Log says : "No sg devices found and sg kernel module is not loaded after update". 
After setup script update, I have updated core packages (from binary). Tried to reinstall from both binary or source, and nothing helps.
I have gone back to my backup, did the same thing after couple of days, and result is exactly the same.
Can not launch RA at all.
Can you please recommend, where I can start to fix. I can work on my Backed up version (with RA 1.7.6) but obviously I would like to have a chance to update packages to latest version.
Any suport on where to start digging would be much appreciated.

**Comment by joolswills** [comment]
Please use the forum as requested.
