### ISSUE TITLE
Help! Got this screen after a shutdown 

### ISSUE THREAD

**Issue by Shawn1982x** [RetroPie/RetroPie-Setup#2947]
![15781159868003971228793537054691](https://user-images.githubusercontent.com/59495922/71760321-db212080-2e89-11ea-955e-2bc37d9961cb.jpg)
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.

**Comment by joolswills** [comment]
Use the forum.
