### ISSUE TITLE
Unable to build on RPi 4 from master

### ISSUE THREAD

**Issue by Nidrax** [RetroPie/RetroPie-Setup#2955]
Running install script from fkms_rpi4 branch you get the warning: `You are running on the development fkms_rpi4 branch which is now merged into master and will be deleted soon - you should switch back to the master branch.` but it's impossible to build on RPi4 from **master** due to issues with sdl2.

During instalation of emulationstation I get `unable to install binary for sdl 2` error when the script tries to fetch **libsdl2-2.0-0_2.0.10+3rpi_armhf.deb**.

**Comment by joolswills** [comment]
Use the forum as requested when opening an issue. Thanks.
