### ISSUE TITLE
Empty terminal on loading rom - pi 4

### ISSUE THREAD

**Issue by jambo2020** [RetroPie/RetroPie-Setup#2956]
Every time I load I rom, regardless of emulator, my desktop is shown, a terminal pops up with no text or errors, then my splash screen will load up and the rom works like normal.

Any ideas? I'm running on a pi 4 so is this the reason?

**Comment by cmitu** [comment]
Please use the forum as explained in the issue - the issue tracker is not for support questions.
NOTE: as noted in the 1st issue, PI4 support is a work in progress, so some things might not work.
