### ISSUE TITLE
Did not find needed package(s), could not install packages in ubuntu mate 19.10 eoan

### ISSUE THREAD

**Issue by engrpanda** [RetroPie/RetroPie-Setup#2971]
1.) log of emulation station
Log started at: Sun 02 Feb 2020 05:30:38 PM PST

RetroPie-Setup version: 4.5.12 (d2344c3)
System: Ubuntu 19.10 - Linux panda 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'emulationstation' : EmulationStation - Frontend used by RetroPie for launching emulators
= = = = = = = = = = = = = = = = = = = = =

Did not find needed package(s): cmake libsdl2-dev libsm-dev libvlc-dev libvlccore-dev rapidjson-dev gnome-terminal. I am trying to install them now.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsdl2-dev : Depends: libudev-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Could not install package(s): cmake libsdl2-dev libsm-dev libvlc-dev libvlccore-dev rapidjson-dev gnome-terminal.

Log ended at: Sun 02 Feb 2020 05:30:41 PM PST
Total running time: 0 hours, 0 mins, 3 secs
_______________________________________________________________
2.)log of retro arch
Log started at: Sun 02 Feb 2020 05:29:31 PM PST

RetroPie-Setup version: 4.5.12 (d2344c3)
System: Ubuntu 19.10 - Linux panda 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'retroarch' : RetroArch - frontend to the libretro emulator cores - required by all lr-* emulators
= = = = = = = = = = = = = = = = = = = = =

Did not find needed package(s): libudev-dev libxkbcommon-dev libsdl2-dev libusb-1.0-0-dev libpulse-dev libavcodec-dev libavformat-dev libavdevice-dev. I am trying to install them now.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libudev-dev : Depends: libudev1 (= 242-7ubuntu3) but 242-7ubuntu3.2 is to be installed
E: Unable to correct problems, you have held broken packages.
Could not install package(s): libudev-dev libxkbcommon-dev libsdl2-dev libusb-1.0-0-dev libpulse-dev libavcodec-dev libavformat-dev libavdevice-dev.

Log ended at: Sun 02 Feb 2020 05:29:34 PM PST
Total running time: 0 hours, 0 mins, 3 secs

**Comment by joolswills** [comment]
Please use the forum as directed when opening an issue.
