### ISSUE TITLE
Xpad xbox 360 disconnects when exiting retroarch

### ISSUE THREAD

**Issue by Vinnie881** [RetroPie/RetroPie-Setup#2995]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

This includes edit suggestions for the wiki. There are more people to help on the forum.

Once a problem has been verified on the forum, an issue can be opened here.

Please remove this text before posting.

**Comment by joolswills** [comment]
Please use the forum as detailed.

**Comment by Vinnie881** [comment]
When i exit from from a rom back to emulationstation the controller disconnects then will not reconnect fully until i unplug and replugnin receiver.  It seems like the xpad driver is foing something when the current program changes.  Anyway to fix this?
