### ISSUE TITLE
Drastic Bug with screen

### ISSUE THREAD

**Issue by T0biasCZe** [RetroPie/RetroPie-Setup#3004]
Hello, drastic DS emu on RPi3B doesnt start when HDMI isnt connected, but when connected, both HDMI monitors and mini screen connected with GPIO works
[Video](https://youtu.be/5H7dTuEL1kA)

**Comment by cmitu** [comment]
Please use the forum, as directed in the issue template, as this is not a RetroPie-Setup bug.
