### ISSUE TITLE
installation script for reicast pulls from the now-abandoned master branch

### ISSUE THREAD

**Issue by mulcahey** [RetroPie/RetroPie-Setup#3009]
I'm in conversation with a reicast contributor, who confirmed that the reicast master branch is abandoned, and is only kept for historical reasons.  RetroPie-Setup should now pull from the alpha branch.

**Comment by cmitu** [comment]
Thank you for the information, but can you please use the forum for questions/suggestions/support issues in the future ?

**Comment by mulcahey** [comment]
Issue closed, but I already did mention this in the forum (just maybe not as clearly as I did here).  Also it's not a suggestion/question/support request.. it's a defect report, because (according to at least one contributor to reicast) you're pulling from an abandoned branch.
