### ISSUE TITLE
Splitwolf no longer builds due to removed repository 

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#3017]
https://github.com/gabomdq/SDL_GameControllerDB which is used as a submodule has been removed.

https://bitbucket.org/linuxwolf6/splitwolf/issues/32/git-submodule-sdl_gamecontrollerdb-is-no

**Comment by hhromic** [comment]
@joolswills just as a heads-up, the upstream SDL GameControllerDB repository is now restored and working again. So probably this is no longer an issue.

**Comment by quicksilver7837** [comment]
Would it be possible to add this script module back again? I would be glad to test it out to confirm it works again.

**Comment by joolswills** [comment]
Done.

**Comment by lazd** [comment]
@DoomJedi might be related to this, but sounds like this was fixed.

**Comment by DoomJedi** [comment]
Okay, thank you. Might need to update retropie setup...
