### ISSUE TITLE
lr-atari800 could not be build on ubuntu 18.04 headless

### ISSUE THREAD

**Issue by uwe42** [RetroPie/RetroPie-Setup#3027]
While perfoming a fresh install the atari800 build step fails and stops the rest of the installation.

`Could not sucssessfully build lr-atari800 [...] ~/RetroPie-setup/tmp/build/lr-atari800/atari800_libretro.so not found`

System: x86
OS: ubuntu 18.04 server

**Comment by joolswills** [comment]
Need a log from the build. Also please use the forum first as detailed when opening an issue.

**Comment by joolswills** [comment]
Should be ok now. Was an upstream commit causing the issue which has been reverted (not a retropie bug). Use the forum if you have further issues.
