### ISSUE TITLE
Emulationstation faild to start on ubuntu 18.04 server

### ISSUE THREAD

**Issue by uwe42** [RetroPie/RetroPie-Setup#3028]
I followed this guide: https://retropie.org.uk/docs/Debian/

starting emulationstation results in:

```
lvl0: 	Error creating SDL window!
	        No available video device
lvl0: 	Renderer failed to initialize!
lvl0: 	Window failed to initialize!
```

System: x86
OS: ubuntu 18.04 server

**Comment by uwe42** [comment]
maybe related to https://github.com/RetroPie/RetroPie-Setup/issues/3027

**Comment by joolswills** [comment]
Please use the forum first.
