### ISSUE TITLE
Asking for retropie login on boot? (after update)

### ISSUE THREAD

**Issue by BrunnaMaiaradaSilva** [RetroPie/RetroPie-Setup#3035]
just updated my retropie through retropie setup 'update'.
all went fine.
rebooted and it loads up the splash then goes to a login screen?
it says:

Raspbian GNU/Linux 9 retropie ttyl
retropie login:
password:

FYI: It wont let you type anything in the password section.

**Comment by cmitu** [comment]
Please use the forum for support questions. 
FWIW, this is covered in the [Docs](https://retropie.org.uk/docs/FAQ/#why-emulationstation-doesnt-start-automatically-after-an-update).
