### ISSUE TITLE
bashwelcometweak.sh affecting sftp & network connection. pi4 & pi3

### ISSUE THREAD

**Issue by 2play** [RetroPie/RetroPie-Setup#3036]
Good day to all.
I have been testing clean installs on pi4 and pi3 and the last couple days after updating to latest script and apply **bashwelcometweak.sh** script 
- pi4 becomes "slow" and "clogged/unresponsive" 
- the ftp connections over sftp and especially with `sudo -s  /usr/lib/sftp-server` 
wont connect, or if connected it will keep disconnecting and in general network connection becomes  messed.

If removed on pi3 seems to fix it. But on pi4 not.

Above take place with manual install guide.

**Comment by cmitu** [comment]
Please use the forum for support questions, as directed in the template.
