### ISSUE TITLE
broken lr-vice build

### ISSUE THREAD

**Issue by valerino** [RetroPie/RetroPie-Setup#3115]
hi,
in latest 4.6 release lr-vice build from source is broken, due to changes in vice-libretro repo itself (they just changed Makefile filename).

fix is easy, you can [cherry-pick from my fork](https://github.com/valerino/RetroPie-Setup/commit/6871f3e194f5ca8c0fc97a7701e147377b63d705).

**Comment by cmitu** [comment]
Fixed by https://github.com/RetroPie/RetroPie-Setup/commit/e521bf6b1cac58138d601b3fabff9c44f0370b3f.
