### ISSUE TITLE
BOX86 support!!!

### ISSUE THREAD

**Issue by Askmewho** [RetroPie/RetroPie-Setup#3117]
Hi guys!! now than retropie use mesa you should add BOX86 as an experimental package (also an updater from source as usual bc it's on heavy development)
I have several tests on this emulator and it's getting better and better.

[](url)https://www.youtube.com/watch?v=xW6irIWN-Nk&t=222s

[](url)https://www.youtube.com/watch?v=gSK9zbl9MyI&t=1719s

and an all list here

[](url)https://www.youtube.com/watch?v=gSK9zbl9MyI&list=PLhgmBihZpcBxWacPE05P-tN_ZuPBy8cxh

retropie should be able to shutdown emulation station and start an x session for the targeted game and went back when the game exit.

also, you may add gl4es (needed for some games).. but eventually mesa willl support s3tc decompression, they are on it (at least they said that to me)

github referrences

https://github.com/ptitSeb/box86

https://github.com/ptitSeb/gl4es

we dont need gl4es to get 2.1 gl profile, just bc it support s3tc soft decompression.

**Comment by Dagnillo** [comment]
I agree, would love to see this added

**Comment by Askmewho** [comment]
Box86 seems to run great on wayland too. So the non x11 should not be an obstacle to have it on retropie.

**Comment by Askmewho** [comment]
Box86 running on wayland on rk3399

https://youtu.be/a1NFvm22wFI

**Comment by Askmewho** [comment]
I tested weston on retropie official beta image with box86 and it's running great aside major glitches on full screen, something it's wrong on mesa upstream or weston package.

**Comment by cmitu** [comment]
@Askmewho Please don't use this issue tracker as a forum. If you wish to discuss this more, use the forum or submit a PR.
