### ISSUE TITLE
Display flickers after install retropie 4.6 rpi4

### ISSUE THREAD

**Issue by FelixSauer** [RetroPie/RetroPie-Setup#3120]
Hello, everyone,

I have the following error.
After a new installation of retropie-buster-4.6-rpi4.img.gz, retropie starts well until the first input via controller. After that the GUI starts to flicker!

Anyone got a hint?

**Comment by cmitu** [comment]
Please use the forum, as directed in the issue template. Make sure you look/search for existing topics before opening a new topic.
