### ISSUE TITLE
Wiimote Nunchuk Axis not working

### ISSUE THREAD

**Issue by awesomecoder3000** [RetroPie/RetroPie-Setup#3122]
Version: RetroPie 4.6
Device: Raspberry Pi 3 B+
Issue: Hello, when I run the steps in the RetroPie docs and GitHub wiki for connecting WiiMotes and Nunchuks, all the buttons work, except the Nunchuk axis stick, I have tried all the options and some other options and after everything, the axis still isn’t working with RetroPie.

**Comment by cmitu** [comment]
Please use the forum for support questions, as indicated in the template.
You've already had a topic opened there, there's no need to open an issue.
