### ISSUE TITLE
lr-flycast problem with Star Wars Episode 1 - Racer

### ISSUE THREAD

**Issue by Retro1968** [RetroPie/RetroPie-Setup#3128]
Raspberry Pi 4 with RetroPie 4.6

If i start "Star Wars Episode 1 - Racer" (Dreamcast) with the emulator "lr-flycast", the "Start Button" works correctly to break the intro and to break the next intro sequence. But when the screen comes that says "PRESS START BUTTON" to start the race and i press it nothing goes further..

If i use the emulator "redream" instead, i have no issues, so the romfiles are ok.

Is it possible to fix that?

Cheers
Retro1968

**Comment by joolswills** [comment]
Please use the forum.
