### ISSUE TITLE
Adding a reset input for both retroarch and emulationstation on retropie emulationstation

### ISSUE THREAD

**Issue by Askmewho** [RetroPie/RetroPie-Setup#3146]
Many user doesn't know than emulationstation and retroarch use different input configurations. And sometimes does create conflicts if you have one for emulationstation abd other for retroarch. It's time to add and useful and clean way to do that instead of creating more unnecessary threads bc of that situations. We have the retropie setup option managing the packages. But it would be really useful a reset option for inputs for both from emulationstation.

**Comment by joolswills** [comment]
Please use the forum as requested when opening an issue.
