### ISSUE TITLE
Problem with usb stick retropie 4.6 pi4

### ISSUE THREAD

**Issue by DonPanse** [RetroPie/RetroPie-Setup#3149]
Hi i have a problem with my retropie. When i use a usb stick For the games.
Come this on the pictures.

Now i install retropie again. Without load games on usb stick.

![06EFCD70-E64E-43B9-8D06-7CC73180B7A0](https://user-images.githubusercontent.com/63316300/82423293-df8a5680-9a83-11ea-9f2b-529d7a8a0a08.jpeg)

**Comment by cmitu** [comment]
Please use the forum for support question, as instructed in the issue template.
