### ISSUE TITLE
USB Error 71 on USB Gamepad

### ISSUE THREAD

**Issue by idemiq** [RetroPie/RetroPie-Setup#3217]
Following a clean installation of the Retropie 4.6 (Pi4) image (md5: 9154d998cba5219ddf23de46d8845f6c) an error is logged to the console at startup which reads:

"usb 1-1.3: device not accepting address 3, error -71"

This occurs when certain gamepads are connected, in this case; a [RetroFlag Classic USB Gamepad](http://retroflag.com/Classic-USB-Controller-J.html).

This occurs whether-or-not other devices are connected, and regardless of physical port assignment.

**Comment by cmitu** [comment]
Please use the forum for support questions - as directed in the issue template.
The error you mention is not from RetroPie, but from the Linux kernel, so there's nothing in RetroPie-Setup that could fix it.
