### ISSUE TITLE
MAME (experimental) fails to compile on Ubuntu 20.04 mini/server

### ISSUE THREAD

**Issue by johnodon** [RetroPie/RetroPie-Setup#3228]
Ubuntu 18.04 works as expected.  20.04 no longer has python in the path.

RP v4.6.7 

= = = = = = = = = = = = = = = = = = = = =
Building 'mame' : MAME emulator
= = = = = = = = = = = = = = = = = = = = =

Removing additional swap
Adding 5075 MB of additional swap
Setting up swapspace version 1, size = 5 GiB (5321519104 bytes)
no label, UUID=a9d782a2-e629-4f3d-927e-4d78db137903
swapon: /home/pi/RetroPie-Setup/tmp/swap: swapon failed: Invalid argument
GCC 9 detected
makefile:1032: *** Python is not available in path.  Stop.
strip: 'mame64': No such file
Removing additional swap
/home/pi
Could not successfully build mame - MAME emulator (/home/pi/RetroPie-Setup/tmp/build/mame/mame64 not found).

**Comment by joolswills** [comment]
Please use the forum first as detailed when opening an issue.

Python is usually in the path, so I don't think this is a retropie issue. Builds ok here on my x86_64 system with Ubuntu 20.04. Please provide details of system when you post on the forum (check the pinned topics). 

Thanks.

**Comment by joolswills** [comment]
Actually this has been reported on the forum and is a known issue. Technically upstream needs a fix, but I believe @cmitu will submit a PR..

**Comment by XD3l** [comment]
Unsubcribe

**Comment by hifihedgehog** [comment]
As of today, I am still getting this error in a fresh and fully updated install of Ubuntu 20.04.
