### ISSUE TITLE
lr-mame 2010 broken .7z support

### ISSUE THREAD

**Issue by millansoft** [RetroPie/RetroPie-Setup#3231]
While the wiki states that lr-mame2010 supports 7z format, there is somekind of problem about it as stated in the following:

https://retropie.org.uk/forum/topic/27920/lr-mame-2010-and-7z-format

**Comment by cmitu** [comment]
Answered in the forum topic (7zip archives are not supported), no need for an additional issue. 
You can open an issue upstream and ask them to correct the `.info` file for the core.
