### ISSUE TITLE
What APT packages are installed when I run this?

### ISSUE THREAD

**Issue by Botspot** [RetroPie/RetroPie-Setup#3235]
TL;DR on a stock Raspbian system, what APT packages will be installed when I install retropie? Is there a list of all of them somewhere?

I plan to add RetroPie to an app store I am making.
The app store is supposed to manage which apt packages each app installs, so when you uninstall them the app store can remove unnecessary packages.
Is there a centralized place I can look to get this installed package list? Or will finding all of them them take some serious effort?

**Comment by cmitu** [comment]
Each module in RetroPie has a [_depends](https://github.com/RetroPie/RetroPie-Setup/blob/0ce9f214a142f87251e51d2c5c6d2bee1c28b79f/scriptmodules/emulators/pcsx-rearmed.sh#L20) function that installs the dependencies for that scriptmodule and this is where the packages are listed. Note that some of the packages have a dynamic list of dependencies, depending on the installation platform (Pi, PC, Odroid, etc.).

For support questions, please use the forum, not the issue tracker - as indicated in the issue template.
