### ISSUE TITLE
RetroArch doesn't save changed values that are already set in an included config

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#3249]
See https://retropie.org.uk/forum/topic/28346/configuration-via-rgui-partly-broken

If we have a custom config with

```
#include /opt/retropie/configs/all/retroarch.cfg
```

changing an option that is set in the config above in RGUI and using "Save current configuration" from RGUI will not save anything.

Bisected to https://github.com/libretro/RetroArch/pull/10524/commits/9eb84728050eb3ba371fd5af9c872ae1c577501b

For now I am going to revert this commit from v1.8.8, but will need revisiting for a proper fix (and a bug report submitted upstream)

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/3250

**Comment by Brunnis** [comment]
@joolswills I took the liberty of submitting an issue for this upstream: https://github.com/libretro/RetroArch/issues/11515

**Comment by joolswills** [comment]
Appreciated. Thanks.

**Comment by joolswills** [comment]
Just to update this - it was resolved in https://github.com/libretro/RetroArch/pull/11540 and will be part of Retroarch v1.9.1
