### ISSUE TITLE
Controls not working for lr-pcsx-rearmed

### ISSUE THREAD

**Issue by bxyanks52** [RetroPie/RetroPie-Setup#3267]
I was playing PSX earlier today and it was working.  I just updated retropie and the underlying OS’ and now the controls are not working. I had a saved game for Tomb Raider and when I load where I left off, it says there is no controller. If I start any PSX game from scratch, controls don’t work.  However, hot keys still work and it’s only pcsx-rearmed where I’m having the issue. Other emulators work fine. Any help would be much appreciative.

**Comment by cmitu** [comment]
Please use the forum for support questions, as specified in the issue template.
The problem was already reported there and has a solution - https://retropie.org.uk/forum/topic/28702/.
