### ISSUE TITLE
Retroarch configuration problem

### ISSUE THREAD

**Issue by jhdgghost** [RetroPie/RetroPie-Setup#3275]
Hello,

From short time ago i have this message at the when i updated retropie in last updated version of Retropie in my rpi with last updated setup

Error running 'git checkout rpi' - returned 128
Error running 'git pull' - returned 128
Error running 'git submodule update --init --recursive' - returned 128

In the log indicate that the problem is retroarch

= = = = = = = = = = = = = = = = = = = = =
Configuring 'retroarch' : RetroArch - frontend to the libretro emulator cores - required by all lr-* emulators
= = = = = = = = = = = = = = = = = = = = =

fatal: not a git repository (or any of the parent directories): .git

The error appears in binary and source. I remove and reinstall and delete any previous source.

Retroarch is at 1.8.8 version in my rpi4.

[rps_2020-12-19_183236.txt](https://github.com/RetroPie/RetroPie-Setup/files/5720387/rps_2020-12-19_183236.txt)

**Comment by cmitu** [comment]
Please use the forum for support questions, as indicated in the issue template.
