### ISSUE TITLE
es-themes: Retrorama turbo

### ISSUE THREAD

**Issue by lipebello** [RetroPie/RetroPie-Setup#3277]
Please add my theme redesign on retropie setup, so people can install it
https://github.com/lipebello/es-theme-retrorama-turbo
thanks

**Comment by cmitu** [comment]
The theme is now added to RetroPie's list of included themes. User will need to update their RetroPie-Setup script first and then they'll be able to install it.

Thank you for the contribution.

**Comment by lipebello** [comment]
Thank you very much!
