### ISSUE TITLE
Netplay - failed to initialize

### ISSUE THREAD

**Issue by ooskay** [RetroPie/RetroPie-Setup#3282]
Dear All,
I do realy need help to fully understand how netplay works. On Retropie on pi3,
When i update port/ip on netplay configuration tool, i see that it does not update retroach.cfg in opt/config/all or arcade selection. Just it update retronetplay.cfg . Retroarch.cfg still contains old informations. How i do fix that?  If there is any priority, which configs are using first when a lanch a game over netplay?

Second question;
is there have any full log other than, /dev/shm/runcommand.log  to able to use to tract whats going at the background when a client or host ran a game over netplay?

and last question,
with the same setup, Lan to Lan works well. But most times getting "failed to initialize" message for the setups when client or host not in same network. I've configured port mapings on HOST and it works as should be. On host, ports valid and opened and waiting to packets. but client side getting failed to initialize error and i can not find what is the issue... 

What/where should i change/look/check?

thanks advance..
Ps:If is there any paid support for netplay , i'm in.. please get in contact with me..

**Comment by joolswills** [comment]
Please use the forum for support.
