### ISSUE TITLE
Question: Microsoft repos being installed on raspbian

### ISSUE THREAD

**Issue by ricardoandren** [RetroPie/RetroPie-Setup#3306]
Does this privacy vulnerability also impact RetroPie? And are there any plans to add this repo to RetroPie aswell, I hope not.

**Comment by joolswills** [comment]
Please can you provide a link?

**Comment by ricardoandren** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=301011

**Comment by ricardoandren** [comment]
They are stealthly deploying microsoft vscode via raspberrypi-sys-mods

**Comment by joolswills** [comment]
I've not read everything yet, but basically RetroPie images are based on Raspbian / Raspberry Pi OS, so we are impacted by their changes, and however they choose to resolve them. I doubt we will take a different route from whatever they decide but will check it out in detail.

**Comment by ricardoandren** [comment]
Sooo your saying that unless it doesnt require a lot of changes made your keeping a capitalist-telemetry-ridden-privacy-violating repo from microsoft in your retro emulation OS, even if its just sending a text file back and forth? The server will still know you've used their repo, and also they will still know your IP.

**Comment by joolswills** [comment]
We won't be doing anything on RetroPie in relation to this. It's not a RetroPie issue.
