### ISSUE TITLE
Shoulder buttons ps3 controller not working on PPSSPP and PPSSPP 1.5.4

### ISSUE THREAD

**Issue by rogerioronin** [RetroPie/RetroPie-Setup#3309]
Raspberry 3b
Retropie version 4.7.7

ERROR - Shoulder buttons ps3 controller not working on PPSSPP and PPSSPP 1.5.4 (my ps3 control is original)

sorry my bad english

**Comment by cmitu** [comment]
Please use the forum for support requests, as directed in the issue template.
