### ISSUE TITLE
Standalone Emulators

### ISSUE THREAD

**Issue by retro24** [RetroPie/RetroPie-Setup#3321]
Hello

BuZz Is it possible to add the option in the retropie-setup script when installing any emulator to create also a script in the ports or emulators folder that runs directly the emulator standalone it self???

instead to work only by running a rom/game.

And create an extra menu in Emulationstation called stand-alone Emulators for example
i think its a great addition to retropie this
 
Thanks

**Comment by dankcushions** [comment]
Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

That said, Retropie already runs many standalone emulators - you can run these directly via command line if you want, and you can add/amend emulationstation menus to have these as launchable items if you want, via editing the XML. However many standalone emulators won't be built with or contain UIs to be usable without being launched with a game.
