### ISSUE TITLE
update retroarch to 1.9.5 to add softpatching for more cores

### ISSUE THREAD

**Issue by bigboo3000** [RetroPie/RetroPie-Setup#3360]
Hi

The latest 1.9.5 retroarch version add a new RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE

Now genesis-plus-gx and beetle-pce cores can use softpatching for roms only (not-CD content).

Could you please update retroarch because softpatching would greatly simplify my roms management ?

Thanks

**Comment by joolswills** [comment]
It will be updated when we are ready. Please use the forum and not the bug tracker for stuff like this.
