### ISSUE TITLE
Amiberry Whdload on Retropie 

### ISSUE THREAD

**Issue by venkman383** [RetroPie/RetroPie-Setup#3363]
Hi.. I have an RP4 with retropie installed. I can get everything to work, mame, c64 etc except amiberry. I have loaded all the kickstart roms and various lha files. They all Show in the amiga menu but when i run them i always get the blue amiga dos screen (release 1.3) which comes up with:
Unknown command IF
1>

any ideas what im doing wrong? Randomly i have an old. RP3 with the same amiga settings and they all seem to work fine on there. I want to get them working on my rp4 as this is the basis for my arcade unit.

Any help would be much appreciated.

**Comment by joolswills** [comment]
Please use the forum as detailed when opening an issue.
