### ISSUE TITLE
Did not find libraspberrypi-bin ...

### ISSUE THREAD

**Issue by huangqingchao** [RetroPie/RetroPie-Setup#3376]
When compiling retroarch, an error "Did not find libraspberrypi-bin ..." will be issued. But the system installed on my Raspberry Pi 4 is "Debian-Pi-Aarch64 (a system developed based on Debian)", not Raspberrypi os. How can i fix it?

[rps_2021-07-19_171003.log](https://github.com/RetroPie/RetroPie-Setup/files/6841173/rps_2021-07-19_171003.log)

**Comment by joolswills** [comment]
It's not supported. Please use the forum first as detailed when opening an issue.
