### ISSUE TITLE
lr-mame problem 

### ISSUE THREAD

**Issue by isidoro-80** [RetroPie/RetroPie-Setup#3405]
hello i have install lr-mame for to play games of the following systems: apfm1000, apple 1 and 2, applegs, and others
i install rom and bios in this directory:

Roms | home/pi/RetroPie/roms/mame-libretro
Configuration | /opt/retropie/configs/mame-libretro
BIOS | /home/pi/RetroPie/BIOS/mame

the games don't start. mame cannot find the bios and drivers (I believe it is the hash file). 
I put the hash file apfm1000.xml and bios apfm in:
bios /home/pi/RetroPie/BIOS/mame
file hash /home/pi/RetroPie/BIOS/mame/hash
can someone help me?

i tried to put bios and has files in other directories but without success
in the image find the boot log of the rom

![20210927_210810](https://user-images.githubusercontent.com/75086284/135038550-687e7194-61cd-4de8-b360-1a6eb59ec40d.jpg)

**Comment by cmitu** [comment]
Please use the forum, as detailed in issue template.
