### ISSUE TITLE
Update SDL1 script for Debian 11

### ISSUE THREAD

**Issue by alessandrofrancesconi** [RetroPie/RetroPie-Setup#3411]
Debian 11 Bullseye has been released as the new stable.
The function to retrieve the correct SDL1 package ([get_pkg_ver_sdl1](https://github.com/RetroPie/RetroPie-Setup/blob/7efdc0e43c5550feeada9f0f34d7eadf314436de/scriptmodules/supplementary/sdl1.sh#L18)) should handle the new Debian version "11".

**Comment by kraoc** [comment]
A workaround I used is detailed here:
https://forums.raspberrypi.com/viewtopic.php?p=1940160#p1940160

**Comment by alessandrofrancesconi** [comment]
> A workaround I used is detailed here: https://forums.raspberrypi.com/viewtopic.php?p=1940160#p1940160

That's cool... I'm the author of that forum thread, and I hadn't seen that post yet :)
I will try

**Comment by kraoc** [comment]
RetroPie up & running on my Pi 4B :)

Still some issues compiling some tools... as of Retropie Manager which depends on python-dev and I didn't found a workaround.
But this tool seems deprecated so not really a problem.
