### ISSUE TITLE
Update kodi to fix addon issues 

### ISSUE THREAD

**Issue by Codythedragonrude** [RetroPie/RetroPie-Setup#3437]
I'm trying to use pluto and tubi add ons both are incompatible with the outdated 18.2 version that is currently the only option 

If you asked me the easiest way to solve this dilemma would be to allow building kodi from source in retropie setup instead of providing a binary that obviously is not being updated to the latest kodi stable version to keep add on compatibility working

**Comment by joolswills** [comment]
Please use the forum first a detailed when opening an issue.
