### ISSUE TITLE
Ports don't show launch art

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [RetroPie/RetroPie-Setup#3444]
Games in the `Ports` system never show individual ROM launch art. I know you can set a "launching" image for the whole system but it never uses the individual scraped cover art like it does for other systems.

I looked in the runcommand script and I found the `show_launch` function that displays the art. It looked pretty straightforward. It looked like a simple addition would add another check for `$IS_PORT` and then look in the `ports` folder for an image file that matches the ROM title, just like it does in the `$SYSTEM` folder when `$IS_SYS` is true.

I'm no coder, but as I said it looked pretty straightforward, so I went ahead and modified the function like so, but nothing happened. Why doesn't this work: https://github.com/s1eve-mcdichae1/RetroPie-Setup/commit/1f23a81e949ed07dac57747ac0fe9ad8bba2feee

**Comment by cmitu** [comment]
> Why doesn't this work: s1eve-mcdichae1@1f23a81

You don't have the pictures/screenshots where the code expects it to be ?

**Comment by s1eve-mcdichae1** [comment]
> > Why doesn't this work: [s1eve-mcdichae1/RetroPie-Setup@1f23a81](https://github.com/s1eve-mcdichae1/RetroPie-Setup/commit/1f23a81)
> 
> You don't have the pictures/screenshots where the code expects it to be ?

I do, though, I have them in:

```
1220:             "$HOME/.emulationstation/downloaded_media/ports/screenshots/${ROM_BN}"
```

...oh, I think I might be onto something else, though. *Runcommand* doesn't *call* the *launch script* as the `%ROM%` parameter; *the launch script calls Runcommand*, and with all kinds of weird stuff as the `%ROM%` param depending on how each particular port is set up.

I guess I don't see an easy way around this, then. I'll just have to use a more generic "launching" image...

**Comment by cmitu** [comment]
That's probably why the ports launching images cannot use the same setup as regular ROM based systems.

**Comment by s1eve-mcdichae1** [comment]
> That's probably why 

yeah, probably ;)

This all feels familiar, I think I've worked it out once before. Not how to make it work, of course, but why it didn't, at least.
