### ISSUE TITLE
Wolf4sdl game data

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [RetroPie/RetroPie-Setup#3446]
In the Wolfenstein 3D docs we are instructed to rename three files from the Spear of Destiny expansion from extension `.sod` to `.sd1`. (Presumably because the source files are available in both forms and so no one way is going to work in the scripts without *some* renaming.)

But then the install script still checks for the old `.sod` file when determining whether to download the shareware version. If we rename our registered version files as instructed, then the shareware will still be downloaded because the filenames don't match.

PR #3445 fixes this to search for the correct file. I also added a function that should automatically rename the `.sod` files so we don't have to do it manually.

**Comment by cmitu** [comment]
If you already opened a PR for it, why open a separate issue ? One is enough.
