### ISSUE TITLE
Con't install/update lr-mgba and other things

### ISSUE THREAD

**Issue by kirihito-kun** [RetroPie/RetroPie-Setup#3449]
Hi I tried to install Retro Pi on a Raspberry Pi 4A today, it worked fine at first but when I tried to run the basic installer it said the packages like:
* lr-mgba
* lr-mobile
* lr-gpsp
* lr-genesis-plus-gx
* lr-gambatte 
and many more cannot install or update. I have run apt-get update and apt-get upgrade very often and let retro pi check for updates and so far nothing is working.

**Comment by joolswills** [comment]
Please follow the instructions in the text you removed

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/
