### ISSUE TITLE
PS3 Emulator and raspberry pi bullseye

### ISSUE THREAD

**Issue by paulnegz** [RetroPie/RetroPie-Setup#3452]
This is not a report of a bug. I did not see a discord link and I am not sure if this is the right place but is there any way to add support for a PS3 emulator? 
Also, there are packages that currently do not compiler on the new raspberry pi bullseye OS

**Comment by joolswills** [comment]
You must have missed the text you removed when posting

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/

>Once a problem has been verified on the forum, an issue can be opened here.

>Please remove this text before posting.

Please post on the forum first. Bullseye is not yet supported on the Raspberry Pi. There is no PS3 emulator included, and a Raspberry Pi doesn't have the power to emulate such a system.
