### ISSUE TITLE
目前的4.7.1版本是否还不能支持zero2W设备？

### ISSUE THREAD

**Issue by hubRAM** [RetroPie/RetroPie-Setup#3464]
rt，我是用zero 2 w设备安装 4.7.1 版本镜像包；进入系统想链接WiFi时，提示我 unable to connect to network；使用WIFI菜单中的3种方法都类似提示；所以目前的4.7.1版本是否还不能支持zero2W设备？

**Comment by cmitu** [comment]
For the PI Zero 2W, use the weekly image from http://files.retropie.org.uk/images/weekly/retropie-buster-4.7.20-rpi2_3.img.gz.
For other support questions, please use the forum, as indicated in the issue template.
