### ISSUE TITLE
speech and alternate music don't work in uqm port

### ISSUE THREAD

**Issue by atfrase** [RetroPie/RetroPie-Setup#3483]
[The Ur-Quan Masters](http://sc2.sourceforge.net/) can be configured to use fully voiced dialogue and alternate music from the original 3DO version of the game, but these do not work in the RetroPie port. The installer downloads the relevant content files (`uqm-*-voice.uqm` and `uqm-*-3domusic.uqm`), and the game's setup menu shows options to enable them, but they do not take effect.

It looks to me like this is because RetroPie's `uqm.sh` install script (and the RetroPie-hosted pre-built binary archive produced from that script) install those two archives to the wrong directory, where the game does not find them. I'll submit a PR momentarily to correct this for installations from source, but the hosted pre-built archive will have to be updated as well.

**Comment by cmitu** [comment]
Fixed with the mentioned PR
