### ISSUE TITLE
Uninstalling Retropie wipes existing Retroarch installation

### ISSUE THREAD

**Issue by maxp-hover** [RetroPie/RetroPie-Setup#3525]
I had a previous Retroarch installation on Ubuntu and followed the instructions here to try Retropie https://retropie.org.uk/docs/Debian/

I decided I didn't want Retropie and so I ran the uninstaller. Even though I selected "NO" to the question "wipe dependencies" it still deleted my `~/.config/retroarch` folder which was a bit of a hassle.

**Comment by cmitu** [comment]
RetroPie symlinks `~/.config/retroarch` to `/opt/retropie/configs/all/retroarch`. The uninstall procedure will remove `/opt/retropie` entirely, and warns you about it:
```
Are you REALLY sure you want to uninstall RetroPie?

/opt/retropie will be removed - this includes configuration files for all RetroPie components
```

Maybe we should make it more clear that this includes the configuration for emulators/RetroArch/etc ?

**Comment by maxp-hover** [comment]
Yes, I would do so. If you don't know that ~/.config.retroarch is symlinked, this wil come as a surprise even with the warning you mention. 

I realize this is probably not a common situation, since most people will not previously have retroarch before installing Retropie, but still .... for me it was only about an hour's work to rebuild my Retroarch setup, but hypothetically it could be much more of a hassle for someone else (especially considering people store stuff such as BIOS files in their retroarch folder).
