### ISSUE TITLE
linapple configuring a joystick which has only axis4 and axis5 (axis0 and axis1 is not available)

### ISSUE THREAD

**Issue by Niyazi-Oezel** [RetroPie/RetroPie-Setup#3537]
Hello,
I use the linapple on my Retropie (raspberry pi 3b+ with an Ultimarc ipac2 keyboard encoder ).
Ipac2 interface is emulating / encoding arcade joysticks and buttons as two gamepads (Dinput mode).
If I test with jstest under retropie command line my joystick showing six axises but if iI move joystick there is physically onl three axises are existing= axises 2, 4 and 5 (axis 0, 1 and 3 not really existing).
I can edit nano /opt/retropie/configs/apple2/linapple.conf to change or remap buttons and the axises.
But if I change the joy0axis0 = 0 to the joy0axis0 = 4 and the joy0axis1 = 1 to the joy0axis1 = 5 nothing happens.
Maybe the linapple is not listening to the joystick which has more than 4 axises?
Because if I change the joy0axis0 = 0 to the joy0axis0 = 2 its working.
Is there any solution or hints how can I solve this issue?

Kind Regards
Niyazi

**Comment by cmitu** [comment]
As explained in the issue template, use the forum for support questions.
You already have a topic opened there, there's no need to open an issue here also.
