### ISSUE TITLE
SDL1 Install Error due to Missing Files in Mirrors

### ISSUE THREAD

**Issue by rtomasa** [RetroPie/RetroPie-Setup#3583]
Hi,

Yesterday I was able to install SDL1 via RetroPie-Setup in the morning for some testing. After finishing, I tried to install it again in another Pi by the night, but the same failed due to many errors related to missing source files in the raspbian repository.

Not sure if during the day something was deleted from the raspbian repo or maybe the retropie setup was updated with some wrong URLs. Attaching the log file.

[rps_2022-09-30_222043.log](https://github.com/RetroPie/RetroPie-Setup/files/9687789/rps_2022-09-30_222043.log)

Edit: I saw in the SDL1.sh that the package names depend on `__os_debian_ver` which takes the values from `lsb_release` command, so I have no idea how was possible to work the first time if version 11 was not in the sdl1.sh. Adding version 11 and revision 8 to the script worked, but still wondering if something was changed in the retropie script during this time lapse (I always install from GIT)

**Comment by cmitu** [comment]
The new 'bullseye' RaspiOS is not yet supported by RetroPie, that's why you get the errors.
When it will be supported, you'll be able to install it.
