### ISSUE TITLE
Distorted audio when recording in retro arch

### ISSUE THREAD

**Issue by daleti** [RetroPie/RetroPie-Setup#3585]
More details here: https://retropie.org.uk/forum/topic/33331/audio-issue-when-streaming-to-twitch/25

Apparently updated in Retroarch 1.10.3 but retropie setup has an old version included. Is there a way to update retroarch within retropie so it fixes the recording issue?

**Comment by cmitu** [comment]
You alreay have a forum topic opened - don't re-open another identical issue in the issue tracker, the same people monitor both places and we prefer the forum for discussions.

> Is there a way to update retroarch within retropie so it fixes the recording issue?

If you don't want to wait for RetroPie adding a new RetroArch version ([v1.11.0](https://www.libretro.com/index.php/retroarch-1-11-0-release/) is out now), you can manually install it as linked in the forum post. FWIW, I'm testing the new 1.11 version and will try to add it to RetroPie soon.
