### ISSUE TITLE
Update Odroid C2 installation

### ISSUE THREAD

**Issue by ngosang** [RetroPie/RetroPie-Setup#3594]
Odroid C2 fresh install with Ubuntu 20.04 LTS

After following these instructions => https://retropie.org.uk/docs/Odroid-C1-C2/
There is a conflict with libegl, libgl and mali-fbdev.
```
dpkg: error processing archive /var/cache/apt/archives/mali-fbdev_20200618-r6p1-2_arm64.deb (--unpack):
 trying to overwrite '/usr/include/EGL/egl.h', which is also in package libegl-dev:arm64 1.3.2-1~ubuntu0.20.04.2
```
After you see the error in the install command, you have to stop the setup, and execute this command. After that you can launch the installer again.

`sudo apt-get -o Dpkg::Options::="--force-overwrite" install mali-fbdev`

Maybe you can update the install script or the documentation.

**Comment by cmitu** [comment]
Thank you for the note.
I've added a note about it in our installation docs (while also updating the download links to the new Wiki pages).
