### ISSUE TITLE
Minimal install on Ubuntu 20

### ISSUE THREAD

**Issue by sorinpohontu** [RetroPie/RetroPie-Setup#3596]
Hi,

I want to build RetroPie on Ubuntu 20.04.5 LTS, for use with an XBOX Controller.
Since the compiling is taking so much time, I just want to build and install `Super Nintendo` (lr-snes9x2010) and `Sega 8/16 bit` (lr-genesis-plus-gx).
How can I select and build only those platform with required dependencies ?
Is there a wiki page that can point me in the right direction ?

Thanks.

**Comment by joolswills** [comment]
You go to Manage Packages in RetroPie setup and install the ones you want.

Please use the forum for support as.detailed.when opening an issue.
