### ISSUE TITLE
lr-scummvm experimental package fails to build (x86)

### ISSUE THREAD

**Issue by bingo1105** [RetroPie/RetroPie-Setup#3617]
It looks like there is some active development on this package, as the build script references a git "master" branch that no longer exists. There is, however, a "main" branch. I tried to modify the script to reference this new branch but was still unsuccessful in getting it to compile. I'm guessing this is a simple fix...

**Comment by cmitu** [comment]
If fails to build on all platforms, no just for PC.

The main repository has been re-organized and the build process changed entirely. I was waiting for the build to stabilize before changing the scriptmodule. Maybe the time is now.

**Comment by cmitu** [comment]
@bingo1105 can you update your RetroPie-Setup script and try building again the ScummVM libretro core ? The build should work now.

**Comment by bingo1105** [comment]
@cmitu Updated my installation, package built successfully. Thanks very much for the quick turnaround...

**Comment by cmitu** [comment]
Upload the last part of the build log on pastebin.com and post the link.

**Comment by bingo1105** [comment]
@cmitu The relevant part of the log output should be here:
https://pastebin.com/9dLD0eMM

Everything above that point appears normal to me. If you need more logging detail, please let me know.

**Comment by cmitu** [comment]
I don't get that failure, so there's probably something that's missing on your system - `zip`, or `wget` ?
Can you run:
```
cd $HOME/RetroPie-Setup/tmp/build/lr-scummvm
sudo ./bundle_datafiles.sh bundle scummvm.zip
```
and post the output ?

**Comment by bingo1105** [comment]
@cmitu Ugh, you're right, missing zip package. Thank you!

**Comment by cmitu** [comment]
Yes, I assumed as much. Seems we don't add `zip` as a base requirements for RetroPie (just `unzip`).
We'll add it as a dependency, thanks for testing.
