### ISSUE TITLE
samba configuration

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#362]
rather than having a samba share for every subfolder of roms/ it would be simpler just to have a single share for the roms folder. keeps the smb.conf sane too. Would you consider this if I submitted a patch ?

**Comment by joolswills** [comment]
@petrockblog - Just to follow on from this as a lot has changed since  - I think we ought to change the behaviour / permissions so that we don't prevent from accidentally removing them.

With the flexibility of the current script with the ability to reinstall individual emulators, a deleted rom folder can always be restored, but right now an old/defunct rom folder can't be removed and users may want to without having to restore to shell/sudo (nor new folders added). It would also simplify things somewhat. I've never truly been happy with my previous solution, but it seemed a compromise for the simplified samba config vs requested protection. Now I feel that we should be less restrictive in regards to this.

**Comment by joolswills** [comment]
it also came to mind again as the current usbromservice would overwrite the "protection" currently anyway, so I would need to add it there too to make sure the rom folders have the correct ownership etc - I'm just thinking it's best to get rid of it.

**Comment by petrockblog** [comment]
You brought up a good point! I also noticed that many users are not too happy about the restrictive concept of the rom folders with regards to the permissions. I like your idea.
So, should the rom folders simply have "standard" permissions/ownerships?

**Comment by joolswills** [comment]
yeh $user:$user

**Comment by joolswills** [comment]
I'm happy to make these changes
