### ISSUE TITLE
[Amiberry] check-list for next release

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#3634]
Hello!

As promised I'm now raising ticket instead of PR to prevent delays/misunderstanding/mistakes. Below the requirements for new Amiberry release, 5.6.0.

### `depends`:
* libserialport-dev

### `repo`:
`rp_module_repo="git https://github.com/BlitterStudio/amiberry v5.6.0"`

### `data`
There are some new files in `data` that should be included (for virtual keyboard).

### misc:
The patch Retropie does apply has to be removed otherwise the new version won't build. Following lines have to be commented out from `scriptmodules/emulators/amiberry.sh`:

```
applyPatch "$md_data/01_preserve_env.diff"
# use our default optimisation level
sed -i "/CFLAGS += -O3/d" "$md_build/Makefile"
```

### Release note:

https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.0

Thanks.

**Comment by cmitu** [comment]
Thanks for the heads up. I assume 5.6 is the next version ?

**Comment by nemo93** [comment]
That's correct.

**Comment by nemo93** [comment]
Scope for 5.6 has expanded which should bring in an even better compatibility. Yet to compile latest master the following lines have to be commented out from `amiberry.sh`:

```
applyPatch "$md_data/01_preserve_env.diff"
# use our default optimisation level
sed -i "/CFLAGS += -O3/d" "$md_build/Makefile"
```

**Comment by nemo93** [comment]
@cmitu 5.6.0 has been released. I've updated the first post with everything. Let me know if I can be of any further assistance.
