### ISSUE TITLE
PS3 wireless controller + Mame ! not working!!

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#364]
I am unable to make it work:( when i hit TAB central mame screen appears but when i hit any button on my gamepad nothing happens :( In all other emuls is working fine. What do i miss?

**Comment by andrefgj** [comment]
I know it is an old post, but did you get it to work? I am having the same issue. PS3 wireless controller works inside Emulationstation, but in emulator nothing happens. Even I hit TAB in keyboard
