### ISSUE TITLE
ioquake3 does not install on aarch64

### ISSUE THREAD

**Issue by dszakallas** [RetroPie/RetroPie-Setup#3710]
ioquake3 does not install on raspberry pi 4b+ (aarch64):

```
Could not successfully build ioquake3 - Quake 3 source port (/home/luigi/RetroPie-Setup/tmp/build/ioquake3/build/release-linux-aarch64/ioquake3.aarch64 not found).
```

the problem is that the build script translates `aarch64` to `arm64`

https://github.com/ioquake/ioq3/blob/main/Makefile#L13-L15

so the target detection at https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/ports/ioquake3.sh#L35 is incorrect.

This quick and dirty change resolves the issue
```diff
--- a/scriptmodules/ports/ioquake3.sh
+++ b/scriptmodules/ports/ioquake3.sh
@@ -32,7 +32,7 @@ function build_ioquake3() {

 function _arch_ioquake3() {
     # exact parsing from Makefile
-    echo "$(uname -m | sed -e 's/i.86/x86/' | sed -e 's/^arm.*/arm/')"
+    echo "$(uname -m | sed -e 's/i.86/x86/' | sed -e 's/^arm.*/arm/' | sed -e 's/aarch64/arm64/')"
 }

 function install_ioquake3() {
```

Let me know if you are interested in a PR with this change.

**Comment by cmitu** [comment]
Thank you for the heads up and any PR to fix it is welcomed.
