### ISSUE TITLE
libretro flycast should be built from upstream

### ISSUE THREAD

**Issue by theofficialgman** [RetroPie/RetroPie-Setup#3711]
According to the old downstream repo you should now use the upstream flycast repo to build the libretro core
old downstream repo: https://github.com/libretro/flycast

upstream repo which you should now use: https://github.com/flyinghead/flycast

**Comment by cmitu** [comment]
Yes, we are aware of the change (see https://github.com/RetroPie/RetroPie-Setup/pull/3450).
However, the new upstream is not 100% compatible with the Pi3's legacy GPU drivers, so it was reverted (https://github.com/RetroPie/RetroPie-Setup/pull/3462).

**Comment by cmitu** [comment]
Should be fixed with #3789, as separate package for now.
