### ISSUE TITLE
Uninstall RetroPie silently

### ISSUE THREAD

**Issue by polhaghverdian** [RetroPie/RetroPie-Setup#3729]
I am trying to automate the uninstallation process, and is there any way I could disable the dialog options when running the following command,  ` ./retropie_packages.sh setup uninstall`. I have also tried running with `__nodialog=1`, doesn't change anything.

**Comment by cmitu** [comment]
No, but you can look at the source and run the uninstall commands that are called from the `setup` module - see https://github.com/RetroPie/RetroPie-Setup/blob/86f65883db28def40d24bf3646905932a015dc19/scriptmodules/admin/setup.sh#L650
