### ISSUE TITLE
How can I build it on PC for raspberry

### ISSUE THREAD

**Issue by Hemingway2003** [RetroPie/RetroPie-Setup#3730]
It really cost lots of time on my tiny raspberry, so I wonder know is there any way to do a crossing platform building,

just like build it on x86_64 for arm64 -- aarch64

Thanks : )

**Comment by cmitu** [comment]
Please use the forum for support questions.
For the Pi, we provide binaries in order to avoid building from source, but if you want to cross-compile, you can use the `builder/image` module to do so - see https://retropie.org.uk/forum/topic/13057/cross-compiling-the-retropie
