### ISSUE TITLE
problem after upgrading, upgrading, upgrading, retropie

### ISSUE THREAD

**Issue by Giandj** [RetroPie/RetroPie-Setup#3735]
Hi,
I have always update & upgraded my system from 4.7.x (4.7.1, 4.7.2 , 4.7.19... 4.8...4.8.1..and so on) to every new version (on my Raspberry Pi4 8GB),
but now I have found some problems (in controller mapping/remapping) from 4.8.3 to the latest version 4.8.4,
are you shure that .cfg files are upgraded too?  
I refer to mapped controller .cfg files for every emultators, in Retropie are correctly upgraded during updating ? 

It seems that Retropie cannot upgrade correctly the .cfg files (code) during updating process, is it possible ?
The best solution I found is to delete, every .cfg (before controller mapping/re-mapping) for every emulators, after last 
Reteropie 4.8.4 update, otherwise emulators pre-mapped controllers still not works propery (like before the update).

Someone else has found this problem ?

**Comment by cmitu** [comment]
Please use the forum for support questions.
