### ISSUE TITLE
No longer build lr-mame on x64 system

### ISSUE THREAD

**Issue by litaniast** [RetroPie/RetroPie-Setup#3736]
Using Ubuntu 22.04.2

Recently libretro MAME source was updated based on MAME 0.256 but because of that, current build shell of lr-mame no longer work. It needs update but I don't know how.

Log says

Compressing src/mame/layout/zac_proto.lay...
Compressing src/mame/layout/zapcomputer.lay...
Compressing src/mame/layout/zodiac.lay...
Compressing src/mame/layout/zoo.lay...
1549 source file(s) found
...p/RetroPie-Setup/tmp/build/lr-mame/scripts/toolchain.lua:535: attempt to concatenate a nil value
stack traceback:
	...p/RetroPie-Setup/tmp/build/lr-mame/scripts/toolchain.lua:535: in function 'toolchain'
	...iaotp/RetroPie-Setup/tmp/build/lr-mame/scripts/genie.lua:1220: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:109: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'
make: *** [makefile:1341: build/projects/retro/mamearcade/gmake-linux/Makefile] 오류 1
Removing additional swap
Could not successfully build lr-mame - MAME emulator - MAME (current) port for libretro (/home/ariaotp/RetroPie-Setup/tmp/build/lr-mame/mamearcade_libretro.so not found).
/home/ariaotp

Log ended at: 2023. 07. 28. (금) 16:20:43 JST
Total running time: 0 hours, 2 mins, 51 secs

**Comment by cmitu** [comment]
This is an upstream issue, nothing that can be solved in the RetroPie scriptmodule.

In the future, please use the forum for support issues and not the issue tracker
