### ISSUE TITLE
omxiv - bullseye - multiple definition of OMX_RENDER_TRANSITION

### ISSUE THREAD

**Issue by pwallner** [RetroPie/RetroPie-Setup#3750]
Just try to compile retropi on my rpi zero 2w (running bullseye) and now I got a compile error at omxiv:
```omx_render.h:71: multiple definition of `OMX_RENDER_TRANSITION'```
I found [here](https://github.com/HaarigerHarald/omxiv/commit/d1e455309608c139b20f63977c2b1c60cc340194) the solution, just tried to change it and it compiled fine.

Temporary hack is to change content in file `omxiv.sh`  to `rp_module_repo="git https://github.com/HaarigerHarald/omxiv.git master"`.

Kindly ask to update the file `omx_render.h` in your repo!

**Comment by cmitu** [comment]
`omxiv` is not supported on RaspiOS _bullseye_ and it's not going to be used by RetroPie in the upcoming release which will add support for _bullseye_. See https://github.com/RetroPie/RetroPie-Setup/pull/3674.
