### ISSUE TITLE
dolphin build script failing to find qt6-svg-dev dependency on Ubuntu

### ISSUE THREAD

**Issue by diegov-au** [RetroPie/RetroPie-Setup#3756]
Based on the current Dolphin docs, the dependences for QT6 are qt6-base-dev qt6-base-private-dev libqt6svg6-dev. Swapping qt6-svg-dev for libqt6svg6-dev seemed to do the trick.

**Comment by cmitu** [comment]
This is a case where Ubuntu diverges from 'upstream' (Debian) and they're doing so inconsistently.

Debian has `libqt6svg6-dev` only in `sid/unstable`, while Ubuntu doesn't have it anymore in their 23.x releases, instead being replaced with `qt6-svg-dev`. We'll see how this can be tackled in the build script.
