### ISSUE TITLE
Retropie and Kodi in Bookworm

### ISSUE THREAD

**Issue by txutxifel** [RetroPie/RetroPie-Setup#3771]
Hello
I have updated retropie to bookworm from bullseye.

I know that bookworm is not supported yet, but I have updated my Rp4 because I use it mainly as a mediacenter, (I only use Mame sometimes).

In general it works correctly (I had to recompile everything). I have only found two errors:

Now Kodi asks for superuser password at the beginning -> I understand that the execution command has changed:

`root        9288  0.0  0.1  10740  3744 ?        S    10:34   0:00 sudo openvt -sw -- su -c /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone pi
root        9289  0.0  0.0  10740  1640 pts/2    Ss+  10:34   0:00 sudo openvt -sw -- su -c /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone pi
root        9290  0.0  0.0   5256   768 pts/2    S    10:34   0:00 openvt -sw -- su -c /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone pi
root        9291  0.0  0.0   9720  3256 tty3     Ss+  10:34   0:00 su -c /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone pi
pi          9292 59.2 14.8 3181064 541700 ?      RLsl 10:34  59:03 /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone
`

I have tried to modify the sudoers file (020_Kodi) without success.

Kodi also fails by exiting to emulationstation->Relaunch Kodi

Thank you very much for the work, I hope it helps.

**Comment by cmitu** [comment]
Please use the forum for discussions or support questions, as noted in the issue template.
