### ISSUE TITLE
MAME Coin Button?

### ISSUE THREAD

**Issue by ghost** [RetroPie/RetroPie-Setup#38]
I'm just curious if there is a button to add a coin to MAME roms?

**Comment by lordluca** [comment]
In mame insert coin is 6 on keyboard.

How can I map it to button on the controller?

**Comment by P3ter** [comment]
Hi !
When a MAME game is running, press "TAB" on your keyboard to open the MAME config panel.

**Comment by Mautobu** [comment]
GUYS. This ticket was closed and answered in September 2012. Seriously.

**Comment by pescu25** [comment]
how?
the link is broken.

**Comment by HerbFargus** [comment]
https://github.com/retropie/RetroPie-Setup/wiki/FAQ#why-cant-i-insert-coins-in-arcade-emulators
