### ISSUE TITLE
Why can't I select let settings?

### ISSUE THREAD

**Issue by InfernalWolf666** [RetroPie/RetroPie-Setup#3839]
I tried to change the path in the script, it worked, but after installation, of course, the games would no longer start!

I edit file - retropie_packages.sh 

`home="$(eval echo ~$user)"
datadir="$home/RetroPie"
biosdir="$datadir/BIOS"
romdir="$datadir/roms"
emudir="$rootdir/emulators"
configdir="$rootdir/configs"`

I changed these lines to these lines

`home=/home/MyUserName/Documents/Emulators/
datadir="$home/RetroPie"
biosdir="$datadir/BIOS"
romdir="$datadir/roms"
emudir="$rootdir/emulators"
configdir="$rootdir/configs"`

tell me how to write the path correctly

**Comment by cmitu** [comment]
Plese use the forum for support, as asked in the issue template.
