### ISSUE TITLE
Ubuntu or General Desktop Environment - Prevent Double Istance of "Retropie"... it's possible ?

### ISSUE THREAD

**Issue by DjDiabolik** [RetroPie/RetroPie-Setup#3898]
![immagine](https://github.com/RetroPie/RetroPie-Setup/assets/9040397/27241a77-0dad-4f22-a4f0-c084a09eee59)

At default Ubuntu GNOME Desktop on Left Bar it's appear the icon "Rpie" (because Rpie and not Retropie ?!!? I can edit it ? How i can do ? But it's a totally different question..lol).

From GNOME Desktop it's need a single click and a Gnome-Terminal has been launched and after EmulationStation.
if you double click by mistake two difference istance of ES it's been started and this creates some general problems.

Can i prevent this appends? It's GNOME have some setting to prevent this ?

**Comment by cmitu** [comment]
Please use the forum for general questions.

**Comment by DjDiabolik** [comment]
ops..
You thinks it's better to use "Help and Support" or "Ideas and Development" ? @cmitu
