### ISSUE TITLE
GZDoom doesnt install properly 

### ISSUE THREAD

**Issue by Gron21** [RetroPie/RetroPie-Setup#3912]
im trying to install gzdoom from retropie setup and show an error

i upload log

[rps_2024-04-29_112516.log.gz](https://github.com/RetroPie/RetroPie-Setup/files/15147319/rps_2024-04-29_112516.log.gz)

im on raspberry pi 5 and this is my os 

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by cmitu** [comment]
Please use the forum, as detailed in the issue template. 
Support for Pi5 is pending in RetroPie, so don't expect things to work 100%.
