### ISSUE TITLE
Gamepad input not working in RetroPie-Setup script when launched via EmulationStation

### ISSUE THREAD

**Issue by Fede2782** [RetroPie/RetroPie-Setup#3919]
This bug is reproducible on Ubuntu 24.04 LTS release with Ubuntu Desktop, installed RetroPie following the steps and everything works correctly except for the gamepad in the RetroPie-Setup script opened via the EmulationStation section. When launched via EmulationStation the keyboard doesn't work neither. 

Input via keyboard/gamepad doesn't work also in runcommand and other command-line based configuration script. Joy2Key is installed correctly. Gamepad/keyboard input works fine when launched manually in the gnome terminal shell in all sections and other configuration menus of RetroPie-Setup. 

If you need logs I can provide you what you need.

Have a good day

**Comment by cmitu** [comment]
Please use the forum for support questionsm. You already have a topic opened there - https://retropie.org.uk/forum/topic/35461/ - there's no point in opening an issue also.
