### ISSUE TITLE
Ports -> gzdoom.sh fails to build from source on Bookworm

### ISSUE THREAD

**Issue by RapidEdwin08** [RetroPie/RetroPie-Setup#3935]
Pi5 with Bookworm fails to compile GZDoom from source with this error:
`Could not successfully install GZDoom is a feature centric port for all Doom engine games, based on ZDoom (/home/pi/RetroPie-Setup/tmp/build/gzdoom/release/zmusic/lib/libzmusic.so.1.1.12 not found).`

Was able to look at log and see libzmusic.so.1.1.13 instead of libzmusic.so.1.1.12.
Updating Line#75 to 1.1.13 seems to resolve.

_Current Line#75: "release/zmusic/lib/libzmusic.so.1.1.12"_
**Proposal Line#75: "release/zmusic/lib/libzmusic.so.1.1.13"**

[gzdoom.sh Line#75](https://github.com/RapidEdwin08/RetroPie-Setup/blob/19b03acfdc38872a00416469a766210f26c0211a/scriptmodules/ports/gzdoom.sh#L75)

**Comment by cmitu** [comment]
Thank you for the heads up, upstream probably bumped the ZMusic api version. I'll fix it the module, in the future please use the forum to report the error.
