### ISSUE TITLE
Installation: behaviour on failure

### ISSUE THREAD

**Issue by rofl0r** [RetroPie/RetroPie-Setup#3941]
my internet connection is flaky, and about 1/20 clones fails. is there any possibility for recovery? by choosing install again, it seems to do compile everything over again - the only thing that appears to be skipped is cloning. this is already 3rd try and each try took hours.

**Comment by cmitu** [comment]
Please use the forum for support question, as directed in the issue template.

**Comment by rofl0r** [comment]
no, i won't register at $randomforum, unless one can write a post without registering.
