### ISSUE TITLE
Is an Amiberry upgrade to 5.7.4 planned for Buster user?

### ISSUE THREAD

**Issue by NoobieMaks** [RetroPie/RetroPie-Setup#3987]
@cmitu 

Sorry to bother you here but I don't know how to contact you in a better way/ directly.
My question belongs to your last commit regarding amiberry.

Under this link I can see that amiberry 5.7.1 was locked for Buster user: https://github.com/RetroPie/RetroPie-Setup/commit/a233272b5c09899fc2ca1016dd5c8a4e510bff22

But you made a manually upgrade for the content of 5.7.2 to the locked 5.7.1.
So to say you made a 5.7.1+

Do you also plan to do so with the content of the latest release 5.7.4?
Especially the bugfix of the joystick input would be great, because the current 5.7.1+ is acting wrong in that part.

Link:
https://github.com/BlitterStudio/amiberry/releases/tag/v5.7.4
...joystick input didn't work with retroarch mapping after latest changes (https://github.com/BlitterStudio/amiberry/issues/1363)

br
Maks

**Comment by cmitu** [comment]
> Sorry to bother you here but I don't know how to contact you in a better way/ directly.

Use the forums, as I said the previous couple of times.

As far as I'm concerned, there's no plan for v5.7.4 on Buster since the `dispmanx` support needed has been removed in v5.7.2. A few critical (for v5.7.1) fixes were added to the RetroPie Buster package, but that's about it.
