### ISSUE TITLE
DAEMON_ARGS (see wiki under x360 help) doesn't detach kernel driver.

### ISSUE THREAD

**Issue by ProfessorKaos64** [RetroPie/RetroPie-Setup#410]
I found out why my PS3 USB controller doesn't hotplug right (unplug and plug controller back in via USB). This is in reference to [Section 1](https://github.com/petrockblog/RetroPie-Setup/wiki/Setting-up-the-XBox360-controller) of the Xbox 360 controller wiki page.
```
/etc/default/xboxdrv
/etc/init.d/xboxdrv
```
What **isn't** happening is the kernel driver being properly detached. If you run `xboxdrv --detach-kernel-driver` on the command line after unplugging and plugging back in the controller (which the process of doing so, you will see the sony kernel module take over) it works just fine, but not using the xboxdrv service from the help page. 

Overview of steps to reproduce:

1. enable xboxdrv service per the wiki
2. reboot, press PS button on controller
3. Verify xboxdrv is the only /dev/input/js0 and controller functions
4. unplug controller
5. plug controller back in
6. verify sony_hid kernel module takes over, test controller after hitting PS button
7 restart xboxdrv service

This works to rectify the situation:

1. run `sudo xboxdrv --detach-kernel-driver`
2. Check jstest-gtk, xboxdrv is now the default driver of /dev/input/js0
3. controller works

I know the -d option is specified, but it does not properly detach the sony_hid module. Doing this manually works just fine. Any help?

**Comment by joolswills** [comment]
You shouldn't need to use the xboxdrv for the PS3 controller - or at least I didn't.  A long time has passed since this ticket was opened, so please let me know if you have tried this with the latest image etc.

**Comment by joolswills** [comment]
Or are you saying it's a problem when using a 360 and a ps3 controller together ?

**Comment by joolswills** [comment]
Closing as we have a new driver, and using retropie-setup should set it up properly to work (for 2 joypads)
