### ISSUE TITLE
Central config of keyboard controls

### ISSUE THREAD

**Issue by djcross** [RetroPie/RetroPie-Setup#453]
I'm trying to configure a USB keyboard for use with the emulators - when I run `retroarch-joyconfig` I am presented with 'Couldn't open joystick #0`

I've only just started today with looking at RetroPie, so any guidance would be great :)

using sd-card image v2.3

```
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.12.22+ #691 PREEMPT Wed Jun 18 18:29:58 BST 2014 armv6l GNU/Linux
```

**Comment by igorissen** [comment]
But when you add a joystick, the keyboard doesn't work any more!

**Comment by joolswills** [comment]
you should open a new issue about this rather than commenting on an unrelated issue - you might do better to report this to the retroarch project if it is a retroarch issue.

**Comment by joolswills** [comment]
ok i see you also opened a new issue. thanks.
