### ISSUE TITLE
Atari 7800 roms load to black screen

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#611]
I've tried a number of Atari 7800 roms (No-Intro set) and they all uniformly produce a black screen. I compiled everything yesterday.

**Comment by gizmo98** [comment]
Yeah, that's true. It's a work in progress module. It builds and there is no segmentation fault but there is also no picture.

**Comment by joolswills** [comment]
I think we should probably leave experimental stuff to those that mostly work, but may have a few issues. No picture is not quite ready for experimental imho :)

**Comment by gizmo98** [comment]
Yeah, I thought it would work with the right BIOS. If it is not working until the end of the week i will kick it out. :-)

**Comment by joolswills** [comment]
This is implemented and working.
