### ISSUE TITLE
Add ES theme as module: ZOID

### ISSUE THREAD

**Issue by petrockblog** [RetroPie/RetroPie-Setup#616]
A user has presented another theme for ES, that he calls "Zoid": http://blog.petrockblock.com/forums/topic/theme-zoid/

I did not have a closer look at that yet, but if the theme looks appropriate and complete, we could think about adding it as another module.

**Comment by joolswills** [comment]
is it a new theme or an extension of the simple theme with additional backgrounds ? if its an extension of the simple theme I guess it should be fed upstream + we might want to consider using it as default (if it's good)?

**Comment by robertybob** [comment]
Bump.

**Comment by robertybob** [comment]
Any update on this @joolswills ?

**Comment by robertybob** [comment]
FWIW, this needs artwork fro the RetroPie menu. I've knocked up a very rough one if the original author doesn't resurface and want to add his/her own.

**Comment by joolswills** [comment]
it is now included. thanks.

**Comment by joolswills** [comment]
(In regards to missing retropie artwork etc, please submit a pull request / open a ticket on https://github.com/RetroPie/es-theme-zoid -

**Comment by HerbFargus** [comment]
I added it already- thanks @robertybob  but yes sage advice for future reference
