### ISSUE TITLE
[Feature Request] Add PPSSPP Emulator

### ISSUE THREAD

**Issue by robertybob** [RetroPie/RetroPie-Setup#677]
This has been successful built on a RPi2 
[Link](https://github.com/hrydgard/ppsspp/issues/7479#issuecomment-75403013)

>Got it working on RPI2.

>You don't need to change much:

>you need to get the EGL, GLES, GLESv2 and KHR headers from the mesa packages, preferably put them in the ppsspp source folder
>change CMakeLists.txt and remove RPI references: ppssppsdl uses SDL2 which already has videocore backend, so we don't need any rpi-specific backend here
>add the egl/gles include folder (where you copied the EGL, GLES, GLESv2 and KHR folders from mesa) and the egl/gles lib folder (the rpi one - /opt/vc/lib) - you can see in CMakeLists.txt how it was done previously for rpi
>Run cmake, edit CMakeCache.txt and set FBDEV to ON, GLES2 to ON, maybe even MOBILE_DEVICE to ON, run cmake again, then run make.

>A bit disappointed with the performance (GPU clocked at 500MHz), it runs fullspeed on the odroid... 
>https://www.youtube.com/watch?v=O8juShfoJtE

If this runs better than the current N64 emulators then surely it's worth including?

**Comment by robertybob** [comment]
@joolswills ? :)

**Comment by robertybob** [comment]
bump

**Comment by joolswills** [comment]
We don't always have time to respond to all tickets immediately. I had read this, but haven't had time to look into it further yet.

**Comment by julianxhokaxhiu** [comment]
This would be easy for you to include I think https://github.com/libretro/libretro-ppsspp

**Comment by GAMELASTER** [comment]
libretro dont work :) tested

**Comment by barbudreadmon** [comment]
Actually, libretro-ppsspp works if you tweak the sources a little, but is too slow.

**Comment by GAMELASTER** [comment]
Barbudreadmon: i looked some videos and its possible, and its not so much slow :-) but i didnt get idea how to do it.. mmm

**Comment by barbudreadmon** [comment]
You are talking about ppsspp-libretro or ppssppsdl ? I know ppssppsdl run at (near ?) full speed, but i'm not sure the same is possible on libretro-ppsspp at the moment.

**Comment by joolswills** [comment]
both ppsspp and the libretro port are now available from the experimental menu (update retropie-setup script first). Cheers!

**Comment by julianxhokaxhiu** [comment]
Awesome! Thank you
