### ISSUE TITLE
Duke Nukem 3D Mouse problems

### ISSUE THREAD

**Issue by PowerWiesel** [RetroPie/RetroPie-Setup#684]
I can’t get my mouse running for aiming and shooting etc. For example it’s working wiith Quake out of the box.

In the menu (megaton edition) you can move the curser, but you can’t click anything.

Ingame there is also a moving courser, but you can’t shoot or aim.

I tried in_mouse 1 and MouseAiming = 1 and several little things that dind’t work

**Comment by joolswills** [comment]
Thanks - Yeh I can confirm this.

**Comment by agenttank** [comment]
same here, but i don't really care ;)
fresh install of retropie 2.6 full image

**Comment by luxiouronimo** [comment]
i can confirm and add:

raspberry pi 2, installed retropie-v3.0beta2-rpi2.img, and install from yesterday's (5/19/15) binaries..

in the in-game menu the mouse works and i can click menu items, but in-game the mouse does not affect the aim/view or movement, even when toggling mouse move with the 'u' key.

clicking mouse1 does however shoot.

**Comment by joolswills** [comment]
It's a known issue as above.

**Comment by luxiouronimo** [comment]
to be clear, relating to v3.beta2-rpi2, you can click the in-game menu and that works, and in-game you can shoot.

**Comment by joolswills** [comment]
yep - this is the issue. the mouse works in the menus, but not for aiming.

**Comment by davidj1987** [comment]
Is Duke 3D eduke or a retroarch port? Is this issue related to this issue: https://github.com/libretro/Genesis-Plus-GX/issues/31

In this emulator mouse buttons work but the cursor doesn't move. :/

**Comment by joolswills** [comment]
unrelated issue.

**Comment by PowerWiesel** [comment]
Thank you very much:)

**Comment by davidj1987** [comment]
I'm having mouse issues with eduke...is there something I need to enable?

**Comment by HerbFargus** [comment]
This issue is closed. Please see the wiki (https://github.com/retropie/retropie-setup/wiki/Duke-Nukem-3D)  and use the forum for support
