### ISSUE TITLE
GpSP Change Controller

### ISSUE THREAD

**Issue by Ceuse** [RetroPie/RetroPie-Setup#714]
Is there a way to change the Default controller GpSP uses? by default it allways uses J0

**Comment by gizmo98** [comment]
Joystick 0 is hard coded. You can modify the source code:
https://github.com/gizmo98/gpsp/blob/master/input.c#L1037

If you need joypad 1 modify line 1037 to "SDL_JoystickOpen(1);"

**Comment by joolswills** [comment]
Closing - old problem that is unlikely to be fixed in the source since we also have lr-gpsp.
