### ISSUE TITLE
[Enhancent] Integration of Limelight Streamer

### ISSUE THREAD

**Issue by jayp76** [RetroPie/RetroPie-Setup#721]
Is it possible to integrate Limeligt?

**Comment by joolswills** [comment]
looks interesting. adding this link for reference https://github.com/irtimmer/limelight-embedded

**Comment by stsfin** [comment]
I made a Guide to the wiki how to manually add it to retropie and emulation station: https://github.com/petrockblog/RetroPie-Setup/wiki/Quickguide-for-configuring-limelight-with-Retropie-and-Emulation-Station

just updated the wikipage after I found working OC settings to get the 1080p/60FPS streaming running... 1080p/30fps and 720p/60fps work without OC.

**Comment by stsfin** [comment]
I'll probably try to make an script that automates the install as much as possible (more on that later)

**Comment by stsfin** [comment]
Here is the installer script I created:

https://github.com/stsfin/RetropieLimelightInstaller/blob/master/limelightRetroInstall.sh

Should help integration.

**Comment by stsfin** [comment]
Updated the installer script with eventID selection. Now the controller can be in anyport. I will create a secondary script with only ip and controller reconfiguration to make it easier

**Comment by stsfin** [comment]
Updated the script, it is basically now complete, tested with 3 different retropie installations: https://github.com/stsfin/RetropieLimelightInstaller  
@joolswills be free to fork it for RetroPie :)

**Comment by stsfin** [comment]
Im having trouble in integrating the reconfig script to Emulation station.  The read command just gives "ead: read error: 0: bad file descriptor" when running the reconfig-script from the ports-section... it works nicely from the console... @joolswills any pointers?

**Comment by stsfin** [comment]
The installer now creates a new "device"-menu under Emulation station for better integration... Still no luck with the reconfiguration script though.

**Comment by stsfin** [comment]
![2015-03-29 16 34 40](https://cloud.githubusercontent.com/assets/558170/6885629/ce40d956-d631-11e4-8056-ab3566921518.jpg)
![2015-03-29 16 34 49](https://cloud.githubusercontent.com/assets/558170/6885630/cf31a534-d631-11e4-9e39-0063b06a6c70.jpg)
![2015-03-29 16 35 24](https://cloud.githubusercontent.com/assets/558170/6885631/d05a1b62-d631-11e4-9cdc-60d035a6b46c.jpg)

**Comment by joolswills** [comment]
regarding the problem - use `<dev/tty` on the read command.

**Comment by stsfin** [comment]
@joolswills , thanks will try it out if it works i will update the script to add the reconfigurator to the menu

**Comment by stsfin** [comment]
Thanks for @joolswills for helping me with the last obstacle... Here it is, the final version of the script with the reconfigurator accesible from emulation station after install: https://github.com/stsfin/RetropieLimelightInstaller/archive/2.0.1.zip

**Comment by stsfin** [comment]
Here is how it looks and works after install https://youtu.be/CT0Zhmh9e9o

**Comment by taalas** [comment]
Commented on some minor issues in the merged code. Should I rather have commented here?

**Comment by stsfin** [comment]
If you are refering to the code that will be implemented to Retropie you
should comment in that thread.

Jonne Backhaus
______________
+358-45-1141905
jonne.backhaus@gmail.com
jonne.backhaus@androidsuomi.fi

Google+: http://backhaus.fi/+/
LinkedIn: http://backhaus.fi/linkedin/

**Comment by taalas** [comment]
I commented in Rewrite limelight setup script to a module #792
