### ISSUE TITLE
Hatari IPF support 

### ISSUE THREAD

**Issue by NaWer** [RetroPie/RetroPie-Setup#732]
Please add hatari IPF support using capsimage library :
https://github.com/libretro/hatari/blob/master/readme.txt

**Comment by joolswills** [comment]
this has been added now - you will need to compile from source for now as I have not yet updated any binaries.

**Comment by joolswills** [comment]
was quite some work to implement!

**Comment by joolswills** [comment]
Binaries are now updated.

**Comment by NaWer** [comment]
Yeah! Thanks you! I'll try as soon as possible. Probably next week end ;)
