### ISSUE TITLE
Unable to update RetroPie-Setup

### ISSUE THREAD

**Issue by Totien** [RetroPie/RetroPie-Setup#798]
Hello.  I'm sorry for being so new at this.  I've tried several times to update my script, but I've not had any success. 

When I try from within ./retropie-setup.sh, I get the error that it cannot connect to github.

When I try git clone --depth=1 git://github.com/petrockblog/RetroPie-Setup.git I get the error that RetroPie-Setup is not an empty directory.  I'd prefer to keep any files I've made changes to if there's a way to do that.

Thanks for the support.

**Comment by joolswills** [comment]
to update do git pull or use the option in retropie_setup.sh

if you have local changes you can "git stash" them first.

if you are getting connection errors, you might have a networking issue.
