### ISSUE TITLE
Allow retroarch driver selection from config menu before running retroarch-joyconfig

### ISSUE THREAD

**Issue by cyberkni** [RetroPie/RetroPie-Setup#812]
My GP Wiz40 arcade controller board causes retroarch to have a floating point exception upon the first input to a joystick(this translated to an event on one of the axes controls instead of a button).

I was able to work around the config issue by running retroarch-joyconfig with the --driver linuxraw option.

It would be cool if the setup menu would hold my hand and run it this way for me.

**Comment by joolswills** [comment]
with the integrated emulationstation configuration (ES triggers a script that configures retroarch), this may no longer be needed - the joyconfig stuff is still there, but doesnt usually need to be used.

in regards to getting a fix for this for retroarch-joyconfig - I would suggest reporting it to the retroarch project.
