### ISSUE TITLE
Need support for Ipega PG-9025 controller

### ISSUE THREAD

**Issue by urtzai** [RetroPie/RetroPie-Setup#834]
I'm trying to config my Ipega PG-9025 with no succeed... I'll be very appreciated to have some kind of setup, guidance...

Thanks

**Comment by sur0x** [comment]
Im looking forward for this as well.

Did you tried this: 

http://askubuntu.com/questions/608386/using-ipega-bluetooth-gamepad-with-steam-linux

**Comment by urtzai** [comment]
Nop! But thanks! I will. How do you pair your device with raspberry? I'm still stuck in that point...

Thanks for your info, I'll let you know if I achieve something.

**Comment by urtzai** [comment]
I've created a question in stackoverflow, perhaps i'll get more clues... http://stackoverflow.com/questions/30481198/using-ipega-bluetooth-gamepad-with-retropie

**Comment by urtzai** [comment]
Finally I found a solution: http://stackoverflow.com/questions/30481198/using-ipega-bluetooth-gamepad-with-retropie/30613619#30613619

I hope it will be usefull

**Comment by wingsofsarrow** [comment]
do u guys know if you can use two ipega controllers at once for two player games

**Comment by Zarroc1991** [comment]
I have the same question. How do I use 2 ipega controllers

**Comment by platon-actual** [comment]
> Finally I found a solution: http://stackoverflow.com/questions/30481198/using-ipega-bluetooth-gamepad-with-retropie/30613619#30613619
> 
> I hope it will be usefull

Hello, sorry for reopening an old thread. Didn't work for me, as it looks, bluez-tools aren't installed on the latest Retropie release.
Still struggling with this.
