### ISSUE TITLE
Crashes over wireless ssh Putty

### ISSUE THREAD

**Issue by jediguy13** [RetroPie/RetroPie-Setup#837]
I am trying to configure a controller over ssh with my wireless dongle attached, and it works fine. But when I try and exit the setup, the raspberry pi's wifi crashes. The wlan0 interface says it's down and I can't put it back up. The only way to fix is to reboot. A way around this would be to Crtl+C force exit the program, but that's not fun. Please fix.

**Comment by joolswills** [comment]
Not sure this is something in our control. But without any logs (dmesg / syslog etc) I am unable to advise.
