### ISSUE TITLE
Adding o2em -- Odyssey 2 Emulator -- to Retropie

### ISSUE THREAD

**Issue by truckershitch** [RetroPie/RetroPie-Setup#852]
o2em is command-line based but I think a frontend could be created for it.  It is a little tricky to compile -- there are several changes to be made to the source code including changing the source files to lower case.

See http://emulvideopac.blogspot.com/2013/02/en-install-o2em-on-linux-and-recompile-it.html for compilation help.

There is another version called o2em2 but I don't think it works as well as the original.

Thanks!

**Comment by joolswills** [comment]
We have the libretro port of o2em though - so unless something works better on the commandline one, do we need it ?

**Comment by joolswills** [comment]
closing due to no feedback.
