### ISSUE TITLE
THEME simplified static canela new logo v2.0 

### ISSUE THREAD

**Issue by InsecureSpike** [RetroPie/RetroPie-Setup#858]
hi Florian, the theme has been updated with the new logo, (and new text)
i've remade some of the banners and added 5 new ones.

the zip contains the theme and a boot screen too

https://www.mediafire.com/?46ermnrvcp221fc

**Comment by robertybob** [comment]
Great work!

**Comment by robertybob** [comment]
Any chance of this making the next beta @joolswills?

**Comment by joolswills** [comment]
We missed the last one, but I'll add it before the next release (which may not be a beta depending how this one goes). thanks.

**Comment by robertybob** [comment]
Thanks @joolswillis , I presume it'll be Beta 5 (or the equivalent) ?

**Comment by joolswills** [comment]
It didn't make the last release, but it is included now if you update retropie-setup, you can install it from the supplementary menu.
