### ISSUE TITLE
When using ps3 controller over usb the down on directional pad enables hotkeys

### ISSUE THREAD

**Issue by tachu** [RetroPie/RetroPie-Setup#866]
I've run the setup several times and setup the config and verified through jstest that the buttons are mapped correctly i have enable hotkey to 0 which is the select button but somehow pressing  the down button on the d-pad doesn't work. and if i press a another button like the O or X on the controller it either does reset or tries to open the retroarch menu

**Comment by joolswills** [comment]
I assume you are running the latest retropie (via source or image ?) - It helps to provide details of stuff like this.

Likely the same issue as https://github.com/petrockblog/RetroPie-Setup/issues/864
