### ISSUE TITLE
Mario Golf Advance Tour and Mario Tennis Power Tour

### ISSUE THREAD

**Issue by craigerskine** [RetroPie/RetroPie-Setup#875]
I searched everywhere on the net for info about this issue but can't find anything.

When I try to load Mario Golf of Mario Tennis on GBA with the default settings from a fresh install of RetroPie, the games reset to the GBA loading screen when choosing a character at the very beginning.

Has anyone else seen this with any other GBA games and if so is there a workaround?

**Comment by joolswills** [comment]
which emulator ? This would probably be best posted on the forum rather than this issue tracker - also please include what version of retropie etc you are running.

**Comment by craigerskine** [comment]
Sorry for the post in the wrong area.

I'm using the default emulator for GBA, whatever is used if you don't change anything and just try to launch a GBA game... I'm not sure what it is offhand. I'm using RP 3.0 Beta 3, this also happened in RP 3.0 Beta 2.

Note: Both games using the exact same roms launch and play fine in other emulators as well as OpenEmu.

**Comment by joolswills** [comment]
sometimes not everything works with every emulator and sometimes emulators have bugs. retropie has a selection of gba emulators which can be switched between - read the wiki for more information.

**Comment by HerbFargus** [comment]
mario golf advance tour seems to work better on gpsp rather than the libretro-gpsp emulator (press x or m as a rom loads to change the emulator). Mario Golf tennis doesn't work on either default emulator, but it does work on lr-vba-next (which you would install from the experimental menu- its a bit laggy though) neither work on lr-mgba at the moment but that may be an upstream issue. I think we can consider this issue closed.

**Comment by joolswills** [comment]
thanks.

**Comment by craigerskine** [comment]
Thank you for the info.

**Comment by darth2499** [comment]
I know this has been closed for over 4 years now, but I wanted to point out that I have the same issue with Mario Golf where right before the character selection the GBA loading screen pops out and I can never progress any further. Running on Raspberry Pi Zero W.

**Comment by craigerskine** [comment]
@darth2499 Use the no-intro romset from archive.org, that fixed all my issues.

**Comment by joolswills** [comment]
Please use the forum.
