### ISSUE TITLE
Core Input Remapping Options not working in RGUI

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#877]
referenced from this forum post: http://blog.petrockblock.com/forums/topic/core-input-remapping-options/#post-100250 

In theory this setting should allow one to change the default core configurations for the retropad rather than reconfiguring each controller with retroarch.cfg or autoconfigs. For example the default retropad controls for the megadrive 3 button are as follows:

![megadrive3btn](https://cloud.githubusercontent.com/assets/10035308/7336303/aec335e0-ebb4-11e4-93b3-26037dd26ffb.png)

but with the core remapping option you could change the retropad so that A button on the megadrive pad would be mapped in the core to X instead of Y (or any other button) without necessarily changing your retroarch.cfg or autoconfigs (so it would changed from ABC=YBA to ABC=XBA). As it stands right now, if you wanted to have Y be X, you'd have to map your X button as Y which can cause confusion for other emulators when you try to use them if you're using autoconfigs. (btw is there a way to have emulator specific autoconfigs?) -hopefully my explanation wasn't too confusing.

**Comment by joolswills** [comment]
Please can you try with a new retroarch built from source ? There has been a lot of work on retroarch recently (they have been rewriting large parts), and I think this is fixed now. I just tried it and it seemed ok here.

**Comment by joolswills** [comment]
Just to clarify - I've only tested this on demand in the RGUI - not saving/loading etc.

**Comment by HerbFargus** [comment]
Yeah I've been meaning to test it with the recent changes. I just built a fresh image and built retroarch from binary and it works brilliantly- but my hotkeys aren't requiring me to press select first before they work- so if I just press X it enters the menu, if I press start it exits, etc. (this all happened before I made any core input remapping changes) I wonder if they changed the nulbindings with their recent updates.

**Comment by joolswills** [comment]
Can confirm and a PITA as I just uploaded a new retroarch binary assuming nothing would have broken from the one I was testing which was just a few days older or so. Will look into it.

**Comment by joolswills** [comment]
https://github.com/libretro/RetroArch/issues/1982

**Comment by joolswills** [comment]
Fixed upstream now (At least from my initial testing). Please can you build retroarch from source again and test ?

**Comment by joolswills** [comment]
I have updated the retroarch binaries also.

**Comment by HerbFargus** [comment]
I updated from binary and can confirm it is now working.

**Comment by joolswills** [comment]
hurray.

so back to this ticket - is the core remapping stuff working for you ok also ?

**Comment by HerbFargus** [comment]
Core remapping works as well :)

**Comment by HerbFargus** [comment]
Thanks :)
