### ISSUE TITLE
adding configs folder to ./emulationstation folder

### ISSUE THREAD

**Issue by InsecureSpike** [RetroPie/RetroPie-Setup#882]
could this be a possible enhancement, the moving of the configs folder and contents to the home/pi/.emulationstation folder, so as this location can store/hold any/all edited retroarch.cfg files,
so as these don't get updated/overwritten/modified by updates.
and these files would override any in the original location, just like the es_systems.cfg

**Comment by joolswills** [comment]
the files don't get overwritten with updates - Moving them to another location wouldn't really help and would create a lot of confusion - the .emulationstation folder is for emulationstation, and not other configs.

**Comment by InsecureSpike** [comment]
ah i see, thank you for clearing up my confusion

**Comment by joolswills** [comment]
just fyi, if you update retropie-setup and do a new binaries install, it should not overwrite existing files but create a new config in most cases. new retroarch.cfg will be called retroarch.cfg.rp-dist for example
