### ISSUE TITLE
Add overclock settings to limelight for 1080p/60FPS support

### ISSUE THREAD

**Issue by stsfin** [RetroPie/RetroPie-Setup#885]
There should be a Yes or Now question in the limelight setup script to auto add the needed overclock setting for the PI2 to run Limelight on 1080p -resolution with the 60fps.

These are working: arm_freq=1100 core_freq=500 sdram_freq=500 h264_freq=500 over_voltage=8 force_turbo=1 temp_limit=80

**Comment by joolswills** [comment]
those are unsafe though, and could void warranty. Users can overclock with raspi-config bu I prefer to leave it to them to do it.

**Comment by joolswills** [comment]
best thing would be to document this on the wiki perhaps ?
