### ISSUE TITLE
Upgrading GCC version

### ISSUE THREAD

**Issue by yesman85** [RetroPie/RetroPie-Setup#889]
Is it possible to upgrade packages to use GCC 4.8 or 4.9? Unfortunately Raspbian doesn't support 4.7..

**Comment by joolswills** [comment]
Raspbian Wheezy has 4.7 - if you are running a newer raspbian or want to change default compiler you can change it in scriptmodules/system.sh

**Comment by joolswills** [comment]
raspberrypi.org still offer Debian Wheezy and it is the version still currently officially supported.
