### ISSUE TITLE
Permissions on RetroArch core options

### ISSUE THREAD

**Issue by biscuits99** [RetroPie/RetroPie-Setup#893]
In RetroPie 3 beta 4, the permissions of:
/opt/retropie/configs/all/retroarch-core-options.cfg

dont allow user Pi to write to it (same on dispmanx.cfg).

This seems to be causing issues when setting core options via RGUI and generally using the file from RetroArch.

Seems much happier when user Pi can read and write to it.

**Comment by joolswills** [comment]
thanks. well spotted - this is a bug (one of mine) ;-)

**Comment by joolswills** [comment]
thanks. should be sorted now - wont fix up existing installations unless they do a full binary install (or re-installs one of the retroarch modules that creates this).
