### ISSUE TITLE
xbox driver used for ps3 usb controller

### ISSUE THREAD

**Issue by hbooo** [RetroPie/RetroPie-Setup#898]
Hello, 

I have a xbox360 controller and a ps3 controller. Both are connected by usb, both are detected with xbox driver and it's almost impossible to configure joystick on my ps3 controller because it detects both direction when I try to configure them.

I'm using retropie 3 beta 4

**Comment by joolswills** [comment]
unplug the other one when you are configuring them ?

**Comment by seijmo** [comment]
I already tried but I still have xbox gamepad (userspace driver) #2 detected.

**Comment by joolswills** [comment]
Does this happen with the latest image (which has a new xboxdrv driver) ?

**Comment by HerbFargus** [comment]
closed due to no feedback, simple workaround is to just disable xboxdrv on configuration.
