### ISSUE TITLE
Not saving. 

### ISSUE THREAD

**Issue by baldy32** [RetroPie/RetroPie-Setup#901]
My RetroPie will not save. In game saves will not work. Save states will not work as well. Save states come up with this message -Failed to save state to "home/pi/RetroPie/roms/snes/ (game name).state"

I do not know how to fix this.

**Comment by joolswills** [comment]
You may do better to ask on the retropie-setup forum for help with his.

**Comment by joolswills** [comment]
http://blog.petrockblock.com/forums/
