### ISSUE TITLE
Emulationstation controller config not recognizing XBox360 right trigger - Beta 4

### ISSUE THREAD

**Issue by stsfin** [RetroPie/RetroPie-Setup#902]
Emulationstation controller config does not recognize the right trigger when its asking the not recognizing XBox360 right trigger when its asking the right bottom button. 

I've tested this with two different wired xbox360 controllers which both work on the pc and xbox. And the controller has worked on previous betas withouth issues.

**Comment by joolswills** [comment]
Did you install the xbox 360 userspace driver first from supplementary menu (and reboot) ?

**Comment by stsfin** [comment]
@joolswills that did the trick. Will close this issue.
