### ISSUE TITLE
Gasia gamepad PS3 nobrand

### ISSUE THREAD

**Issue by billgatos** [RetroPie/RetroPie-Setup#907]
Please add support for this driver 
https://github.com/supertypo/qtsixa

This controller is a PS3 compatible controler and has a usb pen to connect wireless.
info about the contrller:
https://www.worten.pt/inicio/worten-gamer/acessorios/acessorios-ps3/comando-wireless-dualshock-6axis-n-play-p-ps3-pc.html

**Comment by gizmo98** [comment]
There is a install option for gasia gamepads now.
