### ISSUE TITLE
MSX configuration

### ISSUE THREAD

**Issue by amm297** [RetroPie/RetroPie-Setup#910]
Hi all,

I'm trying to configure msx with a key combination because i'm using an old retro gaming machine, so when i save any change it don't work after exit a game and play other, is there any mathod to solve it ?

thanks

**Comment by robertybob** [comment]
Best ask in the forums to see if anyone has can help you there :)

**Comment by joolswills** [comment]
Thanks @robertybob - yeh this is best posted on the forum. Cheers.
