### ISSUE TITLE
Breaks up the installation because of spaces in the file name

### ISSUE THREAD

**Issue by SpiritOffice** [RetroPie/RetroPie-Setup#921]
RetroPie-Setup/scriptmodules/ports/Super Mario War.sh

First installation. 
It stops and says something like "missing rp_module_id in file Super"

The problem is it can't handle the full name of "/RetroPie-Setup/scriptmodules/ports/Super Mario War.sh".
After i renamed this file to SuperMarioWar.sh, it continues the installation.

**Comment by joolswills** [comment]
thanks.

fixed in 8c172669068040a7ab47ae5f7b174e91ccbca82d - missed that when merging the pull request.
