### ISSUE TITLE
How can i get Nintendo World Championships 1990 (NES) get to work?

### ISSUE THREAD

**Issue by FreddeHamm** [RetroPie/RetroPie-Setup#922]
Hey, sorry i'm new here, hope it's correct for posting this here. i configured my retropie and everything works very well. But i can't Nintendo World Championships 1990 for the NES get to work. It stucks at the start screen. Can anyone help?

**Comment by joolswills** [comment]
Please use the retropie forum for support questions

http://blog.petrockblock.com/forums/forum/retropie-project-forum/
