### ISSUE TITLE
Lightguns and RetroPie

### ISSUE THREAD

**Issue by P3ter** [RetroPie/RetroPie-Setup#923]
Hi,

Is it possible to use USB lightguns with a RetroPie setup on MAME/FBA games ?

And also, could wiimotes be used like lightguns when installed like this (method 2) : https://github.com/RetroPie/RetroPie-Setup/wiki/Wiimotes-with-classic-controllers .

Regards,
P3ter

**Comment by joolswills** [comment]
If any of the emulators support using a gamepad as a lightgun to move the target, it may work with the wiimote, but I don't have an answer for you I'm afraid.

**Comment by joolswills** [comment]
You might do better to see if anyone on the forum has tried - this is less of a support area, but an issue tracker for bugs/feature requests etc.

**Comment by P3ter** [comment]
Ok thanks for your answer ;-)
