### ISSUE TITLE
Experimental Package Stability Tests

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/RetroPie-Setup#925]
Here's the link for chart:

https://docs.google.com/spreadsheets/d/1z45RZfz7RJViKz5coGLodhtB3CnG9E_7SaHc_138qeM/edit?usp=sharing

most have been tested with a Raspberry Pi 2, I'm not sure how much the stability changes compared to a Rpi 1. I was unable to test some of them and I have a few I've yet to test- I just figure its easier to track here than on the forums.

**Comment by joolswills** [comment]
Thanks - very useful. I will compare this to the module code (in some cases the module itself needs some scripting improvements even though it runs stable) and go from there.

**Comment by joolswills** [comment]
I think I will move some out of experimental before 3.0 final.

Basically the stable ones that don't have any issues or need scripting improvements.

**Comment by joolswills** [comment]
How would you like me to mark them as no longer in experimental - remove them to move the row to another sheet ?

**Comment by HerbFargus** [comment]
You can mark them however you'd like- I can add another drop down option for "moved out of experimental" or you can toss them on another column or sheet- just as long as its clear.

**Comment by joolswills** [comment]
For now I have greyed them out. feel free to improve on that :)

**Comment by HerbFargus** [comment]
Pretty much resolved for the time being.
