### ISSUE TITLE
No Video output on lr-handy

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#932]
Reported here:

http://blog.petrockblock.com/forums/topic/lynx-no-video-output-v3-0-rc1/

Bisected and reported upstream. 

https://github.com/libretro/libretro-handy/issues/9

**Comment by joolswills** [comment]
I debugged the problem and made a pull request for upstream with the fix.

**Comment by HerbFargus** [comment]
I rebuilt from source and I can confirm it is now working.

**Comment by joolswills** [comment]
I have updated the other ticket. feel free to read. I'll close this once I have built new binaries.

**Comment by HerbFargus** [comment]
Well I'll say thanks regardless of your code format :D

**Comment by joolswills** [comment]
Cheers. well the point is mixing indentation in a single file becomes a mess, and it's pretty common in development not to do it. But when there is ego involved. well..

**Comment by joolswills** [comment]
New binaries. built.
