### ISSUE TITLE
"version info" retropie menu script

### ISSUE THREAD

**Issue by gonzo-the-great** [RetroPie/RetroPie-Setup#949]
hello, would it be possible to add a new bash script in the retropie-menu,
that basically tells you what version of retropie your currently running? 

thank you

**Comment by HerbFargus** [comment]
I'm not quite sure how that would be possible as it is in constant development, and it would change any time the script was updated. But I could be wrong...

**Comment by gonzo-the-great** [comment]
or at least, somehow of showing the current version number

**Comment by robertybob** [comment]
If it wasn't updated so often (thank god it is) then I'd suggest putting the version number within Emulationstation (e.g adding 'RetroPie 3' to the Simple theme main menu in the bottom right corner)

**Comment by joolswills** [comment]
We could display the script version in regards to git revision, but not much else - and it would be a rough guideline only since you could have an updated script, but ancient binaries etc.

**Comment by joolswills** [comment]
@HerbFargus has added this to the RetroPie-Setup menu now.

**Comment by HerbFargus** [comment]
Resolved as of https://github.com/RetroPie/RetroPie-Setup/pull/1273

There isn't any clean way to address binary versions or anything like that so this will only apply to the current version of the setup script. At least gives users a a gauge of where they are at.
