### ISSUE TITLE
No module aptpackages on binary based installation

### ISSUE THREAD

**Issue by Havelock-Vetinari** [RetroPie/RetroPie-Setup#951]
Binary based installation failed with following message:

    = = = = = = = = = = = = = = = = = = = = =
    Binaries-based installation
    = = = = = = = = = = = = = = = = = = = = =
  
    Log started at: Thu Aug 13 09:41:35 UTC 2015
    
    = = = = = = = = = = = = = = = = = = = = =
    Error
    = = = = = = = = = = = = = = = = = = = = =
    
    No module 'aptpackages' found for platform rpi2
    
My version of setup repo: f0778fa84b0190935b8414a71c4ef4ab3f1bea71

**Comment by joolswills** [comment]
Please update teh script and try again. A call was missed during some re-organization last night.

**Comment by Havelock-Vetinari** [comment]
Works now. Thx.
