### ISSUE TITLE
Mupen64plus Problems :(

### ISSUE THREAD

**Issue by Willicraft15243** [RetroPie/RetroPie-Setup#955]
I have a Zhidong zd-n108 model controller on Xinput mode, so there shouldn't be a problem with detecting it but I cannot get the .cfg or .ini file to properly read my gamepad when I start up mupen64plus (not libretro). Please help, it only reads the keyboard

**Comment by HerbFargus** [comment]
have you looked at the linked videos on this page? https://github.com/RetroPie/RetroPie-Setup/wiki/Nintendo-64 the format for controls with mupen64plus are different than most other configs.
