### ISSUE TITLE
Base installation option

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#958]
When I rebuild everything, I like to first build just a few core things like ES + RetroPie, themes and thats about it. I then want to add in 1 emulator for testing.

Is there a way to select ONLY what is "needed" to get everything at least one emulator to show up in ES and work?

**Comment by HerbFargus** [comment]
It's something that we are looking into for the future. see https://github.com/RetroPie/RetroPie-Setup/issues/936

**Comment by joolswills** [comment]
You can do this manually via menu 5 - just install what you want.
