### ISSUE TITLE
[RP3.0] Emulationstation doesn't recognize zipped Wonderswan games

### ISSUE THREAD

**Issue by zerojay** [RetroPie/RetroPie-Setup#963]
When launching Emulationstation, if my Wonderswan games are zipped, a Wonderswan section does not show up whatsoever. When unzipped, they are recognized and added to Emulationstation.

Likely a small change to a list of recognized ROM extensions.

**Comment by HerbFargus** [comment]
Thank you for the input. I have submitted a fix: https://github.com/RetroPie/RetroPie-Setup/pull/964
