### ISSUE TITLE
Do not understand, ES can not find my ROMS

### ISSUE THREAD

**Issue by SoundChaos** [RetroPie/RetroPie-Setup#97]
I am very new to linux, although I do have extensive knowledge of computers overall.. I just do not understand anything about this program. I used the instructions to install RetroPie, but emulation station closes saying there are no games in the systems. Apparently I did not install right? I should not install it as root and not install it through an X terminal? I do not have any idea how to do it any way else, and now that its done, I cant figure out how to fix it.

my roms are located in /home/root/RetroPie/roms , which is the directory it created for itself. there are roms for snes, nes, gba, and gbc, all with the correct extensions, but it doesn't seem emulationstation is looking for the correct path, and I don't even know where to start to change that.

I tried looking at the config file with the "nano ~/.emulationstation/es_systems.cfg" line, but I couldn't make heads or tails of what it was saying in there. Please someone give me an idiot proof explanation to whats going on and how to possibly fix it?

**Comment by vegas81** [comment]
So im having a similar problem with my retopie, my linux guru buddy cant figure it out either. So im running retro pie on my desktop, i have the ROMs and everything is running, but when i get to the emulationstation it does not see the ROMs and their for i cannot get any games off scraper. Any ideas or help would be greatly appreciated. I JUST WANT TO PLAY SOME RETRO GAMES!!!! LOL

**Comment by joolswills** [comment]
@vegas81 please use the retropie forum for help / support https://retropie.org.uk/forum

**Comment by g0rski** [comment]
For ppl whe will have the same issue. In my case it turned out that roms i`ve put into ./roms/nes/* had read only access. The fastest way to fix it is:
1. Log in via SSH to retropi
2. go to directory ./RetroPi/roms (in my case, since I have retropie alongside with osmc it was ~/RetroPie/roms
3. execute: sudo chmod 666 *.zip  (or sudo chmod 666 *  - for ignore extension) - 444 should be enouht but who cares - speed over perfection baby!!

**Comment by TitanLife** [comment]
where does retropie look for the games? I have one ROM that will not launch. Gets to Loading screen and is kicked back out to the menu screen. my video snaps, wheel, boxart and cartart all work but the rom doesn't whether I use the PBP or cue/bin combination. Using, /home/pi/RetroPie/roms/psx/Castlevania - Symphony of the Night (USA).cue for rom path, (Yep checked all the spaces in the path and verified the path in the cue file pointing to the bin of the same name).

I also verified the paths to be correct and other roms in the same path work fine.. I'm just wondering is there an xml file or a config file somewhere that I may be missing? Forgive my ignorance with linux. Dialed in with WinSCP and SSH so I can pretty much move around if I need to.

Thanks in advance!
