### ISSUE TITLE
Links/aliases to important directories

### ISSUE THREAD

**Issue by ProxyCell** [RetroPie/RetroPie-Setup#972]
Would it be possible to have an optional setup script that adds in some links/aliases/shortcuts to the important directories directly in the $homedir

**Comment by joolswills** [comment]
I don't feel this is needed as a built in thing. What is your use case ?

**Comment by ProxyCell** [comment]
well, just faster/easier to traverse to some harder to reach folders when accessing the Pi over SFTP
it would let me drag and drop some files

**Comment by joolswills** [comment]
If you need that I would just make the symlinks yourself (if you have tested that works). I don't want to start making symlinks in users folders by default for the sake of making drag and drop easier on a specific sftp client.

**Comment by ProxyCell** [comment]
good point, other users may want their homedir cleaer
