### ISSUE TITLE
[RP3.0] - ScummVM "Error Running Game"

### ISSUE THREAD

**Issue by NizZ8** [RetroPie/RetroPie-Setup#973]
Disregard--Issue was fixed when i did a reboot after removing the games from the scummvm app and then re-adding them.

I'm getting a "Error running Game: Game data not found" error when i try to launch a game.  If i launch it directly in ScummVM it will start correctly, just not through the ES UI.  I tried deleting the .svm's and re-creating them but that didn't work either.

**Comment by NizZ8** [comment]
Disregard--Issue was fixed when i did a reboot after removing the games from the scummvm app and then re-adding them.

**Comment by HerbFargus** [comment]
I've had similar issues- I wonder why it is that it doesn't remember the settings.

**Comment by HerbFargus** [comment]
@joolswills 

worth reopening to just give a second look to make sure that this isnt a bug as I've yet to get it working on mine.

**Comment by joolswills** [comment]
thanks. will check.

**Comment by HerbFargus** [comment]
tested it again on the jessie build following the suggestion to reboot above and it works with no problems. no idea why it wasn't working on my other build, little weird but whatever. Glad it works now.
