### ISSUE TITLE
Script file to safely shut down kodi installed through experimental packages

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#974]
This could be as a future idea/development also:)

I installed Retropie (rasp pi 1, model b) and afterwards kodi (Helix 14.2, from experimental packages). I managed to make it bottable on start up. I even managed to enable my cec-controller.

Now the problem is that everytime i hit exit , power off system OR reboot, it always goes back to ES. This is where i thought about scripts (which i am planning to run through specific app called advanced launcher).

So maybe a script will do the trick? 

What script has to do: It will SAFELY power off (completely) system (smth like shutdown -P now or smth similar). This script would be run through Advanced Launcher’s menu i suppose (or in other way-i am open to ideas). I am a linux (and scripting) noob so i do not have the knowledge to do it.

Anyone can help with this one?

Edit: To help someone out i found this:

http://wiki.openelec.tv/index.php/Autostart.sh

Is this my command?

case “$1″ in
halt)
# your commands here
;;
poweroff)
# your commands here
;;
reboot)
# your commands here
;;
*)
# your commands here
;;
esac

I suppose where it says # your commands here, it needs a command? And what is the complete script with command?

Any help appreciated

**Comment by joolswills** [comment]
I'm going to close this I'm afraid - for guidance on doing any custom scripting please use the forum. Thanks.
