### ISSUE TITLE
Add controller config picture to rom section

### ISSUE THREAD

**Issue by secsven** [RetroPie/RetroPie-Setup#978]
hey,

this is a feature request to add the controller config overview as shown here:
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration

to the menu

Thanks

**Comment by joolswills** [comment]
Not sure I understand your request sorry.

**Comment by joolswills** [comment]
oh - you want the pictures of the controllers added to retropie-setup ? Surely it's easy enough just to reference the wiki - and easier for us to maintain? Or you mean something else ?

**Comment by secsven** [comment]
yes exactly, I do not always have internet, or the wiki available when running retropie ... so I thought it might would be an enhancement to have the controller overview available via the GUI

**Comment by HerbFargus** [comment]
@taalas has discussed an interactive controller config integrating the diagrams that he's created- but I don't know if that will happen anytime soon. Ideally it should be integrated with retroarch rather than retropie or emulationstation

**Comment by joolswills** [comment]
I don't really want to include the images in retropie-setup - as it's just another thing to maintain then - if you don't have internet access perhaps it could be useful to print the ones you want ?
