### ISSUE TITLE
C64 (vice) assign keyboard to joystick buttons

### ISSUE THREAD

**Issue by Haris1977** [RetroPie/RetroPie-Setup#981]
Is that possible?

**Comment by joolswills** [comment]
I know it is possible the other way round (keyboard to joystick). not sure though - you might want to check the documentation out. This is the wrong place for support though - as we use this just as a bugtracker - please open a thread up on the retropie forum - http://blog.petrockblock.com/forums/forum/retropie-project-forum/

**Comment by Haris1977** [comment]
Thanks:) I will try in Retropie forum..
