### ISSUE TITLE
Possible dgen config issue

### ISSUE THREAD

**Issue by biscuits99** [RetroPie/RetroPie-Setup#983]
Not sure if dgen, for Megadrive, Sega32x, SegaCD should be looking in their system folder for dgenrc or the /all directory?

Megadrive has a dgenrc in its system directory, but none of the others do. Also, there is no dgenrc file in the /all directory, but all the emulator.cfg files point to that.

This is in RetroPie 3 final.

**Comment by joolswills** [comment]
thanks - good spot, now fixed.
