### ISSUE TITLE
SAM Coupé emulator addition, alls cool on a rPi 2!!

### ISSUE THREAD

**Issue by gonzo-the-great** [RetroPie/RetroPie-Setup#991]
hi, would it be possible to add this emulator to the experimental menu, if it can be run on the Pi that is,

http://simonowen.com/blog/2014/02/02/simcoupe-raspi-sdl20/

http://simonowen.com/blog/2012/05/07/simcoupe-raspberry-pi/

ill try this out shortly
thanks

**Comment by gonzo-the-great** [comment]
yeah it boots, not tried anything else, but please could you add it to the experimental menu

thanks

**Comment by gonzo-the-great** [comment]
ok just loaded up SAM cards.sad, loads up nice and quick, but the mouse is very jumpy, which means its very hard to control, sadly, but on i'll test & play

**Comment by gonzo-the-great** [comment]
oh, btw, heres the SimCoupe.cfg, suggestions how to make the mouse less choppy/jumpy?

http://pastebin.com/tfA70z2a

i have it running on one of my rpi B+ boards overclocked to moderate

**Comment by gonzo-the-great** [comment]
alls cool on a rPi 2!!

**Comment by gonzo-the-great** [comment]
has anyone else been able to try this out yet?

**Comment by joolswills** [comment]
Reference to source for myself - https://github.com/simonowen/simcoupe/

**Comment by HerbFargus** [comment]
Preliminary Module:

http://pastebin.com/2echyVVC

**Comment by joolswills** [comment]
Thanks - added in 11e797da04ed464b25a8f6115a6110c8d6d74277
