### ISSUE TITLE
Issue with PS2 controller in GPSP

### ISSUE THREAD

**Issue by thatharryguy** [RetroPie/RetroPie-Setup#992]
So I have setup every other emulator on my system to work flawlessly with the PS2 controller that I am using, however when it comes to the GBA emulator I cannot get it to use the d-pad for directional controls. It forces the use of the analog stick which is far too sensitive and not what I am looking for.

Can anyone help me configure the GPSP controls such that i can use the d-pad for directional input?

**Comment by joolswills** [comment]
This would be better asked on the retropie forum - but if using the libretro core - it should be possible to use the retroarch gui to do this.
