### ISSUE TITLE
Retropie Menu Missing

### ISSUE THREAD

**Issue by moehij** [RetroPie/RetroPie-Setup#998]
Hi, I've installed retropie 2.6 from an image and when ive run it it loads but retropie menu is missing from the emulationstation main screen. 
The retropie image shows up while loading its just missing from view.

Can anyone help me with this please

**Comment by HerbFargus** [comment]
That's because the retropie menu wasn't added until 3.0. Install the 3.0 Image as 2.6 is no longer supported.

Also use the forum (http://blog.petrockblock.com/forums/forum/retropie-project-forum/) for questions like this as github is used as a bug tracker.
