### ISSUE TITLE
[RPI2] Mame 0.78 build failed

### ISSUE THREAD

**Issue by nemo93** [RetroPie/RetroPie-Setup#999]
I've updated Retropie Setup this morning and I was about to give a try to these new (eperimental) versions to check roms compatibility, perf etc. However I just could't build any of those. I'll have a look later today but meanwhile I've decided to raise this ticket just in case. 

Let me enclose compilation logs to this ticket. If you need anything else please shout.

http://www.pastefile.com/hqSPOA

**Comment by joolswills** [comment]
probably because I use distcc and my distcc is forced to gcc 4.8 - so they just need modifiying to force gcc 4.8 also.

**Comment by joolswills** [comment]
Changed to gcc 4.8 - please try again. it should def fix 2003 building, as the compiler crashed from your logs in that one.

**Comment by nemo93** [comment]
No same results. I've updated Retropie Script before launching the compilation :) While writing this I'm exploring some other options. In case you're interested here are the 2 logs after build failed:

http://www.pastefile.com/rQgPP3

**Comment by joolswills** [comment]
well, in the case of the lr-mame2003, your compiler crashed. Maybe out of memory ? What system ? memory split etc.

**Comment by joolswills** [comment]
the compiler crashed in both cases.

**Comment by HerbFargus** [comment]
I was able to get lr-mame2003 to build on my rpi2 (after like an hour of compiling) but when I add roms to the mame-libretro folder they don't show up when I refresh emulationstation. not sure if its a conflict with lr-mame4all or what. also this line shouldn't affect things in the future should it?: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-imame4all.sh#L39

**Comment by joolswills** [comment]
well, when they are out of experimental ill have to remove that line - to be honest, its only for upgrading from 2.6 - but then too much breaks really, so I should just remove some of the backward compatibility stuff for 2.6

**Comment by joolswills** [comment]
in regards to roms not showing up - check ES config perhaps?

**Comment by HerbFargus** [comment]
they show up fine for mame4all and lr-imame4all.

```
  <system>
    <name>mame-libretro</name>
    <fullname/>
    <path>~/RetroPie/roms/mame-libretro</path>
    <extension> </extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ mame-libretro %ROM%</command>
    <platform>arcade</platform>
    <theme>mame</theme>
  </system>
```

missing the .zip extension. probably needs to be added int platforms.cfg?

**Comment by joolswills** [comment]
it's done.

**Comment by HerbFargus** [comment]
thanks, yeah it works great!

**Comment by joolswills** [comment]
:)

**Comment by nemo93** [comment]
sorry for not replying earlier but... I've spent the rest of the day playing to all the IREM games I was desperate to see running on pi \o/ I do confirm that Mame 0.78 works amazingly well... Not sure why the build went wrong the first time but after I removed everything in the tmp/ directory everything went well the next time. Except the issue mentioned by @HerbFargus that you already fixed!

Seriously this Mame version is so much superior to the one shipped by default in Retropie that it would make sense to simply use this version as default Mame application (at least on pi2). 

All IREM games work smoothly (except Ninja Baseball Bateman that has slowdowns but still playable) with sound, the same goes with Mortal Kombat 1/2/3 (the 1 has sound issues), Darius and Ninja Warrior works ok at full speed with sound! Konami games are just fine too. Some games also work faster than with FBA (latest experimental version you just added some days ago) like Crude Busters. 

CPS1 games just play perfectly. However I got no luck with CPS2 games (all of them) and I didn't try Neo Geo games for now. 

I've seen the wonderful job done by @HerbFargus regarding the wiki section for Mame and I'll try to update the table.

If you need me to test specific things please let me know. Let me insist this version is just awesome!!

**Comment by joolswills** [comment]
Thanks for the feedback - sounds good! - as it uses its own rom folder, we can ship it alongside the current one, and people who want to use it can just use the mame-libretro romfolder.

I will get a bit more feedback from others (in case there are problems missed), but it sounds like it will do well to be included and moved out of experimental.

Thanks again.

**Comment by nemo93** [comment]
You're very welcome!! oh and as @HerbFargus mentioned also the build time is rather long (1h+) on pi2 compared to other emulators. Perhaps a small notification or some words in the description as a reminder would help!

Feel free to close that one off btw.

**Comment by joolswills** [comment]
Advancemame 0.93/1.2 also take a long time to build

**Comment by joolswills** [comment]
i don't recommend anyone builds everything from source unless they are incredibly patient, or have a distributed compiler set up etc.

**Comment by joolswills** [comment]
Will consider adding some info regarding build time.
